export type EngineCategory = {
  id: string;
  label: string;
  description: string;
  permission: "settings" | "content" | "marketing" | "support" | "subscriptions";
  links?: Array<{ label: string; href: string; help: string }>;
};

export const ENGINE_CATEGORIES: EngineCategory[] = [
  { id: "branding_design", label: "Branding & Design", description: "Brand colors, identity presentation, approved layout choices, and visual defaults.", permission: "settings" },
  { id: "navigation_menus", label: "Navigation & Menus", description: "Customer-facing labels, destinations, order, and visibility for approved navigation slots.", permission: "content", links: [{ label: "Edit page and footer content", href: "/admin/content", help: "Manage published labels and footer destinations." }] },
  { id: "pages_sections", label: "Pages & Page Sections", description: "Editorial pages, SEO fields, calls to action, section visibility, and constrained layouts.", permission: "content", links: [{ label: "Open Content Management", href: "/admin/content", help: "Create, preview, publish, archive, and restore page content." }] },
  { id: "homepage_composition", label: "Homepage Composition", description: "Homepage rows, card limits, linked records, visibility, and approved presentation variants.", permission: "marketing", links: [{ label: "Manage homepage", href: "/admin/marketing?workspace=homepage", help: "Manage homepage rows and featured content." }] },
  { id: "service_taxonomies", label: "Service Catalog & Taxonomies", description: "Service categories, service names, aliases, option groups, materials, add-ons, and inclusions.", permission: "content", links: [{ label: "Manage service catalog", href: "/admin/content?workspace=catalog", help: "Edit ordinary catalog records with dependency previews." }] },
  { id: "salon_lifecycle", label: "Salon Setup & Lifecycle", description: "Application, setup-completion, approval, activation, discoverability, and offboarding rules.", permission: "settings", links: [{ label: "Manage salons", href: "/admin/salons", help: "Review individual salon status and lifecycle actions." }] },
  { id: "booking_availability", label: "Booking & Availability Rules", description: "Safe scheduling bounds, buffers, availability rules, reminders, cancellation choices, and booking presentation.", permission: "settings", links: [{ label: "Review bookings", href: "/admin/bookings", help: "Operational booking records remain historically protected." }] },
  { id: "payments_subscriptions", label: "Payments, Deposits & Subscription Presentation", description: "Validated deposit display, plan presentation, and payment-provider configuration status. Financial history is never editable here.", permission: "subscriptions", links: [{ label: "Open subscriptions", href: "/admin/subscriptions", help: "Review subscription state and protected billing history." }, { label: "Open finance", href: "/admin/finance", help: "Inspect deposits, refunds, and the billing ledger." }] },
  { id: "search_discovery", label: "Search, Discovery & Location", description: "Deterministic search vocabulary, aliases, phrases, misspellings, ranking boosts, stop words, and discovery defaults.", permission: "settings", links: [{ label: "Preview salon discovery", href: "/salons", help: "Open the customer-facing deterministic search experience." }] },
  { id: "markets_service_areas", label: "Markets & Service Areas", description: "Supported countries, markets, cities, boroughs, service areas, centers, and activation state.", permission: "settings", links: [{ label: "Manage location records", href: "/admin/salons", help: "View salon-to-market assignments before lifecycle changes." }] },
  { id: "media_uploads", label: "Media & Upload Rules", description: "Upload limits, approved formats, image renditions, focal points, video posters, and storage status.", permission: "settings" },
  { id: "languages_translations", label: "Languages & Translations", description: "Supported locales, direction, order, interface translations, fallback coverage, review, publication, and rollback.", permission: "content" },
  { id: "notifications_templates", label: "Notifications & Templates", description: "Customer-safe subjects, templates, delivery timing, and channel switches. Provider secrets stay in deployment settings.", permission: "content", links: [{ label: "Review customer support", href: "/admin/support", help: "Inspect support delivery context and replies." }] },
  { id: "trust_quality", label: "Trust, Reviews & Quality Rules", description: "Trust labels, verification presentation, quality thresholds, moderation choices, and review health.", permission: "settings", links: [{ label: "Open quality reports", href: "/admin/quality", help: "Review the records affected by published thresholds." }, { label: "Moderate reviews", href: "/admin/reviews", help: "Manage review lifecycle with audit history." }] },
  { id: "promotions_campaigns", label: "Promotions & Campaigns", description: "Promotion availability, bounded rollout, homepage campaigns, featured salons, and trending content.", permission: "marketing", links: [{ label: "Open Marketing", href: "/admin/marketing", help: "Create and audit promotions and paid placements." }] },
  { id: "customer_support", label: "Customer Support Configuration", description: "Support categories, statuses, service targets, response templates, complaint reasons, and escalation presentation.", permission: "support", links: [{ label: "Open support inbox", href: "/admin/support", help: "Read and respond to customer requests." }, { label: "Open complaints", href: "/admin/complaints", help: "Review verified complaints and protected history." }] },
  { id: "users_roles", label: "Users, Roles & Permissions", description: "Role presentation, bounded permissions, identity health, and protected deletion workflows. Authentication secrets remain inaccessible.", permission: "settings", links: [{ label: "Manage admin team", href: "/admin/settings", help: "Add users and assign explicit permissions." }] },
  { id: "ai_automation", label: "AI & Automation", description: "Provider-neutral, disabled-by-default assistance with budgets, review gates, usage, prompts, testing, and deterministic fallback.", permission: "settings" },
  { id: "test_data_maintenance", label: "Test Data & Maintenance", description: "Explicitly labeled test batches, dependency preview, protected cleanup, and maintenance confirmations.", permission: "settings" },
  { id: "integrations_system", label: "Integrations & System Status", description: "Plain-language health for migrations, database, storage, payments, maps, notifications, translation, deployment, and optional AI.", permission: "settings" },
  { id: "configuration_history", label: "Configuration History, Publishing & Recovery", description: "Drafts, published versions, actor history, import/export, conflict handling, rollback, and last-known-good recovery.", permission: "settings" },
];

export const ENGINE_CATEGORY_IDS = new Set(ENGINE_CATEGORIES.map((category) => category.id));
