import {expect} from '@playwright/test';
import {test} from './helpers/hydration';
import {p0OwnerFixture} from './helpers/p0OwnerFixture';
import {DASHBOARD_SOURCE_MESSAGES} from '../../src/i18n/dashboard-source-catalog';
test.use({serviceWorkers:'block'});
for(const [locale,width,height] of [['en',390,844],['fr',768,900],['es',1440,1000],['zh-CN',844,390]] as const){
 test(`Business products show real stock and retain filters through edit and reload in ${locale}`,async({page},info)=>{
  const f=await p0OwnerFixture(page,{populated:true,locale});
  const t=(s:string)=>(DASHBOARD_SOURCE_MESSAGES as Record<string,Record<string,string>>)[locale]?.[s]||s;
  Object.assign(f.records.salon_products[0],{name:'Growth Oil',inventory_quantity:2,low_stock_threshold:3,track_inventory:true,product_status:'Active',is_visible:true});
  f.records.salon_products.push({...f.records.salon_products[0],id:'33000000-0000-4000-8000-000000000091',name:'Edge Control',inventory_quantity:0,product_status:'Draft'},{...f.records.salon_products[0],id:'33000000-0000-4000-8000-000000000092',name:'Comb',inventory_quantity:undefined});
  await page.setViewportSize({width,height});await page.goto('/salon/dashboard/products');
  await expect(page.getByRole('heading',{name:t('Products'),exact:true}).first()).toBeVisible();await page.screenshot({path:info.outputPath('products-viewport.png')});
  const catalog=page.getByRole('region',{name:t('Product catalog'),exact:true});await expect(catalog).toBeVisible();if(width===390)await expect(catalog.getByRole('heading',{name:'Growth Oil',exact:true})).toBeInViewport();
  await expect(catalog.getByRole('article',{name:'Growth Oil',exact:true})).toContainText(t('Low stock'));
  await expect(catalog.getByRole('article',{name:'Edge Control',exact:true})).toContainText(t('Out of stock'));
  await expect(catalog.getByRole('article',{name:'Comb',exact:true})).toContainText(t('Stock unavailable'));
  await catalog.getByRole('combobox',{name:t('Stock level'),exact:true}).selectOption('low');
  await expect(catalog.getByRole('article')).toHaveCount(1);
  await catalog.getByRole('button',{name:t('List view'),exact:true}).click();
  await catalog.getByRole('link',{name:t('Edit product'),exact:true}).click();
  await expect(page.getByRole('textbox',{name:t('Name'),exact:true})).toHaveValue('Growth Oil');
  await page.goBack();await expect(catalog.getByRole('article')).toHaveCount(1);
  await page.reload();await expect(catalog.getByRole('combobox',{name:t('Stock level'),exact:true})).toHaveValue('low');
  await expect(catalog.getByRole('button',{name:t('List view'),exact:true})).toHaveAttribute('aria-pressed','true');
  await catalog.getByRole('combobox',{name:t('Stock level'),exact:true}).selectOption('all');
  await catalog.getByRole('textbox',{name:t('Search products'),exact:true}).fill('no matches');await expect(catalog.getByRole('article')).toHaveCount(0);
  await expect(catalog.getByText(t('No products match these filters.'),{exact:true})).toBeVisible();
  await catalog.getByRole('textbox',{name:t('Search products'),exact:true}).fill('');
  await catalog.getByRole('button',{name:t('Grid view'),exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:info.outputPath('products-final.png')});
  expect(f.actions).toEqual([]);expect(f.unexpected).toEqual([]);
 });
}
for (const [locale,width,height,staff] of [['en',390,844,false],['fr',768,1024,false],['es',1440,1000,false],['zh-CN',844,390,false],['en',390,844,true]] as const) {
 test(`Business products put required details before photos and preserve drafts at ${width}x${height}${staff?' for permitted staff':''}`,async({page},info)=>{
  const f=await p0OwnerFixture(page,{populated:true,locale});
  if(staff)await page.route('**/api/salon/workspace',route=>route.fulfill({json:{salon:f.business,isOwner:false,isTeamMember:true,permissions:{products:true},records:f.records}}));
  const t=(s:string)=>(DASHBOARD_SOURCE_MESSAGES as Record<string,Record<string,string>>)[locale]?.[s]||s;
  await page.setViewportSize({width,height});await page.goto('/salon/dashboard/products/new');
  const editor=page.getByRole('dialog',{name:t('Add product'),exact:true});
  const name=editor.getByRole('textbox',{name:t('Name'),exact:true});
  const price=editor.getByRole('textbox',{name:t('Regular price (USD)'),exact:true});
  await expect(name).toBeVisible();await page.screenshot({path:info.outputPath('product-required-first.png')});
  const photoLabel=editor.getByText(t('Product Photos'),{exact:true});
  const layout=await Promise.all([name.boundingBox(),price.boundingBox(),photoLabel.boundingBox()]);
  expect(layout.every(Boolean)).toBe(true);
  expect(layout[0]!.y+layout[0]!.height).toBeLessThan(layout[2]!.y);
  expect(layout[1]!.y+layout[1]!.height).toBeLessThan(layout[2]!.y);
  await name.fill('Owner product draft');await price.fill('37');
  await editor.getByRole('textbox',{name:t('SKU'),exact:true}).fill('DRAFT-37');
  await editor.getByRole('textbox',{name:t('Description'),exact:true}).fill('Original unsaved product description');
  const photos=editor.locator('details').filter({has:page.getByText(t('Product Photos'),{exact:true})});await photos.locator('summary').click();
  await expect(photos).toContainText(t('Save the record details before adding photos'));
  await expect(photos.locator('input[type="file"]:enabled')).toHaveCount(0);
  await photos.locator('summary').click();await photos.locator('summary').click();
  await expect(name).toHaveValue('Owner product draft');await expect(price).toHaveValue('37');
  await expect(editor.getByRole('textbox',{name:t('SKU'),exact:true})).toHaveValue('DRAFT-37');
  await expect(editor.getByRole('textbox',{name:t('Description'),exact:true})).toHaveValue('Original unsaved product description');
  expect(f.actions).toEqual([]);expect(f.unexpected).toEqual([]);
  expect(await editor.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
  f.failNextSave();
  const failure=page.waitForResponse(response=>response.url().endsWith('/api/salon/records/save')&&response.status()===503);
  await editor.getByRole('button',{name:t('Save Product'),exact:true}).click();await failure;
  await expect(name).toHaveValue('Owner product draft');await expect(price).toHaveValue('37');
  await editor.getByRole('button',{name:t('Save Product'),exact:true}).click();
  await expect.poll(()=>f.records.salon_products.find(row=>row.name==='Owner product draft')?.price).toBe(37);
  await expect(page).toHaveURL(/\/products\/[0-9a-f-]{36}$/);
  await page.reload();
  const saved=page.getByRole('dialog',{name:/Owner product draft/});
  await expect(saved.getByRole('textbox',{name:t('Description'),exact:true})).toHaveValue('Original unsaved product description');
  const savedPhotos=saved.locator('details').filter({has:page.getByText(t('Product Photos'),{exact:true})});
  await savedPhotos.locator('summary').click();await expect(savedPhotos.locator('input[type="file"]')).toBeEnabled();
  await saved.getByRole('textbox',{name:t('Name'),exact:true}).fill('Another unsaved title');
  await savedPhotos.locator('summary').click();await savedPhotos.locator('summary').click();
  await expect(saved.getByRole('textbox',{name:t('Name'),exact:true})).toHaveValue('Another unsaved title');
  await expect(savedPhotos.locator('input[type="file"]')).toHaveCount(1);
  expect(f.actions).toHaveLength(2);expect(f.unexpected).toEqual([]);
 });
}
