import {expect} from '@playwright/test';import {test} from './helpers/hydration';import {p0OwnerFixture} from './helpers/p0OwnerFixture';import {MASTER_BUILD_COPY} from '../../src/i18n/master-build-source-catalog';import type {BusinessAds} from '../../src/lib/businessAdvertising';
import {buildAuthStorageKeys} from '../../src/lib/authSessionCore';import type {AdminAds} from '../../src/lib/businessAdvertising';
test.use({serviceWorkers:'block'});
for(const [locale,column,width,height]of [['en',0,390,844],['fr',1,768,900],['es',2,1440,1000],['zh-CN',3,844,390]]as const){
 test(`Master advertising reviews benefits, recovers response loss and cancels in ${locale}`,async({page},info)=>{
  const f=await p0OwnerFixture(page,{populated:true,locale});await page.setViewportSize({width,height});const t=(s:string)=>MASTER_BUILD_COPY.find(row=>row[0]===s)?.[column]||s;
  const offer={id:'44000000-0000-4000-8000-000000000001',title:'Original owner campaign',plan:'premium',price_cents:10000,discount_percent:15,discount_cents:1500,credit_cents:1000,balance_cents:7500,fingerprint:'a'.repeat(32),starts_at:'2026-10-10T12:00:00Z',ends_at:'2026-10-17T12:00:00Z',radius_miles:25};let ads:BusinessAds={salon_id:f.business.id,is_demo:false,eligible:true,benefits:{plan:'premium',discount_percent:15,credit_available_cents:1000,period_start:'2026-09-01T00:00:00Z',period_end:'2026-10-01T00:00:00Z',early_hours:48},offers:[offer],reservations:[]};
  const posts:Record<string,unknown>[]=[];await page.route('**/api/salon/advertising',r=>{if(r.request().method()==='POST'){const body=r.request().postDataJSON();posts.push(body);if(posts.length===1)return r.fulfill({status:503,json:{code:'AD_UNAVAILABLE',request_id:'55000000-0000-4000-8000-000000000001'}});ads=body.action==='reserve'?{...ads,offers:[],benefits:{...ads.benefits,credit_available_cents:0},reservations:[{id:body.id,title:offer.title,status:'reserved',balance_cents:7500,credit_cents:1000,expires_at:offer.starts_at,campaign_id:null}]}:{...ads,offers:[offer],benefits:{...ads.benefits,credit_available_cents:1000},reservations:ads.reservations.map(x=>({...x,status:'cancelled'}))};return r.fulfill({json:{ads,id:body.id,verified:true}});}return r.fulfill({json:{ads}});});
  await page.goto('/salon/dashboard/subscription');const panel=page.getByRole('region',{name:t('Advertising benefits'),exact:true});await expect(panel).toContainText('Original owner campaign');await panel.getByRole('button',{name:t('Review ad reservation'),exact:true}).click();const review=panel.getByRole('group',{name:t('Review ad reservation'),exact:true});await expect(review).toContainText('75');expect(posts).toHaveLength(0);
  await review.getByRole('button',{name:t('Confirm reservation'),exact:true}).click();await expect(panel.getByRole('alert')).toContainText('55000000-0000-4000-8000-000000000001');await expect(review).toBeVisible();await review.getByRole('button',{name:t('Confirm reservation'),exact:true}).click();await expect(panel.getByRole('status')).toContainText(t('Reservation saved. Platform support must verify the invoice balance before scheduling the placement.'));expect(posts[1]).toEqual(posts[0]);
  await page.reload();await expect(panel.getByRole('list',{name:t('Your ad reservations')})).toContainText('Original owner campaign');await panel.getByRole('button',{name:t('Cancel reservation'),exact:true}).click();await panel.getByRole('button',{name:t('Confirm cancellation'),exact:true}).click();await expect(panel.getByRole('status')).toContainText(t('Reservation cancelled. Unused credit is available in the same allowance period.'));await page.reload();await expect(panel.getByRole('button',{name:t('Review ad reservation'),exact:true})).toBeEnabled();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await panel.screenshot({path:info.outputPath('advertising-benefits.png')});ads={...ads,is_demo:true,eligible:false};await page.reload();await expect(panel).toContainText(t('Advertising is unavailable for this account.'));await expect(panel.getByRole('button',{name:t('Review ad reservation'),exact:true})).toBeDisabled();expect(f.unexpected).toEqual([]);
 });
}
for(const [width,height]of [[390,844],[768,900],[1440,1000],[844,390]])test(`Master advertising Admin inventory and verified invoice recovery at ${width}px`,async({page},info)=>{
 const f=await p0OwnerFixture(page,{role:'admin',populated:true});await page.setViewportSize({width,height});await page.addInitScript(({key,session})=>localStorage.setItem(key,JSON.stringify(session)),{key:buildAuthStorageKeys(f.provider).admin,session:f.session});
 const space='44000000-0000-4000-8000-000000000001',id='33000000-0000-4000-8000-000000000001';let ads:AdminAds={spaces:[],reservations:[{id,business_name:'Own reviewed business',title:'Reviewed booking',status:'reserved',price_cents:10000,discount_cents:1500,credit_cents:1000,balance_cents:7500,expires_at:'2030-10-01T00:00:00Z',campaign_id:null}]};
 const posts:{action:string;input:Record<string,unknown>}[]=[];await page.route('**/api/admin/ad-spaces',r=>{if(r.request().method()==='POST'){const body=r.request().postDataJSON();posts.push(body);if(posts.length===1)return r.fulfill({status:503,json:{code:'AD_UNAVAILABLE',request_id:'55000000-0000-4000-8000-000000000001'}});if(body.action==='create')ads={...ads,spaces:[{...body.input,active:true}]};if(body.action==='fulfill')ads={...ads,reservations:ads.reservations.map(x=>({...x,status:'fulfilled',campaign_id:space}))};if(body.action==='close')ads={...ads,spaces:ads.spaces.map(x=>({...x,active:false}))};return r.fulfill({json:{ads,verified:true}});}return r.fulfill({json:{ads}});});
 await page.route('**/api/admin/featured-campaigns?**',r=>r.fulfill({json:{campaigns:[],salons:[],settings:{empty_title:'Fixture',empty_body:'Fixture',empty_href:'/partner'}}}));await page.route('**/api/admin/market-workspaces?**',r=>r.fulfill({json:{states:[],markets:[]}}));
 await page.goto('/internal/acceptance/admin-workflows/marketing/featured');const panel=page.getByRole('region',{name:'Plan advertising inventory',exact:true});await expect(panel).toContainText('Own reviewed business');
 await panel.getByLabel('Placement title',{exact:true}).fill('September space');await panel.getByLabel('Listed price (USD)',{exact:true}).fill('100');await panel.getByLabel('General access opens (at least 48 hours ahead)').fill('2030-09-05T10:00');await panel.getByLabel('Placement starts',{exact:true}).fill('2030-09-10T10:00');await panel.getByLabel('Placement ends',{exact:true}).fill('2030-09-17T10:00');await panel.getByLabel('I reviewed the price, availability and dates.').check();await panel.getByRole('button',{name:'Publish ad space',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('55000000-0000-4000-8000-000000000001');await expect(panel.getByLabel('Placement title',{exact:true})).toHaveValue('September space');await panel.getByRole('button',{name:'Publish ad space',exact:true}).click();await expect(panel.getByRole('status')).toHaveText('Saved and independently verified.');expect(posts[1]).toEqual(posts[0]);expect(posts[1].input.price_cents).toBe(10000);
 await panel.getByLabel('Verified invoice reference').fill('invoice-fixture-001');await panel.getByLabel('Verified received amount (USD)').fill('75');await panel.getByLabel('I verified the invoice, exact received amount and business.').check();await panel.getByRole('button',{name:'Confirm and schedule placement',exact:true}).click();await expect(panel).toContainText('fulfilled');expect(posts[2]).toEqual({action:'fulfill',input:{id,invoice_reference:'invoice-fixture-001',payment_verified:true,received_cents:7500}});await page.reload();await expect(panel).toContainText('fulfilled');await expect(panel.getByRole('button',{name:'Confirm and schedule placement',exact:true})).toHaveCount(0);await panel.getByRole('button',{name:'Close new reservations',exact:true}).click();await expect(panel).toContainText('Closed inventory');await page.reload();await expect(panel).toContainText('Closed inventory');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await panel.screenshot({path:info.outputPath('advertising-admin.png')});expect(f.unexpected).toEqual([]);
});
