import {expect} from '@playwright/test';import {test} from './helpers/hydration';import {p0OwnerFixture} from './helpers/p0OwnerFixture';import {MASTER_BUILD_COPY} from '../../src/i18n/master-build-source-catalog';
test.use({serviceWorkers:'block'});
for(const [locale,column,width,height]of [['en',0,390,844],['fr',1,768,900],['es',2,1440,1000],['zh-CN',3,844,390]] as const){
 test(`Master Google help review and recovery without live activation in ${locale}`,async({page},info)=>{
  const f=await p0OwnerFixture(page,{populated:true,locale});await page.setViewportSize({width,height});const t=(s:string)=>MASTER_BUILD_COPY.find(row=>row[0]===s)?.[column]||s;
  let providerWrites=0;await page.route('**/api/salon/integrations/google',r=>{if(r.request().method()==='POST')providerWrites++;return r.fulfill({json:{available:false,status:'deferred'}});});
  const ticket='44000000-0000-4000-8000-000000000001';let help={salon_id:f.business.id,level:'review',is_demo:false,fingerprint:'a'.repeat(32),fields:{name:'Save',phone:'+12125550100',description:'Original owner description',address:null,area:'Harlem',location_type:'home',mobile:false,radius_miles:null,page:'https://girlzculture.com/salon/owned-fixture',hours:{Monday:'09:00–17:00'}},review:{name:true,phone:true,description:true,hours:true,public_page:false,privacy_review_required:true},requests:[] as {id:string;kind:string;status:string;created_at:string}[]};
  const posts:Record<string,unknown>[]=[];await page.route('**/api/salon/google-help',r=>{if(r.request().method()==='POST'){const body=r.request().postDataJSON();posts.push(body);if(posts.length===1)return r.fulfill({status:503,json:{code:'GOOGLE_HELP_UNAVAILABLE',request_id:'55000000-0000-4000-8000-000000000001'}});help={...help,requests:[{id:ticket,kind:body.kind,status:'Open',created_at:new Date().toISOString()}]};return r.fulfill({json:{help,verified:true,ticket_id:ticket}});}return r.fulfill({json:{help}});});
  await page.goto('/salon/dashboard/settings/integrations');const panel=page.getByRole('region',{name:t('Google profile setup help'),exact:true});await expect(panel).toContainText('Original owner description');await expect(panel.locator('dd[data-no-translate]').filter({hasText:/^Save$/})).toHaveText('Save');
  const request=panel.getByRole('button',{name:t('Request a profile review'),exact:true});await expect(request).toBeDisabled();await panel.getByRole('checkbox').check();await request.click();await expect(panel.getByRole('alert')).toContainText('55000000-0000-4000-8000-000000000001');await expect(panel.getByRole('checkbox')).toBeChecked();await request.click();
  await expect(panel.getByRole('status')).toContainText(ticket);expect(posts[1]).toEqual(posts[0]);expect(posts[1]).toEqual({id:expect.any(String),kind:'profile_review',fingerprint:'a'.repeat(32)});
  await page.reload();await expect(panel.getByRole('list',{name:t('Your setup requests'),exact:true})).toContainText(ticket);await expect(panel.getByRole('checkbox')).not.toBeChecked();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await panel.screenshot({path:info.outputPath('google-help.png')});
  help={...help,is_demo:true};await page.reload();await expect(panel).toContainText(t('Demo businesses cannot send setup requests.'));await expect(panel.getByRole('checkbox')).toHaveCount(0);expect(providerWrites).toBe(0);expect(f.unexpected).toEqual([]);
 });
}
test('Master Google guide plan shows official guidance without paid setup actions',async({page})=>{await p0OwnerFixture(page,{populated:true});await page.route('**/api/salon/integrations/google',r=>r.fulfill({json:{available:false,status:'deferred'}}));await page.goto('/salon/dashboard/settings/integrations');const panel=page.getByRole('region',{name:'Google profile setup help',exact:true});await expect(panel).toContainText('Guide included');await expect(panel.getByRole('link')).toHaveCount(3);await expect(panel.getByRole('checkbox')).toHaveCount(0);await expect(panel.getByRole('button',{name:/Request/})).toHaveCount(0);for(const link of await panel.getByRole('link').all())expect(new URL((await link.getAttribute('href'))!).hostname).toBe('support.google.com');});
