import {expect} from '@playwright/test';
import {test} from './helpers/hydration';
import {p0OwnerFixture} from './helpers/p0OwnerFixture';
import {rescheduleAssistantCopy} from '../../src/i18n/assistant-reschedule-copy';
import {DASHBOARD_SOURCE_MESSAGES} from '../../src/i18n/dashboard-source-catalog';
import {intlLocale} from '../../src/i18n/catalog';
test.use({serviceWorkers:'block'});
const source=(locale:string,value:string)=>DASHBOARD_SOURCE_MESSAGES[locale]?.[value]||value;
for(const [locale,width,height] of [['en',390,844],['fr',768,1000],['es',1440,1000],['zh-CN',844,390]] as const){
 test(`P0 Assistant reschedule reviews unchanged terms and awaits customer acceptance in ${locale}`,async({page},info)=>{
  const f=await p0OwnerFixture(page,{populated:true,locale}),c=rescheduleAssistantCopy(locale);let confirmations=0;let id='';const original=JSON.stringify(f.records.bookings);
  await page.route('**/api/salon/assistant',async route=>{const body=route.request().postDataJSON();expect(route.request().headers().authorization).toBe(`Bearer ${f.session.access_token}`);
   if(body.action==='confirm'){expect(body).toMatchObject({request_id:id,digest:'d'.repeat(64),confirm:true});confirmations++;return route.fulfill({json:{verified:true,result:{booking_id:f.ids.booking,proposal_id:f.ids.service,status:'Pending',customer_acceptance_required:true,assistant_changed_booking:false},warnings:locale==='es'?[{code:'RESCHEDULE_NOTIFICATION_FAILED',request_id:'18000000-0000-4000-8000-000000000088'}]:[]}});}
   expect(body.action).toBe('plan');id=body.request_id;return route.fulfill({json:{preview_required:true,request:{id,tool:'prepare_booking_reschedule_proposal',risk_class:4,digest:'d'.repeat(64),confirmed_at:null,before_summary:{},arguments:{booking_id:f.ids.booking,date:'2099-10-20',time:'15:00',reason:'Customer requested later time',message:'Please review the proposed time.'},execution_payload:{customer_name:'Sarah GC180',public_reference:'GC-180',service_name:'Silk Press GC180',professional_name:'Aisha',previous_appointment_datetime:'2099-10-20T14:00:00.000Z',appointment_datetime:'2099-10-20T19:00:00.000Z',duration_hours:1,estimated_total:120,deposit_amount:12,time_zone:'America/New_York',reason:'Customer requested later time',message:'Please review the proposed time.'}}}});
  });
  await page.setViewportSize({width,height});await page.goto('/salon/dashboard/bookings');await expect(page.locator('[data-owner-workspace]')).toBeVisible();const dialog=page.getByRole('dialog',{name:'GC Assistant',exact:true});if(!await dialog.isVisible())await page.getByRole('button',{name:'GC Assistant',exact:true}).click();
  await dialog.locator('textarea').fill('Propose moving Sarah on October 20 to 3 PM with Aisha because the customer requested a later time.');await dialog.getByRole('button',{name:source(locale,'Ask GC Assistant'),exact:true}).click();
  await expect(dialog.getByText(c.intro,{exact:true})).toBeVisible();await expect(dialog).toContainText('Sarah GC180');await expect(dialog).toContainText('Aisha');await expect(dialog).toContainText('Silk Press GC180');
  for(const amount of [120,12])await expect(dialog.getByText(new Intl.NumberFormat(intlLocale(locale),{style:'currency',currency:'USD'}).format(amount),{exact:true})).toBeVisible();
  for(const time of ['2099-10-20T14:00:00.000Z','2099-10-20T19:00:00.000Z'])await expect(dialog.getByText(new Intl.DateTimeFormat(intlLocale(locale),{dateStyle:'medium',timeStyle:'short',timeZone:'America/New_York'}).format(new Date(time)),{exact:true})).toBeVisible();
  expect(confirmations).toBe(0);expect(JSON.stringify(f.records.bookings)).toBe(original);const confirm=dialog.getByRole('button',{name:c.confirm,exact:true});await confirm.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`assistant-reschedule-${locale}-${width}.png`)});await confirm.click();
  await expect(dialog.getByText(c.pending,{exact:true})).toBeVisible();expect(confirmations).toBe(1);expect(JSON.stringify(f.records.bookings)).toBe(original);await expect(confirm).toHaveCount(0);await expect(dialog.getByText(source(locale,'Your change was saved and verified.'),{exact:true})).toHaveCount(0);
  if(locale==='es'){await expect(dialog).toContainText(c.warning);await expect(dialog).toContainText('18000000-0000-4000-8000-000000000088');}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 });
}
test('P0 Assistant reschedule retains exact preview after failed readback and reports accepted replay honestly',async({page})=>{
 const f=await p0OwnerFixture(page,{populated:true});let attempts=0,id='';let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/api/salon/assistant',async route=>{const b=route.request().postDataJSON();if(b.action==='confirm'){expect(b.request_id).toBe(id);expect(b.digest).toBe('d'.repeat(64));attempts++;if(attempts===1){await held;return route.fulfill({status:409,json:{code:'ASSISTANT_READBACK_FAILED',request_id:'18000000-0000-4000-8000-000000000089'}});}return route.fulfill({json:{verified:true,replayed:true,result:{proposal_id:f.ids.booking,status:'Accepted'}}});}id=b.request_id;return route.fulfill({json:{preview_required:true,request:{id,tool:'prepare_booking_reschedule_proposal',risk_class:4,digest:'d'.repeat(64),confirmed_at:null,before_summary:{},arguments:{},execution_payload:{customer_name:'Sarah',service_name:'Silk Press',professional_name:'Aisha',previous_appointment_datetime:'2099-10-20T14:00:00Z',appointment_datetime:'2099-10-20T19:00:00Z',duration_hours:1,estimated_total:120,deposit_amount:12,time_zone:'America/New_York'}}}});});
 await page.setViewportSize({width:390,height:844});await page.goto('/salon/dashboard/bookings');await page.getByRole('button',{name:'GC Assistant',exact:true}).click();const dialog=page.getByRole('dialog',{name:'GC Assistant',exact:true});await dialog.locator('textarea').fill('Propose Sarah for 3 PM on October 20.');await dialog.getByRole('button',{name:'Ask GC Assistant',exact:true}).click();const confirm=dialog.getByRole('button',{name:rescheduleAssistantCopy('en').confirm,exact:true});await confirm.click();await expect.poll(()=>attempts).toBe(1);await expect(confirm).toBeDisabled();release();await expect(dialog).toContainText('18000000-0000-4000-8000-000000000089');await expect(confirm).toBeEnabled();await confirm.click();await expect(dialog.getByText(rescheduleAssistantCopy('en').accepted,{exact:true})).toBeVisible();await expect(dialog.getByText(rescheduleAssistantCopy('en').pending,{exact:true})).toHaveCount(0);expect(attempts).toBe(2);
});
