begin;
create function pg_temp.reminder_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'Reminder assertion failed: %',label;end if;end $$;
do $$
declare owner_id uuid:=gen_random_uuid(); business uuid:=gen_random_uuid(); service uuid:=gen_random_uuid(); booking uuid:=gen_random_uuid(); professional uuid:=gen_random_uuid(); claim uuid; blocked boolean:=false; item uuid;
begin
 insert into auth.users(id,email,encrypted_password,email_confirmed_at,raw_user_meta_data) values(owner_id,'reminder@example.test','',now(),'{"role":"salon_owner"}');
 insert into public.salons(id,user_id,name,slug,email,status,subscription_status,subscription_tier) values(business,owner_id,'Reminder test','reminder-test','reminder@example.test','Active','active','Premium');
 insert into public.styles(id,salon_id,service_group_id,name,duration_min_hours,duration_max_hours,base_price,price_display_min,price_display_max) select service,business,id,'Original service',1,1,100,100,100 from public.service_groups where is_active and archived_at is null limit 1;
 insert into public.stylists(id,salon_id,name) values(professional,business,'Another professional');
 insert into public.bookings(id,salon_id,style_id,appointment_datetime,duration_hours,estimated_total,deposit_amount,balance_due,deposit_status,status) values(booking,business,service,now()+interval '24 hours',3,100,10,90,'Paid','Confirmed');
 perform pg_temp.reminder_assert(public.claim_booking_reminder(booking,24,0),'first schedule can claim');
 perform pg_temp.reminder_assert(not public.claim_booking_reminder(booking,24,0),'active lease cannot claim twice');
 claim:=public.claim_scheduled_notification_delivery(booking,'booking_reminder_24h','customer','email','fixture@example.test',booking||':reminder:r0',0);
 perform pg_temp.reminder_assert(claim is not null,'current confirmed schedule claims channel');
 update public.notification_delivery_log set delivery_status='delivered' where id=claim;
 perform public.complete_booking_reminder(booking,24,0);
 perform pg_temp.reminder_assert(not public.claim_booking_reminder(booking,24,0),'completed schedule cannot send twice');
 update public.bookings set appointment_datetime=now()+interval '24 hours 15 minutes' where id=booking;
 perform pg_temp.reminder_assert((select schedule_revision=1 from public.bookings where id=booking),'reschedule advances exactly once');
 perform pg_temp.reminder_assert(not public.claim_booking_reminder(booking,24,0) and not public.claim_booking_reminder(booking,24),'stale and legacy workers cannot claim changed schedule');
 perform pg_temp.reminder_assert(public.claim_booking_reminder(booking,24,1),'rescheduled appointment receives its own reminder');
 perform pg_temp.reminder_assert((select count(*)=2 from public.booking_reminder_claims where booking_id=booking),'old delivery history retained');
 perform set_config('app.reminder_complete_revision','',true);
 begin update public.booking_reminder_claims set completed_at=now() where booking_id=booking and reminder_hours=24; exception when others then if sqlerrm='REMINDER_REVISION_REQUIRED' then blocked:=true;else raise;end if;end;
 perform pg_temp.reminder_assert(blocked,'old broad completion cannot complete new schedule');
 perform pg_temp.reminder_assert((select completed_at is null from public.booking_reminder_claims where booking_id=booking and schedule_revision=1),'new claim still pending');
 perform pg_temp.reminder_assert(public.claim_scheduled_notification_delivery(booking,'booking_reminder_24h','customer','email','fixture@example.test',booking||':reminder:r0',0) is null,'stale channel blocked');
 claim:=public.claim_scheduled_notification_delivery(booking,'booking_reminder_24h','customer','email','fixture@example.test',booking||':reminder:r1',1);
 perform pg_temp.reminder_assert(claim is not null,'new schedule channel not suppressed by prior delivery');
 update public.bookings set schedule_revision=200,status='Confirmed' where id=booking;
 perform pg_temp.reminder_assert((select schedule_revision=1 from public.bookings where id=booking),'clients cannot manufacture revision');
 update public.bookings set status='Cancelled' where id=booking;
 perform pg_temp.reminder_assert(public.claim_scheduled_notification_delivery(booking,'booking_reminder_24h','customer','sms','000',booking||':reminder:sms:r1',1) is null,'cancelled after batch claim cannot reserve next channel');
 perform pg_temp.reminder_assert(not exists(select from public.due_booking_reminders(24) where id=booking),'cancelled not queued');
 update public.bookings set status='Confirmed',stylist_id=professional where id=booking;
 perform pg_temp.reminder_assert((select schedule_revision=2 from public.bookings where id=booking),'accepted substitute is new schedule');
 perform pg_temp.reminder_assert(public.claim_booking_reminder(booking,24,2),'substitute receives fresh reminder');
 perform pg_temp.reminder_assert(public.fail_booking_reminder_claim(booking,24,'exact-incident',2)='retryable','failure retains retryable state');
 perform pg_temp.reminder_assert(not public.claim_booking_reminder(booking,24,2),'backoff enforced');
 update public.booking_reminder_claims set next_attempt_at=now()-interval '1 second' where booking_id=booking and schedule_revision=2;
 perform pg_temp.reminder_assert(public.claim_booking_reminder(booking,24,2),'failed schedule retries after due');
 perform public.fail_booking_reminder_claim(booking,24,'exact-incident',2);
 update public.booking_reminder_claims set next_attempt_at=now()-interval '1 second' where booking_id=booking and schedule_revision=2;
 perform pg_temp.reminder_assert(public.claim_booking_reminder(booking,24,2),'third attempt');
 perform pg_temp.reminder_assert(public.fail_booking_reminder_claim(booking,24,'exact-incident',2)='terminal','bounded failure');
 perform pg_temp.reminder_assert((select error_message='REMINDER_PERMANENT_FAILURE_REFERENCE:exact-incident' from public.booking_reminder_claims where booking_id=booking and schedule_revision=2),'exact incident retained');
 perform pg_temp.reminder_assert(not exists(select from public.due_booking_reminders(24) where id=booking),'terminal claim not queued');
 -- Earlier completed rows must not fill the selection batch forever.
 for i in 1..251 loop
  item:=gen_random_uuid();professional:=gen_random_uuid();
  insert into public.stylists(id,salon_id,name) values(professional,business,'Queue professional '||i);
  insert into public.bookings(id,salon_id,style_id,stylist_id,appointment_datetime,duration_hours,estimated_total,deposit_amount,balance_due,deposit_status,status) values(item,business,service,professional,now()+interval '24 hours'+make_interval(secs=>i),1,100,10,90,'Paid','Confirmed');
  if i<=250 then perform public.claim_booking_reminder(item,24,0);perform public.complete_booking_reminder(item,24,0);end if;
 end loop;
 perform pg_temp.reminder_assert(exists(select from public.due_booking_reminders(24) where id=item),'251st due booking not starved by completed first 250');
 perform pg_temp.reminder_assert(not has_function_privilege('authenticated','public.due_booking_reminders(integer)','execute') and not has_function_privilege('anon','public.claim_scheduled_notification_delivery(uuid,text,text,text,text,text,integer)','execute'),'client roles cannot read scheduler or reserve other business deliveries');
 perform pg_temp.reminder_assert(not has_function_privilege('authenticated','public.complete_booking_reminder(uuid,integer,integer)','execute') and has_function_privilege('service_role','public.complete_booking_reminder(uuid,integer,integer)','execute'),'completion restricted to worker');
end $$;
rollback;
select 'Reminder revision, cancellation, retry, history and queue assertions passed' as result;
