-- Disposable local database only. Real invoker/service role; all fixtures roll back.
begin;
create function pg_temp.schedule_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'Schedule guard assertion failed: %',label;end if;end $$;
create function pg_temp.schedule_reject(command text,expected text) returns void language plpgsql as $$declare rejected boolean:=false;begin begin execute command;exception when others then if position(expected in sqlerrm)>0 then rejected:=true;else raise;end if;end;perform pg_temp.schedule_assert(rejected,expected);end $$;
do $$
declare salon uuid:=gen_random_uuid();actor uuid:=gen_random_uuid();other_actor uuid:=gen_random_uuid();lease uuid:=gen_random_uuid();second_lease uuid:=gen_random_uuid();a jsonb;staged jsonb;first_schedule text;first_method text;
 baseline jsonb:=jsonb_build_object('fingerprint',repeat('a',64),'subscription_fingerprint',repeat('b',64),'default_method',null,'schedule',jsonb_build_object('id','sub_sched_fixture','subscription','sub_schedule_fixture','customer','cus_schedule_fixture','livemode',false));
 before_subscription jsonb;
begin
 insert into auth.users(id,email,encrypted_password,email_confirmed_at,raw_user_meta_data)values(actor,'schedule-'||actor||'@example.test','',now(),'{"role":"salon_owner"}'),(other_actor,'schedule-'||other_actor||'@example.test','',now(),'{"role":"salon_owner"}');
 insert into public.salons(id,user_id,email,name,slug,status)values(salon,actor,'schedule-'||actor||'@example.test','Local schedule fixture','schedule-'||salon,'Pending');
 insert into public.subscriptions(salon_id,tier,status,stripe_customer_id,stripe_subscription_id)values(salon,'Premium','active','cus_schedule_fixture','sub_schedule_fixture');
 select to_jsonb(s) into before_subscription from public.subscriptions s where salon_id=salon;
 perform pg_temp.schedule_assert(not has_table_privilege('authenticated','public.subscription_mutation_leases','select'),'browser cannot read private provider intents');
 perform pg_temp.schedule_assert(not has_function_privilege('anon','public.mark_payment_schedule_apply(uuid,uuid,text,text,boolean,text)','execute'),'anonymous cannot mark a provider stage');
 perform pg_temp.schedule_assert(not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in('acquire_subscription_mutation','assert_subscription_mutation','release_subscription_mutation','reserve_scheduled_payment_method_attempt','mark_payment_schedule_apply')and prosecdef),'invoker only');
 set local role service_role;
 perform pg_temp.schedule_reject(format('select public.acquire_subscription_mutation(%L,%L,%L,%L)',salon,other_actor,'sub_schedule_fixture',lease),'SUBSCRIPTION_MUTATION_IDENTITY_CONFLICT');
 perform pg_temp.schedule_assert(public.acquire_subscription_mutation(salon,actor,'sub_schedule_fixture',lease),'owner can acquire lifecycle lease');
 perform pg_temp.schedule_assert(public.assert_subscription_mutation(salon,actor,'sub_schedule_fixture',lease),'read-only preview can assert a lease');
 perform pg_temp.schedule_assert((select not write_started from public.subscription_mutation_leases where stripe_subscription_id='sub_schedule_fixture'),'read-only preview does not mark a mutation');
 perform pg_temp.schedule_reject(format('select public.acquire_subscription_mutation(%L,%L,%L,%L)',salon,actor,'sub_schedule_fixture',second_lease),'SUBSCRIPTION_MUTATION_BUSY');
 perform pg_temp.schedule_reject(format('select public.reserve_subscription_payment_method_attempt(%L,%L,%L,%L,false)',salon,actor,'cus_schedule_fixture','sub_schedule_fixture'),'SUBSCRIPTION_MUTATION_BUSY');
 perform pg_temp.schedule_assert(public.record_subscription_mutation_request(salon,actor,'sub_schedule_fixture',lease,'{"path":"/subscriptions/sub_schedule_fixture","values":{"cancel_at_period_end":true},"idempotency_key":"fixture-only","baseline_hashes":{}}'),'intent recorded before provider boundary');
 perform pg_temp.schedule_assert(public.record_subscription_mutation_response(salon,actor,'sub_schedule_fixture',lease,'req_fixture'),'safe provider request id recorded');
 update public.subscription_mutation_leases set expires_at=now()-interval '1 second' where stripe_subscription_id='sub_schedule_fixture';
 perform pg_temp.schedule_reject(format('select public.acquire_subscription_mutation(%L,%L,%L,%L)',salon,actor,'sub_schedule_fixture',second_lease),'SUBSCRIPTION_MUTATION_REVIEW_REQUIRED');
 perform pg_temp.schedule_reject(format('select public.reserve_subscription_payment_method_attempt(%L,%L,%L,%L,false)',salon,actor,'cus_schedule_fixture','sub_schedule_fixture'),'SUBSCRIPTION_MUTATION_BUSY');
 perform pg_temp.schedule_assert(not public.release_subscription_mutation(salon,actor,'sub_schedule_fixture',second_lease),'foreign generation cannot clear uncertainty hold');
 perform pg_temp.schedule_assert(public.release_subscription_mutation(salon,actor,'sub_schedule_fixture',lease),'same verified operation can release');
 a:=public.reserve_scheduled_payment_method_attempt(salon,actor,'cus_schedule_fixture','sub_schedule_fixture',false,'pm_old',baseline);
 perform pg_temp.schedule_assert(a->'schedule_baseline'=baseline,'exact schedule baseline is durable');
 perform pg_temp.schedule_reject(format('select public.acquire_subscription_mutation(%L,%L,%L,%L)',salon,actor,'sub_schedule_fixture',second_lease),'SUBSCRIPTION_MUTATION_BUSY');
 perform public.bind_subscription_payment_method_attempt((a->>'id')::uuid,'cs_schedule_fixture');
 perform public.claim_subscription_payment_method_attempt((a->>'id')::uuid,'cs_schedule_fixture',lease);
 staged:=public.mark_payment_schedule_apply((a->>'id')::uuid,lease,'seti_fixture','pm_new');first_schedule:=staged->>'schedule_first_apply_at';
 perform pg_temp.schedule_assert(first_schedule is not null and staged->>'first_apply_at' is null,'schedule stage has independent first-send clock');
 perform pg_temp.schedule_reject(format('select public.mark_payment_schedule_apply(%L,%L,%L,%L)',a->>'id',lease,'seti_fixture','pm_other'),'PAYMENT_METHOD_APPLY_IDENTITY_CONFLICT');
 update public.subscription_payment_method_attempts set lease_expires_at=now()-interval '1 second' where id=(a->>'id')::uuid;
 perform public.claim_subscription_payment_method_attempt((a->>'id')::uuid,'cs_schedule_fixture',second_lease);
 staged:=public.mark_payment_schedule_apply((a->>'id')::uuid,second_lease,'seti_fixture','pm_new',true,'req_schedule');
 perform pg_temp.schedule_assert(staged->>'schedule_first_apply_at'=first_schedule and staged->>'schedule_request_id'='req_schedule','recovery preserves stage clock and request evidence');
 staged:=public.mark_subscription_payment_method_apply((a->>'id')::uuid,second_lease,'seti_fixture','pm_new');first_method:=staged->>'first_apply_at';
 perform pg_temp.schedule_assert(first_method is not null and staged->>'schedule_first_apply_at'=first_schedule,'current subscription stage is separate');
 reset role;
 update public.salons set user_id=other_actor,email='schedule-'||other_actor||'@example.test' where id=salon;
 set local role service_role;
 perform pg_temp.schedule_reject(format('select public.mark_payment_schedule_apply(%L,%L,%L,%L,true)',a->>'id',second_lease,'seti_fixture','pm_new'),'PAYMENT_METHOD_OWNER_IDENTITY_CONFLICT');
 reset role;
 update public.salons set user_id=actor,email='schedule-'||actor||'@example.test' where id=salon;
 set local role service_role;
 perform pg_temp.schedule_assert(public.finish_subscription_payment_method_attempt((a->>'id')::uuid,second_lease,'completed','seti_fixture','pm_new','req_subscription'),'verified method result completes');
 perform pg_temp.schedule_assert(public.acquire_subscription_mutation(salon,actor,'sub_schedule_fixture',lease),'terminal method result permits later lifecycle change');
 perform pg_temp.schedule_assert(public.release_subscription_mutation(salon,actor,'sub_schedule_fixture',lease),'later lifecycle releases');
 reset role;
 perform pg_temp.schedule_assert((select to_jsonb(s)=before_subscription from public.subscriptions s where salon_id=salon),'guard RPCs never mutate subscription commercial data');
end $$;
rollback;
