-- Synthetic rollback-only proposal, substitution, authorization and retry checks.
begin;
create function pg_temp.change_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'Appointment change assertion failed: %',label;end if;end $$;
create function pg_temp.change_reject(command text,expected text) returns void language plpgsql as $$declare rejected boolean:=false;begin begin execute command;exception when others then if position(expected in sqlerrm)>0 then rejected:=true;else raise;end if;end;perform pg_temp.change_assert(rejected,expected);end $$;
do $$
declare oa uuid:=gen_random_uuid();ob uuid:=gen_random_uuid();staff uuid:=gen_random_uuid();ba uuid:=gen_random_uuid();bb uuid:=gen_random_uuid();service uuid:=gen_random_uuid();booking uuid:=gen_random_uuid();pa uuid:=gen_random_uuid();pb uuid:=gen_random_uuid();foreign_prof uuid:=gen_random_uuid();proposal uuid;again uuid;option_id uuid;req uuid:=gen_random_uuid();opts jsonb;original jsonb;result public.bookings;token_a jsonb;token_b jsonb;
begin
 insert into auth.users(id,email,encrypted_password,email_confirmed_at,raw_user_meta_data) values(oa,'change-a@example.test','',now(),'{"role":"salon_owner"}'),(ob,'change-b@example.test','',now(),'{"role":"salon_owner"}'),(staff,'change-staff@example.test','',now(),'{"role":"salon_team"}');
 update public.platform_identities set primary_role='salon_team' where user_id=staff;
 insert into public.salons(id,user_id,name,slug,email,status,subscription_status,subscription_tier) values(ba,oa,'Change A','change-a','change-a@example.test','Active','active','Premium'),(bb,ob,'Change B','change-b','change-b@example.test','Active','active','Premium');
 insert into public.styles(id,salon_id,service_group_id,name,duration_min_hours,duration_max_hours,base_price,price_display_min,price_display_max) select service,ba,id,'Original named service',1,1,250,250,250 from public.service_groups where is_active and archived_at is null limit 1;
 insert into public.stylists(id,salon_id,name,is_active,is_draft) values(pa,ba,'Original professional',true,false),(pb,ba,'Substitute professional',true,false),(foreign_prof,bb,'Foreign professional',true,false);
 insert into public.salon_team_members(salon_id,user_id,email,name,role,status,permissions,stylist_id) values(ba,staff,'change-staff@example.test','Assigned staff','Stylist','Active','{"bookings":true}',pb);
 insert into public.bookings(id,salon_id,style_id,stylist_id,appointment_datetime,duration_hours,estimated_total,deposit_amount,balance_due,deposit_status,status) values(booking,ba,service,pa,now()+interval '3 days',3,100,10,90,'Paid','Confirmed');
 select to_jsonb(b) into original from public.bookings b where id=booking;
 opts:=jsonb_build_array(jsonb_build_object('appointment_datetime',now()+interval '3 days','duration_hours',3,'stylist_id',pb));
 perform pg_temp.change_reject(format('select public.create_booking_reschedule_proposal(%L,%L,%L,%L,%L,null,%L::jsonb,now()+interval ''1 day'',%L)',booking,ba,ob,'Salon owner','Proposal',opts,req),'RESCHEDULE_FORBIDDEN');
 perform pg_temp.change_reject(format('select public.create_booking_reschedule_proposal(%L,%L,%L,%L,%L,null,%L::jsonb,now()+interval ''1 day'',%L)',booking,ba,staff,'Salon owner','Proposal',opts,req),'RESCHEDULE_FORBIDDEN');
 proposal:=public.create_booking_reschedule_proposal(booking,ba,oa,'Salon owner','Original reason $100',null,opts,now()+interval '1 day',req);
 again:=public.create_booking_reschedule_proposal(booking,ba,oa,'Salon owner','Original reason $100',null,opts,now()+interval '2 days',req);
 perform pg_temp.change_assert(again=proposal and (select count(*)=1 from public.booking_reschedule_proposals where booking_id=booking),'same request creates one proposal');
 perform pg_temp.change_assert((select to_jsonb(b)=original from public.bookings b where id=booking),'proposal does not alter any booked terms');
 perform pg_temp.change_reject(format('select public.create_booking_reschedule_proposal(%L,%L,%L,%L,%L,null,%L::jsonb,now()+interval ''1 day'',%L)',booking,ba,oa,'Salon owner','Changed reason',opts,req),'RESCHEDULE_REQUEST_REUSED');
 perform pg_temp.change_reject(format('select public.create_booking_reschedule_proposal(%L,%L,%L,%L,%L,null,%L::jsonb,now()+interval ''1 day'',gen_random_uuid())',booking,ba,oa,'Salon owner','Foreign professional',jsonb_set(opts,'{0,stylist_id}',to_jsonb(foreign_prof))),'RESCHEDULE_STYLIST_UNAVAILABLE');
 perform pg_temp.change_reject(format('select public.create_booking_reschedule_proposal(%L,%L,%L,%L,%L,null,%L::jsonb,now()+interval ''1 day'',gen_random_uuid())',booking,ba,oa,'Salon owner','Shorter service',jsonb_set(opts,'{0,duration_hours}','1')),'RESCHEDULE_BOOKED_DURATION_REQUIRED');
 select id into option_id from public.booking_reschedule_options where proposal_id=proposal;
 update public.stylists set assigned_service_ids='{}' where id=pb;
 perform pg_temp.change_reject(format('select public.respond_booking_reschedule(%L,%L,''accept'')',proposal,option_id),'RESCHEDULE_STYLIST_UNAVAILABLE');
 update public.stylists set assigned_service_ids=array[service] where id=pb;
 insert into public.salon_blockouts(salon_id,stylist_id,starts_at,ends_at,reason) values(ba,pb,now()+interval '3 days',now()+interval '3 days 4 hours','Synthetic conflict');
 perform pg_temp.change_reject(format('select public.respond_booking_reschedule(%L,%L,''accept'')',proposal,option_id),'BOOKING_RESOURCE_CONFLICT');
 delete from public.salon_blockouts where salon_id=ba;
 result:=public.respond_booking_reschedule(proposal,null,'decline');
 perform pg_temp.change_assert(result.stylist_id=pa and result.duration_hours=3 and result.estimated_total=100 and result.deposit_amount=10 and result.balance_due=90,'decline preserves original appointment and money');
 proposal:=public.create_booking_reschedule_proposal(booking,ba,oa,'Salon owner','Customer approved substitution',null,opts,now()+interval '1 day',gen_random_uuid());
 select id into option_id from public.booking_reschedule_options where proposal_id=proposal;
 result:=public.respond_booking_reschedule(proposal,option_id,'accept');
 perform pg_temp.change_assert(result.stylist_id=pb and result.appointment_datetime=(original->>'appointment_datetime')::timestamptz and result.duration_hours=3 and result.estimated_total=100 and result.deposit_amount=10 and result.balance_due=90,'accept changes professional only; current catalog price and duration never replace booking');
 perform pg_temp.change_reject(format('select public.respond_booking_reschedule(%L,%L,''accept'')',proposal,option_id),'RESCHEDULE_PROPOSAL_UNAVAILABLE');
 opts:=jsonb_set(opts,'{0,stylist_id}',to_jsonb(pa));
 proposal:=public.create_booking_reschedule_proposal(booking,ba,oa,'Salon owner','Stale appointment',null,opts,now()+interval '1 day',gen_random_uuid());
 select id into option_id from public.booking_reschedule_options where proposal_id=proposal;
 update public.bookings set duration_hours=4 where id=booking;
 perform pg_temp.change_reject(format('select public.respond_booking_reschedule(%L,%L,''accept'')',proposal,option_id),'RESCHEDULE_PROPOSAL_UNAVAILABLE');
 token_a:=public.claim_booking_communication_token(booking,gen_random_uuid(),repeat('a',64),now()+interval '1 day');
 token_b:=public.claim_booking_communication_token(booking,gen_random_uuid(),repeat('b',64),now()+interval '1 day');
 perform pg_temp.change_assert(token_a=token_b and (select count(*)=1 from public.booking_guest_access_tokens where booking_id=booking and revoked_at is null),'notification retry reuses the same still-valid link');
 perform pg_temp.change_assert((select count(*)=1 from public.booking_guest_access_audit where booking_id=booking and action='issued'),'issuance audit is kept without recording another issuance on reuse');
 perform pg_temp.change_assert(not has_function_privilege('authenticated','public.claim_booking_communication_token(uuid,uuid,text,timestamptz)','EXECUTE'),'no client token generation');
 perform pg_temp.change_assert(not has_function_privilege('service_role','public.respond_booking_reschedule_internal(uuid,uuid,text)','EXECUTE'),'no bypass of current appointment checks');
 perform pg_temp.change_assert(not has_function_privilege('authenticated','public.create_booking_reschedule_proposal(uuid,uuid,uuid,text,text,text,jsonb,timestamptz,uuid)','EXECUTE'),'no direct proposal creation');
end $$;
rollback;
