-- Disposable local database only. No Stripe calls; actual service_role and rollback.
begin;
create function pg_temp.phase_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'Explicit phase assertion failed: %',label;end if;end $$;
create function pg_temp.phase_reject(command text,expected text) returns void language plpgsql as $$declare rejected boolean:=false;begin begin execute command;exception when others then if position(expected in sqlerrm)>0 then rejected:=true;else raise;end if;end;perform pg_temp.phase_assert(rejected,expected);end $$;
do $$
declare salon uuid:=gen_random_uuid();actor uuid:=gen_random_uuid();other_actor uuid:=gen_random_uuid();lease uuid:=gen_random_uuid();retry uuid:=gen_random_uuid();a jsonb;baseline jsonb;plan jsonb;bad jsonb;first_clock text;before_subscription jsonb;
 source jsonb:='{"id":"sub_sched_phase_fixture","object":"subscription_schedule","customer":"cus_phase_fixture","subscription":"sub_phase_fixture","livemode":false,"status":"active","current_phase":{"start_date":100,"end_date":200},"default_settings":{"default_payment_method":null,"collection_method":"charge_automatically"},"phases":[{"start_date":0,"end_date":100,"default_payment_method":"pm_past","items":[{"price":"price_past","quantity":1}]},{"start_date":100,"end_date":200,"default_payment_method":"pm_old","items":[{"price":"price_current","quantity":1}]},{"start_date":200,"end_date":300,"default_payment_method":null,"items":[{"price":"price_future","quantity":2}]}],"metadata":{"agreement":"preserve"},"end_behavior":"release"}';
 empty jsonb:='{"phases[1].discounts":"inherit","phases[1].items[0].discounts":"none"}';
begin
 insert into auth.users(id,email,encrypted_password,email_confirmed_at,raw_user_meta_data)values(actor,'phase-'||actor||'@example.test','',now(),'{"role":"salon_owner"}'),(other_actor,'phase-'||other_actor||'@example.test','',now(),'{"role":"salon_owner"}');
 insert into public.salons(id,user_id,email,name,slug,status)values(salon,actor,'phase-'||actor||'@example.test','Local phase fixture','phase-'||salon,'Pending');
 insert into public.subscriptions(salon_id,tier,status,stripe_customer_id,stripe_subscription_id)values(salon,'Premium','active','cus_phase_fixture','sub_phase_fixture');
 select to_jsonb(s)into before_subscription from public.subscriptions s where salon_id=salon;
 perform pg_temp.phase_assert(not has_table_privilege('authenticated','public.subscription_payment_schedule_intents','select'),'private intent not browser readable');
 perform pg_temp.phase_assert(not has_function_privilege('anon','public.prepare_payment_phase_apply(uuid,uuid,text,text,jsonb)','execute'),'anonymous cannot prepare');
 perform pg_temp.phase_assert(not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in('prepare_payment_phase_apply','archive_payment_phase_intent')and prosecdef),'service-only invoker');
 set local role service_role;
 perform public.acquire_subscription_mutation(salon,actor,'sub_phase_fixture',lease);
 perform pg_temp.phase_reject(format('select public.archive_payment_phase_intent(%L,%L,%L,%L,%L,%L)',salon,other_actor,'sub_phase_fixture',lease,source,empty),'PAYMENT_METHOD_LEASE_LOST');
 perform pg_temp.phase_reject(format('select public.archive_payment_phase_intent(%L,%L,%L,%L,%L,%L)',salon,actor,'sub_phase_fixture',lease,source,empty),'PAYMENT_SCHEDULE_INTENT_UNVERIFIED');
 perform public.record_subscription_mutation_request(salon,actor,'sub_phase_fixture',lease,'{"path":"/subscription_schedules/sub_sched_phase_fixture","values":{"phases[0][default_payment_method]":"pm_old"},"idempotency_key":"phase_fixture","baseline_hashes":{}}');
 perform public.record_subscription_mutation_response(salon,actor,'sub_phase_fixture',lease,'req_verified');
 perform pg_temp.phase_assert(public.archive_payment_phase_intent(salon,actor,'sub_phase_fixture',lease,source,empty),'exact verified source archived');
 perform public.release_subscription_mutation(salon,actor,'sub_phase_fixture',lease);
 baseline:=jsonb_build_object('kind','explicit_phases','api_version','2025-06-30.basil','fingerprint',repeat('a',64),'subscription_fingerprint',repeat('b',64),'default_method',null,'schedule',source,'empty_discounts',empty);
 plan:=jsonb_build_object('api_version','2025-06-30.basil','source_fingerprint',repeat('c',64),'expected_fingerprint',repeat('d',64),'request_fingerprint',repeat('e',64),'target_method','pm_new','request',jsonb_build_object('proration_behavior','none','default_settings[default_payment_method]','pm_new'),'expected_state',jsonb_set(jsonb_set(source,'{default_settings,default_payment_method}','"pm_new"'),'{phases,1,default_payment_method}','"pm_new"'));
 a:=public.reserve_scheduled_payment_method_attempt(salon,actor,'cus_phase_fixture','sub_phase_fixture',false,'pm_old',baseline);
 perform public.bind_subscription_payment_method_attempt((a->>'id')::uuid,'cs_phase_fixture');
 perform public.claim_subscription_payment_method_attempt((a->>'id')::uuid,'cs_phase_fixture',lease);
 perform pg_temp.phase_reject(format('select public.mark_payment_schedule_apply(%L,%L,%L,%L)',a->>'id',lease,'seti_phase','pm_new'),'PAYMENT_SCHEDULE_DURABLE_PLAN_MISSING');
 bad:=jsonb_set(plan,'{expected_state,phases,2,items,0,quantity}','9');
 perform pg_temp.phase_reject(format('select public.prepare_payment_phase_apply(%L,%L,%L,%L,%L)',a->>'id',lease,'seti_phase','pm_new',bad),'PAYMENT_SCHEDULE_PLAN_COMMERCIAL_CHANGE');
 bad:=jsonb_set(plan,'{expected_state,phases,0,default_payment_method}','"pm_new"');
 perform pg_temp.phase_reject(format('select public.prepare_payment_phase_apply(%L,%L,%L,%L,%L)',a->>'id',lease,'seti_phase','pm_new',bad),'PAYMENT_SCHEDULE_PLAN_COMMERCIAL_CHANGE');
 bad:=jsonb_set(plan,'{expected_state,phases,2,default_payment_method}','"pm_new"');
 perform pg_temp.phase_reject(format('select public.prepare_payment_phase_apply(%L,%L,%L,%L,%L)',a->>'id',lease,'seti_phase','pm_new',bad),'PAYMENT_SCHEDULE_PLAN_COMMERCIAL_CHANGE');
 a:=public.prepare_payment_phase_apply((a->>'id')::uuid,lease,'seti_phase','pm_new',plan);
 perform pg_temp.phase_assert(a->'phase_apply_plan'=plan and a->'schedule_first_apply_at'='null'::jsonb,'payload durable before first send');
 bad:=jsonb_set(plan,'{request_fingerprint}',to_jsonb(repeat('f',64)));
 perform pg_temp.phase_reject(format('select public.prepare_payment_phase_apply(%L,%L,%L,%L,%L)',a->>'id',lease,'seti_phase','pm_new',bad),'PAYMENT_SCHEDULE_DURABLE_PLAN_CONFLICT');
 a:=public.mark_payment_schedule_apply((a->>'id')::uuid,lease,'seti_phase','pm_new');first_clock:=a->>'schedule_first_apply_at';
 perform pg_temp.phase_reject(format('select public.acquire_subscription_mutation(%L,%L,%L,%L)',salon,actor,'sub_phase_fixture',retry),'SUBSCRIPTION_MUTATION_BUSY');
 update public.subscription_payment_method_attempts set lease_expires_at=now()-interval '1 second'where id=(a->>'id')::uuid;
 perform public.claim_subscription_payment_method_attempt((a->>'id')::uuid,'cs_phase_fixture',retry);
 a:=public.prepare_payment_phase_apply((a->>'id')::uuid,retry,'seti_phase','pm_new',plan);
 a:=public.mark_payment_schedule_apply((a->>'id')::uuid,retry,'seti_phase','pm_new',true,'req_reconciled');
 perform pg_temp.phase_assert(a->'phase_apply_plan'=plan and a->>'schedule_first_apply_at'=first_clock,'recovery never resets generation payload or clock');
 reset role;
 update public.salons set user_id=other_actor,email='phase-'||other_actor||'@example.test'where id=salon;
 set local role service_role;
 perform pg_temp.phase_reject(format('select public.prepare_payment_phase_apply(%L,%L,%L,%L,%L)',a->>'id',retry,'seti_phase','pm_new',plan),'PAYMENT_METHOD_OWNER_IDENTITY_CONFLICT');
 reset role;
 update public.salons set user_id=actor,email='phase-'||actor||'@example.test'where id=salon;
 set local role service_role;
 perform public.finish_subscription_payment_method_attempt((a->>'id')::uuid,retry,'completed','seti_phase','pm_new','req_reconciled');
 perform public.acquire_subscription_mutation(salon,actor,'sub_phase_fixture',lease);
 perform pg_temp.phase_assert(exists(select 1 from public.subscription_payment_schedule_intents i where i.salon_id=salon and i.source=baseline->'schedule'),'archive survives next generation lease reset');
 reset role;
 perform pg_temp.phase_assert((select to_jsonb(s)from public.subscriptions s where salon_id=salon)=before_subscription,'canonical plan price and subscription data untouched');
end $$;
rollback;
