-- Local disposable fixtures: no real provider, payment or customer notification.
begin;
create temporary table operation_assertions(label text);grant select,insert on operation_assertions to service_role;
create function pg_temp.oassert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'Assistant operations: %',label;end if;insert into operation_assertions values(label);end $$;
create function pg_temp.oreject(command text,expected text) returns void language plpgsql as $$declare denied boolean:=false;begin begin execute command;exception when others then if position(expected in sqlerrm)>0 then denied:=true;else raise;end if;end;perform pg_temp.oassert(denied,expected);end $$;
create function pg_temp.odraft(b uuid,a uuid,op text,target uuid,changes jsonb) returns jsonb language plpgsql as $$declare preview jsonb;args jsonb;begin
 args:=jsonb_build_object('operation',op,'record_id',target,'changes_json',changes::text);preview:=public.preview_gc_business_operation(b,a,args);
 return public.save_gc_assistant_request(jsonb_build_object('id',gen_random_uuid(),'salon_id',b,'requested_by',a,'locale','en','tool',case when op like 'photo_%' then 'prepare_photo_change' when op='client_card' then 'prepare_client_card_change' when op='review_reply' then 'prepare_review_reply' else 'prepare_stock_change' end,'arguments',args,'execution_payload',preview->'payload','before_summary',preview->'before','risk_class',4,'permission',case when op like 'photo_%' then 'photos' when op='client_card' then 'client_history' when op='review_reply' then 'reviews' else 'products' end,'digest',repeat('a',64)),'[]'::jsonb);
end $$;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();oa uuid:=gen_random_uuid();ob uuid:=gen_random_uuid();staff uuid:=gen_random_uuid();customer uuid:=gen_random_uuid();pa uuid:=gen_random_uuid();pb uuid:=gen_random_uuid();service uuid:=gen_random_uuid();serviceb uuid:=gen_random_uuid();booka uuid:=gen_random_uuid();bookb uuid:=gen_random_uuid();reviewa uuid:=gen_random_uuid();reviewb uuid:=gen_random_uuid();supply uuid;d jsonb;r jsonb;again jsonb;v jsonb;op text;n bigint;notifications bigint;
begin
 insert into auth.users(id,email,encrypted_password,email_confirmed_at,raw_user_meta_data) values(oa,'operations-a@example.test','',now(),'{"role":"salon_owner"}'),(ob,'operations-b@example.test','',now(),'{"role":"salon_owner"}'),(staff,'operations-staff@example.test','',now(),'{"role":"salon_team"}'),(customer,'operations-customer@example.test','',now(),'{"role":"customer"}');
 update public.platform_identities set primary_role='salon_team' where user_id=staff;
 insert into public.customers(id,name,email)values(customer,'Invented customer','operations-customer@example.test');
 insert into public.salons(id,user_id,name,slug,email,status,subscription_status,subscription_tier,gallery_photos,cover_photo_url)values(a,oa,'Operations A','operations-a','operations-a@example.test','Active','active','Premium','["https://example.test/a.jpg","https://example.test/a2.jpg"]'::jsonb,'https://example.test/a.jpg'),(b,ob,'Operations B','operations-b','operations-b@example.test','Active','active','Premium','["https://example.test/b.jpg"]'::jsonb,'https://example.test/b.jpg');
 insert into public.salon_team_members(salon_id,user_id,email,name,role,status,permissions)values(a,staff,'operations-staff@example.test','Limited','Staff','Active','{"products":true,"client_history":true,"client_edit":true}');
 insert into public.salon_products(id,salon_id,name,price,inventory_quantity,track_inventory)values(pa,a,'Oil A',20,10,true),(pb,b,'Private B',99,50,true);
 insert into public.styles(id,salon_id,service_group_id,name,duration_min_hours,duration_max_hours,base_price)select service,a,id,'Service A',1,1,100 from public.service_groups where is_active limit 1;
 insert into public.styles(id,salon_id,service_group_id,name,duration_min_hours,duration_max_hours,base_price)select serviceb,b,id,'Service B',1,1,999 from public.service_groups where is_active limit 1;
 insert into public.bookings(id,salon_id,style_id,customer_id,guest_name,appointment_datetime,duration_hours,estimated_total,deposit_amount,balance_due,deposit_status,status)values(booka,a,service,customer,'Invented customer',now()-interval '2 days',1,100,0,100,'Not paid','Completed'),(bookb,b,serviceb,customer,'Invented customer',now()-interval '3 days',1,999,0,999,'Not paid','Completed');
 insert into public.reviews(id,booking_id,salon_id,customer_id,rating_overall,written_review,display_name) values(reviewa,booka,a,customer,5,'Review A','Sample'),(reviewb,bookb,b,customer,1,'Private B review','Sample');
 select count(*) into notifications from public.notification_delivery_log;
 perform set_config('request.jwt.claim.role','service_role',true);
 set local role service_role;
 v:=public.read_gc_business_stock(a,oa);perform pg_temp.oassert(v->'products'->0->>'name'='Oil A' and jsonb_array_length(v->'products')=1,'own stock only');
 perform pg_temp.oreject(format('select public.read_gc_business_stock(%L,%L)',b,oa),'ASSISTANT_ACCESS_DENIED');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''stock_restock'',%L,%L)',a,oa,pb,'{"kind":"product","quantity":2,"cost_cents":0,"note":"Counted"}'),'ASSISTANT_RECORD_NOT_FOUND');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''stock_restock'',%L,%L)',a,staff,pa,'{"kind":"product","quantity":2,"cost_cents":500,"note":"Paid for stock"}'),'ASSISTANT_ACCESS_DENIED');
 reset role;
 d:=pg_temp.odraft(a,oa,'stock_restock',pa,'{"kind":"product","quantity":2,"cost_cents":500,"note":"Paid for stock"}');
 perform pg_temp.oassert((select inventory_quantity=10 from public.salon_products where id=pa),'stock unchanged until confirmation');
 perform pg_temp.oreject(format('select public.confirm_gc_assistant_request(%L,%L,%L,%L)',d->>'id',a,oa,repeat('b',64)),'ASSISTANT_PREVIEW_STALE');
 r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true','stock confirm '||r::text);
 again:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(again->>'replayed'='true' and again->'result'=r->'result','idempotent replay receipt');
 perform pg_temp.oassert((select inventory_quantity=12 from public.salon_products where id=pa),'stock durable readback');
 perform pg_temp.oassert((select count(*)=1 from public.business_finance_expenses where salon_id=a and amount_cents=500),'restock cost once');
 d:=pg_temp.odraft(a,oa,'stock_correction',pa,'{"kind":"product","quantity":9,"note":"Physical count"}');
 perform public.record_business_stock(a,oa,gen_random_uuid(),'restock',jsonb_build_object('product_id',pa,'expected_revision',2,'quantity',1));
 r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'code'='ASSISTANT_PREVIEW_STALE' and (select inventory_quantity=13 from public.salon_products where id=pa),'late stock change rejects stale review');
 d:=pg_temp.odraft(a,oa,'stock_consumption',pa,'{"kind":"product","quantity":3,"note":"Used today"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true' and (select inventory_quantity=10 from public.salon_products where id=pa),'consumption persisted');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''stock_consumption'',%L,%L)',a,oa,pa,'{"kind":"product","quantity":50,"note":"Too many"}'),'ASSISTANT_STOCK_INSUFFICIENT');
 d:=pg_temp.odraft(a,oa,'stock_correction',pa,'{"kind":"product","quantity":0,"note":"Physical empty shelf"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true' and (select inventory_quantity=0 from public.salon_products where id=pa),'zero correction valid');
 d:=pg_temp.odraft(a,oa,'stock_settings',pa,'{"kind":"product","track_inventory":false,"low_stock_threshold":4,"note":"Disable tracking"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true' and (select not track_inventory and low_stock_threshold=4 from public.salon_products where id=pa),'stock settings persisted');
 d:=pg_temp.odraft(a,oa,'supply_create',null,'{"name":"Towels","unit":"items","quantity":20,"low_stock_threshold":5,"note":"Opening count"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));supply:=(r->'result'->>'id')::uuid;perform pg_temp.oassert(r->>'verified'='true' and (select inventory_quantity=20 from public.business_supplies where id=supply),'supply created');
 d:=pg_temp.odraft(a,oa,'supply_archive',supply,'{"note":"Retired"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true' and (select archived_at is not null from public.business_supplies where id=supply),'supply safely archived');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''photo_cover'',null,%L)',a,oa,'{"url":"https://example.test/b.jpg"}'),'ASSISTANT_RECORD_NOT_FOUND');
 d:=pg_temp.odraft(a,oa,'photo_details',null,'{"url":"https://example.test/a2.jpg","category":"services","title":"Boho braids","caption":"Actual saved work","featured":true,"source_locale":"en"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true','photo details '||r::text);
 perform pg_temp.oassert((select photo_metadata->'https://example.test/a2.jpg'->>'title'='Boho braids' from public.salons where id=a),'photo metadata persisted');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''photo_remove'',null,%L)',a,oa,'{"url":"https://example.test/a.jpg"}'),'ASSISTANT_REPLACE_COVER_FIRST');
 d:=pg_temp.odraft(a,oa,'photo_cover',null,'{"url":"https://example.test/a2.jpg"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true' and (select cover_photo_url='https://example.test/a2.jpg' from public.salons where id=a),'cover changed from own saved gallery');
 d:=pg_temp.odraft(a,oa,'photo_remove',null,'{"url":"https://example.test/a.jpg"}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true' and (select jsonb_array_length(gallery_photos)=1 from public.salons where id=a),'photo removed from gallery only');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''client_card'',%L,%L)',a,oa,bookb,'{"locale":"en","patch":{"notes":"Not authorized"}}'),'ASSISTANT_RECORD_NOT_FOUND');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''client_card'',%L,%L)',a,staff,booka,'{"locale":"en","patch":{"notes":"Not authorized"}}'),'ASSISTANT_ACCESS_DENIED');
 d:=pg_temp.odraft(a,oa,'client_card',booka,'{"locale":"fr","patch":{"notes":"Serviettes douces","formula":{"technique":"Boho","duration_minutes":120}}}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true','client saved '||r::text);
 v:=public.read_business_client_card(a,oa,booka);perform pg_temp.oassert(v->>'notes'='Serviettes douces' and v->'visits'->0->'formula'->>'technique'='Boho','client formula and language readback');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''review_reply'',%L,%L)',a,oa,reviewb,'{"reply":"Not authorized"}'),'ASSISTANT_RECORD_NOT_FOUND');
 d:=pg_temp.odraft(a,oa,'review_reply',reviewa,'{"reply":"Thank you for visiting."}');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true','review reply saved '||r::text);
 perform pg_temp.oassert((select salon_reply='Thank you for visiting.' and reply_revision=1 from public.reviews where id=reviewa),'canonical review readback');
 d:=pg_temp.odraft(a,oa,'review_reply',reviewa,'{"reply":"An updated reply."}');perform public.save_business_review_reply(a,reviewa,oa,gen_random_uuid(),1,'Changed in another tab.','Clear');r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'code'='ASSISTANT_PREVIEW_STALE','changed review rejects confirmation');
 -- After-review revocation, expiry and malformed raw calls all fail closed.
 update public.salon_products set track_inventory=true where id=pa;
 d:=pg_temp.odraft(a,staff,'stock_restock',pa,'{"kind":"product","quantity":1,"cost_cents":0,"note":"Received"}');
 update public.salon_team_members set permissions='{}' where salon_id=a and user_id=staff;
 perform pg_temp.oreject(format('select public.confirm_gc_assistant_request(%L,%L,%L,%L)',d->>'id',a,staff,repeat('a',64)),'ASSISTANT_ACCESS_DENIED');
 d:=pg_temp.odraft(a,oa,'stock_restock',pa,'{"kind":"product","quantity":1,"cost_cents":0,"note":"Received"}');
 update public.gc_assistant_requests set expires_at=now()-interval '1 minute' where id=(d->>'id')::uuid;
 perform pg_temp.oreject(format('select public.confirm_gc_assistant_request(%L,%L,%L,%L)',d->>'id',a,oa,repeat('a',64)),'ASSISTANT_PREVIEW_EXPIRED');
 d:=pg_temp.odraft(a,oa,'stock_restock',pa,'{"kind":"product","quantity":1,"cost_cents":0,"note":"Received"}');
 perform pg_temp.oreject(format('select public.confirm_gc_assistant_request(%L,%L,%L,%L)',d->>'id',b,ob,repeat('a',64)),'ASSISTANT_REQUEST_NOT_FOUND');
 r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'verified'='true' and (select inventory_quantity=1 from public.salon_products where id=pa),'zero-cost restock has no invented expense');
 perform pg_temp.oassert((select count(*)=1 from public.business_finance_expenses where salon_id=a),'zero-cost restock does not create an expense');
 d:=pg_temp.odraft(a,oa,'photo_details',null,'{"url":"https://example.test/a2.jpg","category":"services","title":"Review draft","caption":"Original","featured":false,"source_locale":"en"}');
 perform public.update_business_photo_details(a,oa,'https://example.test/a2.jpg','{"category":"services","title":"Saved elsewhere","caption":"Actual","featured":true,"source_locale":"en"}',(select photo_metadata->'https://example.test/a2.jpg' from public.salons where id=a));
 r:=public.confirm_gc_assistant_request((d->>'id')::uuid,a,oa,repeat('a',64));perform pg_temp.oassert(r->>'code'='ASSISTANT_PREVIEW_STALE' and (select photo_metadata->'https://example.test/a2.jpg'->>'title'='Saved elsewhere' from public.salons where id=a),'late photo metadata is preserved');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''client_card'',%L,%L)',a,oa,booka,'{"locale":"en","patch":{"formula":{"permissions":"all"}}}'),'ASSISTANT_INVALID_INPUT');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''stock_consumption'',%L,%L)',a,oa,pa,'{"kind":"product","quantity":0,"note":"Bad"}'),'ASSISTANT_INVALID_INPUT');
 perform pg_temp.oreject(format('select pg_temp.odraft(%L,%L,''photo_cover'',null,%L)',a,oa,'{"url":"https://example.test/a2.jpg","salon_id":"foreign"}'),'ASSISTANT_INVALID_INPUT');
 perform pg_temp.oassert((select count(*)=notifications from public.notification_delivery_log),'no customer notifications');
 perform pg_temp.oassert((select inventory_quantity=50 from public.salon_products where id=pb) and (select salon_reply is null from public.reviews where id=reviewb),'other business unchanged');
 perform pg_temp.oassert(not has_function_privilege('authenticated','public.preview_gc_business_operation(uuid,uuid,jsonb)','execute') and not has_function_privilege('anon','public.confirm_gc_assistant_request(uuid,uuid,uuid,text)','execute'),'raw anonymous and authenticated RPC denied');
end $$;
select count(*)||' assistant operational database assertions passed' from operation_assertions;
rollback;
