const messages = {
  en: { selection: "Selected service: {total} after {saving} savings. The protected deposit stays {deposit}; the remaining service balance is {balance}. Checkout still checks eligibility and availability.", booking: "Original booking: {total}, including a {deposit} protected deposit and {balance} original remaining balance. Current recorded unpaid balance: {unpaid}. No booking or payment changed.", missing: "A complete verified amount is unavailable. I have kept the missing selection or evidence explicit; no booking or payment changed.", unavailable: "unavailable" },
  fr: { selection: "Prestation sélectionnée : {total} après {saving} de réduction. L’acompte protégé reste de {deposit} ; le solde de la prestation est de {balance}. L’admissibilité et la disponibilité sont encore vérifiées lors de la réservation.", booking: "Réservation initiale : {total}, dont {deposit} d’acompte protégé et {balance} de solde initial. Solde impayé actuellement enregistré : {unpaid}. Aucune réservation ni aucun paiement n’a changé.", missing: "Le montant complet vérifié est indisponible. Le choix ou le justificatif manquant reste indiqué ; aucune réservation ni aucun paiement n’a changé.", unavailable: "indisponible" },
  es: { selection: "Servicio seleccionado: {total} tras un ahorro de {saving}. El depósito protegido sigue siendo {deposit}; el saldo del servicio es {balance}. La reserva aún debe verificar elegibilidad y disponibilidad.", booking: "Reserva original: {total}, con un depósito protegido de {deposit} y un saldo original de {balance}. Saldo impagado registrado actualmente: {unpaid}. No cambió ninguna reserva ni pago.", missing: "No está disponible el importe completo verificado. La selección o evidencia que falta se indica expresamente; no cambió ninguna reserva ni pago.", unavailable: "no disponible" },
  "zh-CN": { selection: "所选服务优惠 {saving} 后为 {total}。受保护订金仍为 {deposit}，服务余款为 {balance}。预约结账时仍需核实优惠资格和可用时间。", booking: "原预约金额为 {total}，其中受保护订金为 {deposit}，原余款为 {balance}。当前记录的未付余额：{unpaid}。未更改预约或付款。", missing: "无法提供完整且经核实的金额。缺少的选项或依据已明确保留；未更改预约或付款。", unavailable: "无法核实" },
  wo: { selection: "Sarwiis bi nga tànn: {total}, ginnaaw wàññi {saving}. Avans bi aar na te des {deposit}; desit bi mooy {balance}. Checkout dina seet ndax am nga sañ-sañ ak waxtu wu féex.", booking: "Randeewu bi njëkk: {total}, ak avans {deposit} ak desit bu njëkk {balance}. Desit bi ñu bind léegi: {unpaid}. Soppiwuma randeewu walla fay gi.", missing: "Amuma lim bu mat te wóor. Tànneef walla firnde bi des leeral na; soppiwuma randeewu walla fay gi.", unavailable: "amaguñu ko" },
};
export function assistantMoneyReadText(key: keyof typeof messages.en, locale: string, values: Record<string, string> = {}) {
  const copy = messages[locale as keyof typeof messages] || messages.en;
  return copy[key].replace(/\{(\w+)\}/g, (_match, name: string) => values[name] ?? "");
}
