export const BOOKING_MONEY_COPY = [
 ["Booking outcomes and offers","Résultats des rendez-vous et offres","Resultados de citas y ofertas","预约结果与优惠"],
 ["Refresh booking evidence","Actualiser les données","Actualizar datos de citas","刷新预约依据"],
 ["Checking booking evidence…","Vérification des données…","Verificando datos de citas…","正在核查预约依据…"],
 ["Booking money evidence could not be verified. Reload to check the current records.","Les données financières des rendez-vous n’ont pas pu être vérifiées. Actualisez les enregistrements.","No se pudieron verificar los datos financieros de las citas. Actualiza los registros.","无法核实预约金额依据。请刷新以检查当前记录。"],
 ["Only the owner or a team member with full finance and booking access can view these figures.","Seuls le propriétaire ou les membres disposant de tous les accès financiers et aux rendez-vous peuvent consulter ces chiffres.","Solo el propietario o el equipo con acceso completo a finanzas y citas puede ver estas cifras.","仅店主或同时拥有完整财务及预约权限的团队成员可查看这些数据。"],
 ["Records changed during verification. Refresh to read a consistent result.","Les enregistrements ont changé pendant la vérification. Actualisez pour obtenir un résultat cohérent.","Los registros cambiaron durante la verificación. Actualiza para ver un resultado coherente.","记录在核查过程中发生变化。请刷新以读取一致的结果。"],
 ["Choose a shorter period, up to one year, to verify this booking cohort.","Choisissez une période plus courte, d’un an maximum, pour vérifier ces rendez-vous.","Elige un período más corto, de hasta un año, para verificar estas citas.","请选择不超过一年的较短时段，以核查这组预约。"],
 ["Appointments dated {from} to {to}, in {zone}. Statuses are the current recorded states, not a reconstruction of the past.","Rendez-vous du {from} au {to}, fuseau {zone}. Les statuts sont ceux enregistrés actuellement, sans reconstitution du passé.","Citas del {from} al {to}, zona {zone}. Los estados son los registrados actualmente, no una reconstrucción del pasado.","预约日期为 {from} 至 {to}，时区 {zone}。状态为当前记录，并非对历史状态的重建。"],
 ["Cancelled appointments","Rendez-vous annulés","Citas canceladas","已取消预约"],
 ["No-shows","Absences","Ausencias","未到店预约"],
 ["{count} bookings · agreed value {value}","{count} rendez-vous · montant convenu {value}","{count} citas · importe acordado {value}","{count} 个预约 · 约定金额 {value}"],
 ["Verified platform receipts: {received}; verified refunds: {refunded}.","Encaissements plateforme vérifiés : {received} ; remboursements vérifiés : {refunded}.","Cobros de plataforma verificados: {received}; reembolsos verificados: {refunded}.","已验证的平台收款：{received}；已验证退款：{refunded}。"],
 ["Business-recorded receipts: {received}; recorded refunds: {refunded}.","Encaissements enregistrés par l’entreprise : {received} ; remboursements enregistrés : {refunded}.","Cobros registrados por el negocio: {received}; reembolsos registrados: {refunded}.","商家记录的收款：{received}；记录的退款：{refunded}。"],
 ["Net recorded receipts retained: {value}","Encaissements nets conservés : {value}","Cobros netos registrados retenidos: {value}","记录中的净保留收款：{value}"],
 ["Linked receipts include payments before the appointment period through its end date. Later receipts and refunds are excluded. Agreed value is not measured lost revenue; retained money is not a refund-policy decision.","Les encaissements liés incluent les paiements antérieurs jusqu’à la fin de la période. Les paiements et remboursements ultérieurs sont exclus. Le montant convenu n’est pas une perte mesurée ; le montant conservé ne décide pas de la politique de remboursement.","Se incluyen cobros vinculados anteriores al período hasta su fecha final. Se excluyen cobros y reembolsos posteriores. El importe acordado no mide ingresos perdidos; el dinero retenido no determina la política de reembolso.","关联收款包括预约时段之前至结束日的付款，排除之后的收款及退款。约定金额不等于已测得的收入损失；保留款项也不代表退款政策决定。"],
 ["Recorded business-offer usage","Utilisation des offres enregistrées","Uso registrado de ofertas del negocio","已记录的商家优惠使用情况"],
 ["{count} bookings have incomplete offer evidence. Attribution is unavailable until those records are reviewed.","Les données d’offre de {count} rendez-vous sont incomplètes. L’attribution est indisponible jusqu’à leur vérification.","{count} citas tienen datos de oferta incompletos. La atribución no está disponible hasta revisar esos registros.","{count} 个预约的优惠依据不完整。审核这些记录之前无法提供优惠归属数据。"],
 ["No business-offer use is recorded for this appointment cohort.","Aucune utilisation d’offre n’est enregistrée pour ces rendez-vous.","No se registra uso de ofertas del negocio en este grupo de citas.","这组预约未记录商家优惠使用情况。"],
 ["{completed} completed · {cancelled} cancelled · {noShow} no-show · {other} other current states", "{completed} terminés · {cancelled} annulés · {noShow} absences · {other} autres statuts actuels", "{completed} completadas · {cancelled} canceladas · {noShow} ausencias · {other} otros estados actuales", "{completed} 个已完成 · {cancelled} 个已取消 · {noShow} 个未到店 · {other} 个其他当前状态"],
 ["Agreed discounts: {discount}; net recorded receipts: {receipts}.","Remises convenues : {discount} ; encaissements nets enregistrés : {receipts}.","Descuentos acordados: {discount}; cobros netos registrados: {receipts}.","约定优惠金额：{discount}；记录中的净收款：{receipts}。"],
 ["Attribution uses the offer saved with each booking. It does not prove the offer caused the booking, incremental revenue, profitability, or marketing return.","L’attribution utilise l’offre enregistrée avec chaque rendez-vous. Elle ne prouve ni son effet sur la réservation, ni un revenu supplémentaire, une rentabilité ou un retour marketing.","La atribución usa la oferta guardada en cada cita. No demuestra que causara la reserva, ingresos adicionales, rentabilidad ni retorno de marketing.","归属依据为每个预约保存的优惠，不能证明优惠促成了预约、增加了收入、产生了利润或营销回报。"],
] as const;
export function bookingMoneyCopy(locale: string, source: string, values: Record<string, string> = {}) {
 const index = ["en", "fr", "es", "zh-CN"].indexOf(locale);
 const translated = BOOKING_MONEY_COPY.find(row => row[0] === source)?.[index < 0 ? 0 : index] || source;
 return translated.replace(/\{([^}]+)\}/g, (token, key) => values[key] ?? token);
}
