const en = {
  title: "Schedule opportunities", refresh: "Refresh schedule", loading: "Checking the next seven days…",
  period: "{from} to {to} · {zone}. Checked {time}.",
  explanation: "Current remaining capacity, independent of your finance reporting period. This does not measure past demand or guarantee that a service fits an opening.",
  totals: "{free} free professional-minutes · {booked} booked · {held} held at checkout · {capacity} capacity after closures and blockouts.",
  share: "Booked share: {percent}% of current capacity.", noCapacity: "No configured capacity remains in this window.",
  denominator: "Draft and inactive professionals are excluded. Minutes add across professionals. Overlapping bookings and holds count once per person; blockouts are excluded from capacity. Holds are not bookings or revenue.",
  own: "Only your assigned professional’s schedule is included.", opportunity: "{date} · {name}", business: "Business schedule",
  detail: "{free} minutes free of {capacity} capacity; {booked} booked and {held} held at checkout.",
  review: "Review this calendar", empty: "No open interval remains in the verified schedule.",
  error: "Schedule opportunities could not be verified. Refresh to check the current calendar.",
  hours: "Working hours are incomplete. Review business and professional hours; unavailable capacity is not zero.",
  changed: "Calendar settings or access changed during the read. Refresh to verify the current schedule.",
  denied: "This view requires current calendar access.", limited: "Up to six dates and professionals with the most remaining open time. Current evidence only; no historical trend or price benchmark is inferred.",
  interval: "{start}–{end}", unavailable: "Unavailable, not zero.",
};
type Keys = keyof typeof en;
export const BUSINESS_SCHEDULE_COPY: Record<string, Record<Keys, string>> = {
  en,
  fr: { title: "Possibilités du planning", refresh: "Actualiser le planning", loading: "Vérification des sept prochains jours…", period: "Du {from} au {to} · {zone}. Vérifié à {time}.", explanation: "Capacité restante actuelle, indépendante de la période de votre rapport financier. Elle ne mesure pas la demande passée et ne garantit pas qu’une prestation tient dans un créneau.", totals: "{free} minutes-professionnel libres · {booked} réservées · {held} retenues au paiement · {capacity} de capacité après fermetures et blocages.", share: "Part réservée : {percent} % de la capacité actuelle.", noCapacity: "Aucune capacité configurée ne reste dans cette période.", denominator: "Les professionnels inactifs ou en brouillon sont exclus. Les minutes s’additionnent entre professionnels. Les réservations et retenues qui se chevauchent comptent une seule fois par personne ; les blocages sont exclus de la capacité. Les retenues ne sont ni des rendez-vous ni du chiffre d’affaires.", own: "Seul le planning du professionnel qui vous est attribué est inclus.", opportunity: "{date} · {name}", business: "Planning de l’établissement", detail: "{free} minutes libres sur {capacity} ; {booked} réservées et {held} retenues au paiement.", review: "Consulter ce calendrier", empty: "Aucun créneau libre ne reste dans le planning vérifié.", error: "Les possibilités du planning n’ont pas pu être vérifiées. Actualisez pour consulter le calendrier actuel.", hours: "Les horaires de travail sont incomplets. Vérifiez ceux de l’établissement et des professionnels ; une capacité indisponible n’est pas nulle.", changed: "Les paramètres du calendrier ou les accès ont changé pendant la lecture. Actualisez pour vérifier le planning actuel.", denied: "Cette vue nécessite un accès actuel au calendrier.", limited: "Jusqu’à six dates et professionnels offrant le plus de temps libre restant. Données actuelles uniquement ; aucune tendance historique ni référence tarifaire n’est déduite.", interval: "{start}–{end}", unavailable: "Indisponible, pas zéro." },
  es: { title: "Oportunidades de la agenda", refresh: "Actualizar agenda", loading: "Comprobando los próximos siete días…", period: "Del {from} al {to} · {zone}. Comprobado a las {time}.", explanation: "Capacidad restante actual, independiente del período del informe financiero. No mide la demanda pasada ni garantiza que un servicio quepa en un hueco.", totals: "{free} minutos de profesionales libres · {booked} reservados · {held} retenidos durante el pago · {capacity} de capacidad tras cierres y bloqueos.", share: "Proporción reservada: {percent}% de la capacidad actual.", noCapacity: "No queda capacidad configurada en este período.", denominator: "Se excluyen los profesionales inactivos o en borrador. Los minutos se suman entre profesionales. Las reservas y retenciones superpuestas cuentan una sola vez por persona; los bloqueos se excluyen de la capacidad. Las retenciones no son citas ni ingresos.", own: "Solo se incluye la agenda del profesional que tienes asignado.", opportunity: "{date} · {name}", business: "Agenda del negocio", detail: "{free} minutos libres de {capacity}; {booked} reservados y {held} retenidos durante el pago.", review: "Revisar este calendario", empty: "No queda ningún intervalo libre en la agenda verificada.", error: "No se pudieron verificar las oportunidades de la agenda. Actualiza para consultar el calendario actual.", hours: "Los horarios laborales están incompletos. Revisa los del negocio y de los profesionales; una capacidad no disponible no equivale a cero.", changed: "La configuración del calendario o el acceso cambió durante la lectura. Actualiza para verificar la agenda actual.", denied: "Esta vista requiere acceso vigente al calendario.", limited: "Hasta seis fechas y profesionales con más tiempo libre restante. Solo datos actuales; no se infieren tendencias históricas ni referencias de precios.", interval: "{start}–{end}", unavailable: "No disponible, no cero." },
  "zh-CN": { title: "排班机会", refresh: "刷新排班", loading: "正在核查未来七天…", period: "{from} 至 {to} · {zone}。核查时间：{time}。", explanation: "当前剩余接待能力，与财务报告期间无关。这不代表过去的需求，也不保证某项服务能安排在空档内。", totals: "专业人员空闲 {free} 分钟 · 已预约 {booked} 分钟 · 结账暂留 {held} 分钟 · 扣除停业和封锁后可用总量 {capacity} 分钟。", share: "已预约比例：当前可用总量的 {percent}%。", noCapacity: "此期间没有剩余的已配置接待时间。", denominator: "不计入未激活或草稿状态的专业人员。分钟数按专业人员累计。同一人的重叠预约和暂留时间只计算一次；封锁时段不计入可用总量。暂留时间不代表预约或收入。", own: "仅包含您所分配专业人员的排班。", opportunity: "{date} · {name}", business: "商家排班", detail: "可用总量 {capacity} 分钟，空闲 {free} 分钟；已预约 {booked} 分钟，结账暂留 {held} 分钟。", review: "查看此日历", empty: "经核查的排班中已无空闲时段。", error: "无法核实排班机会。请刷新以查看当前日历。", hours: "工作时间配置不完整。请查看商家及专业人员的工作时间；不可用的接待数据不等于零。", changed: "读取期间日历设置或权限发生变化。请刷新以核查当前排班。", denied: "此视图需要当前有效的日历访问权限。", limited: "最多显示剩余空闲时间最多的六个日期与专业人员组合。仅依据当前数据，不推断历史趋势或价格基准。", interval: "{start}–{end}", unavailable: "数据不可用，不代表零。" },
};
export function scheduleCopy(locale: string, key: Keys, values: Record<string, string> = {}) {
  return (BUSINESS_SCHEDULE_COPY[locale]?.[key] || en[key]).replace(/\{(\w+)\}/g, (_, token: string) => values[token] ?? `{${token}}`);
}
