// Functional localization; native-language and physical-device acceptance remain separate.
const rows: readonly (readonly [string, string, string, string, string])[] = [
  ["New conversation", "Nueva conversación", "Nouvelle conversation", "Waxtaan wu bees", "新对话"],
  ["Starting a new conversation clears this panel. Saved business actions remain in the audit history.", "Iniciar una nueva conversación borra este panel. Las acciones guardadas permanecen en el historial de auditoría.", "Une nouvelle conversation efface ce panneau. Les actions enregistrées restent dans l’historique d’audit.", "Su nga tàmbalee waxtaan wu bees, li ci pano bii dina faru. Jëf yi ñu denc dinañu des ci jaar-jaaru seet.", "开始新对话会清空此面板。已保存的业务操作仍保留在审计历史中。"],
  ["Translation is not configured yet. Keep the original text or enter a reviewed translation.", "La traducción aún no está configurada. Conserva el original o introduce una traducción revisada.", "La traduction n’est pas encore configurée. Conservez l’original ou saisissez une traduction relue.", "Tekki bi pareegul. Dencal mbind mi njëkk walla dugal tekki bu ñu seet.", "翻译尚未配置。请保留原文或输入经审核的译文。"],
  ["The translation account could not be authenticated. Contact platform support; the original text is unchanged.", "No se pudo autenticar la cuenta de traducción. Contacta con soporte; el original no cambió.", "Le compte de traduction n’a pas pu être authentifié. Contactez l’assistance ; l’original reste inchangé.", "Mënunu dëggal kontu tekki bi. Waxal ak ndimbal; mbind mi soppeekuul.", "无法验证翻译账户。请联系平台支持；原文未更改。"],
  ["Translation is currently unavailable under the configured limits. Keep the original text or contact platform support.", "La traducción no está disponible con los límites actuales. Conserva el original o contacta con soporte.", "La traduction est indisponible avec les limites actuelles. Conservez l’original ou contactez l’assistance.", "Tekki bi féexul ci kemu yi ñu tëral. Dencal mbind mi walla wax ak ndimbal.", "按当前限额暂时无法翻译。请保留原文或联系平台支持。"],
  ["Translation is temporarily unavailable. The original text is unchanged.", "La traducción no está disponible temporalmente. El original no cambió.", "La traduction est temporairement indisponible. L’original reste inchangé.", "Tekki bi féexul léegi. Mbind mi soppeekuul.", "翻译暂时不可用。原文未更改。"],
  ["I found {count} matching businesses near {location}. You can compare them below, or tell me what you would like to change.", "Encontré {count} negocios que coinciden cerca de {location}. Puedes compararlos abajo o decirme qué quieres cambiar.", "J’ai trouvé {count} établissements correspondants près de {location}. Comparez-les ci-dessous ou dites-moi ce que vous souhaitez modifier.", "Gis naa {count} liggéeyukaay yu méngoo te jege {location}. Mën nga leen mengale fii suuf walla wax ma li nga bëgg soppi.", "在 {location} 附近找到了 {count} 家符合条件的商家。您可以在下方比较，或告诉我想调整哪些条件。"],
  ["Read aloud", "Leer en voz alta", "Lire à voix haute", "Jàngal ma ko", "朗读"],
  ["Pause audio", "Pausar audio", "Mettre en pause", "Taxawal baat bi", "暂停语音"],
  ["Resume audio", "Reanudar audio", "Reprendre la lecture", "Tambaliwaat baat bi", "继续朗读"],
  ["Stop audio", "Detener audio", "Arrêter la lecture", "Dakkal baat bi", "停止朗读"],
  ["Spoken answers use an installed voice on this device. Audio is not saved.", "Las respuestas se leen con una voz instalada en este dispositivo. Girlz Culture no guarda el audio.", "Les réponses utilisent une voix installée sur cet appareil. Girlz Culture ne conserve pas l’audio.", "Tontu yi dañuy jëfandikoo baat bu nekk ci sa aparey. Girlz Culture du denc baat bi.", "朗读使用此设备上安装的语音。Girlz Culture 不保存音频。"],
  ["No on-device voice is available for this language. You can continue reading the answer.", "No hay una voz instalada para este idioma. Puedes seguir leyendo la respuesta.", "Aucune voix locale n’est disponible dans cette langue. Vous pouvez continuer à lire la réponse.", "Amul baat ci sa aparey bu méngoo ak làkk wii. Mën nga jàng tontu bi.", "此设备没有该语言的本地语音。您可以继续阅读回答。"],
  ["Audio stopped. You can continue reading the answer.", "El audio se detuvo. Puedes seguir leyendo la respuesta.", "La lecture audio s’est arrêtée. Vous pouvez continuer à lire la réponse.", "Baat bi taxaw na. Mën nga jàng tontu bi.", "语音已停止。您可以继续阅读回答。"],
  ["The free translation allowance is exhausted. Keep the original text or enter a reviewed translation. No paid upgrade was made.", "Se agotó la cuota gratuita de traducción. Conserva el original o introduce una traducción revisada. No se contrató un plan de pago.", "Le quota gratuit de traduction est épuisé. Conservez l’original ou saisissez une traduction relue. Aucun forfait payant n’a été activé.", "Li ñu may ci tekki bu amul fay jeex na. Dencal mbind mi njëkk walla dugal tekki bu ñu seet. Jëndunu benn plan.", "免费翻译额度已用尽。请保留原文或输入经审核的译文。未升级到付费套餐。"],
  ["The translation provider does not currently support this language. Keep the original text or enter a reviewed translation.", "El proveedor de traducción no admite este idioma actualmente. Conserva el original o introduce una traducción revisada.", "Le service de traduction ne prend pas encore en charge cette langue. Conservez l’original ou saisissez une traduction relue.", "Jumtuwaayu tekki bi mëneegul làkk wii. Dencal mbind mi njëkk walla dugal tekki bu ñu seet.", "翻译服务目前不支持此语言。请保留原文或输入经审核的译文。"],
  ["The translation provider is busy. Try again later; the original text is unchanged.", "El proveedor de traducción está ocupado. Inténtalo más tarde; el original no cambió.", "Le service de traduction est occupé. Réessayez plus tard ; l’original reste inchangé.", "Jumtuwaayu tekki bi dafay liggéey. Jéemaatal ci kanam; mbind mi soppeekuul.", "翻译服务繁忙。请稍后重试；原文未更改。"],
  ["The translation did not preserve the original details and was rejected. The original text is unchanged.", "La traducción no conservó los detalles originales y se rechazó. El original no cambió.", "La traduction n’a pas conservé les détails d’origine et a été rejetée. L’original reste inchangé.", "Tekki bi sàmmul xibaar yi njëkk, moo tax ñu bañ ko. Mbind mi soppeekuul.", "译文未保留原始细节，已被拒绝。原文未更改。"],
  ["I found {count} matching businesses. You can compare them below, or tell me what you would like to change.", "Encontré {count} negocios que coinciden. Puedes compararlos abajo o decirme qué quieres cambiar.", "J’ai trouvé {count} établissements correspondants. Comparez-les ci-dessous ou dites-moi ce que vous souhaitez modifier.", "Gis naa {count} liggéeyukaay yu méngoo. Mën nga leen mengale fii suuf walla wax ma li nga bëgg soppi.", "找到了 {count} 家符合条件的商家。您可以在下方比较，或告诉我想调整哪些条件。"],
  ["I couldn't find a match for these details. Would you like to change the date, price or distance?", "No encontré coincidencias. ¿Quieres cambiar la fecha, el precio o la distancia?", "Je n’ai pas trouvé de résultat correspondant. Souhaitez-vous modifier la date, le prix ou la distance ?", "Gisuma lu méngoo ak lii. Ndax bëgg nga soppi bés bi, njëg bi walla sorewaay bi?", "未找到符合这些条件的结果。您想调整日期、价格或距离吗？"],
  ["I couldn't find that in the published Help center. Try a more specific question or contact support.", "No encontré esa información en el centro de ayuda publicado. Haz una pregunta más específica o contacta con soporte.", "Je n’ai pas trouvé cette information dans le centre d’aide publié. Précisez votre question ou contactez l’assistance.", "Gisuma loolu ci ndimbal li ñu siiwal. Laajal lu gën a leer walla wax ak ndimbal.", "在已发布的帮助中心中未找到该信息。请提出更具体的问题或联系支持人员。"],
];
export const GCIA_SOURCE_MESSAGES: Record<string, Record<string, string>> = Object.fromEntries(
  ["es", "fr", "wo", "zh-CN"].map((locale, index) => [locale, Object.fromEntries(rows.map(row => [row[0], row[index + 1]]))]),
);
export function gciaText(source: string, locale: string, values: Record<string, string | number> = {}) {
  return (GCIA_SOURCE_MESSAGES[locale]?.[source] || source).replace(/\{(\w+)\}/g, (token, key: string) => Object.hasOwn(values, key) ? String(values[key]) : token);
}
