// Functional localization; native-language and physical-device acceptance remain separate.
const rows: readonly (readonly [string, string, string, string, string])[] = [
  ["New conversation", "Nueva conversación", "Nouvelle conversation", "Waxtaan wu bees", "新对话"],
  ["Starting a new conversation clears this panel. Saved business actions remain in the audit history.", "Iniciar una nueva conversación borra este panel. Las acciones guardadas permanecen en el historial de auditoría.", "Une nouvelle conversation efface ce panneau. Les actions enregistrées restent dans l’historique d’audit.", "Su nga tàmbalee waxtaan wu bees, li ci pano bii dina faru. Jëf yi ñu denc dinañu des ci jaar-jaaru seet.", "开始新对话会清空此面板。已保存的业务操作仍保留在审计历史中。"],
  ["Translation is not configured yet. Keep the original text or enter a reviewed translation.", "La traducción aún no está configurada. Conserva el original o introduce una traducción revisada.", "La traduction n’est pas encore configurée. Conservez l’original ou saisissez une traduction relue.", "Tekki bi pareegul. Dencal mbind mi njëkk walla dugal tekki bu ñu seet.", "翻译尚未配置。请保留原文或输入经审核的译文。"],
  ["The translation account could not be authenticated. Contact platform support; the original text is unchanged.", "No se pudo autenticar la cuenta de traducción. Contacta con soporte; el original no cambió.", "Le compte de traduction n’a pas pu être authentifié. Contactez l’assistance ; l’original reste inchangé.", "Mënunu dëggal kontu tekki bi. Waxal ak ndimbal; mbind mi soppeekuul.", "无法验证翻译账户。请联系平台支持；原文未更改。"],
  ["Translation is currently unavailable under the configured limits. Keep the original text or contact platform support.", "La traducción no está disponible con los límites actuales. Conserva el original o contacta con soporte.", "La traduction est indisponible avec les limites actuelles. Conservez l’original ou contactez l’assistance.", "Tekki bi féexul ci kemu yi ñu tëral. Dencal mbind mi walla wax ak ndimbal.", "按当前限额暂时无法翻译。请保留原文或联系平台支持。"],
  ["Translation is temporarily unavailable. The original text is unchanged.", "La traducción no está disponible temporalmente. El original no cambió.", "La traduction est temporairement indisponible. L’original reste inchangé.", "Tekki bi féexul léegi. Mbind mi soppeekuul.", "翻译暂时不可用。原文未更改。"],
  ["I found {count} matching businesses near {location}. You can compare them below, or tell me what you would like to change.", "Encontré {count} negocios que coinciden cerca de {location}. Puedes compararlos abajo o decirme qué quieres cambiar.", "J’ai trouvé {count} établissements correspondants près de {location}. Comparez-les ci-dessous ou dites-moi ce que vous souhaitez modifier.", "Gis naa {count} liggéeyukaay yu méngoo te jege {location}. Mën nga leen mengale fii suuf walla wax ma li nga bëgg soppi.", "在 {location} 附近找到了 {count} 家符合条件的商家。您可以在下方比较，或告诉我想调整哪些条件。"],
  ["Read aloud", "Leer en voz alta", "Lire à voix haute", "Jàngal ma ko", "朗读"],
  ["Pause audio", "Pausar audio", "Mettre en pause", "Taxawal baat bi", "暂停语音"],
  ["Resume audio", "Reanudar audio", "Reprendre la lecture", "Tambaliwaat baat bi", "继续朗读"],
  ["Stop audio", "Detener audio", "Arrêter la lecture", "Dakkal baat bi", "停止朗读"],
  ["Spoken answers use an installed voice on this device. Audio is not saved.", "Las respuestas se leen con una voz instalada en este dispositivo. Girlz Culture no guarda el audio.", "Les réponses utilisent une voix installée sur cet appareil. Girlz Culture ne conserve pas l’audio.", "Tontu yi dañuy jëfandikoo baat bu nekk ci sa aparey. Girlz Culture du denc baat bi.", "朗读使用此设备上安装的语音。Girlz Culture 不保存音频。"],
  ["No on-device voice is available for this language. You can continue reading the answer.", "No hay una voz instalada para este idioma. Puedes seguir leyendo la respuesta.", "Aucune voix locale n’est disponible dans cette langue. Vous pouvez continuer à lire la réponse.", "Amul baat ci sa aparey bu méngoo ak làkk wii. Mën nga jàng tontu bi.", "此设备没有该语言的本地语音。您可以继续阅读回答。"],
  ["Audio stopped. You can continue reading the answer.", "El audio se detuvo. Puedes seguir leyendo la respuesta.", "La lecture audio s’est arrêtée. Vous pouvez continuer à lire la réponse.", "Baat bi taxaw na. Mën nga jàng tontu bi.", "语音已停止。您可以继续阅读回答。"],
  ["The free translation allowance is exhausted. Keep the original text or enter a reviewed translation. No paid upgrade was made.", "Se agotó la cuota gratuita de traducción. Conserva el original o introduce una traducción revisada. No se contrató un plan de pago.", "Le quota gratuit de traduction est épuisé. Conservez l’original ou saisissez une traduction relue. Aucun forfait payant n’a été activé.", "Li ñu may ci tekki bu amul fay jeex na. Dencal mbind mi njëkk walla dugal tekki bu ñu seet. Jëndunu benn plan.", "免费翻译额度已用尽。请保留原文或输入经审核的译文。未升级到付费套餐。"],
  ["The translation provider does not currently support this language. Keep the original text or enter a reviewed translation.", "El proveedor de traducción no admite este idioma actualmente. Conserva el original o introduce una traducción revisada.", "Le service de traduction ne prend pas encore en charge cette langue. Conservez l’original ou saisissez une traduction relue.", "Jumtuwaayu tekki bi mëneegul làkk wii. Dencal mbind mi njëkk walla dugal tekki bu ñu seet.", "翻译服务目前不支持此语言。请保留原文或输入经审核的译文。"],
  ["The translation provider is busy. Try again later; the original text is unchanged.", "El proveedor de traducción está ocupado. Inténtalo más tarde; el original no cambió.", "Le service de traduction est occupé. Réessayez plus tard ; l’original reste inchangé.", "Jumtuwaayu tekki bi dafay liggéey. Jéemaatal ci kanam; mbind mi soppeekuul.", "翻译服务繁忙。请稍后重试；原文未更改。"],
  ["The translation did not preserve the original details and was rejected. The original text is unchanged.", "La traducción no conservó los detalles originales y se rechazó. El original no cambió.", "La traduction n’a pas conservé les détails d’origine et a été rejetée. L’original reste inchangé.", "Tekki bi sàmmul xibaar yi njëkk, moo tax ñu bañ ko. Mbind mi soppeekuul.", "译文未保留原始细节，已被拒绝。原文未更改。"],
  ["I found {count} matching businesses. You can compare them below, or tell me what you would like to change.", "Encontré {count} negocios que coinciden. Puedes compararlos abajo o decirme qué quieres cambiar.", "J’ai trouvé {count} établissements correspondants. Comparez-les ci-dessous ou dites-moi ce que vous souhaitez modifier.", "Gis naa {count} liggéeyukaay yu méngoo. Mën nga leen mengale fii suuf walla wax ma li nga bëgg soppi.", "找到了 {count} 家符合条件的商家。您可以在下方比较，或告诉我想调整哪些条件。"],
  ["I couldn't find a match for these details. Would you like to change the date, price or distance?", "No encontré coincidencias. ¿Quieres cambiar la fecha, el precio o la distancia?", "Je n’ai pas trouvé de résultat correspondant. Souhaitez-vous modifier la date, le prix ou la distance ?", "Gisuma lu méngoo ak lii. Ndax bëgg nga soppi bés bi, njëg bi walla sorewaay bi?", "未找到符合这些条件的结果。您想调整日期、价格或距离吗？"],
  ["I couldn't find that in the published Help center. Try a more specific question or contact support.", "No encontré esa información en el centro de ayuda publicado. Haz una pregunta más específica o contacta con soporte.", "Je n’ai pas trouvé cette information dans le centre d’aide publié. Précisez votre question ou contactez l’assistance.", "Gisuma loolu ci ndimbal li ñu siiwal. Laajal lu gën a leer walla wax ak ndimbal.", "在已发布的帮助中心中未找到该信息。请提出更具体的问题或联系支持人员。"],
  ["Saved conversation context","Contexto de conversación guardado","Contexte de conversation enregistré","Jokkoo bi ñu denc","已保存的对话上下文"],
  ["Save this context for 30 days","Guardar este contexto durante 30 días","Enregistrer ce contexte pendant 30 jours","Denc jokkoo bii diirub 30 fan","保存此上下文30天"],
  ["Resume saved context","Retomar el contexto guardado","Reprendre le contexte enregistré","Dellu ci jokkoo bi ñu denc","恢复已保存的上下文"],
  ["Delete saved context","Eliminar el contexto guardado","Supprimer le contexte enregistré","Màbb jokkoo bi ñu denc","删除已保存的上下文"],
  ["No saved context is available.","No hay contexto guardado disponible.","Aucun contexte enregistré n’est disponible.","Amul jokkoo bu ñu denc.","没有可用的已保存上下文。"],
  ["Saved context expires: {value0}","El contexto guardado caduca: {value0}","Expiration du contexte enregistré : {value0}","Jokkoo bi ñu denc dina jeex: {value0}","已保存上下文的到期日期：{value0}"],
  ["Context saved for 30 days. Only you can resume it in this business.","Contexto guardado durante 30 días. Solo tú puedes retomarlo en este negocio.","Contexte enregistré pour 30 jours. Vous seul pouvez le reprendre dans cet établissement.","Denc nañu jokkoo bi diirub 30 fan. Yaw rekk moo ci mën a dellu ci liggéeyukaay bii.","上下文已保存30天。只有您可以在此商家中恢复它。"],
  ["Saved context deleted. Business audit records are unchanged.","Contexto guardado eliminado. Los registros de auditoría del negocio no cambian.","Contexte enregistré supprimé. Les journaux d’audit de l’établissement restent inchangés.","Màbb nañu jokkoo bi ñu denc. Dencukaayi saytu liggéey bi soppeekuñu.","已删除保存的上下文。商家的审计记录未更改。"],
  ["Saved context resumed. Ask a new question to read current information.","Contexto guardado retomado. Haz una nueva pregunta para consultar información actual.","Contexte enregistré repris. Posez une nouvelle question pour consulter les informations actuelles.","Dellu nañu ci jokkoo bi ñu denc. Laajal laaj bu bees ngir xam xibaar yi am léegi.","已恢复保存的上下文。请提出新问题以查询当前信息。"],
  ["Ask about services, products, professionals or business settings before saving context.","Pregunta por servicios, productos, profesionales o ajustes del negocio antes de guardar el contexto.","Interrogez l’assistant sur les services, produits, professionnels ou paramètres avant d’enregistrer le contexte.","Laajal ci sarwiis yi, mbir yi, boroom xam-xam yi walla réglage yi bala ngay denc jokkoo bi.","保存上下文前，请先询问服务、商品、专业人员或商家设置。"],
  ["Saved context could not be loaded or changed. Your current conversation is still available.","No se pudo cargar ni cambiar el contexto guardado. Tu conversación actual sigue disponible.","Le contexte enregistré n’a pas pu être chargé ou modifié. Votre conversation actuelle reste disponible.","Mënuñu yeb walla soppi jokkoo bi ñu denc. Sa jokkoo bi am léegi mungi fi.","无法加载或更改已保存的上下文。当前对话仍然可用。"],
  ["Save business topic references and your response language for 30 days. Chat text, customer details and proposed changes are not saved as memory. Current permissions and business facts are checked again when you ask a question.","Guarda referencias a temas del negocio y el idioma de respuesta durante 30 días. El texto del chat, los datos de clientes y los cambios propuestos no se guardan como memoria. Al preguntar, se vuelven a comprobar los permisos y los datos actuales.","Enregistrez les références aux sujets de l’établissement et la langue de réponse pendant 30 jours. Le texte du chat, les données des clients et les modifications proposées ne sont pas mémorisés. Les droits et les données actuels sont revérifiés à chaque question.","Denc ay màndargaal waxtaanu liggéey ak làkku tontu bi diirub 30 fan. Mbindu jokkoo, xibaaru kiliyaan ak coppite yi ñu tëral dencuñu leen ni xel. Dinañu seetaat sañ-sañ ak xibaaru liggéey yi saa yoo laajee.","将商家话题引用和回复语言保存30天。聊天文本、客户详情和拟议更改不会存为记忆。每次提问时都会重新检查当前权限和商家信息。"],
  ["Saving replaces your previous saved context. Expired context cannot be resumed and is removed by the daily cleanup. Business audit history is retained separately.","Al guardar se reemplaza el contexto guardado anterior. El contexto caducado no se puede retomar y se elimina en la limpieza diaria. El historial de auditoría se conserva por separado.","L’enregistrement remplace le contexte précédent. Un contexte expiré ne peut pas être repris et est supprimé lors du nettoyage quotidien. L’historique d’audit est conservé séparément.","Denc bii dina wuutu jokkoo bi nga dencoon. Jokkoo bu jeex kenn mënu ci dellu, te dinañu ko màbb ci set-setal bu bés bu nekk. Jaar-jaaru saytu liggéey bi dañu koy denc ci wetam.","保存将替换之前保存的上下文。过期上下文无法恢复，并会在每日清理时删除。商家审计历史单独保留。"],
];
export const GCIA_SOURCE_MESSAGES: Record<string, Record<string, string>> = Object.fromEntries(
  ["es", "fr", "wo", "zh-CN"].map((locale, index) => [locale, Object.fromEntries(rows.map(row => [row[0], row[index + 1]]))]),
);
export function gciaText(source: string, locale: string, values: Record<string, string | number> = {}) {
  return (GCIA_SOURCE_MESSAGES[locale]?.[source] || source).replace(/\{(\w+)\}/g, (token, key: string) => Object.hasOwn(values, key) ? String(values[key]) : token);
}
