// Generated by scripts/generate-interface-source-registry.mjs.
// Do not hand-edit; regenerate after customer-facing copy changes.
export const GENERATED_SOURCE_MESSAGES = {
  "source.503fe2be648e": {
    "source": "100 miles",
    "impact": "standard"
  },
  "source.1028d69a2fee": {
    "source": "15 min",
    "impact": "standard"
  },
  "source.801663ffab21": {
    "source": "20% off",
    "impact": "standard"
  },
  "source.d3ddf7a34d22": {
    "source": "30 min",
    "impact": "standard"
  },
  "source.983be76344ba": {
    "source": "45 min",
    "impact": "standard"
  },
  "source.b4bfffeb619b": {
    "source": "60 min",
    "impact": "standard"
  },
  "source.4d04eece64a7": {
    "source": "Account connected",
    "impact": "standard"
  },
  "source.ea87741c7c7b": {
    "source": "Account created. Check your email to confirm it, then log in.",
    "impact": "standard"
  },
  "source.968d27b46a89": {
    "source": "Account created. Confirm your email, then log in to complete your salon application.",
    "impact": "standard"
  },
  "source.a951f4d0a0fa": {
    "source": "Account Details",
    "impact": "standard"
  },
  "source.6e702cb4e0c7": {
    "source": "Account Status",
    "impact": "standard"
  },
  "source.2f68d770f0dc": {
    "source": "Account unavailable",
    "impact": "standard"
  },
  "source.d0638bb07b46": {
    "source": "Activate promotion",
    "impact": "standard"
  },
  "source.4e2e91b40c29": {
    "source": "Activate subscription",
    "impact": "booking"
  },
  "source.2f5dcc92240f": {
    "source": "Active Blocks",
    "impact": "standard"
  },
  "source.15363eb576e7": {
    "source": "Active filters",
    "impact": "standard"
  },
  "source.e9e7205b6f0b": {
    "source": "Add another",
    "impact": "standard"
  },
  "source.5bcf4db4336b": {
    "source": "Add item",
    "impact": "standard"
  },
  "source.cb78db4bbad6": {
    "source": "Add language",
    "impact": "standard"
  },
  "source.ee611e536d6e": {
    "source": "Add Product",
    "impact": "standard"
  },
  "source.de6594c0c501": {
    "source": "Add Service",
    "impact": "standard"
  },
  "source.581f19bb90f2": {
    "source": "Add Style",
    "impact": "standard"
  },
  "source.752de79d7121": {
    "source": "Add Stylist",
    "impact": "standard"
  },
  "source.bb25b8516d74": {
    "source": "Admin access",
    "impact": "standard"
  },
  "source.500188faa84f": {
    "source": "Admin login",
    "impact": "security"
  },
  "source.71adefcd1937": {
    "source": "Admin Login",
    "impact": "security"
  },
  "source.dff73a258538": {
    "source": "Admin notes",
    "impact": "standard"
  },
  "source.eeaa13a51a89": {
    "source": "Admin response",
    "impact": "standard"
  },
  "source.e20c4bf694c2": {
    "source": "admin@girlzculture.com",
    "impact": "standard"
  },
  "source.45449576972d": {
    "source": "Affected feature",
    "impact": "standard"
  },
  "source.ab43eb50ea62": {
    "source": "Affected surfaces:",
    "impact": "standard"
  },
  "source.50004d6595e3": {
    "source": "After you sign up, you’ll complete a short application to list your salon.",
    "impact": "security"
  },
  "source.4c7ac989857c": {
    "source": "Alert thresholds",
    "impact": "standard"
  },
  "source.8da023614791": {
    "source": "All Bookings",
    "impact": "booking"
  },
  "source.f136c558660a": {
    "source": "All features",
    "impact": "standard"
  },
  "source.a438b7180dd4": {
    "source": "All markets",
    "impact": "standard"
  },
  "source.34a5adb1782c": {
    "source": "All plans",
    "impact": "standard"
  },
  "source.cbe8ec59a80a": {
    "source": "All Reviews",
    "impact": "standard"
  },
  "source.8721d71a0a5b": {
    "source": "All severity",
    "impact": "standard"
  },
  "source.1740d80893cd": {
    "source": "All states",
    "impact": "standard"
  },
  "source.6405179d241b": {
    "source": "All statuses",
    "impact": "standard"
  },
  "source.2a153ef29153": {
    "source": "Alphabetical (recommended)",
    "impact": "standard"
  },
  "source.8559034a07c9": {
    "source": "Already have an account?",
    "impact": "standard"
  },
  "source.90346db04697": {
    "source": "Amounts are stored from Stripe invoices, refunds, and credit notes. State and market are snapshots from the salon record when each event was received.",
    "impact": "booking"
  },
  "source.0aafdfb493fb": {
    "source": "Any rating",
    "impact": "standard"
  },
  "source.65de73c5706f": {
    "source": "Any visibility",
    "impact": "standard"
  },
  "source.0d9ba174ebf2": {
    "source": "Application submitted!",
    "impact": "standard"
  },
  "source.e2e5335e3c55": {
    "source": "application[key] ?",
    "impact": "standard"
  },
  "source.e6681179a3b5": {
    "source": "Apply first. After approval, activate your selected plan securely through Stripe test mode.",
    "impact": "standard"
  },
  "source.d316560592f3": {
    "source": "Approve application",
    "impact": "standard"
  },
  "source.4faa9c5e66c1": {
    "source": "Approve the due-diligence application, reject it with a reason, then activate the salon when it is ready for subscription setup.",
    "impact": "booking"
  },
  "source.448f7fcd78b0": {
    "source": "Array.from(root?.querySelectorAll",
    "impact": "standard"
  },
  "source.39e8fad00ff2": {
    "source": "Asked Questions",
    "impact": "standard"
  },
  "source.317cf96bbf4d": {
    "source": "Assigned admin",
    "impact": "standard"
  },
  "source.e01eacc119b7": {
    "source": "Audit Trail",
    "impact": "standard"
  },
  "source.408fc571e4c1": {
    "source": "Authorized Users",
    "impact": "standard"
  },
  "source.8c912530883b": {
    "source": "Availability & Calendar",
    "impact": "standard"
  },
  "source.2a4e138feed0": {
    "source": "Availability date",
    "impact": "standard"
  },
  "source.d4a5f3f886aa": {
    "source": "Available styles",
    "impact": "standard"
  },
  "source.9cdbf376d050": {
    "source": "Available Times",
    "impact": "standard"
  },
  "source.1eab45fedb40": {
    "source": "Beauty. Culture. Confidence.",
    "impact": "standard"
  },
  "source.b7cefb86f67f": {
    "source": "Best-Performing Partners",
    "impact": "standard"
  },
  "source.12bf7fc0c82a": {
    "source": "block.startsWith(\"### \") ?",
    "impact": "standard"
  },
  "source.4afe276b6586": {
    "source": "Blog categories",
    "impact": "standard"
  },
  "source.9b99dde2b360": {
    "source": "Blog Management",
    "impact": "standard"
  },
  "source.003d871bc5c8": {
    "source": "Book Appointment",
    "impact": "booking"
  },
  "source.165dda17b619": {
    "source": "Book trusted beauty professionals on your schedule, anytime and anywhere.",
    "impact": "standard"
  },
  "source.148618bf18cf": {
    "source": "Booked until",
    "impact": "standard"
  },
  "source.c36fdafe4375": {
    "source": "Booking deposits",
    "impact": "booking"
  },
  "source.b3309b27dcca": {
    "source": "Booking Details",
    "impact": "booking"
  },
  "source.2f266d8f6179": {
    "source": "Booking Management",
    "impact": "booking"
  },
  "source.8bc4caddc54b": {
    "source": "Booking Messages",
    "impact": "booking"
  },
  "source.7c9053b51ba7": {
    "source": "Booking unavailable",
    "impact": "booking"
  },
  "source.ec4f40f16aaf": {
    "source": "Bookings & Appointments",
    "impact": "booking"
  },
  "source.456b4136acf7": {
    "source": "Bookings + subscriptions",
    "impact": "booking"
  },
  "source.2121c7784436": {
    "source": "Bookings Overview",
    "impact": "booking"
  },
  "source.e4956c8eb1e2": {
    "source": "Brief explanation",
    "impact": "standard"
  },
  "source.c4b2dd23db02": {
    "source": "Browse styles",
    "impact": "standard"
  },
  "source.00614ceeeb30": {
    "source": "Browse Styles",
    "impact": "standard"
  },
  "source.9d8fab420102": {
    "source": "Business & address",
    "impact": "standard"
  },
  "source.edbf4346d72d": {
    "source": "Business details",
    "impact": "standard"
  },
  "source.ed015c5e3010": {
    "source": "Business Growth & Admin",
    "impact": "standard"
  },
  "source.a10a31503e1c": {
    "source": "Business Information",
    "impact": "standard"
  },
  "source.b7ba36c7a167": {
    "source": "c.cancellationThreshold ? (",
    "impact": "booking"
  },
  "source.21636936db94": {
    "source": "Campaign upload",
    "impact": "standard"
  },
  "source.c6085eb5c6bd": {
    "source": "Cancel booking",
    "impact": "booking"
  },
  "source.35b7999ad273": {
    "source": "Cancel Booking & Process Refund",
    "impact": "booking"
  },
  "source.4f8b84ac75e8": {
    "source": "Cancel upload",
    "impact": "booking"
  },
  "source.68b8022f1a7c": {
    "source": "Cancellation Monitoring",
    "impact": "booking"
  },
  "source.e212c93cd5e6": {
    "source": "Cancellation reason",
    "impact": "booking"
  },
  "source.70cd2ee25017": {
    "source": "Cancellation scheduled",
    "impact": "booking"
  },
  "source.7e900370a009": {
    "source": "Card grid",
    "impact": "standard"
  },
  "source.d31c249199c3": {
    "source": "Card slot",
    "impact": "standard"
  },
  "source.232ef6dc296d": {
    "source": "Card source",
    "impact": "standard"
  },
  "source.602fc5527955": {
    "source": "Card text",
    "impact": "standard"
  },
  "source.4625bdd7e795": {
    "source": "Card title",
    "impact": "standard"
  },
  "source.c953117e2d3b": {
    "source": "Catalog lists are alphabetized automatically. Salon owners see active changes the next time their Styles & Pricing editor loads.",
    "impact": "standard"
  },
  "source.04410a8861bc": {
    "source": "Change location",
    "impact": "standard"
  },
  "source.8c684290ce0b": {
    "source": "Change password",
    "impact": "security"
  },
  "source.62269d6285ea": {
    "source": "Change reason",
    "impact": "standard"
  },
  "source.ae097b6b73f1": {
    "source": "Charged now",
    "impact": "standard"
  },
  "source.e185048ce3c0": {
    "source": "Check again",
    "impact": "standard"
  },
  "source.04aa34b7d91f": {
    "source": "Check the complete street address, city, state, and ZIP below, then save again. Your salon stays out of nearby results until its map location is verified.",
    "impact": "standard"
  },
  "source.9d3f067abf78": {
    "source": "Checking live availability…",
    "impact": "standard"
  },
  "source.28dac644f726": {
    "source": "Choose a city, market, or address",
    "impact": "standard"
  },
  "source.4de619e3bb53": {
    "source": "Choose a translation to edit, preview, publish, or restore.",
    "impact": "standard"
  },
  "source.a23eff716581": {
    "source": "Choose category",
    "impact": "standard"
  },
  "source.09b969bbf9fb": {
    "source": "Choose color",
    "impact": "standard"
  },
  "source.ba85878b59c8": {
    "source": "Choose from the platform catalog, then set your price.",
    "impact": "booking"
  },
  "source.7801b461c742": {
    "source": "Choose replacement",
    "impact": "standard"
  },
  "source.1608eb005071": {
    "source": "Choose salon",
    "impact": "standard"
  },
  "source.d162f601f5e0": {
    "source": "Choose your location, compare real prices and reviews, and book with confidence.",
    "impact": "booking"
  },
  "source.8d3409a337e2": {
    "source": "City, neighborhood, or ZIP",
    "impact": "standard"
  },
  "source.412226715c56": {
    "source": "Clear filters",
    "impact": "standard"
  },
  "source.e088320bb2ea": {
    "source": "Clear location",
    "impact": "standard"
  },
  "source.67300d0fed7c": {
    "source": "Clear search",
    "impact": "standard"
  },
  "source.247fd63183c7": {
    "source": "Clear selection",
    "impact": "standard"
  },
  "source.e4ba801351dc": {
    "source": "Clear slot",
    "impact": "standard"
  },
  "source.a4c41c6ef844": {
    "source": "Compare plans",
    "impact": "standard"
  },
  "source.824bdcf6878f": {
    "source": "Complex records stay in purpose-built editors so validation, relationship previews, and protected history remain clear.",
    "impact": "standard"
  },
  "source.7b194b96ebf5": {
    "source": "Configuration controls",
    "impact": "standard"
  },
  "source.4a7c565d4c44": {
    "source": "Confirm password",
    "impact": "security"
  },
  "source.2c0f9b9317e6": {
    "source": "Confirmation Code",
    "impact": "standard"
  },
  "source.4999d673201c": {
    "source": "Confirmed invoice, renewal, plan-change, refund, and credit events received through the signed Stripe webhook.",
    "impact": "booking"
  },
  "source.2b658ffd9420": {
    "source": "Contact support",
    "impact": "standard"
  },
  "source.4832e45812a2": {
    "source": "Contact us",
    "impact": "standard"
  },
  "source.2631f16105c3": {
    "source": "Context preview",
    "impact": "standard"
  },
  "source.7a4e54ca71c7": {
    "source": "Continue setup",
    "impact": "standard"
  },
  "source.dfc349b9c6f1": {
    "source": "Control public labels, safe internal destinations, order, visibility, and New badges. External URLs and markup are rejected server-side.",
    "impact": "standard"
  },
  "source.4802c44091db": {
    "source": "Create Promotion",
    "impact": "standard"
  },
  "source.f3cb57f4b9de": {
    "source": "Current language",
    "impact": "standard"
  },
  "source.1bf6e6464d46": {
    "source": "Current offers",
    "impact": "standard"
  },
  "source.ec5cfba8f01b": {
    "source": "Current plan",
    "impact": "standard"
  },
  "source.4c9712f8d3e6": {
    "source": "Currently published:",
    "impact": "standard"
  },
  "source.d28ea62b8b54": {
    "source": "Custom destination",
    "impact": "standard"
  },
  "source.3b992ca6cd0b": {
    "source": "Custom position",
    "impact": "standard"
  },
  "source.77d433f98236": {
    "source": "Customer login",
    "impact": "security"
  },
  "source.309c693a5ffa": {
    "source": "Customer name",
    "impact": "standard"
  },
  "source.b5f89d831c2f": {
    "source": "Customer navigation",
    "impact": "standard"
  },
  "source.726ab6b6c805": {
    "source": "Daily request limit must be between 0 and 10,000.",
    "impact": "standard"
  },
  "source.0336b2bf650e": {
    "source": "Default buffer",
    "impact": "standard"
  },
  "source.bdf337f85aad": {
    "source": "Dependencies & safe actions",
    "impact": "standard"
  },
  "source.bbe27c93e727": {
    "source": "Deposit Amount",
    "impact": "booking"
  },
  "source.3ffa89447c06": {
    "source": "Deposit paid",
    "impact": "booking"
  },
  "source.81e5f759aabd": {
    "source": "Describe the issue, what happened, and the resolution you are seeking.",
    "impact": "standard"
  },
  "source.0467d447c351": {
    "source": "Describe the style, area, date, budget, or rating. Every result comes from current Girlz Culture salon, price, location, and availability data.",
    "impact": "booking"
  },
  "source.91bdda6b3687": {
    "source": "Descriptive offer",
    "impact": "standard"
  },
  "source.60b334c71dab": {
    "source": "Directions available",
    "impact": "standard"
  },
  "source.5f1293a21937": {
    "source": "Display order",
    "impact": "standard"
  },
  "source.89f24f888e28": {
    "source": "Draft preview",
    "impact": "standard"
  },
  "source.87682e27aacd": {
    "source": "Draft preview:",
    "impact": "standard"
  },
  "source.6c0bed6e704d": {
    "source": "Drag and drop, or choose a file.",
    "impact": "standard"
  },
  "source.973e7486db4f": {
    "source": "e.g. ht or zh-CN",
    "impact": "standard"
  },
  "source.eb5e206fcaf7": {
    "source": "e.g., Knotless Braids",
    "impact": "standard"
  },
  "source.709d23d3c29b": {
    "source": "Earnings & Payouts",
    "impact": "standard"
  },
  "source.c5abdcde6865": {
    "source": "Earnings Trend",
    "impact": "standard"
  },
  "source.99da1f9e92df": {
    "source": "Edit titles, visibility, and order without a code change.",
    "impact": "standard"
  },
  "source.153c9b215753": {
    "source": "Effective date",
    "impact": "standard"
  },
  "source.0821dec60212": {
    "source": "Eligible salon",
    "impact": "standard"
  },
  "source.11d4ef334a15": {
    "source": "Eligible targets",
    "impact": "standard"
  },
  "source.c94d3175a656": {
    "source": "Email address",
    "impact": "standard"
  },
  "source.16727df3003b": {
    "source": "Email subject",
    "impact": "standard"
  },
  "source.ac9393ea8765": {
    "source": "Emergency revert",
    "impact": "standard"
  },
  "source.a40890f5deda": {
    "source": "Engine areas",
    "impact": "standard"
  },
  "source.8743d80ebd24": {
    "source": "Enter a city, neighborhood, or ZIP above, or share your location when you are ready. We never ask for location permission automatically.",
    "impact": "standard"
  },
  "source.6c1c8a6ca3f4": {
    "source": "Enter a city, neighborhood, or ZIP, or share your location when you are ready.",
    "impact": "standard"
  },
  "source.a77ff8607fc4": {
    "source": "Enter a valid contact email address (name@example.com).",
    "impact": "standard"
  },
  "source.82dccfb84adf": {
    "source": "Enter a valid email address such as name@example.com",
    "impact": "standard"
  },
  "source.7a16b78b49db": {
    "source": "Enter a valid ZIP code (12345 or 12345-6789).",
    "impact": "standard"
  },
  "source.ab45ae5b415e": {
    "source": "Enter code",
    "impact": "standard"
  },
  "source.c127459d607f": {
    "source": "Enter the stylist's name.",
    "impact": "standard"
  },
  "source.5a5376ab4997": {
    "source": "Enter valid display, native, and Intl locale values.",
    "impact": "standard"
  },
  "source.bef203b477cd": {
    "source": "Entire salon",
    "impact": "standard"
  },
  "source.f3d7eb2b15aa": {
    "source": "Environment:",
    "impact": "standard"
  },
  "source.1a3ee7793a6d": {
    "source": "Error severity",
    "impact": "standard"
  },
  "source.39322e7fa017": {
    "source": "Error status",
    "impact": "standard"
  },
  "source.1636f5a9808d": {
    "source": "Estimated Total",
    "impact": "standard"
  },
  "source.329cb94db385": {
    "source": "Expert tips, style inspiration, and real stories from the braid community.",
    "impact": "standard"
  },
  "source.30bd33e760d2": {
    "source": "Explore. Compare. Book with confidence.",
    "impact": "standard"
  },
  "source.6f7db049612e": {
    "source": "Feature enabled",
    "impact": "standard"
  },
  "source.a6288a284854": {
    "source": "Feature unavailable",
    "impact": "standard"
  },
  "source.388eaebee35c": {
    "source": "Featured Salons",
    "impact": "standard"
  },
  "source.1542d1d3d9ca": {
    "source": "Filters:",
    "impact": "standard"
  },
  "source.9b72bfcc1cfd": {
    "source": "Financial records",
    "impact": "standard"
  },
  "source.794d2b0fdada": {
    "source": "Find official Girlz Culture social channels, fresh salon work, platform news, and beauty inspiration.",
    "impact": "standard"
  },
  "source.ae09a70461a8": {
    "source": "Find salons",
    "impact": "standard"
  },
  "source.40d1f6c0e354": {
    "source": "Find Salons",
    "impact": "standard"
  },
  "source.df6e68628eae": {
    "source": "Finding locations…",
    "impact": "standard"
  },
  "source.a3205e0ef774": {
    "source": "Finding matches...",
    "impact": "standard"
  },
  "source.c516d2dfc833": {
    "source": "Finish setup",
    "impact": "standard"
  },
  "source.42695908def8": {
    "source": "Fixed discount",
    "impact": "standard"
  },
  "source.399f2cd9ffe3": {
    "source": "For Professionals",
    "impact": "standard"
  },
  "source.51075e94d386": {
    "source": "For security, use a password you do not use elsewhere.",
    "impact": "security"
  },
  "source.7c7fb7753ef7": {
    "source": "For Stylists",
    "impact": "standard"
  },
  "source.26e06aaa8c99": {
    "source": "Forbidden: this admin role does not have access to this section.",
    "impact": "standard"
  },
  "source.79eff64aa1d0": {
    "source": "Forbidden: this salon role cannot update these profile fields.",
    "impact": "standard"
  },
  "source.062589116deb": {
    "source": "Forbidden: this salon role does not have access to this section.",
    "impact": "standard"
  },
  "source.4c29f7f03358": {
    "source": "Forgot password?",
    "impact": "security"
  },
  "source.a005b4058495": {
    "source": "Full details",
    "impact": "standard"
  },
  "source.64346b483c0a": {
    "source": "Full Name",
    "impact": "standard"
  },
  "source.1183cee68c86": {
    "source": "Fuzzy tolerance",
    "impact": "standard"
  },
  "source.0e16b52652e2": {
    "source": "Get Directions",
    "impact": "standard"
  },
  "source.a1991e8d526d": {
    "source": "Girlz Culture",
    "impact": "standard"
  },
  "source.eba58f3cc16e": {
    "source": "Grace period",
    "impact": "standard"
  },
  "source.59269e099c20": {
    "source": "Haitian Creole",
    "impact": "standard"
  },
  "source.5db37d63ff8b": {
    "source": "Hero framing",
    "impact": "standard"
  },
  "source.5bef849834bd": {
    "source": "Hero zoom",
    "impact": "standard"
  },
  "source.cd5711c9dcd8": {
    "source": "Hide immediately",
    "impact": "standard"
  },
  "source.163a88c60210": {
    "source": "Homepage Rows",
    "impact": "standard"
  },
  "source.1e5ee27ce804": {
    "source": "Horizontal carousel",
    "impact": "standard"
  },
  "source.d996154734ed": {
    "source": "How can we help?",
    "impact": "standard"
  },
  "source.d7e190542d79": {
    "source": "Identity deletion & email reuse",
    "impact": "security"
  },
  "source.5d40f9f2cd92": {
    "source": "Impact:",
    "impact": "standard"
  },
  "source.e82f14ed31df": {
    "source": "Import drafts",
    "impact": "standard"
  },
  "source.fabb5cdfc8d6": {
    "source": "Import preview",
    "impact": "standard"
  },
  "source.232d9866b8cb": {
    "source": "Integrations & System Status",
    "impact": "standard"
  },
  "source.aa3a4dd907c8": {
    "source": "Join Now",
    "impact": "standard"
  },
  "source.18f45cc042de": {
    "source": "JPG or PNG · maximum original size 12 MB",
    "impact": "standard"
  },
  "source.d600f02ffecd": {
    "source": "Keep your response warm, respectful, and on-brand.",
    "impact": "standard"
  },
  "source.66734da79059": {
    "source": "Kreyòl ayisyen",
    "impact": "standard"
  },
  "source.ca786b54ddf5": {
    "source": "Language order must be between 0 and 100,000.",
    "impact": "standard"
  },
  "source.380a207b5135": {
    "source": "Language registry & translations",
    "impact": "standard"
  },
  "source.bf0e99f413fd": {
    "source": "Last 14 days · database records only",
    "impact": "standard"
  },
  "source.6b16d2ab1c78": {
    "source": "Learn about featured placement →",
    "impact": "standard"
  },
  "source.bdda9f9adb86": {
    "source": "Learn more →",
    "impact": "standard"
  },
  "source.e1fc8a9420cd": {
    "source": "Leave Review",
    "impact": "standard"
  },
  "source.237a7d6bedfc": {
    "source": "Legal, payment, safety, security, and booking translations require explicit human review confirmation.",
    "impact": "security"
  },
  "source.af36dc7b9be2": {
    "source": "Length Options",
    "impact": "standard"
  },
  "source.7797fc03828a": {
    "source": "Licenses & supporting documents",
    "impact": "standard"
  },
  "source.48bb50b53cbf": {
    "source": "Linked salon",
    "impact": "standard"
  },
  "source.c3ffe1ef49d0": {
    "source": "Loading account…",
    "impact": "standard"
  },
  "source.b5b255570f49": {
    "source": "Loading application...",
    "impact": "standard"
  },
  "source.6155044e8645": {
    "source": "Loading application…",
    "impact": "standard"
  },
  "source.153f2deb31b8": {
    "source": "Loading booking messages…",
    "impact": "booking"
  },
  "source.d6b61171cda1": {
    "source": "Loading details…",
    "impact": "standard"
  },
  "source.ef2341f5ccef": {
    "source": "Loading editable content…",
    "impact": "standard"
  },
  "source.42b87840f593": {
    "source": "Loading governed settings…",
    "impact": "standard"
  },
  "source.56372f533dd3": {
    "source": "Loading lifecycle rules…",
    "impact": "standard"
  },
  "source.b88d45b249d9": {
    "source": "Loading monitored errors…",
    "impact": "standard"
  },
  "source.73d48e68ce4a": {
    "source": "Loading navigation…",
    "impact": "standard"
  },
  "source.d2c1dfc3de53": {
    "source": "Loading platform administration…",
    "impact": "standard"
  },
  "source.14b5a37fcf21": {
    "source": "Loading salons",
    "impact": "standard"
  },
  "source.8956c9141b48": {
    "source": "Loading secure booking…",
    "impact": "booking"
  },
  "source.4bf91800d196": {
    "source": "Loading signup…",
    "impact": "standard"
  },
  "source.541ebe74ceb9": {
    "source": "Loading your beauty journey…",
    "impact": "standard"
  },
  "source.e7385126e285": {
    "source": "Loading your salon workspace…",
    "impact": "standard"
  },
  "source.f7c400ed695f": {
    "source": "Log in",
    "impact": "standard"
  },
  "source.efd197f3fce4": {
    "source": "Main navigation",
    "impact": "standard"
  },
  "source.b68be532ac2a": {
    "source": "Manage login, notifications, publication, and business account details.",
    "impact": "security"
  },
  "source.c2e19cee771a": {
    "source": "Manage safe platform rules, labels, thresholds, and behavior with drafts, review, publication history, and rollback. Credentials remain in secure deployment settings.",
    "impact": "standard"
  },
  "source.94dd62ee59a9": {
    "source": "Manage salons",
    "impact": "standard"
  },
  "source.5c9a858e1b79": {
    "source": "Manage subscription",
    "impact": "booking"
  },
  "source.604ee7e209b2": {
    "source": "Manage the media that tells your salon’s story.",
    "impact": "standard"
  },
  "source.c27ea1b8d2f9": {
    "source": "Manage your bookings, favorites, reviews, and account details.",
    "impact": "booking"
  },
  "source.54d5b9adfc82": {
    "source": "Manage your signature styles, pricing, options, and inclusions.",
    "impact": "standard"
  },
  "source.26f12c39b3c9": {
    "source": "Manual workflow",
    "impact": "standard"
  },
  "source.96968ac5e163": {
    "source": "Marketing administration",
    "impact": "standard"
  },
  "source.c36fd394a9b7": {
    "source": "Marketing overview",
    "impact": "standard"
  },
  "source.f497ad9eb7f9": {
    "source": "Marketplace setup",
    "impact": "standard"
  },
  "source.1266ed22824c": {
    "source": "Marketplace status",
    "impact": "standard"
  },
  "source.7f68ad89ec31": {
    "source": "Media Rules & Dimensions",
    "impact": "standard"
  },
  "source.058f36b25e30": {
    "source": "Mobile navigation",
    "impact": "standard"
  },
  "source.8b784d18c936": {
    "source": "Moderation required",
    "impact": "safety"
  },
  "source.226026526d1d": {
    "source": "Monthly budget must be between $0 and $100,000.",
    "impact": "standard"
  },
  "source.bf7117ef3cae": {
    "source": "More filters",
    "impact": "standard"
  },
  "source.385b4b232f2a": {
    "source": "Most Popular",
    "impact": "standard"
  },
  "source.57bfdf278467": {
    "source": "Most reviews",
    "impact": "standard"
  },
  "source.07dd6f321e97": {
    "source": "Move earlier",
    "impact": "standard"
  },
  "source.bb4c848fa4dc": {
    "source": "Move later",
    "impact": "standard"
  },
  "source.08bdec178602": {
    "source": "Move left/right",
    "impact": "standard"
  },
  "source.9f88b63e04e4": {
    "source": "Move up/down",
    "impact": "standard"
  },
  "source.feff301529be": {
    "source": "My Page",
    "impact": "standard"
  },
  "source.5d3eb2787034": {
    "source": "Name A–Z",
    "impact": "standard"
  },
  "source.080ec6fcc0b2": {
    "source": "Name Z–A",
    "impact": "standard"
  },
  "source.3945a5d48ef4": {
    "source": "Name, owner/contact, ID, city, state, ZIP, market or borough",
    "impact": "standard"
  },
  "source.9703026304af": {
    "source": "name@example.com",
    "impact": "standard"
  },
  "source.9e61fee4bf78": {
    "source": "Navigation & menus",
    "impact": "standard"
  },
  "source.6c2c4c24f01d": {
    "source": "Nearest center",
    "impact": "standard"
  },
  "source.111976197edf": {
    "source": "Need an account?",
    "impact": "standard"
  },
  "source.97e2e9fd5798": {
    "source": "Need help?",
    "impact": "standard"
  },
  "source.cbdcde2413d8": {
    "source": "Needs Attention + hide",
    "impact": "standard"
  },
  "source.33a506cf6ec5": {
    "source": "Needs review",
    "impact": "standard"
  },
  "source.2c34891e488b": {
    "source": "New batch name, e.g. July checkout QA",
    "impact": "standard"
  },
  "source.739e818452f3": {
    "source": "new Date(booking.service_started_at).getTime()",
    "impact": "booking"
  },
  "source.d850ee188c7c": {
    "source": "New password",
    "impact": "security"
  },
  "source.c6a9afc3f9ef": {
    "source": "New promotion",
    "impact": "standard"
  },
  "source.ffc791243176": {
    "source": "Next opening",
    "impact": "standard"
  },
  "source.fe6687820101": {
    "source": "Next photo",
    "impact": "standard"
  },
  "source.933d88cd451c": {
    "source": "Next review",
    "impact": "standard"
  },
  "source.d3c94796d9f9": {
    "source": "No appointments",
    "impact": "booking"
  },
  "source.f794cf40a5a4": {
    "source": "No buffer",
    "impact": "standard"
  },
  "source.72a49518a002": {
    "source": "No promotions",
    "impact": "standard"
  },
  "source.0b1c4eb8424c": {
    "source": "No promotions yet. Create a draft, preview it, then activate it when ready.",
    "impact": "standard"
  },
  "source.a5bdc2715ec4": {
    "source": "No radius",
    "impact": "standard"
  },
  "source.e06b4fb6b0ea": {
    "source": "No salons found — try a nearby area.",
    "impact": "standard"
  },
  "source.da49fb3e5c45": {
    "source": "Not offered",
    "impact": "standard"
  },
  "source.1f22e07160cd": {
    "source": "Not staged",
    "impact": "standard"
  },
  "source.18650168a17b": {
    "source": "Notes or special requests (allergies, accessibility, service details…)",
    "impact": "standard"
  },
  "source.a92e15bc0ae1": {
    "source": "Notification Preferences",
    "impact": "standard"
  },
  "source.5cd0aa47c5a6": {
    "source": "Notification templates",
    "impact": "standard"
  },
  "source.a02f67774b9c": {
    "source": "Notifications are blocked. Allow them in your browser or device settings, then try again.",
    "impact": "standard"
  },
  "source.bb864b84cdb0": {
    "source": "Object.entries(preview.reduce",
    "impact": "standard"
  },
  "source.de73518a399a": {
    "source": "Occurrences by day · last 14 days",
    "impact": "standard"
  },
  "source.28cdc4bd1e13": {
    "source": "Offers only",
    "impact": "standard"
  },
  "source.aafd9b645990": {
    "source": "Only approved, paid video campaigns within their real radius are shown.",
    "impact": "standard"
  },
  "source.a970c9a90f3c": {
    "source": "Only records explicitly registered in a named batch can be touched. Names, email domains, dates, and empty fields are never used to guess. Paid and audited history is retained or anonymized.",
    "impact": "standard"
  },
  "source.6f4789b025a1": {
    "source": "Open →",
    "impact": "standard"
  },
  "source.b4c9c83849a1": {
    "source": "Open batch",
    "impact": "standard"
  },
  "source.ff5b51387f28": {
    "source": "Open booking",
    "impact": "booking"
  },
  "source.35e8e17ec7bc": {
    "source": "Open Roles",
    "impact": "standard"
  },
  "source.79f2032ea42c": {
    "source": "Open salon",
    "impact": "standard"
  },
  "source.930a9018d50d": {
    "source": "Optional for customers. When enabled, every new sign-in requires a six-digit email code.",
    "impact": "standard"
  },
  "source.f1e123dd150d": {
    "source": "Order must be between 0 and 100,000.",
    "impact": "standard"
  },
  "source.96ef71934710": {
    "source": "Our Products",
    "impact": "standard"
  },
  "source.db29279880c3": {
    "source": "Our Stylists",
    "impact": "standard"
  },
  "source.a806d765009a": {
    "source": "Overall rating",
    "impact": "standard"
  },
  "source.d09656c441d7": {
    "source": "Overall Rating",
    "impact": "standard"
  },
  "source.bb7a3b0e69b4": {
    "source": "Owner dashboard",
    "impact": "standard"
  },
  "source.1d0564ae78a8": {
    "source": "Page composition",
    "impact": "standard"
  },
  "source.015b7398b08b": {
    "source": "Page title",
    "impact": "standard"
  },
  "source.1de6d0816c54": {
    "source": "Password updated",
    "impact": "security"
  },
  "source.899a10c131b9": {
    "source": "Past Bookings",
    "impact": "booking"
  },
  "source.dc80127fcd41": {
    "source": "Payment methods",
    "impact": "booking"
  },
  "source.0704b50f2057": {
    "source": "Payout Account",
    "impact": "standard"
  },
  "source.b971a034b4e1": {
    "source": "Per-Stylist Availability",
    "impact": "standard"
  },
  "source.6d291177ef59": {
    "source": "Percentage discount",
    "impact": "standard"
  },
  "source.aaf61f3b409c": {
    "source": "Percentage off",
    "impact": "standard"
  },
  "source.4907c3f80be7": {
    "source": "Plain-text message",
    "impact": "standard"
  },
  "source.7c39b5a1b695": {
    "source": "Platform Admin",
    "impact": "standard"
  },
  "source.3f03c15d0123": {
    "source": "Platform Administration",
    "impact": "standard"
  },
  "source.449b5f460fb5": {
    "source": "Platform Settings",
    "impact": "standard"
  },
  "source.0ae7b020e731": {
    "source": "Please enter a valid email address (name@example.com).",
    "impact": "standard"
  },
  "source.7365d4da7395": {
    "source": "Please enter a valid ZIP code (12345 or 12345-6789).",
    "impact": "standard"
  },
  "source.b2e2352e9043": {
    "source": "Preview for",
    "impact": "standard"
  },
  "source.d3f3ef51e589": {
    "source": "Preview import",
    "impact": "standard"
  },
  "source.09972524c11e": {
    "source": "Previous photo",
    "impact": "standard"
  },
  "source.fd6211f2a982": {
    "source": "Previous review",
    "impact": "standard"
  },
  "source.63af45e3593d": {
    "source": "Private documents",
    "impact": "standard"
  },
  "source.75674afc93a7": {
    "source": "Private PDF, JPG, or PNG · up to 10 MB each",
    "impact": "standard"
  },
  "source.e328e4c2a95e": {
    "source": "Profile Completion",
    "impact": "standard"
  },
  "source.b1072ed658a8": {
    "source": "Profile settings",
    "impact": "standard"
  },
  "source.62f550cb2b13": {
    "source": "Promo & Discount Codes",
    "impact": "standard"
  },
  "source.edfcc5e373d8": {
    "source": "Promo code",
    "impact": "standard"
  },
  "source.555fec629695": {
    "source": "Promotion Performance",
    "impact": "standard"
  },
  "source.0a56b1d27c31": {
    "source": "Promotion visibility",
    "impact": "standard"
  },
  "source.9e54993aed01": {
    "source": "Public page",
    "impact": "standard"
  },
  "source.64fefb5acd58": {
    "source": "Publish change",
    "impact": "standard"
  },
  "source.7022bbbd27b2": {
    "source": "Publish status",
    "impact": "standard"
  },
  "source.22d678d12784": {
    "source": "Published promotions are shown according to your active plan. Performance reporting will remain empty until real views, clicks, and attributed bookings are collected.",
    "impact": "booking"
  },
  "source.a521d2f7f901": {
    "source": "Quality Threshold",
    "impact": "standard"
  },
  "source.c40810f5c31d": {
    "source": "Quick Actions",
    "impact": "standard"
  },
  "source.157bcd443041": {
    "source": "Radius center",
    "impact": "standard"
  },
  "source.f583b897834a": {
    "source": "Ranking boost",
    "impact": "standard"
  },
  "source.342c46503455": {
    "source": "Rating high–low",
    "impact": "standard"
  },
  "source.646061e2f388": {
    "source": "Read More",
    "impact": "standard"
  },
  "source.c7a01a31f6ed": {
    "source": "Ready for your next look?",
    "impact": "standard"
  },
  "source.4ea236ebad1d": {
    "source": "Ready to shape the future of beauty?",
    "impact": "standard"
  },
  "source.7d09b29bf74b": {
    "source": "Reassign to",
    "impact": "standard"
  },
  "source.8aebf36d41d7": {
    "source": "Recent Activity",
    "impact": "standard"
  },
  "source.892aca2bdedf": {
    "source": "Recent Promotions",
    "impact": "standard"
  },
  "source.83c623252bb1": {
    "source": "Recent Reviews",
    "impact": "standard"
  },
  "source.8b574ebb62c2": {
    "source": "Recent verification is required. Sign out, sign in again, complete the verification code, and retry within 15 minutes.",
    "impact": "security"
  },
  "source.851f13c19369": {
    "source": "Recheck eligibility",
    "impact": "standard"
  },
  "source.6bc9ee86ca82": {
    "source": "Recommended: booking alerts",
    "impact": "booking"
  },
  "source.d6369430e67e": {
    "source": "Reconnect to view live availability, pricing, and bookings. Previously visited public pages may still be available.",
    "impact": "booking"
  },
  "source.5654774fed87": {
    "source": "Reference, route, or technical cause",
    "impact": "standard"
  },
  "source.9cf53df4cc60": {
    "source": "Refresh checklist",
    "impact": "standard"
  },
  "source.939fea83dc87": {
    "source": "Remaining balance",
    "impact": "standard"
  },
  "source.8eee07bdc8bf": {
    "source": "Remove material",
    "impact": "standard"
  },
  "source.e7eaff78b315": {
    "source": "Remove section",
    "impact": "standard"
  },
  "source.521dd31be482": {
    "source": "Replacement record",
    "impact": "standard"
  },
  "source.4d0255e85ede": {
    "source": "request failed",
    "impact": "standard"
  },
  "source.5c4bc97ee5d0": {
    "source": "Reset password",
    "impact": "security"
  },
  "source.ab300c41bc74": {
    "source": "Restore draft",
    "impact": "standard"
  },
  "source.eed38a8e6f17": {
    "source": "Retry search",
    "impact": "standard"
  },
  "source.a3d070bc45a5": {
    "source": "Return home",
    "impact": "standard"
  },
  "source.a5fdd7b999fa": {
    "source": "Review & publish",
    "impact": "standard"
  },
  "source.7e40d378e3c6": {
    "source": "Review decision",
    "impact": "standard"
  },
  "source.d0b749c40c36": {
    "source": "Review Distribution",
    "impact": "standard"
  },
  "source.c49dbcbfcd54": {
    "source": "Reviews & Moderation",
    "impact": "safety"
  },
  "source.eaa1ae650af5": {
    "source": "Rotate 90°",
    "impact": "standard"
  },
  "source.d0c7f5a99ef8": {
    "source": "Rule active",
    "impact": "standard"
  },
  "source.6fb9a2485316": {
    "source": "Safe action",
    "impact": "standard"
  },
  "source.448e957dba03": {
    "source": "Safe health summaries only. Credentials, connection strings, provider responses, raw SQL, and secret values are never displayed here.",
    "impact": "standard"
  },
  "source.b31aef39deb6": {
    "source": "Safety sandbox",
    "impact": "safety"
  },
  "source.9cec90aadd67": {
    "source": "Salon accounts use SMS two-factor verification. If SMS delivery is unavailable, the code is sent to the account email.",
    "impact": "security"
  },
  "source.f91ed311fe4e": {
    "source": "Salon application",
    "impact": "standard"
  },
  "source.5da29ab6705e": {
    "source": "Salon Application",
    "impact": "standard"
  },
  "source.59013a9d1301": {
    "source": "Salon login",
    "impact": "security"
  },
  "source.c8612b5c9f84": {
    "source": "Salon Logo",
    "impact": "standard"
  },
  "source.d255e860fcbb": {
    "source": "Salon operations",
    "impact": "standard"
  },
  "source.d48d6a88eafb": {
    "source": "Salon photos",
    "impact": "standard"
  },
  "source.63d294ecd3b6": {
    "source": "Salon Promotions",
    "impact": "standard"
  },
  "source.35490bc18f18": {
    "source": "Salon reply:",
    "impact": "standard"
  },
  "source.0ca45f2a0dbc": {
    "source": "Salon subscriptions",
    "impact": "booking"
  },
  "source.432631fda999": {
    "source": "Salon totals",
    "impact": "standard"
  },
  "source.1a650489fba6": {
    "source": "Salon, customer name, and a valid local appointment time are required.",
    "impact": "booking"
  },
  "source.089447226155": {
    "source": "Salon, style, and date are required.",
    "impact": "standard"
  },
  "source.164a1a95864f": {
    "source": "Sanitized cause",
    "impact": "standard"
  },
  "source.179359b39edb": {
    "source": "Save changes",
    "impact": "standard"
  },
  "source.fa2984b367b8": {
    "source": "Save Changes",
    "impact": "standard"
  },
  "source.4f25637a5b7e": {
    "source": "Save draft",
    "impact": "standard"
  },
  "source.3f1909e2983e": {
    "source": "Save hours",
    "impact": "standard"
  },
  "source.f62a6b681347": {
    "source": "Save Logo",
    "impact": "standard"
  },
  "source.948302e71d3e": {
    "source": "Save media",
    "impact": "standard"
  },
  "source.17e4a1088589": {
    "source": "Save Page",
    "impact": "standard"
  },
  "source.eb4f0b0efc9a": {
    "source": "Save Post",
    "impact": "standard"
  },
  "source.1076e8efbcbf": {
    "source": "Save Product",
    "impact": "standard"
  },
  "source.02b4503b849d": {
    "source": "Save row",
    "impact": "standard"
  },
  "source.0022a3e10caa": {
    "source": "Save Settings",
    "impact": "standard"
  },
  "source.4646ee7f4968": {
    "source": "Save Stylist",
    "impact": "standard"
  },
  "source.cf0bd8a80071": {
    "source": "Save the service details first, then upload its images.",
    "impact": "standard"
  },
  "source.0a228a597fb4": {
    "source": "Saved promotions",
    "impact": "standard"
  },
  "source.bbcbe4b247f4": {
    "source": "Saving and recalculating salons…",
    "impact": "standard"
  },
  "source.900f3e8998dd": {
    "source": "Saving and verifying in Supabase…",
    "impact": "standard"
  },
  "source.638126ff582e": {
    "source": "Saving decision...",
    "impact": "standard"
  },
  "source.00a509366d18": {
    "source": "Scheduled and Active campaigns require a verified Stripe payment, paid invoice, or approved platform credit covering the full campaign period.",
    "impact": "booking"
  },
  "source.b1bd47e1b093": {
    "source": "Search keys, source, or translation",
    "impact": "standard"
  },
  "source.5ae6c089d01d": {
    "source": "Search salons",
    "impact": "standard"
  },
  "source.f65c33c9e4ab": {
    "source": "Search Salons",
    "impact": "standard"
  },
  "source.e40daa9c6721": {
    "source": "Search style",
    "impact": "standard"
  },
  "source.9926c61c8ae4": {
    "source": "Search styles",
    "impact": "standard"
  },
  "source.02591fea29b4": {
    "source": "Search, keywords & synonyms",
    "impact": "standard"
  },
  "source.dd3d55235136": {
    "source": "Section permissions",
    "impact": "standard"
  },
  "source.939120cda962": {
    "source": "Secure booking",
    "impact": "booking"
  },
  "source.391394c8f82b": {
    "source": "Selected add-ons",
    "impact": "standard"
  },
  "source.60c04eca58f2": {
    "source": "Selected products",
    "impact": "standard"
  },
  "source.b985e2bcf177": {
    "source": "Selected services",
    "impact": "standard"
  },
  "source.0077552211f1": {
    "source": "Selected styles",
    "impact": "standard"
  },
  "source.cca3ee791365": {
    "source": "Selected Work",
    "impact": "standard"
  },
  "source.c70a890d1411": {
    "source": "Send message",
    "impact": "standard"
  },
  "source.b449b942c8ef": {
    "source": "Service group",
    "impact": "standard"
  },
  "source.fa3598a3e47f": {
    "source": "Service Image",
    "impact": "standard"
  },
  "source.bd66e4f9372e": {
    "source": "Share salon",
    "impact": "standard"
  },
  "source.63bb10c08f11": {
    "source": "Share what made this experience great, or where there’s room to improve.",
    "impact": "standard"
  },
  "source.9585cf1ab941": {
    "source": "Share your salon’s work with nearby clients.",
    "impact": "standard"
  },
  "source.396c2137a0b5": {
    "source": "Short description",
    "impact": "standard"
  },
  "source.044b852f30b6": {
    "source": "Show password",
    "impact": "security"
  },
  "source.ada2e9e96fa9": {
    "source": "Sign in",
    "impact": "standard"
  },
  "source.0b81497c8589": {
    "source": "Sign up",
    "impact": "security"
  },
  "source.99d21ae3a65b": {
    "source": "Six vertical slots · maximum 30 seconds · MP4/WebM · optimized before upload.",
    "impact": "standard"
  },
  "source.52e07d3b3586": {
    "source": "Six-digit code",
    "impact": "standard"
  },
  "source.2d7486e817ca": {
    "source": "Size Options",
    "impact": "standard"
  },
  "source.f183f4ac285d": {
    "source": "Slot interval",
    "impact": "standard"
  },
  "source.c602cbe76421": {
    "source": "Social channels",
    "impact": "standard"
  },
  "source.b291fb0a20b7": {
    "source": "Starting price",
    "impact": "booking"
  },
  "source.21bd05b0c1b0": {
    "source": "State *",
    "impact": "standard"
  },
  "source.3764d8cad266": {
    "source": "Status actions",
    "impact": "standard"
  },
  "source.70ceb3f38ee9": {
    "source": "Status history",
    "impact": "standard"
  },
  "source.25e6e3e3abd1": {
    "source": "Still need help?",
    "impact": "standard"
  },
  "source.56b3d7597d53": {
    "source": "Stop words",
    "impact": "standard"
  },
  "source.d5ef851fefd7": {
    "source": "Store Hours",
    "impact": "standard"
  },
  "source.fd2f033ebd4e": {
    "source": "Styles & Pricing",
    "impact": "standard"
  },
  "source.322ca9835504": {
    "source": "Subscription Records",
    "impact": "booking"
  },
  "source.d9694c846cbf": {
    "source": "Subscription saved.",
    "impact": "booking"
  },
  "source.16815828c493": {
    "source": "Super Admin only. This immediately republishes the preceding published version, records the reason, and invalidates configuration caches.",
    "impact": "standard"
  },
  "source.e487e0752b1c": {
    "source": "Super Admin only. This removes the canonical Auth account, revokes access, preserves required history by anonymizing or detaching personal data, and releases the normalized email only after Auth deletion succeeds.",
    "impact": "standard"
  },
  "source.43782b37f011": {
    "source": "Test mode",
    "impact": "standard"
  },
  "source.693040ed6979": {
    "source": "TEST MODE:",
    "impact": "standard"
  },
  "source.28baa9dc55ae": {
    "source": "That local time does not exist in the salon’s timezone. Choose another time.",
    "impact": "standard"
  },
  "source.0d3bba4cc288": {
    "source": "The card uses this salon’s name, cover photo, location, and public profile link.",
    "impact": "standard"
  },
  "source.937729b77a61": {
    "source": "The emergency kill switch is governed above. Core booking, search, support, and publishing continue without AI. No feature can approve a salon, send a reply, issue a refund, change billing, delete an identity, or publish content.",
    "impact": "security"
  },
  "source.978cdd43fef4": {
    "source": "The Engine",
    "impact": "standard"
  },
  "source.53ea53bc4b5f": {
    "source": "The last active Super Admin cannot be suspended, revoked, or removed.",
    "impact": "standard"
  },
  "source.99d294df9f49": {
    "source": "The link may have changed, or this salon may not be published yet. Browse available salons to keep looking.",
    "impact": "standard"
  },
  "source.1756d7b8e5b7": {
    "source": "The record now carries an explicit, durable test-data marker.",
    "impact": "standard"
  },
  "source.c6ea785f27a8": {
    "source": "The salon you requested is not available yet, or the link may need a refresh.",
    "impact": "standard"
  },
  "source.281943d8192f": {
    "source": "These products are advertised for in-person purchase only and appear on your salon’s public page. No online checkout.",
    "impact": "standard"
  },
  "source.dcd8fb471d15": {
    "source": "These salons have active, paid Featured campaigns and are shown only when they are genuinely within the campaign radius of your location.",
    "impact": "standard"
  },
  "source.4e4812b6c5a0": {
    "source": "This browser does not support Web Push. Use current Safari, Chrome, Edge, or Firefox.",
    "impact": "standard"
  },
  "source.ce98a3825ec9": {
    "source": "This file is named as MP4, but its container is not a readable MP4. Export a genuine H.264/AAC MP4 and try again.",
    "impact": "standard"
  },
  "source.b17721d71935": {
    "source": "This file is named as WebM, but its container is not a readable WebM. Export a genuine VP8/VP9 WebM and try again.",
    "impact": "standard"
  },
  "source.fef059380e2b": {
    "source": "This record has booking history and must be archived, not deleted.",
    "impact": "booking"
  },
  "source.75cefd953657": {
    "source": "This refunds the deposit, releases the slot, notifies the customer, and affects your cancellation rate.",
    "impact": "booking"
  },
  "source.45b2d4829bc5": {
    "source": "Times use the salon’s local timezone and include service duration plus cleanup buffer.",
    "impact": "standard"
  },
  "source.836e41eed991": {
    "source": "to confirm",
    "impact": "standard"
  },
  "source.a2a7c604797b": {
    "source": "Total Price",
    "impact": "booking"
  },
  "source.8c3345f3d766": {
    "source": "Total Reviews",
    "impact": "standard"
  },
  "source.273f145410af": {
    "source": "Track your earnings, manage payouts, and view your transaction history.",
    "impact": "standard"
  },
  "source.4ed32a0e08a9": {
    "source": "Transaction History",
    "impact": "standard"
  },
  "source.6be8a417a40d": {
    "source": "Trending Picks",
    "impact": "standard"
  },
  "source.d1e58d4b6256": {
    "source": "Trust Info",
    "impact": "standard"
  },
  "source.042c862e4467": {
    "source": "Try again",
    "impact": "standard"
  },
  "source.0faa668453e0": {
    "source": "Try: Affordable knotless braids near Harlem this Saturday morning",
    "impact": "standard"
  },
  "source.b1f9bfea5f64": {
    "source": "Two-factor verification",
    "impact": "security"
  },
  "source.60a75ec59af3": {
    "source": "Type a private booking message…",
    "impact": "booking"
  },
  "source.7fae68409b06": {
    "source": "Type of Business *",
    "impact": "standard"
  },
  "source.7c5263dbe764": {
    "source": "Unavailable today",
    "impact": "standard"
  },
  "source.0ea26fe6adb4": {
    "source": "Upcoming Appointments",
    "impact": "booking"
  },
  "source.535b127dc82e": {
    "source": "Upcoming Bookings",
    "impact": "booking"
  },
  "source.705e0f84982e": {
    "source": "Upload, trim where your browser supports it, choose a poster frame, preview, moderate, and schedule local placement.",
    "impact": "standard"
  },
  "source.a6a4019397c6": {
    "source": "Uploaded image",
    "impact": "standard"
  },
  "source.e8dbf793c6d3": {
    "source": "Uploading documents…",
    "impact": "standard"
  },
  "source.a3a446cc6c34": {
    "source": "Use # for a large heading, ## or ### for smaller headings, - for bullets, and [label](/page) for a link. HTML is not accepted.",
    "impact": "standard"
  },
  "source.281b6d6e732c": {
    "source": "Use a valid BCP-47 locale such as ht, fil, or zh-CN.",
    "impact": "standard"
  },
  "source.703db3c2e42c": {
    "source": "Use your new password in the customer, salon-owner, or admin login that belongs to your account.",
    "impact": "security"
  },
  "source.e1e0fe832249": {
    "source": "Verification application",
    "impact": "security"
  },
  "source.80f2f2980f48": {
    "source": "Verification code",
    "impact": "security"
  },
  "source.55ab0c400e85": {
    "source": "Verified Client",
    "impact": "standard"
  },
  "source.953de2202761": {
    "source": "Verified coordinates",
    "impact": "standard"
  },
  "source.91f86581f16b": {
    "source": "Version history",
    "impact": "standard"
  },
  "source.af1a0ec85f64": {
    "source": "Video URL",
    "impact": "standard"
  },
  "source.931e1a4b152a": {
    "source": "View all",
    "impact": "standard"
  },
  "source.fe48df2e4a74": {
    "source": "View all →",
    "impact": "standard"
  },
  "source.b1199f1726b6": {
    "source": "View applications",
    "impact": "standard"
  },
  "source.badd385121c5": {
    "source": "View details",
    "impact": "standard"
  },
  "source.b98795a246f0": {
    "source": "View profile",
    "impact": "standard"
  },
  "source.1951520ad9ac": {
    "source": "View salon",
    "impact": "standard"
  },
  "source.2dad0a7efa21": {
    "source": "We’ll notify you of our decision and guide you through the next steps.",
    "impact": "standard"
  },
  "source.8c8b73267861": {
    "source": "Welcome back,",
    "impact": "standard"
  },
  "source.e9ef659a9f0d": {
    "source": "What happened?",
    "impact": "standard"
  },
  "source.4ef9217b5444": {
    "source": "What happens next?",
    "impact": "standard"
  },
  "source.9aa54cdcbdd8": {
    "source": "What service are you looking for?",
    "impact": "standard"
  },
  "source.1885f99e9421": {
    "source": "What style are you looking for?",
    "impact": "standard"
  },
  "source.a921e1c07718": {
    "source": "What’s Included",
    "impact": "standard"
  },
  "source.3764ad9301c4": {
    "source": "Where?",
    "impact": "standard"
  },
  "source.7178df2176d0": {
    "source": "Where? (city, state, or ZIP)",
    "impact": "standard"
  },
  "source.b6d53c7ba0e8": {
    "source": "Works for",
    "impact": "standard"
  },
  "source.ae512695a9a8": {
    "source": "Write a helpful response…",
    "impact": "standard"
  },
  "source.1c80bc4b6eac": {
    "source": "You can still submit. Support will review it manually, and it will not change a business’s quality score without a verified booking.",
    "impact": "booking"
  },
  "source.cc6bb7334283": {
    "source": "You cannot suspend, revoke, or remove your own admin account.",
    "impact": "standard"
  },
  "source.252c16cfab8c": {
    "source": "You must have completed an admin verification code within the last 15 minutes. If prompted, sign out and complete a fresh verified sign-in.",
    "impact": "security"
  },
  "source.c4d4fe6528ff": {
    "source": "You will add and crop your logo, cover image, and gallery in the setup dashboard. Your salon will not become marketplace-visible until all required media is complete.",
    "impact": "standard"
  },
  "source.8ec250898102": {
    "source": "You’re all caught up.",
    "impact": "standard"
  },
  "source.7fe7b9ae48d9": {
    "source": "You’re All Set!",
    "impact": "standard"
  },
  "source.0d5b01cf5729": {
    "source": "You’re offline",
    "impact": "standard"
  },
  "source.e99553534ad1": {
    "source": "Your beauty, your way. We make it effortless.",
    "impact": "standard"
  },
  "source.fd75bbac02b4": {
    "source": "Your beauty.",
    "impact": "standard"
  },
  "source.feb7b7dcc402": {
    "source": "Your dashboard and records remain available, but the public profile is hidden and new bookings are disabled. Contact platform support for status details.",
    "impact": "booking"
  },
  "source.c7b81e0c232a": {
    "source": "Your dashboard works, but the salon stays out of search until every required setup item is complete.",
    "impact": "standard"
  },
  "source.ab42293e29e1": {
    "source": "Your name",
    "impact": "standard"
  },
  "source.26ce41c3476e": {
    "source": "Your salon has been saved, but the owner dashboard stays locked until Girlz Culture approves and activates your store. We’ll email you as soon as the review is complete.",
    "impact": "standard"
  },
  "source.cfaea2700f20": {
    "source": "Your Services",
    "impact": "standard"
  },
  "source.6eba6e13f280": {
    "source": "Your Styles",
    "impact": "standard"
  },
  "source.cd57da690919": {
    "source": "Your way.",
    "impact": "standard"
  },
  "source.4fc05f2763ba": {
    "source": "Zoom in",
    "impact": "standard"
  },
  "source.a4ae4b24a1f5": {
    "source": "Zoom out",
    "impact": "standard"
  }
} as const;
export type GeneratedSourceMessageKey = keyof typeof GENERATED_SOURCE_MESSAGES;
