const en = {
 title: "Import from your Instagram account", intro: "Use a permitted professional account to prepare one private setup draft. Review all six sections before saving anything to your business page.",
 unavailable: "Instagram import is not available for this business yet. Continue with your own information below.", loading: "Checking Instagram import availability…", retry: "Check availability again", connect: "Connect my Instagram account", permission: "I manage this Instagram account and have permission to use its information and the photos I select.",
 connected: "Connected account", retained: "Account read completed; access is disconnected. Saved private information remains available until it expires.", read: "Read my account information", disconnect: "Disconnect Instagram", disconnected: "Instagram disconnected. Previously saved private drafts remain available for your review.",
 accountOnly: "Only this connected account is read. We do not search other accounts or publish to Instagram.", media: "Choose photos for your private draft", photo: "Photo", empty: "No supported photos were returned. You can continue with the available account information or add your own photos later.",
 excerpt: "This is a limited selection from your account, not your complete Instagram history.", limit: "Select up to 16 photos.", draft: "Prepare private draft", working: "Working…", private: "Your selected photos stay private until you explicitly confirm the reviewed draft. Nothing is added to your public gallery now.",
 failed: "This Instagram step could not be completed. Your current draft and selections are still here.", support: "Support reference", unsaved: "Save your current edits before importing another source.", imported: "Instagram source information", captured: "Read on", evidence: "Imported account names and image metadata are source information, not confirmed services, prices, hours or policies.", selected: "Selected photos", previewUnavailable: "Private preview unavailable. Reload the draft before confirming.", manualHelp: "Enter a reference and your own details below. A reference alone does not fetch a website or Instagram account.", photosHelp: "Choose your business's saved photos or privately imported photos. Imported photos are attached only after your explicit review and confirmation.",
} as const;
type Key = keyof typeof en;
export const INSTAGRAM_ONBOARDING_MESSAGES: Record<string, Record<Key, string>> = {
 en,
 fr: {
  title:"Importer depuis votre compte Instagram",intro:"Utilisez un compte professionnel autorisé pour préparer un brouillon privé. Vérifiez les six rubriques avant d’enregistrer des informations sur votre page.",unavailable:"L’import Instagram n’est pas encore disponible pour cette entreprise. Continuez avec vos propres informations ci-dessous.",loading:"Vérification de la disponibilité de l’import Instagram…",retry:"Vérifier à nouveau",connect:"Connecter mon compte Instagram",permission:"Je gère ce compte Instagram et j’ai le droit d’utiliser ses informations et les photos sélectionnées.",connected:"Compte connecté",retained:"Lecture du compte terminée ; l’accès est déconnecté. Les informations privées enregistrées restent disponibles jusqu’à leur expiration.",read:"Lire les informations de mon compte",disconnect:"Déconnecter Instagram",disconnected:"Instagram est déconnecté. Les brouillons privés déjà enregistrés restent disponibles pour vérification.",accountOnly:"Seul ce compte connecté est consulté. Nous ne recherchons pas d’autres comptes et ne publions rien sur Instagram.",media:"Choisissez les photos du brouillon privé",photo:"Photo",empty:"Aucune photo compatible n’a été reçue. Continuez avec les informations du compte ou ajoutez vos photos plus tard.",excerpt:"Il s’agit d’une sélection limitée de votre compte, pas de tout votre historique Instagram.",limit:"Sélectionnez jusqu’à 16 photos.",draft:"Préparer un brouillon privé",working:"Traitement…",private:"Les photos sélectionnées restent privées jusqu’à votre confirmation explicite du brouillon vérifié. Rien n’est ajouté à votre galerie publique maintenant.",failed:"Cette étape Instagram a échoué. Votre brouillon actuel et vos sélections sont conservés.",support:"Référence d’assistance",unsaved:"Enregistrez vos modifications avant d’importer une autre source.",imported:"Informations provenant d’Instagram",captured:"Consultées le",evidence:"Les noms du compte et les métadonnées des images restent des sources, pas des prestations, tarifs, horaires ou conditions confirmés.",selected:"Photos sélectionnées",previewUnavailable:"Aperçu privé indisponible. Rechargez le brouillon avant de confirmer.",manualHelp:"Indiquez une référence et vos informations ci-dessous. Une référence seule ne consulte ni site web ni compte Instagram.",photosHelp:"Choisissez les photos enregistrées de votre entreprise ou les photos importées en privé. Les photos importées ne sont ajoutées qu’après vérification et confirmation explicites.",
 },
 es: {
  title:"Importar desde tu cuenta de Instagram",intro:"Usa una cuenta profesional autorizada para preparar un borrador privado. Revisa las seis secciones antes de guardar información en la página del negocio.",unavailable:"La importación de Instagram aún no está disponible para este negocio. Continúa con tu propia información a continuación.",loading:"Comprobando la disponibilidad de la importación de Instagram…",retry:"Comprobar disponibilidad de nuevo",connect:"Conectar mi cuenta de Instagram",permission:"Administro esta cuenta de Instagram y tengo permiso para usar su información y las fotos que seleccione.",connected:"Cuenta conectada",retained:"La lectura de la cuenta ha terminado y el acceso está desconectado. La información privada guardada sigue disponible hasta que caduque.",read:"Leer la información de mi cuenta",disconnect:"Desconectar Instagram",disconnected:"Instagram se ha desconectado. Los borradores privados guardados siguen disponibles para revisión.",accountOnly:"Solo se consulta esta cuenta conectada. No buscamos otras cuentas ni publicamos en Instagram.",media:"Elige fotos para tu borrador privado",photo:"Foto",empty:"No se recibieron fotos compatibles. Puedes continuar con la información de la cuenta o añadir tus fotos más adelante.",excerpt:"Esta es una selección limitada de tu cuenta, no todo tu historial de Instagram.",limit:"Selecciona hasta 16 fotos.",draft:"Preparar borrador privado",working:"Procesando…",private:"Las fotos seleccionadas permanecen privadas hasta que confirmes expresamente el borrador revisado. Ahora no se añade nada a tu galería pública.",failed:"No se pudo completar este paso de Instagram. Tu borrador actual y tus selecciones siguen aquí.",support:"Referencia de soporte",unsaved:"Guarda tus cambios antes de importar otra fuente.",imported:"Información procedente de Instagram",captured:"Consultada el",evidence:"Los nombres de la cuenta y los metadatos de las imágenes son fuentes, no servicios, precios, horarios o políticas confirmados.",selected:"Fotos seleccionadas",previewUnavailable:"Vista previa privada no disponible. Recarga el borrador antes de confirmar.",manualHelp:"Introduce una referencia y tus datos a continuación. Una referencia por sí sola no consulta un sitio web ni una cuenta de Instagram.",photosHelp:"Elige fotos guardadas del negocio o importadas de forma privada. Las fotos importadas solo se añaden después de tu revisión y confirmación expresas.",
 },
 "zh-CN": {
  title:"从您的 Instagram 账号导入",intro:"使用获授权的专业账号准备一份私密设置草稿。将任何信息保存到商家页面之前，请核对全部六个部分。",unavailable:"此商家暂时无法使用 Instagram 导入。请继续在下方填写您自己的信息。",loading:"正在检查 Instagram 导入是否可用…",retry:"重新检查可用状态",connect:"连接我的 Instagram 账号",permission:"我管理此 Instagram 账号，并有权使用其中的信息和我选择的照片。",connected:"已连接的账号",retained:"账号读取已完成，访问已断开。保存的私密信息在到期前仍可使用。",read:"读取我的账号信息",disconnect:"断开 Instagram 连接",disconnected:"Instagram 已断开连接。之前保存的私密草稿仍可供您核对。",accountOnly:"仅读取此已连接的账号。我们不会搜索其他账号或向 Instagram 发布内容。",media:"选择私密草稿的照片",photo:"照片",empty:"未返回支持的照片。您可以继续使用账号信息，或稍后添加自己的照片。",excerpt:"这里只显示账号中的有限内容，并非完整 Instagram 历史记录。",limit:"最多选择 16 张照片。",draft:"准备私密草稿",working:"处理中…",private:"在您明确确认核对后的草稿之前，所选照片保持私密。现在不会向公开图库添加任何内容。",failed:"无法完成此 Instagram 步骤。您当前的草稿和选择均已保留。",support:"支持参考编号",unsaved:"导入其他来源之前，请先保存当前修改。",imported:"来自 Instagram 的信息",captured:"读取日期",evidence:"导入的账号名称和图片元数据仅作为来源信息，不代表已确认的服务、价格、营业时间或政策。",selected:"所选照片",previewUnavailable:"私密预览暂不可用。请在确认前重新加载草稿。",manualHelp:"请在下方填写来源参考和您自己的信息。仅填写参考地址不会读取网站或 Instagram 账号。",photosHelp:"选择商家已保存的照片或私密导入的照片。只有经过您的明确核对和确认后，才会添加导入的照片。",
 },
};
export const instagramOnboardingText = (locale: string, key: Key) => (INSTAGRAM_ONBOARDING_MESSAGES[locale] || en)[key];
