import { Download, FileText, Image as ImageIcon, Mail, Phone } from "lucide-react";
import { PublicFooter, PublicHeader } from "@/components/site/PublicChrome";
import SafeImage from "@/components/site/SafeImage";
import { getContentPage } from "@/lib/content";

export const dynamic = "force-dynamic";

export default async function Press() {
  const page = await getContentPage("press", { slug: "press", title: "Press", eyebrow: "PRESS", hero_title: "In the News", hero_subtitle: "See how Girlz Culture is redefining the future of beauty and empowering salons and clients everywhere.", hero_image_url: "/images/braids-knotless.jpg", sections: [{ title: "Press Contact", body: "For media inquiries, interviews, or partnership opportunities.\npress@girlzculture.com · (646) 555-0198" }] });
  const news = [["ESSENCE", "Girlz Culture Is Making It Easier to Find Black-Owned Braiding Salons"], ["Forbes", "This Beauty Startup Is Empowering Stylists and Transforming Bookings"], ["Yahoo Finance", "Beauty Tech Platform Girlz Culture Raises Seed Funding"], ["BET", "How Girlz Culture Connects Clients With Top Braiders"]];
  const resources = [[FileText, "Company Overview"], [Download, "Brand Assets"], [ImageIcon, "Press Images"], [FileText, "Fact Sheet"]] as const;
  return <main className="bg-cream text-ink"><PublicHeader/><section className="relative overflow-hidden bg-plum text-white"><div className="mx-auto grid max-w-[1760px] items-center gap-8 px-5 py-10 md:grid-cols-[1fr_.75fr] lg:px-16"><div><p className="text-xs font-bold text-amber">{page.eyebrow}</p><h1 className="mt-4 font-serif text-6xl font-semibold">{page.hero_title}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-white/70">{page.hero_subtitle}</p></div><SafeImage src={page.hero_image_url} fallbackSrc="/images/braids-knotless.jpg" alt="Girlz Culture press" className="h-[320px] w-full rounded-[22px] object-cover object-top"/></div></section>
    <section className="mx-auto max-w-[1600px] px-5 py-9"><h2 className="font-serif text-3xl text-plum">Girlz Culture in the News</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{news.map(([source,title])=><article key={source} className="rounded-[15px] border border-plum/10 bg-white p-5"><b className="text-xl">{source}</b><h3 className="mt-5 font-serif text-lg text-plum">{title}</h3><p className="mt-3 text-xs text-ink/50">May 2026</p><span className="mt-5 block text-xs font-bold text-magenta">Read Article →</span></article>)}</div>
      <section className="mt-8 rounded-[18px] bg-blush/35 p-6"><h2 className="font-serif text-3xl text-plum">Press Kit & Media Resources</h2><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{resources.map(([Icon,label])=><article key={label} className="rounded-xl bg-white p-5 text-center"><Icon className="mx-auto text-plum"/><h3 className="mt-3 font-semibold">{label}</h3><button className="mt-3 text-xs font-bold text-magenta">Download</button></article>)}</div></section>
      <section className="mt-8 grid items-center gap-5 rounded-[18px] bg-blush/45 p-7 md:grid-cols-[1fr_280px]"><div><h2 className="font-serif text-3xl text-plum">{page.sections?.[0]?.title || "Press Contact"}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-ink/60">{page.sections?.[0]?.body}</p><p className="mt-4 flex items-center gap-2 text-sm"><Mail size={16}/>press@girlzculture.com</p><p className="mt-2 flex items-center gap-2 text-sm"><Phone size={16}/>(646) 555-0198</p></div><SafeImage src="/images/braids-cornrows.jpg" fallbackSrc="/images/hero-braids.jpg" alt="Press contact" className="h-48 w-full rounded-xl object-cover"/></section>
    </section><PublicFooter/></main>;
}
