import test from 'node:test';import assert from 'node:assert/strict';import {loadNodeTypescript} from './helpers/load-node-typescript.mjs';
const owner='11000000-0000-4000-8000-000000000001',business='22000000-0000-4000-8000-000000000001',requestId='33000000-0000-4000-8000-000000000001',ticket='44000000-0000-4000-8000-000000000001',reference='55000000-0000-4000-8000-000000000001';
const payload={id:requestId,kind:'profile_review',fingerprint:'a'.repeat(32)};
function fixture({isOwner=true,foreign=false,missing=false,error=null}={}){const calls=[],events=[];const admin={rpc:async(name,args)=>{calls.push({name,args});if(error)return {error:{message:error}};if(name==='request_business_google_help')return {data:{ticket_id:ticket,verified:true}};return {data:{salon_id:foreign?owner:business,requests:missing?[]:[{id:ticket}]}};}};
 const load=loadNodeTypescript(process.cwd(),{'@/lib/supabaseAdmin':{requireSalonOwner:async()=>({admin,isOwner,user:{id:owner},salon:{id:business}})},'@/lib/platformErrors':{capturePlatformError:async e=>{events.push(e);return reference;}},'@/lib/operationalMonitoring':{routeMonitoringProfile:()=>({}),withOperationalMonitoring:(_,h)=>h}});return {calls,events,route:load('src/app/api/salon/google-help/route.ts')};}
const req=(body=payload)=>new Request('https://fixture.test/api/salon/google-help',{method:'POST',body:JSON.stringify(body)});
test('Google help binds authenticated identity, reviewed fingerprint and independent ticket readback',async()=>{const f=fixture(),r=await f.route.POST(req());assert.equal(r.status,200);assert.equal((await r.json()).ticket_id,ticket);assert.deepEqual(f.calls[0],{name:'request_business_google_help',args:{p_salon:business,p_actor:owner,p_request:requestId,p_kind:'profile_review',p_fingerprint:payload.fingerprint}});assert.equal(f.calls[1].name,'read_business_google_help');assert.equal(r.headers.get('Cache-Control'),'private, no-store');});
test('Google help rejects staff and arbitrary body identity before private read',async()=>{const f=fixture({isOwner:false});assert.equal((await f.route.POST(req())).status,403);assert.equal(f.calls.length,0);for(const body of [null,[],{...payload,salon_id:owner},{...payload,kind:'connect'},{...payload,fingerprint:'changed'},{...payload,id:'bad'}]){const c=fixture();assert.equal((await c.route.POST(req(body))).status,400);assert.equal(c.calls.length,0);}});
test('missing or wrong-tenant authoritative ticket never reports verified',async()=>{for(const opts of [{foreign:true},{missing:true}]){const f=fixture(opts),r=await f.route.POST(req());assert.equal(r.status,500);const body=await r.json();assert.equal(body.request_id,reference);assert.equal(r.headers.get('X-Request-ID'),reference);assert.equal(body.verified,undefined);}});
test('scope, entitlement and stale reviews are distinct safe JSON failures',async()=>{for(const [error,status]of [['GOOGLE_HELP_ACCESS_DENIED',403],['GOOGLE_HELP_PLAN_REQUIRED',403],['GOOGLE_HELP_STALE',409],['GOOGLE_HELP_DEMO_DISABLED',403],['private business raw diagnostics',500]]){const f=fixture({error}),r=await f.route.POST(req());assert.equal(r.status,status);const text=await r.text();assert.ok(!text.includes('private business'));assert.equal(f.events[0].salonId,business);assert.ok(!f.events[0].error.message.includes('private'));}});
