import test from 'node:test';
import assert from 'node:assert/strict';
import {typescriptLoader} from './helpers/load-typescript.mjs';
const load=typescriptLoader(process.cwd()),{validateTool}=load('src/lib/gcAssistantCore.ts');
const id='20000000-0000-4000-8000-000000000010';
const args=(operation,change)=>({operation,record_id:id,changes_json:JSON.stringify(change)});
const agreement={effective_from:'2026-09-24',kind:'commission',basis:'after_discount',percent:50,amount_cents:null,period:null};
test('team actions allow only reviewed access grants or typed agreement terms',()=>{
 for(const [operation,v]of [['permissions',{permissions:{bookings:true,settings:false}}],['permissions',{status:'Inactive'}],['arrangement',agreement]]){assert.equal(validateTool('prepare_team_controls',args(operation,v)).risk,4);for(const field of ['salon_id','user_id','stripe_account_id','confirmed','reviewed'])assert.throws(()=>validateTool('prepare_team_controls',args(operation,{...v,[field]:'x'})),/ASSISTANT_INVALID_INPUT/);}
 for(const v of [{permissions:{unknown:true}},{permissions:{bookings:'true'}},{permissions:{}},{status:'Invited'},{}])assert.throws(()=>validateTool('prepare_team_controls',args('permissions',v)),/ASSISTANT_INVALID_INPUT/);
 for(const v of [{...agreement,percent:101},{...agreement,amount_cents:1.5},{...agreement,period:'year'}])assert.throws(()=>validateTool('prepare_team_controls',args('arrangement',v)),/ASSISTANT_INVALID_INPUT/);
 assert.throws(()=>validateTool('prepare_team_controls',{operation:'permissions',record_id:id,changes_json:'{'}),/ASSISTANT_INVALID_INPUT/);
});
function fixture(owner=true,foreign=false,error=null){const calls=[];const context={isOwner:owner,salon:{id:'A'},user:{id:'owner-A'},admin:{async rpc(name,p){calls.push({name,p});return {error,data:{salon_id:foreign?'B':'A',before:{},payload:{operation:'permissions'}}};}}};const helper=typescriptLoader(process.cwd(),{'@/lib/supabaseAdmin':{}})('src/lib/assistantTeamServer.ts');return {calls,read:()=>helper.readAssistantTeam(context),prepare:()=>helper.prepareAssistantTeam(context,args('permissions',{permissions:{bookings:true}}))};}
test('team preparation reads scope but never calls a writer or provider',async()=>{const f=fixture();await f.read();await f.prepare();assert.deepEqual(f.calls.map(x=>x.name),['read_gc_team_controls','preview_gc_team_change']);for(const {p}of f.calls){assert.equal(p.p_salon,'A');assert.equal(p.p_actor,'owner-A');}});
test('nonowners and foreign response scope are blocked before data enters the model',async()=>{for(const method of ['read','prepare']){const f=fixture(false);await assert.rejects(f[method](),/ASSISTANT_ACCESS_DENIED/);assert.equal(f.calls.length,0);await assert.rejects(fixture(true,true)[method](),/ASSISTANT_ACCESS_DENIED/);}});
test('team proposal history rechecks current owner and target without recreating an already confirmed agreement',async()=>{let calls=0;const helper=typescriptLoader(process.cwd(),{'@/lib/supabaseAdmin':{}})('src/lib/assistantProfessionalScope.ts');const context={isOwner:true,salon:{id:'A'},user:{id:'owner'},admin:{async rpc(name,p){calls++;assert.equal(name,'assert_gc_team_target');assert.equal(p.p_record,id);return {data:{salon_id:'A',authorized:true}};}}};await helper.assertAssistantProposalScope(context,'prepare_team_controls',args('arrangement',agreement));assert.equal(calls,1);await assert.rejects(helper.assertAssistantProposalScope({...context,isOwner:false},'prepare_team_controls',args('arrangement',agreement)),/ASSISTANT_ACCESS_DENIED/);assert.equal(calls,1);});
test('team task retains its own retrieval and never switches an unfinished booking to permission changes',()=>{const {continuesActiveTask}=load('src/lib/assistantActiveTask.ts');assert.equal(continuesActiveTask({tool:'prepare_team_controls'},{task_tool:'prepare_team_controls',plan:{tool:'get_team_controls'}}),true);assert.equal(continuesActiveTask({tool:'prepare_manual_appointment'},{task_tool:'prepare_team_controls',plan:{tool:'get_team_controls'}}),false);});
