import test from 'node:test';import assert from 'node:assert/strict';import {loadNodeTypescript} from './helpers/load-node-typescript.mjs';
const owner='11000000-0000-4000-8000-000000000001',business='22000000-0000-4000-8000-000000000001',id='33000000-0000-4000-8000-000000000001',space='44000000-0000-4000-8000-000000000001',reference='55000000-0000-4000-8000-000000000001';
const payload={action:'reserve',id,space_id:space,fingerprint:'a'.repeat(32)};
function fixture({isOwner=true,foreign=false,missing=false,error=null,authError=null}={}){const calls=[],events=[];const ads={salon_id:foreign?owner:business,reservations:missing?[]:[{id,status:'cancelled'}]};const admin={rpc:async(name,args)=>{calls.push({name,args});if(error)return {error:{message:error}};if(name==='read_business_ad_spaces')return {data:ads};if(name==='admin_ad_spaces')return {data:{spaces:[{id:space,active:false}],reservations:[{id,status:'fulfilled',campaign_id:space}]}};return {data:{id,verified:true}};}};
 const load=loadNodeTypescript(process.cwd(),{'@/lib/supabaseAdmin':{requireSalonOwner:async()=>{if(authError)throw Error(authError);return{admin,isOwner,user:{id:owner},salon:{id:business}};},requireAdminPermission:async(_r,permission)=>{assert.equal(permission,'marketing');if(authError)throw Error(authError);return {admin,user:{id:owner}};}},'@/lib/platformErrors':{capturePlatformError:async e=>{events.push(e);return reference;}},'@/lib/operationalMonitoring':{routeMonitoringProfile:()=>({}),withOperationalMonitoring:(_,h)=>h}});return {calls,events,route:load('src/app/api/salon/advertising/route.ts'),adminRoute:load('src/app/api/admin/ad-spaces/route.ts')};}
const req=(body=payload)=>new Request('https://fixture.test/api/salon/advertising',{method:'POST',body:JSON.stringify(body)});
test('Advertising binds authenticated tenant and reviewed quote then independently reads reservation',async()=>{const f=fixture(),r=await f.route.POST(req());assert.equal(r.status,200);assert.equal((await r.json()).verified,true);assert.deepEqual(f.calls[0],{name:'reserve_business_ad_space',args:{p_salon:business,p_actor:owner,p_request:id,p_space:space,p_fingerprint:payload.fingerprint}});assert.equal(f.calls[1].name,'read_business_ad_spaces');});
test('Staff and forged advertising payloads cannot call a database mutation',async()=>{const f=fixture({isOwner:false});assert.equal((await f.route.POST(req())).status,403);assert.equal(f.calls.length,0);for(const body of [null,[],{...payload,salon_id:owner},{...payload,balance_cents:0},{...payload,action:'fulfill'},{...payload,space_id:'bad'}]){const c=fixture();assert.equal((await c.route.POST(req(body))).status,400);assert.equal(c.calls.length,0);}});
test('Advertising cannot report success without exact own reservation readback',async()=>{for(const opts of [{foreign:true},{missing:true}]){const f=fixture(opts),r=await f.route.POST(req());assert.equal(r.status,500);assert.equal((await r.json()).request_id,reference);assert.equal(r.headers.get('X-Request-ID'),reference);}});
test('Owner cancellation keeps the tenant binding and authoritative cancelled status',async()=>{const f=fixture(),r=await f.route.POST(req({action:'cancel',id}));assert.equal(r.status,200);assert.equal(f.calls[0].name,'cancel_business_ad_reservation');assert.deepEqual(f.calls[0].args,{p_salon:business,p_actor:owner,p_request:id});});
test('Advertising failures preserve safe actionable codes and exact protected reference',async()=>{for(const [error,status]of [['AD_QUOTE_CHANGED',409],['AD_ACCESS_DENIED',403],['AD_NOT_AVAILABLE',409],['AD_BUSINESS_NOT_ELIGIBLE',403],['private raw diagnostic',500]]){const f=fixture({error}),r=await f.route.POST(req());assert.equal(r.status,status);assert.ok(!(await r.text()).includes('private raw'));assert.equal(f.events[0].salonId,business);assert.ok(!f.events[0].error.message.includes('private'));}});
test('Advertising admin fulfillment is marketing-scoped, strict and independently read back',async()=>{const f=fixture(),input={id,invoice_reference:'fixture-paid',payment_verified:true,received_cents:7500};const r=await f.adminRoute.POST(req({action:'fulfill',input}));assert.equal(r.status,200);assert.equal((await r.json()).verified,true);assert.deepEqual(f.calls[0].args,{p_actor:owner,p_action:'fulfill',p_input:input});assert.equal(f.calls[1].args.p_action,'read');for(const body of [{action:'fulfill',input:{...input,salon_id:business}},{action:'fulfill',input:{...input,received_cents:1.5}},{action:'close',input:{id,extra:true}},{action:'create',input:{id}},{action:'read',input:{id}}]){const c=fixture();assert.equal((await c.adminRoute.POST(req(body))).status,400);assert.equal(c.calls.length,0);}});
test('Unauthenticated and unauthorized advertising requests return safe JSON',async()=>{for(const path of ['route','adminRoute'])for(const [authError,status]of [['Unauthorized',401],['Forbidden: private membership details',403]]){const f=fixture({authError}),r=await f[path].POST(req());assert.equal(r.status,status);assert.equal(f.calls.length,0);assert.ok(!(await r.text()).includes('private membership'));}});
