import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {loadNodeTypescript} from './helpers/load-node-typescript.mjs';
import {typescriptLoader} from './helpers/load-typescript.mjs';
const load=loadNodeTypescript(process.cwd()),core=load('src/lib/businessFinanceCore.ts');
const id=n=>`17900000-0000-4000-8000-${String(n).padStart(12,'0')}`,business=id(1),actor=id(2),range={start:'2026-09-01T04:00:00Z',end:'2026-09-19T04:00:00Z'};
const sale=(n,patch={})=>({id:`sale:${id(n)}`,salon_id:business,source:'walk_in',kind:'service',status:'completed',occurred_at:'2026-08-15T12:00:00Z',recorded_at:'2026-08-15T12:00:00Z',name:`Service ${n}`,stylist_id:id(3),client_id:null,client_name:`Client ${n}`,list_cents:10000,discount_cents:0,agreed_cents:10000,cost_cents:null,quantity:1,compensation:{kind:'none',version:null},...patch});
function fixture(sales,payments=[],evidence={}){const books={sales,payments,expenses:[],obligations:[],compensation_payments:[]};const admin={rpc:async name=>({data:name==='business_finance_scope'?{kind:'business',stylist_id:null}:true}),from(){const q={select(){return q;},eq(){return q;},maybeSingle:async()=>({data:{id:business,user_id:actor}})};return q;}};const helper=loadNodeTypescript(process.cwd(),{'@/lib/businessFinanceServer':{readBusinessFinances:async(_context,period)=>({books,summary:core.summarizeOperatingBooks(business,books,period),scope:{kind:'business',stylist_id:null},evidence:{unverified_deposit_records:0,unverified_product_payments:0,unverified_refund_records:0,...evidence}})}})('src/lib/assistantOutstandingBalances.ts');return()=>helper.readAssistantOutstandingBalances({admin,salon:{id:business,time_zone:'America/New_York'},user:{id:actor},isOwner:true},range);}
test('cumulative older balances preserve anonymous/future distinction, exact totals and bounded own record links',async()=>{const result=await fixture([...Array.from({length:15},(_,i)=>sale(i+10)),sale(90,{status:'pending',occurred_at:'2026-09-25T12:00:00Z',client_name:null})])();assert.equal(result.completed_count,15);assert.equal(result.completed.length,12);assert.equal(result.completed_unpaid_cents,150000);assert.equal(result.pending_count,1);assert.equal(result.pending_unpaid_cents,10000);assert.equal(result.pending[0].client_name,null);assert.equal(result.as_of_day,'2026-09-18');const url=new URL(result.completed[0].href,'https://fixture.invalid');assert.equal(url.pathname,'/salon/dashboard/earnings');assert.equal(url.searchParams.get('finance_record'),result.completed[0].record);assert.equal(url.searchParams.get('finance_balance'),'unpaid');assert.doesNotMatch(JSON.stringify(result),/client_id|provider_id|email|phone/);});
test('a verified recorded refund does not reopen discharged customer debt',async()=>{const s=sale(10);const receipt={id:'receipt:own',salon_id:business,sale_id:s.id,occurred_at:'2026-09-15T12:00:00Z',stage:'full',method:'cash',amount_cents:10000,original_payment_id:null};const result=await fixture([s],[receipt,{...receipt,id:'refund:own',stage:'refund',amount_cents:2000,original_payment_id:receipt.id}])();assert.equal(result.completed_count,0);assert.equal(result.completed_unpaid_cents,0);});
for(const key of ['unverified_deposit_records','unverified_product_payments','unverified_refund_records'])test(`${key} produces unavailable balances, never zero or a false debt claim`,async()=>{const result=await fixture([sale(10)],[],{[key]:1})();assert.equal(result.available,false);assert.equal(result.completed_unpaid_cents,null);assert.equal(result.completed_count,null);assert.deepEqual(result.completed,[]);assert.deepEqual(result.pending,[]);const p=typescriptLoader(process.cwd())('src/lib/gcAssistantPresentation.ts').presentAssistantResult('get_outstanding_balances',result,'en');assert.match(p.message,/verification is incomplete/);assert.doesNotMatch(p.message,/\$0|Client 10/);});
test('179 preserves every earlier tool and changes only the registered read vocabulary',()=>{const previous=readFileSync('supabase/migrations/20260919052000_assistant_manual_service_receipts.sql','utf8'),next=readFileSync('supabase/migrations/20260919063800_assistant_outstanding_balances.sql','utf8');const list=sql=>[...sql.match(/check\(tool in \(([^;]+)\)\);/)[1].matchAll(/'([^']+)'/g)].map(m=>m[1]);assert.deepEqual(new Set(list(next)),new Set([...list(previous),'get_outstanding_balances']));const assistant=load('src/lib/gcAssistantCore.ts');assert.deepEqual(new Set(list(next)),new Set(Object.keys(assistant.ASSISTANT_TOOLS)));assert.equal(assistant.ASSISTANT_TOOLS.get_outstanding_balances.risk,1);assert.doesNotMatch(next,/grant|create table|delete from|insert into/i);});
test('all four balance locales have identical keys and placeholders',()=>{const {ASSISTANT_BALANCES_COPY:copy}=load('src/i18n/assistant-balances-copy.ts');assert.deepEqual(Object.keys(copy),['en','fr','es','zh-CN']);for(const [locale,rows]of Object.entries(copy)){assert.deepEqual(Object.keys(rows),Object.keys(copy.en));for(const [key,value]of Object.entries(rows)){assert.ok(value.trim());assert.deepEqual(value.match(/\{[^}]+\}/g)||[],copy.en[key].match(/\{[^}]+\}/g)||[],`${locale}:${key}`);}}});
