import test from 'node:test';import assert from 'node:assert/strict';import {typescriptLoader} from './helpers/load-typescript.mjs';
const core=typescriptLoader(process.cwd())('src/lib/businessReviews.ts');
const rows=[{id:'a',rating_overall:5,created_at:'2030-01-01T03:00:00Z',moderation_status:'Published'},{id:'b',rating_overall:3,created_at:'2030-01-01T14:00:00Z',moderation_status:'Published',salon_reply:'Thank you',booking_id:'booking-b'}, {id:'c',rating_overall:1,moderation_status:'Hidden'}, {id:'d',rating_overall:1,moderation_status:'Under review'}, {id:'e',rating_overall:1,moderation_status:'Published',dispute_status:'Removed'},{id:'f',rating_overall:1,moderation_status:'Published',archived_at:'2030-01-01'}];
test('review metrics match public moderation eligibility rather than counting hidden history',()=>{const m=core.reviewMetrics(rows,'America/New_York');assert.equal(m.total,2);assert.equal(m.average,4);assert.equal(m.highRating,1);assert.equal(m.counts.removed,3);assert.equal(m.counts.disputed,1);assert.equal(m.distribution.reduce((n,r)=>n+r.count,0),2);});
test('review trend uses business local month and does not manufacture empty months',()=>{const m=core.reviewMetrics(rows,'America/New_York');assert.deepEqual(Array.from(m.trend,r=>[r.month,r.count,r.average]),[['2029-12',1,5],['2030-01',1,3]]);assert.equal(core.reviewMetrics([],'UTC').average,null);});
test('review search, state, rating and service combine without changing originals',()=>{const source=JSON.stringify(rows);const result=core.filterReviews(rows,{view:'replied',query:'',rating:'3',service:'style-b'},[{id:'booking-b',style_id:'style-b'}]);assert.deepEqual(Array.from(result,r=>r.id),['b']);assert.equal(core.filterReviews(rows,{view:'all',query:'not present',rating:'',service:''},[]).length,0);assert.equal(JSON.stringify(rows),source);});

function routeFixture({foreign=false,moderation='allow',rpcError=null}={}){
 const calls=[];let providerCalls=0;const id='aa000000-0000-4000-8000-000000000001';
 const admin={from(table){const filters={};const q={select(){return q;},eq(k,v){filters[k]=v;return q;},async maybeSingle(){calls.push({table,filters});return {data:foreign?null:{id},error:null};}};return q;},async rpc(name,args){calls.push({name,args});return {data:{review:{id,salon_reply:moderation==='review'?null:args.p_reply,reply_revision:1},content_status:moderation==='review'?'pending':'published'},error:rpcError};}};
 const load=typescriptLoader(process.cwd(),{'@/lib/operationalMonitoring':{routeMonitoringProfile:()=>({}),withOperationalMonitoring:(_,fn)=>fn},'@/lib/platformErrors':{monitoredRouteFailure:async()=>Response.json({error:'The review reply could not be saved.',reference:'44444444-4444-4444-8444-444444444444'},{status:500})},'@/lib/requestSecurity':{enforceRateLimit(){},cleanText:(v,max)=>String(v||'').trim().slice(0,max)},'@/lib/contentModerationServer':{moderatePublicContent:async()=>{providerCalls++;return {outcome:moderation};}},'@/lib/supabaseAdmin':{requireSalonPermission:async()=>({admin,salon:{id:'OWN'},user:{id:'ACTOR'}})}});
 return{calls,providers:()=>providerCalls,run:body=>load('src/app/api/salon/reviews/[id]/reply/route.ts').POST(new Request('https://fixture.test/reply',{method:'POST',body:JSON.stringify(body)}),{params:Promise.resolve({id})})};
}
const input={reply:'Thank you for visiting.',request_id:'aa000000-0000-4000-8000-000000000002',expected_revision:0};
test('foreign review ID is denied before moderation, tools or a write',async()=>{const f=routeFixture({foreign:true});assert.equal((await f.run(input)).status,404);assert.equal(f.providers(),0);assert.equal(f.calls.some(c=>c.name),false);assert.equal(f.calls[0].filters.salon_id,'OWN');});
test('reply uses server actor/business and refuses caller scope injection',async()=>{const f=routeFixture();assert.equal((await f.run({...input,salon_id:'FOREIGN'})).status,400);assert.equal(f.providers(),0);const r=await f.run(input);assert.equal(r.status,200);const call=f.calls.find(c=>c.name);assert.equal(call.args.p_actor,'ACTOR');assert.equal(call.args.p_salon,'OWN');assert.equal(call.args.p_revision,0);assert.equal(call.args.p_request,input.request_id);});
test('pending reply response returns actual public text and explicit held status',async()=>{const f=routeFixture({moderation:'review'});const response=await f.run(input);const body=await response.json();assert.equal(body.content_status,'pending');assert.equal(body.review.salon_reply,null);assert.equal(response.headers.get('cache-control'),'private, no-store');});
test('stale reply fails explicitly without discarding the caller draft',async()=>{const f=routeFixture({rpcError:{message:'REVIEW_REPLY_STALE'}});const response=await f.run(input);assert.equal(response.status,409);assert.equal((await response.json()).code,'REVIEW_REPLY_STALE');assert.equal(input.reply,'Thank you for visiting.');});
