import test from 'node:test';
import assert from 'node:assert/strict';
import { typescriptLoader } from './helpers/load-typescript.mjs';
const business='a3000000-0000-4000-8000-000000000001', actor='a3000000-0000-4000-8000-000000000002', historyId='a3000000-0000-4000-8000-000000000003';
const args={start:'2026-09-01T04:00:00Z',end:'2026-10-01T04:00:00Z'};
function source(n=15,c=40){return {scope:{kind:'business',stylist_id:null},sales:[],bookings:[],receipts:[],arrangements:[],compensation_payments:[],stylists:Array.from({length:n},(_,i)=>({id:`professional-${i}`,salon_id:business,name:i===n-1?'Actual highest earner':`Own professional ${i}`})),obligations:Array.from({length:n},(_,i)=>({id:`wage-${i}`,salon_id:business,stylist_id:`professional-${i}`,due_at:'2026-09-15T14:00:00Z',kind:'wage',amount_cents:i===n-1?99000:100+i,arrangement_version:'saved'})),expenses:Array.from({length:c},(_,i)=>({id:`expense-${i}`,salon_id:business,occurred_at:'2026-09-15T14:00:00Z',category:i===c-1?'Actual largest category':`Own category ${i}`,amount_cents:i===c-1?88000:100+i,treatment:'operating'}))};}
function fixture(options={}){
 const data=options.data||source(),calls=[],requests=[],history=[];
 const admin={async rpc(name,values){calls.push({name,values});if(name==='reserve_gc_assistant_usage')return {data:'usage'};assert.equal(values.p_salon,business);if(name==='p0_business_plan_active')return {data:true};if(name==='p0_actor_has_permission')return {data:!(options.own&&values.p_permission==='earnings')&&!options.denied?.includes(values.p_permission)};if(name==='business_finance_scope')return {data:options.denied?.includes('earnings')?null:data.scope};if(name==='read_business_finance'){assert.equal(values.p_user,actor);if(options.denied?.includes('earnings'))return {error:Error('FINANCE_ACCESS_DENIED')};return {data:options.readData?options.readData(data):data};}throw Error(`Unexpected RPC ${name}`);},from(table){const filters=[];const q={select(){return q;},eq(key,value){filters.push([key,value]);return q;},in(){return q;},order(){return q;},limit(){return q;},update(){return q;},maybeSingle(){return q;},then(resolve,reject){return Promise.resolve().then(()=>{if(table==='ai_automation_features')return {data:{is_enabled:true,provider_key:'openai',model_key:'fixture-model',timeout_ms:20000}};if(table==='ai_usage_events')return {data:null};if(table==='master_styles')return {data:[]};if(table==='gc_assistant_requests')return {data:history.filter(row=>filters.every(([key,value])=>row[key]===value))};throw Error(`Unexpected table ${table}`);}).then(resolve,reject);}};return q;}};
 const load=typescriptLoader(process.cwd(),{'@/lib/supabaseAdmin':{},'@/lib/bookingAvailabilityServer':{},'@/lib/contentModerationServer':{},'@/lib/assistantServiceContribution':{readAssistantServiceContribution:async()=>null},'@/lib/aiAutomationServer':{approvedAiModels:()=>['fixture-model'],approvedAiProviders:()=>['openai'],aiProviderConfigured:()=>true,redactSensitiveText:value=>value}},{URLSearchParams,process:{env:{OPENAI_API_KEY:'fixture-only',AI_OWNER_INPUT_USD_PER_MILLION:'1',AI_OWNER_OUTPUT_USD_PER_MILLION:'4'}},fetch:async(_url,init)=>{requests.push(JSON.parse(init.body));return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(options.answerOnly?{reply:'Current recorded financial amounts.'}:{decision:{clarification:'Which reporting period?'},language_switch:null})}}]});}});
 const context={admin,user:{id:actor},salon:{id:business,time_zone:'America/New_York'},isOwner:!options.own,teamMember:options.own?{stylist_id:data.scope.stylist_id}:null};
 return {load,data,calls,requests,context,read:()=>load('src/lib/gcAssistantServer.ts').readAssistantData(context,'get_earnings_summary',args),async plan(){const result=await this.read();history.push({id:historyId,salon_id:business,requested_by:actor,tool:'get_earnings_summary',permission:'earnings',arguments:args,result});await load('src/lib/gcAssistantPlanningServer.ts').planOwnerRequest({context,admin,salonId:business,userId:actor,locale:'en',text:'Who earned the most and what was the largest expense category?',timeZone:'America/New_York',previousRequestIds:[historyId],answerOnly:options.answerOnly});const payload=JSON.parse(requests.at(-1).messages[1].content);return payload.previous[0]?.result;}};
}
test('actual earnings read and planner retain highest earner beyond twelve professionals',async()=>{const f=fixture();const direct=await f.read();assert.match(JSON.stringify(direct),/Actual highest earner/);const result=await f.plan();assert.match(JSON.stringify(result),/Actual highest earner/);});
test('actual earnings read and answer retain largest expense beyond thirty-two categories',async()=>{const f=fixture({answerOnly:true});const direct=await f.read();assert.equal(direct.expense_categories['Actual largest category'],88000);const result=await f.plan();assert.match(JSON.stringify(result),/Actual largest category/);});


test('both model phases preserve exact complete totals, period, currency and bounded numeric rankings',async()=>{
 for(const answerOnly of [false,true]){const f=fixture({answerOnly}), result=await f.plan(), rank=result.rankings;
  assert.equal(rank.professionals.rows[0].name,'Actual highest earner');assert.equal(rank.professionals.total,15);assert.equal(rank.professionals.total_amount_cents,100491);assert.equal(rank.professionals.highest_amount_cents,99000);assert.equal(rank.professionals.shown_count,12);assert.equal(rank.professionals.is_excerpt,true);
  assert.equal(rank.expenses.rows[0].category,'Actual largest category');assert.equal(rank.expenses.total,40);assert.equal(rank.expenses.total_amount_cents,92641);assert.equal(rank.expenses.highest_amount_cents,88000);assert.equal(rank.expenses.shown_count,12);assert.equal(rank.expenses.is_excerpt,true);
  assert.equal(rank.currency,'USD');assert.equal(rank.period.from,'2026-09-01');assert.equal(rank.period.to,'2026-09-30');assert.equal(rank.period.timeZone,'America/New_York');assert.equal(result.totals.operating_expenses_cents,92641);assert.equal(result.totals.recorded_profit_cents,-193132);assert.equal(result.totals.expenses_completeness_verified,false);assert.match(result.definitions,/not an exact margin/);
 }
});
test('ties use stable identity order and preserve all leader counts beyond the twelve-row model cap',async()=>{
 const data=source(18,35);for(const row of data.obligations)row.amount_cents=300;for(const row of data.expenses)row.amount_cents=400;
 const forward=await fixture({data}).plan();const reverse=structuredClone(data);reverse.obligations.reverse();reverse.expenses.reverse();reverse.stylists.reverse();const backward=await fixture({data:reverse,answerOnly:true}).plan();
 for(const key of ['professionals','expenses']){assert.deepEqual(forward.rankings[key],backward.rankings[key]);assert.equal(forward.rankings[key].leaders_are_excerpt,true);assert.equal(forward.rankings[key].leaders_shown_count,12);assert.equal(forward.rankings[key].leaders.length,12);}
 assert.equal(forward.rankings.professionals.tied_leader_count,18);assert.equal(forward.rankings.expenses.tied_leader_count,35);
});
test('empty records report no leader while recorded zero amounts retain honest zero ties',async()=>{
 const empty=await fixture({data:source(0,0)}).plan();for(const row of Object.values(empty.rankings).filter(row=>row&&typeof row==='object'&&'highest_amount_cents'in row)){assert.equal(row.total,0);assert.equal(row.highest_amount_cents,null);assert.equal(row.tied_leader_count,0);assert.equal(row.is_excerpt,false);}
 const data=source(2,2);for(const row of data.obligations)row.amount_cents=0;for(const row of data.expenses)row.amount_cents=0;const zero=await fixture({data}).plan();assert.equal(zero.rankings.professionals.highest_amount_cents,0);assert.equal(zero.rankings.professionals.tied_leader_count,2);assert.equal(zero.rankings.expenses.highest_amount_cents,0);
});
test('earned compensation ranking differs from gross service sales and recorded compensation payments',async()=>{
 const data=source(2,0);data.obligations[0].amount_cents=0;data.obligations[1].amount_cents=5000;
 data.sales=[{id:'own-sale',salon_id:business,source:'walk_in',kind:'service',occurred_at:'2026-09-15T14:00:00Z',recorded_at:'2026-09-15T14:00:00Z',status:'completed',name:'Own service',stylist_id:'professional-0',client_id:null,client_name:null,list_cents:50000,discount_cents:0,agreed_cents:50000,cost_cents:0,quantity:1,compensation:{kind:'commission',version:'recorded',basis:'after_discount',percent:5}}];
 data.compensation_payments=[{id:'own-payout',salon_id:business,stylist_id:'professional-0',occurred_at:'2026-09-15T14:00:00Z',obligation_id:null,kind:'commission',amount_cents:90000,method:'cash'}];
 const result=await fixture({data}).plan(),rows=result.rankings.professionals.rows;assert.equal(rows[0].id,'professional-1');assert.equal(rows[0].amount_cents,5000);assert.equal(rows[1].service_sales_cents,50000);assert.equal(rows[1].amount_cents,2500);assert.equal(rows[1].paid_cents,90000);assert.equal(result.totals.visits,1);assert.equal(result.totals.cash_received_cents,0);
});
test('unassigned compensation and inventory purchases never become ranked professional earnings or operating expenses',async()=>{
 const data=source(1,1);data.obligations.push({id:'unassigned-wage',salon_id:business,stylist_id:null,due_at:'2026-09-15T14:00:00Z',kind:'wage',amount_cents:999999,arrangement_version:'saved'});data.expenses.push({id:'inventory',salon_id:business,occurred_at:'2026-09-15T14:00:00Z',category:'Inventory asset only',amount_cents:999999,treatment:'inventory_asset'});
 const result=await fixture({data}).plan();assert.equal(result.rankings.professionals.total,1);assert.equal(result.rankings.professionals.unassigned_earned_compensation_cents,999999);assert.equal(result.rankings.professionals.unassigned_excluded,true);assert.equal(result.rankings.expenses.total,1);assert.equal(result.totals.inventory_purchases_cents,999999);assert.doesNotMatch(JSON.stringify(result.rankings.expenses),/Inventory asset only/);
});
test('own-stylist scope never reveals or represents a business-wide ranking and rejects mixed scoped rows',async()=>{
 const data=source(1,0);data.scope={kind:'own',stylist_id:'professional-0'};for(const answerOnly of [false,true]){const result=await fixture({data,own:true,answerOnly}).plan();assert.equal(result.scope,'own_stylist_only');assert.equal(result.rankings.scope,'own_stylist_only');assert.equal(result.rankings.professionals.total,1);assert.equal(result.rankings.expenses,null);}
 const mixed=structuredClone(data);mixed.stylists.push({id:'foreign-professional',salon_id:business,name:'PRIVATE OTHER STAFF'});await assert.rejects(fixture({data:mixed,own:true}).read(),/FINANCE_ACCESS_DENIED/);
 const foreign=source();foreign.expenses[0].salon_id='b3000000-0000-4000-8000-000000000001';await assert.rejects(fixture({data:foreign}).read(),/FINANCE_ACCESS_DENIED/);
 const denied=fixture({denied:['earnings']});await assert.rejects(denied.plan(),/FINANCE_ACCESS_DENIED/);assert.equal(denied.requests.length,0);
});
test('current authorized finance reread replaces old winners before either model phase',async()=>{
 for(const answerOnly of [false,true]){let reads=0;const f=fixture({answerOnly,readData(data){const current=structuredClone(data);if(++reads>1){current.obligations.at(-1).amount_cents=1;current.stylists.at(-1).name='Changed professional';current.expenses.at(-1).amount_cents=1;current.expenses.at(-1).category='Changed expense';}return current;}});const result=await f.plan();assert.equal(result.rankings.professionals.rows[0].id,'professional-13');assert.equal(result.rankings.expenses.rows[0].category,'Own category 38');assert.doesNotMatch(JSON.stringify(result),/Actual highest earner|Actual largest category/);}
});
test('invalid/nonfinite canonical evidence and aggregate overflow fail closed before model transport',async()=>{
 for(const amount of [NaN,Infinity,-1,0.5,Number.MAX_SAFE_INTEGER+1]){const data=source(1,1);data.expenses[0].amount_cents=amount;const f=fixture({data});await assert.rejects(f.plan(),/FINANCE_INVALID_AMOUNT/);assert.equal(f.requests.length,0);}
 const data=source(2,0);for(const row of data.obligations)row.amount_cents=Number.MAX_SAFE_INTEGER;const f=fixture({data});await assert.rejects(f.plan(),/FINANCE_INVALID_AMOUNT/);assert.equal(f.requests.length,0);
});
test('ranking UI copy is registered in all required translations without placeholder loss',()=>{
 const catalog=fixture().load('src/i18n/business-finance-source-catalog.ts').BUSINESS_FINANCE_SOURCE_MESSAGES;
 const labels=['Highest recorded earned compensation','Commission earned plus wages due in the selected period. Service sales and compensation already paid are separate.','No assigned professional earnings in this period.','Professionals tied at this amount','Unnamed professional','Showing tied leaders','Unassigned earned compensation is excluded from this ranking'];
 for(const locale of ['fr','es','zh-CN'])for(const label of labels)assert.ok(catalog[locale][label]?.trim(),`${locale}: ${label}`);
});
test('period-local boundaries exclude the next local day and recorded reversals can produce negative earned compensation',async()=>{
 const data=source(1,1);data.obligations[0].amount_cents=0;data.obligations.push({...data.obligations[0],id:'before-month',due_at:'2026-09-01T03:59:59Z',amount_cents:77777},{...data.obligations[0],id:'last-included',due_at:'2026-10-01T03:59:59Z',amount_cents:100},{...data.obligations[0],id:'next-month',due_at:'2026-10-01T04:00:00Z',amount_cents:88888});
 data.sales=[{id:'prior-service',salon_id:business,source:'walk_in',kind:'service',occurred_at:'2026-08-15T14:00:00Z',recorded_at:'2026-08-15T14:00:00Z',status:'completed',name:'Prior completed service',stylist_id:'professional-0',client_id:null,client_name:null,list_cents:10000,discount_cents:0,agreed_cents:10000,cost_cents:0,quantity:1,compensation:{kind:'commission',version:'saved',basis:'after_discount',percent:50}}];
 data.receipts=[{id:'prior-receipt',salon_id:business,sale_id:'prior-service',occurred_at:'2026-08-15T14:00:00Z',stage:'full',method:'cash',amount_cents:10000,original_payment_id:null},{id:'current-reversal',salon_id:business,sale_id:'prior-service',occurred_at:'2026-09-15T14:00:00Z',stage:'refund',method:'cash',amount_cents:10000,original_payment_id:'prior-receipt'}];
 const result=await fixture({data,answerOnly:true}).plan();assert.equal(result.rankings.professionals.highest_amount_cents,-4900);assert.equal(result.rankings.professionals.rows[0].commission_earned_cents,-5000);assert.equal(result.rankings.professionals.rows[0].wage_due_cents,100);assert.equal(result.totals.cash_received_cents,-10000);assert.equal(result.totals.visits,0);
});
test('revocation after the original earnings read prevents old winner and transcript reaching either model phase',async()=>{
 for(const answerOnly of [false,true]){const options={answerOnly,denied:[],readData(data){options.denied.push('earnings');return data;}};const f=fixture(options);
  if(answerOnly)await assert.rejects(f.plan(),/ASSISTANT_INVALID_PLAN/);else await f.plan();assert.doesNotMatch(JSON.stringify(f.requests),/Actual highest earner|Actual largest category|99000|88000/);
 }
});
