import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {typescriptLoader} from './helpers/load-typescript.mjs';
const salon='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', owner='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', imported='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const origin='https://0123456789abcdef01234567--girlzculture.netlify.app';
const env={INSTAGRAM_ONBOARDING_ACTIVATION:'acceptance',INSTAGRAM_ONBOARDING_APPROVED:'true',INSTAGRAM_ONBOARDING_CLIENT_ID:'123456789',INSTAGRAM_ONBOARDING_CLIENT_SECRET:'synthetic',INSTAGRAM_ONBOARDING_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64'),INSTAGRAM_ONBOARDING_REDIRECT_URI:origin+'/api/salon/onboarding-instagram/callback',INSTAGRAM_ONBOARDING_ACCEPTANCE_OWNER_ID:owner};
const request=(body)=>new Request(origin+'/api/salon/onboarding-instagram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function fixture(options={}){
 const calls=[],reads=[],events=[],provider=[];let ownerReads=0;
 const admin={rpc:async(name,args)=>{calls.push([name,args]);if(name==='instagram_onboarding_account_available')return {data:options.accountAvailable!==false};if(name==='instagram_onboarding_owner')return {data:++ownerReads!==options.revokeAt};if(name==='consume_business_instagram_flow')return {data:options.flow??null};if(name==='manage_business_instagram')return options.mutationError?{error:{message:options.mutationError}}:{data:{disconnected:true}};if(name==='delete_business_instagram_data')return {data:{complete:true,assets:[]}};throw Error('unexpected RPC '+name);},from(table){reads.push(table);const query={select(){return this;},eq(){return this;},in(){return this;},gt(){return this;},order(){return this;},limit(){return this;},maybeSingle:async()=>({data:options.tables?.[table]??null}),single:async()=>({data:options.tables?.[table]??null})};return query;},storage:{from(){throw Error('unexpected storage');}}};
 const context={admin,salon:{id:salon},user:{id:owner},isOwner:options.isOwner!==false};
 const load=typescriptLoader(process.cwd(),{'@/lib/supabaseAdmin':{requireSalonOwner:async()=>context,getSupabaseAdmin:()=>admin},'@/lib/platformErrors':{capturePlatformError:async x=>{events.push(x);return 'safe-reference';}},'@/lib/requestSecurity':{enforceRateLimit(){},RateLimitError:class extends Error{}},'@/lib/instagramOnboardingMediaServer':{stageInstagramOnboardingPhoto:async()=>{throw Error('unexpected stage');}},'@/lib/businessOnboardingDraft':{emptyOnboardingFacts:()=>({identity:{},photos:[]}),onboardingUncertainty:()=>[]}}, {process:{env:options.disabled?{}:env},URLSearchParams,FormData,fetch:async(url,init)=>{provider.push([url,init]);if(String(url).includes('oauth/access_token'))return Response.json({data:[{access_token:'PRIVATE_TEST_TOKEN',user_id:'1234567',permissions:'instagram_business_basic'}]});return Response.json({id:'1234567',user_id:'1789123',username:'owned',name:'Own name',account_type:'BUSINESS'});}});
 return {server:load('src/lib/instagramOnboardingServer.ts'),core:load('src/lib/instagramOnboardingCore.ts'),calls,reads,events,provider};
}
test('staff cannot read provider connections, request OAuth or create drafts',async()=>{const f=fixture({isOwner:false});const response=await f.server.instagramOnboardingRequest(request({action:'authorize',permitted:true}));assert.equal(response.status,403);assert.equal(f.calls.length,0);assert.equal(f.reads.length,0);assert.equal(f.provider.length,0);});
test('unconfigured owner gets honest unavailable and no connection/provider reads',async()=>{const f=fixture({disabled:true});const response=await f.server.instagramOnboardingRequest(new Request(origin+'/api/salon/onboarding-instagram'));assert.equal((await response.json()).status,'unavailable');assert.equal(f.reads.length,0);assert.equal(f.provider.length,0);});
test('explicit permitted source consent precedes OAuth flow persistence',async()=>{const f=fixture();assert.equal((await f.server.instagramOnboardingRequest(request({action:'authorize'}))).status,400);assert.equal(f.calls.filter(c=>c[0]==='manage_business_instagram').length,0);const response=await f.server.instagramOnboardingRequest(request({action:'authorize',permitted:true}));assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);const write=f.calls.find(c=>c[1].p_action==='flow');assert.equal(write[1].p_salon,salon);assert.equal(write[1].p_owner,owner);assert.equal(Object.hasOwn(write[1].p_args,'state'),false);});
test('cross-business connection row fails closed before leaving server',async()=>{const f=fixture({tables:{business_instagram_connections:{salon_id:imported,owner_id:owner,username:'PRIVATE_OTHER_BUSINESS'}}});const response=await f.server.instagramOnboardingRequest(new Request(origin+'/api/salon/onboarding-instagram'));assert.equal(response.status,403);assert.doesNotMatch(await response.text(),/PRIVATE_OTHER/);});
test('fresh permission revoked during status read discards prior result',async()=>{const f=fixture({revokeAt:2});const response=await f.server.instagramOnboardingRequest(new Request(origin+'/api/salon/onboarding-instagram'));assert.equal(response.status,403);});
test('consumed expired or replayed OAuth flow makes zero provider requests',async()=>{const f=fixture(),a=f.core.instagramAuthorization(f.core.instagramConfig(env));const response=await f.server.instagramOnboardingCallback(new Request(origin+'/api/salon/onboarding-instagram/callback?state='+a.state+'&code=secret-code',{headers:{cookie:'__Host-gc-instagram-flow='+a.state}}));assert.equal(response.status,400);assert.equal(f.provider.length,0);assert.doesNotMatch(JSON.stringify(f.events),/secret-code|PRIVATE_TEST_TOKEN/);});
test('owner transfer/generation race rejects callback save with no token disclosure',async()=>{const f=fixture({flow:{salon_id:salon,owner_id:owner,generation:1},mutationError:'INSTAGRAM_CONNECTION_CHANGED'}),a=f.core.instagramAuthorization(f.core.instagramConfig(env));const response=await f.server.instagramOnboardingCallback(new Request(origin+'/api/salon/onboarding-instagram/callback?state='+a.state+'&code=secret-code',{headers:{cookie:'__Host-gc-instagram-flow='+a.state}}));assert.equal(response.status,409);const write=f.calls.find(c=>c[1].p_action==='authorize');assert.equal(write[1].p_args.app_user_id,'1234567');assert.equal(write[1].p_args.provider_user_id,'1789123');assert.match(write[1].p_args.secret,/^v1\./);assert.doesNotMatch(await response.text(),/PRIVATE_TEST_TOKEN|secret-code/);assert.doesNotMatch(JSON.stringify(f.events.map(e=>({message:e.error.message,safeMessage:e.safeMessage}))),/PRIVATE_TEST_TOKEN/);});
test('callback mismatched browser state cannot consume a saved flow',async()=>{const f=fixture();const response=await f.server.instagramOnboardingCallback(new Request(origin+'/api/salon/onboarding-instagram/callback?state=wrong&code=secret'));assert.equal(response.status,400);assert.equal(f.calls.length,0);assert.equal(f.provider.length,0);});
test('known other-business account is rejected before any profile or media read',async()=>{const f=fixture({flow:{salon_id:salon,owner_id:owner,generation:1},accountAvailable:false}),a=f.core.instagramAuthorization(f.core.instagramConfig(env));const response=await f.server.instagramOnboardingCallback(new Request(origin+'/api/salon/onboarding-instagram/callback?state='+a.state+'&code=one-time-code',{headers:{cookie:'__Host-gc-instagram-flow='+a.state}}));assert.equal(response.status,403);assert.equal(f.provider.length,1);assert.equal(f.provider[0][0],'https://api.instagram.com/oauth/access_token');assert.equal(f.calls.some(c=>c[1]?.p_action==='authorize'),false);});
test('forged imported facts/client source URL are rejected instead of fetched',async()=>{const f=fixture();const response=await f.server.instagramOnboardingRequest(request({action:'create_draft',permitted:true,import_id:imported,request_id:salon,locale:'en',media_ids:[],source:{url:'http://localhost/private'}}));assert.equal(response.status,400);assert.equal(f.provider.length,0);assert.equal(f.reads.length,0);});
test('invalid signed deletion never inspects application data',async()=>{const f=fixture();const response=await f.server.instagramOnboardingDeletion(new Request(origin+'/api/salon/onboarding-instagram/data-deletion',{method:'POST',body:'signed_request=forged'}));assert.equal(response.status,400);assert.equal(f.calls.length,0);assert.equal(f.reads.length,0);});
test('signed deletion uses app-scoped account and replay-safe opaque confirmation only',async()=>{const f=fixture();const payload=Buffer.from(JSON.stringify({algorithm:'HMAC-SHA256',user_id:'1234567',issued_at:Math.floor(Date.now()/1000)})).toString('base64url');const signature=createHmac('sha256',env.INSTAGRAM_ONBOARDING_CLIENT_SECRET).update(payload).digest('base64url');const response=await f.server.instagramOnboardingDeletion(new Request(origin+'/api/salon/onboarding-instagram/data-deletion',{method:'POST',body:'signed_request='+signature+'.'+payload}));assert.equal(response.status,200);const result=await response.json();assert.match(result.confirmation_code,/^[a-f0-9]{64}$/);assert.equal(f.calls[0][1].p_user,'1234567');assert.equal(Object.hasOwn(result,'user_id'),false);assert.equal(new URL(result.url).searchParams.has('user_id'),false);assert.equal(f.provider.length,0);});
