import test from 'node:test';
import assert from 'node:assert/strict';
import {typescriptLoader} from './helpers/load-typescript.mjs';
const salon='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',importId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',asset='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const load=()=>typescriptLoader(process.cwd())('src/lib/instagramOnboardingCleanupServer.ts');
function fixture(options={}){
 const calls=[],removed=[];
 const item={id:asset,salon_id:salon,import_id:importId};
 const admin={rpc:async(name,args)=>{calls.push([name,args]);if(name==='delete_business_instagram_data')return {data:options.busy?{complete:false,busy:true,assets:[]}:{complete:args.p_complete===true,assets:[options.foreign?{...item,salon_id:'../foreign'}:item]}};if(name==='queue_business_instagram_expiry')return {data:options.expired?[{id:importId,private_only:options.privateOnly===true,assets:[{...item,preserve_public:options.privateOnly===true&&!options.unusedPrepared}]}]:[]};if(name==='finish_business_instagram_expiry')return {data:null};throw Error('unexpected RPC');},storage:{from:bucket=>({remove:async(paths)=>{removed.push([bucket,paths]);return {error:options.failStorage?{message:'private provider diagnostic'}:null};}})},from(){return {select(){return this;},eq(){return this;},order(){return this;},limit:async()=>({data:options.expired?[]:[{code:'d'.repeat(64),provider_user_id:'100001'}]})};}};
 return {admin,calls,removed};
}
test('in-flight upload keeps signed deletion pending and performs no removal/completion',async()=>{const f=fixture({busy:true});assert.equal(await load().purgeInstagramOnboardingData(f.admin,'100001','d'.repeat(64)),false);assert.equal(f.removed.length,0);assert.equal(f.calls.length,1);});
test('storage failure never marks deletion complete; later replay removes exact reserved paths',async()=>{const f=fixture({failStorage:true});await assert.rejects(load().purgeInstagramOnboardingData(f.admin,'100001','d'.repeat(64)),e=>e.code==='INSTAGRAM_DELETION_PENDING'&&!e.message.includes('private provider'));assert.equal(f.calls.some(c=>c[1]?.p_complete),false);const retry=fixture();assert.equal(await load().purgeInstagramOnboardingData(retry.admin,'100001','d'.repeat(64)),true);assert.deepEqual(retry.removed.map(([bucket])=>bucket),['media-originals','salon-photos']);assert.ok(retry.removed.every(([,paths])=>paths.every(p=>p.startsWith(salon+'/instagram-onboarding/'+importId+'/'+asset))));});
test('malformed/foreign path fields cannot cause arbitrary storage deletion',async()=>{const f=fixture({foreign:true});await assert.rejects(load().purgeInstagramOnboardingData(f.admin,'100001','d'.repeat(64)));assert.equal(f.removed.length,0);});
test('daily existing cleanup retries pending deletions and returns only aggregate counts',async()=>{const f=fixture();const result=await load().processInstagramOnboardingCleanup(f.admin);assert.equal(result.completed,1);assert.equal(result.failed,0);assert.doesNotMatch(JSON.stringify(result),/100001|aaaaaaaa|bbbbbbbb|cccccccc/);});
test('expired applied import removes private original only, preserving approved public gallery object',async()=>{const f=fixture({expired:true,privateOnly:true});const result=await load().processInstagramOnboardingCleanup(f.admin);assert.equal(result.completed,1);assert.deepEqual(f.removed.map(([bucket])=>bucket),['media-originals']);assert.equal(f.calls.at(-1)[0],'finish_business_instagram_expiry');assert.equal(f.calls.at(-1)[1].p_private_only,true);});
test('expired unapplied source removes private and prepared objects without deleting any business',async()=>{const f=fixture({expired:true});await load().processInstagramOnboardingCleanup(f.admin);assert.deepEqual(f.removed.map(([bucket])=>bucket),['media-originals','salon-photos']);assert.equal(f.calls.at(-1)[1].p_private_only,false);});
test('applied import still removes an unselected earlier prepared public image',async()=>{const f=fixture({expired:true,privateOnly:true,unusedPrepared:true});const result=await load().processInstagramOnboardingCleanup(f.admin);assert.equal(result.completed,1);assert.deepEqual(f.removed.map(([bucket])=>bucket),['media-originals','salon-photos']);assert.equal(f.calls.at(-1)[1].p_private_only,true);});
