import test from 'node:test';
import assert from 'node:assert/strict';
import {loadNodeTypescript} from './helpers/load-node-typescript.mjs';
const a='22000000-0000-4000-8000-000000000001',b='22000000-0000-4000-8000-000000000002',now=Date.parse('2026-09-18T16:30:00Z');
const reference='55000000-0000-4000-8000-000000000001';
function fixture({business=a,isOwner=true,broken='',mixed=false}={}){
 const queries=[],rpcCalls=[],events=[];
 const booking=(id,salon,at,status='Confirmed',stylist='person')=>({id,salon_id:salon,appointment_datetime:at,blocked_until:new Date(Date.parse(at)+3600000).toISOString(),duration_hours:1,status,guest_name:salon===a?'Client A':'Private B',stylist_id:stylist,manual_service_name:null,style_id:'service',payment_mode:'live'});
 const tables={bookings:[booking('one',a,'2026-09-18T17:00:00Z'),booking('two',a,'2026-09-18T17:30:00Z'),booking('cancel',a,'2026-09-18T18:00:00Z','Cancelled'),booking('no-show',a,'2026-09-18T13:00:00Z','No Show'),booking('test',a,'2026-09-18T18:00:00Z'),booking('foreign',b,'2026-09-18T17:00:00Z'),booking('tomorrow',a,'2026-09-19T13:00:00Z')],stylists:[{id:'person',salon_id:a,name:'Professional A'},{id:'other',salon_id:b,name:'Private stylist B'}],styles:[{id:'service',salon_id:a,name:'Braids'},{id:'other',salon_id:b,name:'Private service B'}],appointment_waitlist:[{id:'wait',salon_id:a,stylist_id:'person',status:'waiting',starts_after:'2026-09-18T18:00:00Z',starts_before:'2026-09-18T22:00:00Z'},{id:'foreign',salon_id:b,status:'waiting',starts_after:'2026-09-18T18:00:00Z',starts_before:'2026-09-18T22:00:00Z'}],booking_followup_queue:[]};
 tables.bookings.find(row=>row.id==='test').payment_mode='test';
 const admin={from(table){const filters=[];let limit=10000;const q={select(){return q;},eq(k,v){filters.push(['eq',k,v]);return q;},gte(k,v){filters.push(['gte',k,v]);return q;},gt(k,v){filters.push(['gt',k,v]);return q;},lt(k,v){filters.push(['lt',k,v]);return q;},lte(k,v){filters.push(['lte',k,v]);return q;},order(){return q;},limit(n){limit=n;return q;},then(resolve){queries.push({table,filters});if(broken===table)return Promise.resolve({data:null,error:new Error('PRIVATE database details')}).then(resolve);if(table==='booking_followup_queue'){assert.ok(filters.some(([op,k,v])=>op==='eq'&&k==='bookings.salon_id'&&v===business));return Promise.resolve({data:[{booking_id:'visit',schedule_revision:1,bookings:{salon_id:business,guest_name:'Followup '+business,status:'Completed',schedule_revision:1,payment_mode:'live'}}],error:null}).then(resolve);}const rows=tables[table].filter(row=>filters.every(([op,k,v])=>op==='eq'?row[k]===v:op==='gte'?row[k]>=v:op==='gt'?row[k]>v:op==='lt'?row[k]<v:row[k]<=v));return Promise.resolve({data:mixed&&table==='styles'?tables.styles:rows.slice(0,limit),error:null}).then(resolve);}};return q;},async rpc(name,args){rpcCalls.push({name,args});assert.equal(args.p_salon,business);if(broken==='stock')return{error:Error('PRIVATE stock')};return {data:{products:[{name:'Scalp oil',track_inventory:true,inventory_quantity:1,low_stock_threshold:2}],supplies:[]}};}};
 const books={sales:tables.bookings.filter(row=>row.payment_mode!=='test').map(row=>({id:'booking:'+row.id,salon_id:row.salon_id,agreed_cents:10000,list_cents:10000,discount_cents:0,cost_cents:null,compensation:{kind:'none',version:null}})).filter(row=>row.salon_id===business),payments:[{id:'deposit',sale_id:'booking:one',salon_id:a,occurred_at:'2026-09-17T10:00:00Z',stage:'deposit',amount_cents:1000},{id:'balance',sale_id:'booking:one',salon_id:a,occurred_at:'2026-09-18T10:00:00Z',stage:'balance',amount_cents:4000},{id:'refund',sale_id:'booking:one',salon_id:a,occurred_at:'2026-09-18T11:00:00Z',stage:'refund',amount_cents:500,original_payment_id:'deposit'}].filter(row=>row.salon_id===business),expenses:[],obligations:[],compensation_payments:[]};
 const context={admin,salon:{id:business,time_zone:'America/New_York'},user:{id:'owner-'+business},isOwner};
 const load=loadNodeTypescript(process.cwd(),{'@/lib/supabaseAdmin':{requireSalonOwner:async()=>context},'@/lib/requestSecurity':{enforceRateLimit(){},RateLimitError:class extends Error{}},'@/lib/platformErrors':{capturePlatformError:async event=>{events.push(event);return reference;}},'@/lib/operationalMonitoring':{routeMonitoringProfile:()=>({}),withOperationalMonitoring:(_p,h)=>h},'@/lib/businessFinanceServer':{readBusinessFinances:async()=>({books})},'@/lib/bookingAvailabilityServer':{calendarAvailability:async({salonId,date})=>{assert.equal(salonId,business);assert.equal(date,'2026-09-18');return{gaps:[{start:'2026-09-18T18:00:00Z',end:'2026-09-18T20:00:00Z',stylist_id:'person',professional_name:'Professional A'}]};}}});
 return {load,context,queries,rpcCalls,events,books,read:()=>load('src/lib/businessMorningBriefServer.ts').readMorningBrief(new Request('https://girlzculture.com/api/salon/morning-brief'),context,now)};
}
test('Morning brief preserves appointment facts, detects overlap and separates deposits from revenue and balance',async()=>{
 const f=fixture(),brief=await f.read();assert.equal(brief.date,'2026-09-18');assert.equal(brief.appointments.status,'ok');assert.equal(brief.appointments.value.items.length,4);assert.equal(brief.appointments.value.overlaps,1);assert.equal(brief.appointments.value.cancelled,1);assert.equal(brief.appointments.value.no_shows,1);
 assert.deepEqual(brief.money.value,{expected_cents:20000,deposit_cents:1000,received_cents:4500,balance_cents:15500});
 assert.equal(brief.availability.value.waitlist_opportunities,1);assert.equal(brief.inventory.value[0].quantity,1);assert.equal(brief.followups.value.length,1);
 assert.doesNotMatch(JSON.stringify(brief),/Private B|Private stylist B|Private service B|tomorrow|"test"/);
 for(const q of f.queries)assert.ok(q.filters.some(([op,k,v])=>op==='eq'&&k.endsWith('salon_id')&&v===a));
 assert.equal(f.events.length,0);
});
test('Separate business gets only its own records; mixed related data fails closed before UI projection',async()=>{
 const own=await fixture({business:b}).read();assert.equal(own.appointments.value.items.length,1);assert.equal(own.appointments.value.items[0].client,'Private B');assert.doesNotMatch(JSON.stringify(own),/Client A|Braids/);
 const f=fixture({mixed:true}),brief=await f.read();assert.equal(brief.appointments.status,'unavailable');assert.equal(brief.money.status,'unavailable');assert.doesNotMatch(JSON.stringify(brief),/Private stylist B|Private service B/);assert.equal(brief.appointments.request_id,reference);
});
test('A broken source remains unavailable, not a zero total, and uses the exact protected incident reference',async()=>{
 const f=fixture({broken:'stock'}),brief=await f.read();assert.deepEqual(brief.inventory,{status:'unavailable',request_id:reference});assert.equal(brief.appointments.status,'ok');assert.equal(f.events.length,1);assert.equal(f.events[0].salonId,a);assert.doesNotMatch(JSON.stringify(f.events),/PRIVATE stock/);
});
test('Owner scope and explicit business override are rejected before any brief query',async()=>{
 const staff=fixture({isOwner:false});const route=staff.load('src/app/api/salon/morning-brief/route.ts');const denied=await route.GET(new Request('https://girlzculture.com/api/salon/morning-brief'));assert.equal(denied.status,403);assert.equal(staff.queries.length,0);
 const owner=fixture();const invalid=await owner.load('src/app/api/salon/morning-brief/route.ts').GET(new Request('https://girlzculture.com/api/salon/morning-brief?salon_id='+b));assert.equal(invalid.status,400);assert.equal(owner.queries.length,0);assert.equal(invalid.headers.get('cache-control'),'private, no-store');
});
test('Morning money rejects missing or cross-business finance evidence instead of inventing receipts',()=>{
 const f=fixture();const {morningMoney}=f.load('src/lib/businessMorningBrief.ts');const booking={id:'missing',salon_id:a,status:'Confirmed'};assert.throws(()=>morningMoney(a,[booking],f.books,now),/INCOMPLETE/);f.books.payments.push({id:'foreign',salon_id:b,amount_cents:100});assert.throws(()=>morningMoney(a,[],f.books,now),/ACCESS_DENIED/);
});
