import test from 'node:test';
import assert from 'node:assert/strict';
import {explicitFixture,salon} from './helpers/payment-explicit-fixture.mjs';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {createRequire} from 'node:module';
import ts from 'typescript';
test('recognized explicit phase agreement with retained intent permits existing setup-only collection',async()=>{const f=explicitFixture();assert.equal((await f.api.subscriptionPaymentMethodStatus(f.admin,salon)).updateAllowed,true);const before=structuredClone(f.state.schedule);assert.equal((await f.begin()).url,f.state.session.url);assert.deepEqual(f.state.schedule,before);assert.deepEqual(f.calls.filter(c=>c.post).map(c=>c.post),['/checkout/sessions']);});
test('explicit current and future methods change while inherited nulls and all commercial settings persist',async()=>{const f=explicitFixture();const before=structuredClone(f.state.schedule);await f.begin();f.state.session.status='complete';const result=await f.complete();assert.equal(result.updated,true);assert.equal(result.paymentMethod.last4,'4444');before.default_settings.default_payment_method='pm_new';before.phases[1].default_payment_method='pm_new';before.phases[3].default_payment_method='pm_new';assert.deepEqual(f.state.schedule,before);assert.equal(f.state.attempt.status,'completed');assert.ok(f.state.attempt.phase_apply_plan);assert.equal(f.calls.filter(c=>c.post?.startsWith('/subscription_schedules/')).length,1);assert.ok(f.calls.filter(c=>c.post).every(c=>!/(invoices|payment_intents|prices)/.test(c.post)));});

for(const [name,change] of [
 ['missing original intent',s=>s.intent=null],['foreign archived customer',s=>s.intent.stripe_customer_id='cus_foreign'],['foreign archived business',s=>s.intent.salon_id='33333333-3333-4333-8333-333333333333'],['wrong archived mode',s=>s.intent.livemode=true],['unversioned intent',s=>s.intent.api_version='unrecorded'],['commercially stale intent',s=>s.schedule.phases[2].items[0].quantity=2],['ambiguous discount intent',s=>delete s.intent.empty_discounts['phases[1].discounts']],['unknown commercial field',s=>s.schedule.phases[2].new_setting=true],['one-off invoice items',s=>{s.schedule.phases[1].add_invoice_items=[{price:'price_once',quantity:1,discounts:[]}];s.intent.source=structuredClone(s.schedule);}]
])test(`explicit phases fail closed before collection for ${name}`,async()=>{const f=explicitFixture();change(f.state);await assert.rejects(f.begin,error=>error.status===409);assert.equal(f.calls.filter(c=>c.post).length,0);});

for(const delivered of [false,true])test(`explicit phase lost response reconciles immutable payload and stage, delivered=${delivered}`,async()=>{const f=explicitFixture();await f.begin();f.state.session.status='complete';f.state[delivered?'failAfter':'failBefore']=true;await assert.rejects(f.complete,/LOST_/);const original=structuredClone(f.state.attempt.phase_apply_plan),first=f.state.attempt.schedule_first_apply_at;assert.ok(first);f.state.failAfter=false;f.state.failBefore=false;f.state.leaseActive=false;assert.equal((await f.complete()).updated,true);const writes=f.calls.filter(c=>c.post?.startsWith('/subscription_schedules/'));assert.equal(writes.length,delivered?1:2);assert.ok(writes.every(c=>c.key===writes[0].key));assert.deepEqual(f.state.attempt.phase_apply_plan,original);assert.equal(f.state.attempt.schedule_first_apply_at,first);});
test('explicit phases refuse old undelivered replay and permit read-only already-applied reconciliation',async()=>{const f=explicitFixture();await f.begin();f.state.session.status='complete';f.state.failBefore=true;await assert.rejects(f.complete,/LOST_BEFORE/);f.state.failBefore=false;f.state.leaseActive=false;f.state.attempt.schedule_first_apply_at=new Date(Date.now()-24*3600000).toISOString();const writes=f.calls.filter(c=>c.post).length;await assert.rejects(f.complete,error=>error.status===409);assert.equal(f.calls.filter(c=>c.post).length,writes);f.state.leaseActive=false;f.state.schedule=structuredClone(f.state.attempt.phase_apply_plan.expected_state);f.state.subscription.default_payment_method=structuredClone(f.state.method);assert.equal((await f.complete()).updated,true);assert.equal(f.calls.filter(c=>c.post).length,writes);});
test('fresh second preflight rejects changed phases before Stripe send and never compensates',async()=>{const f=explicitFixture();await f.begin();f.state.session.status='complete';let reads=0;f.state.onGet=path=>{if(path.startsWith('/subscription_schedules/')&&++reads===2)f.state.schedule.phases[2].items[0].quantity=9;};await assert.rejects(f.complete,/BASELINE_CHANGED/);assert.deepEqual(f.calls.filter(c=>c.post).map(c=>c.post),['/checkout/sessions']);});
test('post-write commercial mismatch remains uncertain with no automatic restore or subscription write',async()=>{const f=explicitFixture();await f.begin();f.state.session.status='complete';f.state.alterReadback=s=>s.phases[2].items[0].quantity=9;await assert.rejects(f.complete,/READBACK_FAILED/);assert.equal(f.state.attempt.status,'processing');assert.equal(f.calls.filter(c=>c.post).length,2);});
test('phase transition proximity blocks the phase write; cancellation only expires setup',async()=>{const f=explicitFixture();await f.begin();f.state.session.status='complete';f.state.attempt.schedule_baseline.schedule.current_phase.end_date=Math.floor(Date.now()/1000)+20;await assert.rejects(f.complete,/PAYMENT_SCHEDULE_/);assert.equal(f.calls.filter(c=>c.post).length,1);const c=explicitFixture();const before=structuredClone(c.state.schedule);await c.begin();const result=await c.cancel();assert.equal(result.cancelled,true);assert.deepEqual(c.state.schedule,before);assert.deepEqual(c.calls.filter(x=>x.post).map(x=>x.post),['/checkout/sessions','/checkout/sessions/cs_owned/expire']);});
test('completed explicit attempt replay cannot overwrite a later default or resend phase settings',async()=>{const f=explicitFixture();await f.begin();f.state.session.status='complete';await f.complete();const writes=f.calls.filter(c=>c.post).length;f.state.subscription.default_payment_method.id='pm_later';await f.complete();assert.equal(f.state.subscription.default_payment_method.id,'pm_later');assert.equal(f.calls.filter(c=>c.post).length,writes);});
test('explicit path pins schedule transport without changing ordinary setup/subscription API versions',async()=>{const f=explicitFixture();await f.begin();f.state.session.status='complete';await f.complete();for(const c of f.calls.filter(c=>c.post?.startsWith('/subscription_schedules/')))assert.equal(c.options.apiVersion,'2025-06-30.basil');for(const c of f.calls.filter(c=>c.post&&!c.post.startsWith('/subscription_schedules/')))assert.equal(c.options.apiVersion,undefined);assert.ok(f.calls.some(c=>c.get?.startsWith('/subscription_schedules/')&&c.options.apiVersion==='2025-06-30.basil'));});
for(const inherited of [false,true])test(`same-method setup completes without unnecessary phase writes while binding inherited defaults=${inherited}`,async()=>{const f=explicitFixture();f.state.schedule.default_settings.default_payment_method=inherited?null:'pm_new';f.state.schedule.phases[1].default_payment_method='pm_new';f.state.schedule.phases[3].default_payment_method='pm_new';f.state.subscription.default_payment_method=structuredClone(f.state.method);f.state.intent.source=structuredClone(f.state.schedule);await f.begin();f.state.session.status='complete';assert.equal((await f.complete()).updated,true);assert.equal(f.calls.filter(c=>c.post?.startsWith('/subscription_schedules/')).length,inherited?1:0);assert.equal(f.calls.filter(c=>c.post?.startsWith('/subscriptions/')).length,0);assert.equal(f.state.attempt.status,'completed');});
test('exact complete retained request recovers intent; sparse or altered requests never supply guessed discounts',async()=>{const f=explicitFixture(),helper=f.load('src/lib/subscriptionPaymentExplicitPhase.ts');const baseline=await helper.inspectExplicitPhaseSchedule(f.admin,salon,f.state.schedule,f.state.subscription,'cus_owner',false);const plan=helper.prepareExplicitPhasePlan(baseline,'pm_new'),values={...plan.request};values['phases[0][default_payment_method]']='pm_old';values['phases[2][default_payment_method]']='pm_future';assert.deepEqual(helper.recoverPhaseIntent(f.state.schedule,values),f.state.intent.empty_discounts);const original=f.state.intent.empty_discounts;f.state.intent=null;f.state.leaseEvidence={salon_id:salon,stripe_subscription_id:'sub_owner',request_evidence:[{path:'/subscription_schedules/sub_sched_owned',values,provider_request_id:'req_verified'}]};await f.begin();assert.deepEqual(f.state.attempt.schedule_baseline.empty_discounts,original);delete values['phases[0][items][0][tax_rates]'];assert.throws(()=>helper.recoverPhaseIntent(f.state.schedule,values),/ORIGINAL_INTENT_REQUIRED/);});
for(const failure of ['archive','response'])test(`lost ${failure} persistence after a real phase response retains the mutation hold and never reports unapplied`,async()=>{
 const {loadNodeTypescript}=await import('./helpers/load-node-typescript.mjs'),calls=[];
 const admin={async rpc(name){calls.push(name);return{data:failure==='response'&&name==='record_subscription_mutation_response'?false:true};}};
 const guard=loadNodeTypescript(process.cwd(),{'@/lib/stripeServer':{stripeGet:async()=>({}),stripeFailureDiagnostics:()=>null,stripeRequest:async()=>{calls.push('provider-wrote');return{};}},'@/lib/subscriptionPaymentExplicitPhase':{archiveExplicitPhaseResponse:async()=>{throw Error('ARCHIVE_UNCERTAIN');}}})('src/lib/subscriptionMutationGuard.ts');
 await assert.rejects(()=>guard.withSubscriptionMutation({admin,salonId:salon,actorId:salon,subscriptionId:'sub_owner'},provider=>provider.post('/subscription_schedules/sub_sched_owned',{'phases[0][default_payment_method]':'pm_new'},{apiVersion:'2025-06-30.basil',idempotencyKey:'fixture_only'})),error=>error.code==='SUBSCRIPTION_MUTATION_REVIEW_REQUIRED');
 assert.equal(calls.includes('provider-wrote'),true);assert.equal(calls.includes('release_subscription_mutation'),false);
});
test('real Stripe transport sends pinned headers only for the explicitly versioned schedule calls',async()=>{
 const exports={},requests=[],code=ts.transpileModule(readFileSync('src/lib/stripeServer.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 runInNewContext(code,{exports,require:createRequire(import.meta.url),process:{env:{STRIPE_SECRET_KEY:'sk_test_fixture_only'}},URLSearchParams,Response,fetch:async(url,options)=>{requests.push({url,options});return new Response('{}',{status:200,headers:{'request-id':'req_fixture'}});}});
 await exports.stripeRequest('/subscription_schedules/sub_sched_fixture',{'phases[0][iterations]':1},{apiVersion:'2025-06-30.basil'});await exports.stripeGet('/subscription_schedules/sub_sched_fixture',{apiVersion:'2025-06-30.basil'});await exports.stripeGet('/subscriptions/sub_fixture');
 assert.equal(requests[0].options.method,'POST');assert.equal(requests[0].options.headers['Stripe-Version'],'2025-06-30.basil');assert.equal(requests[1].options.headers['Stripe-Version'],'2025-06-30.basil');assert.equal(requests[2].options.headers['Stripe-Version'],undefined);
});
