/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
"use client";
import { FormEvent, useEffect, useState } from "react";
import { BadgePercent } from "lucide-react";
import { getSessionForScope } from "@/lib/supabase";
type Row = Record<string, any>;
export default function AdminPromoCodes() {
  const [codes,setCodes]=useState<Row[]>([]); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  async function headers(){const session=await getSessionForScope("admin");if(!session)throw new Error("Admin sign-in required.");return{Authorization:`Bearer ${session.access_token}`};}
  async function load(){const response=await fetch("/api/admin/promo-codes",{headers:await headers(),cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load codes.");setCodes(Array.isArray(body.codes)?body.codes:[]);}
  useEffect(()=>{void load().catch((error)=>setNotice(error instanceof Error?error.message:"Unable to load codes."));},[]);// eslint-disable-line react-hooks/exhaustive-deps
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;setBusy(true);setNotice("");const form=new FormData(formElement);try{const response=await fetch("/api/admin/promo-codes",{method:"POST",headers:{...(await headers()),"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to create code.");formElement.reset();await load();setNotice("Promo code created in Stripe test mode and Girlz Culture.");}catch(error){setNotice(error instanceof Error?error.message:"Unable to create code.");}finally{setBusy(false);}}
  async function toggle(row:Row){setBusy(true);try{const response=await fetch("/api/admin/promo-codes",{method:"PATCH",headers:{...(await headers()),"Content-Type":"application/json"},body:JSON.stringify({id:row.id,is_active:!row.is_active})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to update code.");await load();setNotice(`${row.code} ${row.is_active?"disabled":"enabled"}.`);}catch(error){setNotice(error instanceof Error?error.message:"Unable to update code.");}finally{setBusy(false);}}
  return <section className="rounded-[14px] border border-plum/10 bg-white p-5"><div className="flex items-center gap-3"><BadgePercent className="text-magenta"/><div><h2 className="font-serif text-2xl text-plum">Promo & Discount Codes</h2><p className="text-xs text-ink/55">Codes are created in Stripe test mode and tracked here.</p></div></div><form onSubmit={create} className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="Code" name="code" placeholder="WELCOME20" required/><label className="text-[10px] font-bold">Discount type<select name="discount_type" className="mt-1 min-h-10 w-full rounded-lg border border-plum/15 px-3 text-xs font-normal"><option value="percent">Percentage off</option><option value="fixed">Fixed amount off</option></select></label><Field label="Value" name="discount_value" type="number" placeholder="20" required/><label className="text-[10px] font-bold">Works for<select name="applies_to" className="mt-1 min-h-10 w-full rounded-lg border border-plum/15 px-3 text-xs font-normal"><option value="both">Bookings + subscriptions</option><option value="booking">Booking deposits</option><option value="subscription">Salon subscriptions</option></select></label><Field label="Starts" name="starts_at" type="datetime-local" required/><Field label="Ends" name="ends_at" type="datetime-local" required/><Field label="Usage limit" name="usage_limit" type="number" placeholder="Unlimited"/><button disabled={busy} className="min-h-10 rounded-lg bg-magenta text-xs font-bold text-white disabled:opacity-50">{busy?"Saving…":"Create code"}</button></form><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-plum/10">{["Code","Discount","Applies to","Dates","Usage","Status"].map((heading)=><th key={heading} className="py-3 pr-4">{heading}</th>)}</tr></thead><tbody>{codes.map((row)=><tr key={row.id} className="border-b border-plum/10"><td className="py-3 font-bold text-plum">{row.code}</td><td>{row.discount_type==="percent"?`${row.discount_value}%`:`$${Number(row.discount_value).toFixed(2)}`}</td><td>{row.applies_to}</td><td>{new Date(row.starts_at).toLocaleDateString()} – {new Date(row.ends_at).toLocaleDateString()}</td><td>{row.usage_count}{row.usage_limit?` / ${row.usage_limit}`:""}</td><td><button disabled={busy} onClick={()=>void toggle(row)} className={`rounded-full px-3 py-1 text-[10px] font-bold ${row.is_active?"bg-green-100 text-green-800":"bg-blush text-plum"}`}>{row.is_active?"Active":"Disabled"}</button></td></tr>)}</tbody></table>{!codes.length?<p className="py-8 text-center text-xs text-ink/50">No promo codes yet.</p>:null}</div>{notice?<p className="mt-4 rounded-lg bg-blush/50 p-3 text-xs text-plum">{notice}</p>:null}</section>;
}
function Field({label,name,type="text",placeholder,required=false}:{label:string;name:string;type?:string;placeholder?:string;required?:boolean}){const numeric=type==="number";const whole=name==="usage_limit";return <label className="text-[10px] font-bold">{label}<input name={name} type={type} inputMode={numeric?(whole?"numeric":"decimal"):undefined} placeholder={placeholder} required={required} min={numeric?(whole?"1":"0.01"):undefined} max={numeric?(whole?"1000000":"10000"):undefined} step={numeric?(whole?"1":"0.01"):undefined} className="mt-1 min-h-10 w-full rounded-lg border border-plum/15 px-3 text-xs font-normal"/></label>;}
