"use client";
import {useEffect,useRef,useState} from 'react';
import {createAuthenticatedApiClient} from '@/lib/scopedApiClient';
import {ScopedApiError} from '@/lib/scopedApiCore';
import type {AdminAds} from '@/lib/businessAdvertising';
const button='min-h-11 rounded-lg border border-border px-4 py-2 text-sm font-semibold gc-disabled-control';
const field='mt-1 min-h-11 w-full rounded-lg border border-border px-3 text-sm';
export default function AdminAdSpaces(){
 const [data,setData]=useState<AdminAds|null>(null),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const pending=useRef<{action:string;input:Record<string,unknown>}|null>(null);
 useEffect(()=>{const controller=new AbortController();void(async()=>{try{const api=await createAuthenticatedApiClient('admin'),body=await api.request<{ads:AdminAds}>('/api/admin/ad-spaces',{signal:controller.signal});if(!controller.signal.aborted){setData(body.ads);setError('');}}catch(failure){if(!controller.signal.aborted)setError(failure instanceof ScopedApiError?`${failure.code} · ${failure.requestId||''}`:'Ad inventory could not be loaded.');}})();return()=>controller.abort();},[version]);
 async function save(action:string,input:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{const api=await createAuthenticatedApiClient('admin'),body=await api.request<{ads:AdminAds;verified:boolean}>('/api/admin/ad-spaces',{method:'POST',body:JSON.stringify({action,input})});if(!body.verified)throw Error('READBACK_FAILED');setData(body.ads);setNotice('Saved and independently verified.');pending.current=null;}catch(failure){setError(failure instanceof ScopedApiError?`${failure.code} · ${failure.requestId||''}`:'The change could not be confirmed. Keep the same values and retry.');}finally{setBusy(false);}}
 return <section aria-label='Plan advertising inventory' className='space-y-4 rounded-xl border border-border bg-white p-5'>
  <h2 className='font-serif text-2xl'>Plan advertising inventory</h2><p className='text-sm'>Publish priced spaces for owner review. Premium receives 48 hours of early access. Reservation balances require an invoice already verified by platform staff; this tool never collects payment.</p>
  <form className='grid gap-3 sm:grid-cols-2 xl:grid-cols-4' onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);const input:Record<string,unknown>={title:f.get('title'),price_cents:Math.round(Number(f.get('price'))*100),capacity:Number(f.get('capacity')),radius_miles:Number(f.get('radius')),opens_at:new Date(String(f.get('opens'))).toISOString(),starts_at:new Date(String(f.get('starts'))).toISOString(),ends_at:new Date(String(f.get('ends'))).toISOString()};const old=pending.current;const oldValues=old?Object.fromEntries(Object.entries(old.input).filter(([k])=>k!=='id')):null;input.id=old?.action==='create'&&JSON.stringify(oldValues)===JSON.stringify(input)?old.input.id:crypto.randomUUID();pending.current={action:'create',input};void save('create',input);}}>
   <label className='text-sm'>Placement title<input name='title' minLength={3} maxLength={100} required className={field}/></label><label className='text-sm'>Listed price (USD)<input name='price' type='number' min='.01' max='10000' step='.01' required className={field}/></label><label className='text-sm'>Available spaces<input name='capacity' type='number' min='1' max='100' step='1' required defaultValue='1' className={field}/></label><label className='text-sm'>Radius (miles)<input name='radius' type='number' min='1' max='250' step='.1' required defaultValue='25' className={field}/></label>
   <label className='text-sm'>General access opens (at least 48 hours ahead)<input name='opens' type='datetime-local' required className={field}/></label><label className='text-sm'>Placement starts<input name='starts' type='datetime-local' required className={field}/></label><label className='text-sm'>Placement ends<input name='ends' type='datetime-local' required className={field}/></label><label className='flex items-center gap-2 text-sm'><input type='checkbox' required/>I reviewed the price, availability and dates.</label><button disabled={busy} className={button}>Publish ad space</button>
  </form>
  {data?<><ul className='space-y-2'>{data.spaces.map(s=><li key={s.id} className='flex flex-wrap items-center justify-between gap-2 border-t border-border py-3 text-sm'><span>{s.title} · ${(s.price_cents/100).toFixed(2)} · {s.active?'Open inventory':'Closed inventory'}</span>{s.active?<button className={button} disabled={busy} onClick={()=>void save('close',{id:s.id})}>Close new reservations</button>:null}</li>)}</ul>
   <h3 className='font-semibold'>Owner-reviewed reservations</h3><ul className='space-y-3'>{data.reservations.map(r=><li key={r.id} className='rounded-lg border border-border p-3 text-sm'><strong>{r.business_name} · {r.title}</strong><p>{r.status} · Price ${(r.price_cents/100).toFixed(2)} · Discount ${(r.discount_cents/100).toFixed(2)} · Credit ${(r.credit_cents/100).toFixed(2)} · Balance ${(r.balance_cents/100).toFixed(2)}</p>{r.status==='reserved'?<form className='mt-3 grid gap-3 sm:grid-cols-2' onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);void save('fulfill',{id:r.id,invoice_reference:String(f.get('reference')||''),received_cents:Math.round(Number(f.get('received')||0)*100),payment_verified:f.get('verified')==='on'});}}>{r.balance_cents>0?<><label>Verified invoice reference<input name='reference' minLength={4} maxLength={160} required className={field}/></label><label>Verified received amount (USD)<input name='received' type='number' min='.01' step='.01' required className={field}/></label><label className='flex gap-2 items-center'><input type='checkbox' name='verified' required/>I verified the invoice, exact received amount and business.</label></>:<p>Fully covered by the reviewed plan credit.</p>}<button className={button} disabled={busy}>Confirm and schedule placement</button></form>:null}</li>)}</ul>
  </>:!error?<p role='status'>Loading advertising…</p>:null}
  {error?<p role='alert' className='break-words gc-text-danger'>{error}</p>:null}{notice?<p role='status'>{notice}</p>:null}<button className={button} disabled={busy} onClick={()=>setVersion(n=>n+1)}>Reload ad inventory</button>
 </section>;
}
