import Link from "next/link";
import { AlertTriangle, ChevronRight, ServerCog, SlidersHorizontal } from "lucide-react";
import { ENGINE_SECTIONS } from "@/lib/engineManifest";

export default function AdminEngineLanding() {
  return <div data-admin-record-landing className="space-y-5">
    <section className="grid gap-3 sm:grid-cols-2">
      <Link href="/admin/engine/incidents" className="rounded-[15px] border border-red-200 bg-white p-5 transition hover:border-magenta hover:bg-blush/20"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-red-700"><AlertTriangle size={20}/></span><h2 className="mt-3 font-serif text-2xl text-plum">Errors & incidents</h2><p className="mt-1 text-xs leading-5 text-ink/55">Search deduplicated operational events, then open one incident for evidence, assignment, and resolution.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-magenta">Open incident queue <ChevronRight size={14}/></span></Link>
      <Link href="/admin/engine/system-status" className="rounded-[15px] border border-teal/20 bg-white p-5 transition hover:border-teal hover:bg-teal/5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal/10 text-teal"><ServerCog size={20}/></span><h2 className="mt-3 font-serif text-2xl text-plum">System & provider status</h2><p className="mt-1 text-xs leading-5 text-ink/55">Review safe configuration presence and run supported connectivity checks without exposing secrets.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-teal">Open system status <ChevronRight size={14}/></span></Link>
    </section>
    <section className="rounded-[15px] border border-plum/10 bg-white p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blush text-magenta"><SlidersHorizontal size={20}/></span><div><h2 className="font-serif text-2xl text-plum">Governed configuration</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-ink/55">Choose one operational area. Its compact control list opens each editable setting on a dedicated, auditable page.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{ENGINE_SECTIONS.filter((section) => section.id !== "overview" && section.id !== "system_health").map((section) => <Link key={section.id} href={`/admin/engine/category-${encodeURIComponent(section.id)}`} className="group rounded-xl border border-plum/10 p-4 transition hover:border-magenta hover:bg-blush/20"><span className="flex items-center justify-between gap-2"><b className="text-sm text-plum">{section.label}</b><ChevronRight size={15} className="text-magenta transition group-hover:translate-x-0.5"/></span><span className="mt-2 block text-[10px] leading-4 text-ink/55">{section.description}</span><span className="mt-3 block text-[9px] font-bold uppercase tracking-wide text-ink/40">{section.categories.length || "Guided"} control {section.categories.length === 1 ? "group" : "groups"}</span></Link>)}</div></section>
  </div>;
}
