"use client";
import {useEffect,useState} from "react";
import {createAuthenticatedApiClient} from "@/lib/scopedApiClient";
type Location=Record<string,unknown>;
export default function BusinessLocationVisit({applicationId}:{applicationId:string}){
 const [location,setLocation]=useState<Location|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[notice,setNotice]=useState("");
 const [visitedAt,setVisitedAt]=useState(""),[evidence,setEvidence]=useState(""),[attested,setAttested]=useState(false),[outcome,setOutcome]=useState("verified");
 const endpoint=`/api/admin/submissions/${applicationId}/location-visit`;
 useEffect(()=>{const controller=new AbortController();void(async()=>{try{const body=await(await createAuthenticatedApiClient("admin")).request(endpoint,{signal:controller.signal});if(!controller.signal.aborted)setLocation(body.location as Location|null);}catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:"Location review unavailable.");}})();return()=>controller.abort();},[endpoint,refresh]);
 async function save(){if(busy||!attested||!visitedAt||evidence.trim().length<10)return;setBusy(true);setError("");setNotice("");try{const body=await(await createAuthenticatedApiClient("admin")).request(endpoint,{method:"POST",body:JSON.stringify({status:outcome,visited_at:new Date(visitedAt).toISOString(),evidence,attest_visited:attested})});if(body.verified!==true)throw new Error("The saved visit could not be verified.");setLocation(body.location as Location);setNotice("Visit record saved and read back. Application approval is a separate action.");}catch(failure){setError(failure instanceof Error?failure.message:"Visit record could not be saved. Your evidence is retained.");}finally{setBusy(false);}}
 if(!location&&!error)return null;
 return <section className="space-y-3 rounded-xl border border-plum/10 bg-white p-4"><h2 className="font-serif text-xl">Private location verification</h2><p className="text-sm">Check practitioner and business licensing for the offered services and location. A platform visit is separate from a government inspection. <a href="https://dos.ny.gov/appearance-enhancement-law" target="_blank" rel="noreferrer" className="underline">New York home and remote practice rules</a></p>{location?<><p className="text-sm">{[location.address_street,location.address_line2,location.address_city,location.address_state,location.address_zip].filter(Boolean).join(", ")}</p><p className="text-sm">Visit: <strong>{String(location.visit_status)}</strong></p>{location.visited_at?<p className="text-xs">{new Date(String(location.visited_at)).toLocaleString()}</p>:null}<p className="whitespace-pre-wrap text-sm">{String(location.visit_evidence||"")}</p><label className="block text-sm">Actual visit date and time<input type="datetime-local" value={visitedAt} onChange={e=>setVisitedAt(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border p-2"/></label><label className="block text-sm">Visit outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border p-2"><option value="verified">Verified in person</option><option value="rejected">Did not meet requirements</option></select></label><label className="block text-sm">Visit evidence<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} maxLength={2000} rows={3} className="mt-1 w-full rounded-lg border p-2"/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)}/>I confirm this in-person visit took place and the evidence is accurate.</label><button type="button" disabled={busy||!attested||!visitedAt||evidence.trim().length<10} onClick={()=>void save()} className="min-h-11 rounded-lg bg-magenta px-4 text-white gc-disabled-control">Save visit record</button></>:null}{error?<p role="alert" className="text-sm gc-text-danger">{error}</p>:null}{notice?<p role="status" className="text-sm">{notice}</p>:null}<button type="button" onClick={()=>{setError("");setRefresh(value=>value+1);}} className="min-h-11 underline">Refresh verification</button></section>;
}
