"use client";

import { useEffect, useState } from "react";
import { KeyRound, ShieldAlert, UserRoundX } from "lucide-react";
import { getSessionForScope } from "@/lib/supabase";

type Role="customer"|"salon_owner"|"salon_team"|"admin";
type Identity={id:string;email:string;name:string;status:string;user_id:string};
const roleLabels:Record<Role,string>={customer:"Customers",salon_owner:"Salon owners",salon_team:"Salon team members",admin:"Platform administrators"};

export default function IdentityDeletionManager(){
  const[data,setData]=useState<Record<Role,Identity[]>>({customer:[],salon_owner:[],salon_team:[],admin:[]});const[role,setRole]=useState<Role>("customer");const[id,setId]=useState("");const[dependencies,setDependencies]=useState<Record<string,unknown>>({});const[eligible,setEligible]=useState(false);const[blocker,setBlocker]=useState("");const[confirmation,setConfirmation]=useState("");const[reason,setReason]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function auth(){const session=await getSessionForScope("admin");if(!session)throw new Error("Your admin session expired.");return{Authorization:`Bearer ${session.access_token}`}}
  async function request(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{...(init?.headers||{}),...(await auth())},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to manage this identity.");return body}
  async function load(){try{const body=await request("/api/admin/identity-deletion");setData({customer:Array.isArray(body.roles?.customer)?body.roles.customer:[],salon_owner:Array.isArray(body.roles?.salon_owner)?body.roles.salon_owner:[],salon_team:Array.isArray(body.roles?.salon_team)?body.roles.salon_team:[],admin:Array.isArray(body.roles?.admin)?body.roles.admin:[]})}catch(error){setMessage(error instanceof Error?error.message:"Unable to load identities.")}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const selected=data[role].find(item=>item.id===id);
  async function preview(value:string){setId(value);setDependencies({});setConfirmation("");setReason("");setMessage("");if(!value)return;setBusy(true);try{const body=await request(`/api/admin/identity-deletion?role=${role}&id=${encodeURIComponent(value)}`);setDependencies(body.dependencies&&typeof body.dependencies==="object"?body.dependencies:{});setEligible(Boolean(body.eligible));setBlocker(String(body.blocker||""))}catch(error){setMessage(error instanceof Error?error.message:"Unable to preview this identity.")}finally{setBusy(false)}}
  async function remove(){if(!selected)return;setBusy(true);setMessage("");try{const body=await request("/api/admin/identity-deletion",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role,id,confirmation,reason})});setMessage(body.message);setId("");setDependencies({});setConfirmation("");setReason("");await load()}catch(error){setMessage(error instanceof Error?error.message:"The identity was not removed.")}finally{setBusy(false)}}
  return <section className="rounded-[15px] border border-red-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-red-50 text-red-700"><UserRoundX/></span><div><h2 className="font-serif text-2xl text-plum">Identity deletion & email reuse</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-ink/60">Super Admin only. This removes the canonical Auth account, revokes access, preserves required history by anonymizing or detaching personal data, and releases the normalized email only after Auth deletion succeeds.</p></div></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Identity type<select value={role} onChange={event=>{setRole(event.target.value as Role);setId("");setDependencies({})}} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 px-3">{(Object.keys(roleLabels) as Role[]).map(value=><option key={value} value={value}>{roleLabels[value]}</option>)}</select></label><label className="text-xs font-bold">Account<select value={id} onChange={event=>void preview(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 px-3"><option value="">Choose an account</option>{data[role].map(item=><option key={item.id} value={item.id}>{item.name} · {item.email} · {item.status}</option>)}</select></label></div>
    {selected?<div className="mt-5 rounded-xl border border-red-200 bg-red-50/45 p-4"><div className="flex items-center gap-2 text-sm font-bold text-plum"><ShieldAlert size={18}/>Permanent account removal preview</div><div className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(dependencies).map(([key,value])=><div key={key} className="rounded-lg bg-white p-3"><b className="font-serif text-xl text-plum">{String(value)}</b><span className="ml-2 text-[10px] capitalize text-ink/60">{key.replaceAll("_"," ")}</span></div>)}</div>{blocker?<p className="mt-4 rounded-lg bg-amber/15 p-3 text-xs font-bold text-plum">{blocker}</p>:null}{eligible?<><label className="mt-4 block text-xs font-bold">Reason<input value={reason} onChange={event=>setReason(event.target.value.slice(0,500))} className="mt-1 min-h-11 w-full rounded-lg border border-red-200 bg-white px-3 font-normal" placeholder="Why this permanent deletion is authorized"/></label><label className="mt-3 block text-xs font-bold">Type <span className="text-red-700">{selected.email}</span> to confirm<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-red-200 bg-white px-3 font-normal"/></label><div className="mt-4 flex items-center gap-2 rounded-lg bg-white p-3 text-[10px] text-ink/60"><KeyRound size={16} className="text-magenta"/>You must have completed an admin verification code within the last 15 minutes. If prompted, sign out and complete a fresh verified sign-in.</div><button type="button" disabled={busy||confirmation.trim().toLowerCase()!==selected.email.trim().toLowerCase()||reason.trim().length<8} onClick={()=>void remove()} className="mt-4 min-h-11 rounded-lg bg-red-700 px-6 text-xs font-bold text-white disabled:opacity-40">{busy?"Verifying and removing…":"Permanently remove identity"}</button></>:null}</div>:null}
    {message?<p role="status" className="mt-4 rounded-lg bg-blush p-3 text-xs text-plum">{message}</p>:null}
  </section>
}
