"use client";
import { useEffect, useState } from "react";
import { ImageIcon } from "lucide-react";
import { getSessionForScope } from "@/lib/supabase";

type Profile = { profile_key:string; display_name:string; aspect_width:number; aspect_height:number; min_width_px:number; min_height_px:number; output_width_px:number; max_bytes:number; safe_area_enabled:boolean; help_text:string };

export default function MediaRulesSettings() {
  const [rows,setRows]=useState<Profile[]>([]); const [open,setOpen]=useState(false); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function headers(){const session=await getSessionForScope("admin");if(!session)throw new Error("Your admin session expired.");return{Authorization:`Bearer ${session.access_token}`};}
  async function load(){try{const response=await fetch("/api/admin/engine/media",{headers:await headers(),cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setRows(Array.isArray(body.profiles)?body.profiles:[])}catch(error){setMessage(error instanceof Error?error.message:"Unable to load media rules.")}}
  useEffect(()=>{if(!open)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[open]); // eslint-disable-line react-hooks/exhaustive-deps
  async function save(row:Profile){setBusy(true);setMessage("");try{const response=await fetch("/api/admin/engine/media",{method:"PATCH",headers:{...(await headers()),"Content-Type":"application/json"},body:JSON.stringify(row)});const body=await response.json();if(!response.ok)throw new Error(body.error);setRows(current=>current.map(item=>item.profile_key===row.profile_key?body.profile:item));setMessage(`${row.display_name} rules saved and audited.`)}catch(error){setMessage(error instanceof Error?error.message:"Unable to save media rules.")}finally{setBusy(false)}}
  function update(key:string,field:keyof Profile,value:string|boolean){setRows(current=>current.map(row=>row.profile_key===key?{...row,[field]:typeof row[field]==="number"?Number(value):value}:row))}
  return <section className="rounded-[13px] border border-plum/10 bg-cream/45 p-4"><button type="button" onClick={()=>setOpen(value=>!value)} className="flex min-h-11 w-full items-center justify-between text-left"><span className="flex items-center gap-2 font-serif text-lg text-plum"><ImageIcon size={19}/>Media Rules & Dimensions</span><b className="text-xs text-magenta">{open?"Close":"Manage"}</b></button>{open?<div className="mt-3 space-y-3"><p className="text-xs leading-5 text-ink/60">Controls validation guidance and server-side upload limits. Changes are audited; aspect ratios remain integrity-protected.</p>{rows.map(row=><article key={row.profile_key} className="rounded-[11px] border border-plum/10 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-bold text-plum">{row.display_name}</h3><p className="text-[10px] text-ink/55">Fixed placement ratio {row.aspect_width}:{row.aspect_height}</p></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={row.safe_area_enabled} onChange={event=>update(row.profile_key,"safe_area_enabled",event.target.checked)} className="accent-magenta"/>Show safe-area guide</label></div><div className="mt-3 grid gap-2 sm:grid-cols-4">{[["Minimum width","min_width_px"],["Minimum height","min_height_px"],["Output width","output_width_px"],["Max bytes","max_bytes"]].map(([label,key])=><label key={key} className="text-[10px] font-bold">{label}<input type="number" min="1" value={row[key as keyof Profile] as number} onChange={event=>update(row.profile_key,key as keyof Profile,event.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-plum/15 px-3 font-normal"/></label>)}</div><label className="mt-3 block text-[10px] font-bold">Guidance<input value={row.help_text||""} onChange={event=>update(row.profile_key,"help_text",event.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-plum/15 px-3 font-normal"/></label><button type="button" disabled={busy} onClick={()=>void save(row)} className="mt-3 min-h-10 rounded-lg bg-magenta px-4 text-xs font-bold text-white disabled:opacity-50">Save placement rules</button></article>)}{message?<p role="status" className="rounded-lg bg-blush/50 p-3 text-xs text-plum">{message}</p>:null}</div>:null}</section>;
}
