"use client";

import { useEffect, useState } from "react";
import { Archive, ArrowRightLeft, RefreshCw, RotateCcw, ShieldAlert, Trash2 } from "lucide-react";
import { getSessionForScope } from "@/lib/supabase";

type Resource={type:string;label:string;actions:string[]};
type RecordSummary={id:string;label:string;status:string;archived:boolean};
type Dependency={label:string;count:number;retention:string};

export default function RecordLifecycleManager(){
  const[resources,setResources]=useState<Resource[]>([]);const[resource,setResource]=useState("");const[records,setRecords]=useState<RecordSummary[]>([]);const[recordId,setRecordId]=useState("");const[dependencies,setDependencies]=useState<Dependency[]>([]);const[actions,setActions]=useState<string[]>([]);const[action,setAction]=useState("");const[replacement,setReplacement]=useState("");const[reason,setReason]=useState("");const[confirmation,setConfirmation]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function auth(){const session=await getSessionForScope("admin");if(!session)throw new Error("Your admin session expired.");return{Authorization:`Bearer ${session.access_token}`}}
  async function json(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{...(init?.headers||{}),...(await auth())},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load record management.");return body}
  async function loadResources(){try{const body=await json("/api/admin/records");setResources(Array.isArray(body.resources)?body.resources:[])}catch(error){setMessage(error instanceof Error?error.message:"Unable to load record types.")}}
  async function loadRecords(type:string){setBusy(true);setMessage("");setRecordId("");setDependencies([]);try{const body=await json(`/api/admin/records?resource=${encodeURIComponent(type)}`);setRecords(Array.isArray(body.records)?body.records:[]);setActions(Array.isArray(body.resource?.actions)?body.resource.actions:[]);setAction(body.resource?.actions?.[0]||"")}catch(error){setRecords([]);setMessage(error instanceof Error?error.message:"Unable to load records.")}finally{setBusy(false)}}
  async function preview(id:string){setRecordId(id);setDependencies([]);setConfirmation("");setReason("");setReplacement("");if(!id)return;setBusy(true);try{const body=await json(`/api/admin/records?resource=${encodeURIComponent(resource)}&id=${encodeURIComponent(id)}`);setDependencies(Array.isArray(body.dependencies?.details)?body.dependencies.details:[]);const nextActions=Array.isArray(body.resource?.actions)?body.resource.actions:[];setActions(nextActions);setAction(body.record?.archived&&nextActions.includes("restore")?"restore":nextActions.find((item:string)=>item!=="restore")||"")}catch(error){setMessage(error instanceof Error?error.message:"Unable to preview dependencies.")}finally{setBusy(false)}}
  useEffect(()=>{const timer=window.setTimeout(()=>void loadResources(),0);return()=>window.clearTimeout(timer)},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const selected=records.find(item=>item.id===recordId);
  const availableActions=selected?.archived?actions.filter(item=>item==="restore"):actions.filter(item=>item!=="restore");
  async function execute(){if(!selected||!action)return;setBusy(true);setMessage("");try{const body=await json("/api/admin/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,id:recordId,action,reason,confirmation,reassign_to:replacement||null})});setMessage(`${body.result?.label||selected.label} was ${action}d safely. The audit event was recorded.`);await loadRecords(resource)}catch(error){setMessage(error instanceof Error?error.message:"The record was not changed.")}finally{setBusy(false)}}
  const actionIcon=action==="delete"?Trash2:action==="reassign"?ArrowRightLeft:action==="restore"?RotateCcw:Archive;
  const ActionIcon=actionIcon;
  return <section className="rounded-[15px] border border-plum/10 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-serif text-2xl text-plum">Safe record management</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-ink/60">Preview related records before changing anything. Financial, booking, refund, dispute, subscription, and audit history is retained; those records are cancelled, offboarded, archived, or anonymized instead of being erased.</p></div><button type="button" onClick={()=>resource&&void loadRecords(resource)} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-plum/15 px-4 text-xs font-bold text-plum"><RefreshCw size={14}/>Refresh</button></div>
      <div className="mt-5 grid gap-3 lg:grid-cols-3"><label className="text-xs font-bold">Record type<select value={resource} onChange={event=>{const value=event.target.value;setResource(value);void loadRecords(value)}} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 px-3"><option value="">Choose a record type</option>{resources.map(item=><option key={item.type} value={item.type}>{item.label}</option>)}</select></label><label className="text-xs font-bold">Record<select value={recordId} onChange={event=>void preview(event.target.value)} disabled={!resource||busy} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 px-3 disabled:bg-cream"><option value="">Choose a record</option>{records.map(item=><option key={item.id} value={item.id}>{item.label} · {item.status}{item.archived?" · Archived":""}</option>)}</select></label><label className="text-xs font-bold">Safe action<select value={availableActions.includes(action)?action:availableActions[0]||""} onChange={event=>setAction(event.target.value)} disabled={!selected} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 px-3 disabled:bg-cream">{availableActions.map(item=><option key={item} value={item}>{item[0].toUpperCase()+item.slice(1)}</option>)}</select></label></div>
    {selected?<div className="mt-5 rounded-xl border border-plum/10 bg-cream/55 p-4"><div className="flex items-center gap-2"><ShieldAlert size={18} className="text-amber"/><b className="text-sm text-plum">Dependency preview for {selected.label}</b></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{dependencies.map(item=><div key={item.label} className="rounded-lg bg-white p-3"><b className="font-serif text-xl text-plum">{item.count}</b><span className="ml-2 text-xs">{item.label}</span><span className="mt-1 block text-[9px] text-ink/50">{item.retention}</span></div>)}{!dependencies.length?<p className="text-xs text-ink/55">No registered dependent records were found.</p>:null}</div>
      {action==="reassign"?<label className="mt-4 block text-xs font-bold">Replacement record<select value={replacement} onChange={event=>setReplacement(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 bg-white px-3"><option value="">Choose the replacement</option>{records.filter(item=>item.id!==selected.id&&!item.archived).map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>:null}
      <label className="mt-4 block text-xs font-bold">Reason<textarea rows={2} value={reason} onChange={event=>setReason(event.target.value.slice(0,500))} className="mt-1 w-full rounded-lg border border-plum/15 bg-white p-3 font-normal" placeholder="Explain why this change is needed"/></label><label className="mt-3 block text-xs font-bold">Type <span className="text-magenta">{selected.label}</span> to confirm<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 bg-white px-3 font-normal"/></label><button type="button" onClick={()=>void execute()} disabled={busy||confirmation!==selected.label||reason.trim().length<5||(action==="reassign"&&!replacement)} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg bg-magenta px-6 text-xs font-bold text-white disabled:opacity-40"><ActionIcon size={15}/>{busy?"Checking dependencies…":`${action[0]?.toUpperCase()||""}${action.slice(1)} ${selected.label}`}</button></div>:null}
    {message?<p role="status" className="mt-4 rounded-lg bg-blush p-3 text-xs text-plum">{message}</p>:null}
  </section>
}
