"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, CircleHelp, DatabaseZap, RefreshCw } from "lucide-react";
import { getSessionForScope } from "@/lib/supabase";

type Status={key:string;label:string;state:"healthy"|"configuration_required"|"migration_required"|"optional";detail:string;required:boolean};
const presentation={healthy:{label:"Healthy",className:"bg-green-100 text-green-800",Icon:CheckCircle2},configuration_required:{label:"Configuration required",className:"bg-amber/15 text-[#7b4a00]",Icon:AlertTriangle},migration_required:{label:"Migration required",className:"bg-red-100 text-red-800",Icon:AlertTriangle},optional:{label:"Optional / not configured",className:"bg-cream text-ink/55",Icon:CircleHelp}};

export default function SystemStatusManager(){const[statuses,setStatuses]=useState<Status[]>([]);const[checkedAt,setCheckedAt]=useState("");const[expectedMigration,setExpectedMigration]=useState("");const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");async function load(){setLoading(true);setMessage("");try{const session=await getSessionForScope("admin");if(!session)throw new Error("Your admin session expired.");const response=await fetch("/api/admin/engine/system-status",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setStatuses(Array.isArray(body.statuses)?body.statuses:[]);setCheckedAt(String(body.checkedAt||""));setExpectedMigration(String(body.expectedMigration||""))}catch(error){setMessage(error instanceof Error?error.message:"Unable to check platform systems.")}finally{setLoading(false)}}useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
return <section className="rounded-[15px] border border-plum/10 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><DatabaseZap className="text-magenta"/><div><h3 className="font-serif text-2xl text-plum">Integrations & System Status</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-ink/55">Safe health summaries only. Credentials, connection strings, provider responses, raw SQL, and secret values are never displayed here.</p></div></div><button type="button" disabled={loading} onClick={()=>void load()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-magenta px-4 text-xs font-bold text-magenta disabled:opacity-50"><RefreshCw size={14} className={loading?"animate-spin":""}/>Check again</button></div>{expectedMigration?<p className="mt-4 rounded-lg bg-cream p-3 text-[10px] text-ink/55">Repository migration target: <b className="text-plum">{expectedMigration}</b>{checkedAt?` · checked ${new Date(checkedAt).toLocaleString()}`:""}</p>:null}<div className="mt-4 grid gap-3 sm:grid-cols-2">{statuses.map(status=>{const view=presentation[status.state];const Icon=view.Icon;return <article key={status.key} className="rounded-xl border border-plum/10 p-4"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><Icon size={17} className={status.state==="healthy"?"text-green-700":status.state==="migration_required"?"text-red-700":"text-amber"}/><div><h4 className="text-xs font-bold text-plum">{status.label}</h4><p className="mt-1 text-[10px] leading-4 text-ink/55">{status.detail}</p></div></div><span className={`shrink-0 rounded-full px-2 py-1 text-[8px] font-bold ${view.className}`}>{view.label}</span></div></article>})}{!statuses.length&&!loading?<p className="rounded-xl border border-dashed p-8 text-center text-xs text-ink/50 sm:col-span-2">No health records were returned.</p>:null}</div>{message?<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-800">{message}</p>:null}</section>}
