"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { DatabaseZap, Download, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { getSessionForScope } from "@/lib/supabase";

type Batch={id:string;name:string;environment:string;status:string;created_at:string};
type Entry={id:string;record_type:string;record_id:string;record_label:string};
type Plan=Entry&{action:string;dependencies:Record<string,number>};
type Candidate={id:string;label:string;status:string};

export default function TestDataManager(){
  const[batches,setBatches]=useState<Batch[]>([]);const[batchId,setBatchId]=useState("");const[preview,setPreview]=useState<Plan[]>([]);const[environment,setEnvironment]=useState("development");const[recordTypes,setRecordTypes]=useState<string[]>([]);const[recordType,setRecordType]=useState("");const[candidates,setCandidates]=useState<Candidate[]>([]);const[recordId,setRecordId]=useState("");const[selectedTypes,setSelectedTypes]=useState<string[]>([]);const[confirmation,setConfirmation]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[report,setReport]=useState<Record<string,unknown>|null>(null);
  async function auth(){const session=await getSessionForScope("admin");if(!session)throw new Error("Your admin session expired.");return{Authorization:`Bearer ${session.access_token}`}}
  async function request(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{...(init?.headers||{}),...(await auth())},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to manage test data.");return body}
  async function load(id=batchId){try{const body=await request(`/api/admin/test-data${id?`?batch_id=${encodeURIComponent(id)}`:""}`);setBatches(Array.isArray(body.batches)?body.batches:[]);setEnvironment(String(body.environment||"development"));setRecordTypes(Array.isArray(body.record_types)?body.record_types:[]);setPreview(Array.isArray(body.preview)?body.preview:[]);const available=[...new Set((body.entries||[]).map((entry:Entry)=>entry.record_type))] as string[];setSelectedTypes(current=>current.filter(type=>available.includes(type)))}catch(error){setMessage(error instanceof Error?error.message:"Unable to load test batches.")}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(""),0);return()=>window.clearTimeout(timer)},[]); // eslint-disable-line react-hooks/exhaustive-deps
  async function createBatch(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const name=String(new FormData(form).get("name")||"");setBusy(true);try{const body=await request("/api/admin/test-data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create_batch",name})});form.reset();setBatchId(body.batch.id);setMessage(`Test batch “${body.batch.name}” created in ${body.batch.environment}.`);await load(body.batch.id)}catch(error){setMessage(error instanceof Error?error.message:"Unable to create the batch.")}finally{setBusy(false)}}
  async function chooseType(type:string){setRecordType(type);setRecordId("");setCandidates([]);if(!type)return;try{const body=await request(`/api/admin/records?resource=${encodeURIComponent(type)}`);setCandidates(Array.isArray(body.records)?body.records:[])}catch(error){setMessage(error instanceof Error?error.message:"Unable to load candidate records.")}}
  async function register(){if(!batchId||!recordType||!recordId)return;setBusy(true);try{await request("/api/admin/test-data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"register",batch_id:batchId,record_type:recordType,record_id:recordId})});setMessage("The record now carries an explicit, durable test-data marker.");setRecordId("");await load(batchId)}catch(error){setMessage(error instanceof Error?error.message:"Unable to mark this record.")}finally{setBusy(false)}}
  async function unregister(id:string){setBusy(true);try{await request("/api/admin/test-data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"unregister",batch_id:batchId,id})});await load(batchId)}catch(error){setMessage(error instanceof Error?error.message:"Unable to remove this marker.")}finally{setBusy(false)}}
  async function execute(){setBusy(true);setMessage("");try{const body=await request("/api/admin/test-data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"execute",batch_id:batchId,selected_types:selectedTypes,confirmation})});setReport(body.report);setConfirmation("");setMessage(`Cleanup completed with ${body.result?.remaining||0} marked record(s) remaining. Download the audit report before leaving this page.`);await load(batchId)}catch(error){setMessage(error instanceof Error?error.message:"No test data was cleared.")}finally{setBusy(false)}}
  function download(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`girlz-culture-test-cleanup-${batchId}.json`;anchor.click();URL.revokeObjectURL(url)}
  const batch=batches.find(item=>item.id===batchId);const grouped=useMemo(()=>Object.entries(preview.reduce<Record<string,Plan[]>>((result,item)=>{(result[item.record_type]??=[]).push(item);return result},{})),[preview]);
  return <section className="rounded-[15px] border border-plum/10 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blush text-magenta"><DatabaseZap/></span><div><h3 className="font-serif text-2xl text-plum">Labeled test-data cleanup</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-ink/60">Only records explicitly registered in a named batch can be touched. Names, email domains, dates, and empty fields are never used to guess. Paid and audited history is retained or anonymized.</p></div></div><span className="rounded-full bg-cream px-3 py-1 text-[10px] font-bold text-plum">{environment}</span></div>
    <form onSubmit={createBatch} className="mt-5 flex flex-col gap-2 sm:flex-row"><input name="name" required minLength={3} maxLength={100} placeholder="New batch name, e.g. July checkout QA" className="min-h-11 flex-1 rounded-lg border border-plum/15 px-3 text-sm"/><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-magenta px-5 text-xs font-bold text-white"><Plus size={15}/>Create test batch</button></form>
    <label className="mt-4 block text-xs font-bold">Open batch<select value={batchId} onChange={event=>{setBatchId(event.target.value);void load(event.target.value)}} className="mt-1 min-h-11 w-full rounded-lg border border-plum/15 px-3"><option value="">Choose a batch</option>{batches.map(item=><option key={item.id} value={item.id}>{item.name} · {item.environment} · {item.status}</option>)}</select></label>
    {batch?<><div className="mt-5 rounded-xl border border-plum/10 bg-cream/40 p-4"><h4 className="font-serif text-xl text-plum">Register a known test record</h4><div className="mt-3 grid gap-2 md:grid-cols-[.8fr_1.4fr_auto]"><select value={recordType} onChange={event=>void chooseType(event.target.value)} className="min-h-11 rounded-lg border border-plum/15 bg-white px-3 text-xs"><option value="">Record type</option>{recordTypes.map(type=><option key={type} value={type}>{type.replaceAll("_"," ")}</option>)}</select><select value={recordId} onChange={event=>setRecordId(event.target.value)} disabled={!recordType} className="min-h-11 rounded-lg border border-plum/15 bg-white px-3 text-xs disabled:bg-cream"><option value="">Choose the exact existing record</option>{candidates.map(item=><option key={item.id} value={item.id}>{item.label} · {item.status}</option>)}</select><button type="button" onClick={()=>void register()} disabled={!recordId||busy} className="min-h-11 rounded-lg border border-magenta px-5 text-xs font-bold text-magenta disabled:opacity-40">Mark as test</button></div></div>
      <div className="mt-5"><div className="flex items-center gap-2"><ShieldCheck className="text-magenta"/><h4 className="font-serif text-xl text-plum">Exact cleanup preview</h4></div>{grouped.map(([type,items])=><div key={type} className="mt-3 rounded-xl border border-plum/10"><label className="flex min-h-11 items-center gap-3 border-b border-plum/10 px-4 text-xs font-bold capitalize"><input type="checkbox" checked={selectedTypes.includes(type)} onChange={event=>setSelectedTypes(current=>event.target.checked?[...new Set([...current,type])]:current.filter(item=>item!==type))} className="accent-magenta"/>{type.replaceAll("_"," ")} · {items?.length||0}</label>{items?.map(item=><div key={item.id} className="flex flex-wrap items-start justify-between gap-3 border-b border-plum/5 px-4 py-3 text-xs last:border-0"><span><b>{item.record_label}</b><span className="mt-1 block text-[10px] text-ink/55">{item.action}</span><span className="mt-1 block text-[9px] text-ink/45">{Object.entries(item.dependencies||{}).map(([key,value])=>`${key.replaceAll("_"," ")}: ${value}`).join(" · ")||"No registered dependencies found"}</span></span><button type="button" onClick={()=>void unregister(item.id)} aria-label={`Remove test marker from ${item.record_label}`} className="text-red-700"><Trash2 size={15}/></button></div>)}</div>)}{!preview.length?<p className="mt-3 rounded-lg border border-dashed p-5 text-center text-xs text-ink/50">No records are marked in this batch.</p>:null}</div>
      {preview.length?<div className="mt-5 rounded-xl border border-red-200 bg-red-50/50 p-4"><p className="text-xs leading-5 text-ink/70">Enable <b>Test-data maintenance tool</b> in The Engine, complete a fresh admin verification, select record types, and type the exact phrase below. Configuration, legal content, real financial history, unmarked records, the acting admin, and the last super-admin are outside this cleanup path.</p><label className="mt-3 block text-xs font-bold">Type <span className="text-red-700">DELETE {batch.name}</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-red-200 bg-white px-3 font-normal"/></label><button type="button" disabled={busy||!selectedTypes.length||confirmation!==`DELETE ${batch.name}`} onClick={()=>void execute()} className="mt-3 min-h-11 rounded-lg bg-red-700 px-6 text-xs font-bold text-white disabled:opacity-40">{busy?"Executing verified cleanup…":"Clear selected test records"}</button></div>:null}
    </>:null}{report?<button type="button" onClick={download} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg bg-plum px-5 text-xs font-bold text-white"><Download size={15}/>Download cleanup audit report</button>:null}{message?<p role="status" className="mt-4 rounded-lg bg-blush p-3 text-xs text-plum">{message}</p>:null}
  </section>
}
