"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {CalendarDays,CalendarCheck,CheckCheck,CircleDollarSign,Plus,UserRound} from "lucide-react";
import {useI18n} from "@/components/i18n/LocaleProvider";
import {BOOKING_GROUPS,bookingMatchesGroup,normalizedBookingStatus,filterBookingPeriod,summarizeBookings,type BookingGroup} from "@/lib/businessBookings";
import {bookingReference} from "@/lib/bookingReference";
import {isBusinessAdded,BOOKING_SOURCE_LABELS} from "@/lib/ownerBusinessMetrics";
type Row=Record<string,unknown>;
export default function BookingsWorkspace({bookings,styles,stylists,timeZone,canUseCalendar}:{bookings:Row[];styles:Row[];stylists:Row[];timeZone:string;canUseCalendar:boolean}){
 const {translateSource:t,formatDate,formatCurrency,formatNumber}=useI18n();const router=useRouter(),params=useSearchParams();const [now]=useState(()=>Date.now());
 const group:BookingGroup=BOOKING_GROUPS.includes(params.get('group') as BookingGroup)?params.get('group') as BookingGroup:params.has('status')?'All':'Upcoming';
 const status=params.get('status')||'All',query=params.get('q')||'';
 const filters={from:params.get('from')||'',to:params.get('to')||'',staff:params.get('staff')||'',service:params.get('service')||''};
 const [draftFrom,setDraftFrom]=useState(filters.from),[draftTo,setDraftTo]=useState(filters.to),[error,setError]=useState('');
 const rows=bookings.filter(row=>row.payment_mode!=='test');
 const period=filterBookingPeriod(rows,filters,timeZone),summary=summarizeBookings(period);
 const style=(row:Row)=>String(row.manual_service_name||styles.find(s=>s.id===row.style_id)?.name||t('Service unavailable'));
 const professional=(row:Row)=>String(stylists.find(s=>s.id===row.stylist_id)?.name||t('Unassigned'));
 const matching=period.filter(row=>bookingMatchesGroup(row,group,now)&&(status==='All'||normalizedBookingStatus(row)===status.toLowerCase().replaceAll('_',' '))&&(!query||[row.guest_name,row.guest_email,row.guest_phone,bookingReference(row),style(row),professional(row),row.status].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>new Date(String(a.appointment_datetime)).getTime()-new Date(String(b.appointment_datetime)).getTime()||String(a.id).localeCompare(String(b.id)));
 const requestedPage=Math.max(1,Number(params.get('page'))||1),pages=Math.max(1,Math.ceil(matching.length/25)),page=Math.min(pages,Math.floor(requestedPage)),visible=matching.slice((page-1)*25,page*25);
 function set(values:Record<string,string>){const next=new URLSearchParams(window.location.search);next.delete('page');for(const [key,value]of Object.entries(values)){if(value)next.set(key,value);else next.delete(key);}window.history.replaceState(null,'',`/salon/dashboard/bookings${next.size?'?'+next:''}`);}
 const href=(row:Row)=>`/salon/dashboard/bookings/${encodeURIComponent(String(row.id))}${params.size?'?'+params:''}`;
 const control='min-h-11 min-w-0 rounded-lg border border-border bg-white px-3 text-sm';
 const money=(value:unknown)=>value==null||!Number.isFinite(Number(value))?t('Not recorded'):formatCurrency(Number(value));
 const date=(row:Row,short=false)=>Number.isFinite(new Date(String(row.appointment_datetime)).getTime())?formatDate(String(row.appointment_datetime),{dateStyle:short?'short':'medium',timeStyle:'short',timeZone}):t('Date unavailable');
 const badge=(row:Row)=>{const value=normalizedBookingStatus(row);return <span className={'rounded-lg px-2 py-1 text-xs font-semibold '+(/completed|confirmed/.test(value)?'bg-emerald-50 gc-text-success':/cancel|failed|disput/.test(value)?'bg-red-50 gc-text-danger':'bg-sky-50 text-sky-800')}>{t(String(row.status||'Status unavailable'))}</span>;};
 const source=(row:Row)=>t(isBusinessAdded(row)?BOOKING_SOURCE_LABELS[String(row.source)]||'Other':'Girlz Culture marketplace');
 const metricCards=<div className="grid grid-cols-2 gap-2 xl:grid-cols-4">{[[CalendarDays,'Appointments in period',formatNumber(summary.total)],[CalendarCheck,'Confirmed',formatNumber(summary.confirmed)],[CheckCheck,'Completed',formatNumber(summary.completed)],[CircleDollarSign,'Completed booking value',formatCurrency(summary.completedAgreedCents/100)]].map(([Icon,label,value])=>{const Symbol=Icon as typeof CalendarDays;return <div key={String(label)} className="min-w-0 rounded-xl border border-border bg-white p-3"><Symbol size={18} className="mb-2 text-primary"/><p className="text-xs text-text-secondary">{t(String(label))}</p><p className="mt-1 break-words font-serif text-2xl">{String(value)}</p></div>;})}</div>;
 return <section aria-label={t('Bookings workspace')} className="space-y-4">
  <header className="flex items-start justify-between gap-3"><div><h1 className="font-serif text-3xl font-bold">{t('Bookings')}</h1><p className="mt-1 hidden text-sm text-text-secondary sm:block">{t('Manage appointments, clients and booking details in one place.')}</p></div><Link aria-label={t('Add an appointment')} href="/salon/dashboard/bookings/new" className="inline-flex shrink-0 min-h-11 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-white"><Plus size={18}/><span className="sr-only sm:not-sr-only">{t('Add an appointment')}</span></Link></header>
  <div className="hidden sm:block">{metricCards}</div>
  <details className="rounded-xl border border-border bg-white p-3 sm:hidden"><summary className="min-h-11 cursor-pointer content-center text-sm font-semibold">{t('Booking summary')} · {formatNumber(summary.total)}</summary><div className="mt-2">{metricCards}</div><p className="mt-2 text-xs text-text-secondary">{t('Summary uses the date, staff and service filters. Booking value is not money received; test bookings are excluded.')}{summary.missingPrices?' '+t('Some completed appointments have no recorded price.'):''}</p></details>
  <p className="hidden text-xs text-text-secondary sm:block"><span data-no-translate>{filters.from || filters.to ? `${filters.from || "—"} – ${filters.to || "—"}` : t("All dates")} · {timeZone}</span><span className="hidden sm:block">{t('Summary uses the date, staff and service filters. Booking value is not money received; test bookings are excluded.')}{summary.missingPrices?' '+t('Some completed appointments have no recorded price.'):''}</span></p>
  <div className="space-y-3 rounded-xl border border-border bg-white p-3">
   <div className="flex items-center gap-2"><span className="rounded-lg bg-primary/10 px-3 py-2 text-sm font-semibold text-primary">{t('List view')}</span>{canUseCalendar?<Link href="/salon/dashboard/availability" className="flex min-h-11 items-center gap-2 px-3 text-sm"><CalendarDays size={16}/>{t('Calendar')}</Link>:null}</div>
   <form role="search" onSubmit={event=>{event.preventDefault();set({q:String(new FormData(event.currentTarget).get('booking_search')||'').trim()});}} className="flex gap-2"><label className="min-w-0 flex-1 text-sm"><span className="sr-only">{t('Search bookings')}</span><input key={query} name="booking_search" type="search" defaultValue={query} placeholder={t('Customer, reference, style, stylist, or status')} className={control+' w-full'}/></label><button className={control+' self-end !bg-primary text-white'}>{t('Search')}</button></form>
   <div role="group" aria-label={t('Booking workflow groups')} className="flex gap-2 overflow-x-auto pb-1">{BOOKING_GROUPS.map(value=><button type="button" key={value} aria-label={t(value)} aria-pressed={value===group} onClick={()=>set({group:value==='Upcoming'?'':value,status:''})} className={control+' shrink-0 '+(value===group?'!bg-primary text-white':'')}>{t(value)} <span className="ml-1">{formatNumber(period.filter(row=>bookingMatchesGroup(row,value,now)).length)}</span></button>)}</div>
   <details open={Boolean(filters.from||filters.to||filters.staff||filters.service||status!=='All')}><summary className="min-h-11 cursor-pointer content-center text-sm font-semibold text-primary">{t('Date, staff and service filters')}</summary><div className="grid grid-cols-2 gap-3 lg:grid-cols-3">
    <label className="text-xs">{t('From date')}<input type="date" value={draftFrom} onChange={e=>setDraftFrom(e.target.value)} className={control+' mt-1 w-full'}/></label><label className="text-xs">{t('To date')}<input type="date" value={draftTo} onChange={e=>setDraftTo(e.target.value)} className={control+' mt-1 w-full'}/></label><button type="button" onClick={()=>{if(draftFrom&&draftTo&&draftFrom>draftTo){setError('End date must not precede start date.');return;}setError('');set({from:draftFrom,to:draftTo});}} className={control+' self-end'}>{t('Apply dates')}</button>
    <label className="text-xs">{t('Staff filter')}<select value={filters.staff} onChange={e=>set({staff:e.target.value})} className={control+' mt-1 w-full'}><option value="">{t('All staff')}</option><option value="unassigned">{t('Unassigned')}</option>{stylists.map(row=><option data-no-translate key={String(row.id)} value={String(row.id)}>{String(row.name)}</option>)}</select></label>
    <label className="text-xs">{t('Service filter')}<select value={filters.service} onChange={e=>set({service:e.target.value})} className={control+' mt-1 w-full'}><option value="">{t('All services')}</option><option value="manual">{t('Custom services')}</option>{styles.map(row=><option data-no-translate key={String(row.id)} value={String(row.id)}>{String(row.name)}</option>)}</select></label>
    <label className="text-xs">{t('Exact status')}<select value={status} onChange={e=>set({status:e.target.value==='All'?'':e.target.value,group:e.target.value==='All'?(group==='Upcoming'?'':group):'All'})} className={control+' mt-1 w-full'}><option value="All">{t('All statuses')}</option>{[...new Set(rows.map(row=>String(row.status||'')).filter(Boolean))].sort().map(value=><option key={value} value={value}>{t(value)}</option>)}</select></label>
   </div></details>
   {params.size?<button type="button" onClick={()=>{setDraftFrom('');setDraftTo('');setError('');window.history.replaceState(null,'','/salon/dashboard/bookings');}} className="min-h-11 text-sm font-semibold text-primary">{t('Clear')}</button>:null}
   {error?<p role="alert" className="text-sm gc-text-danger">{t(error)}</p>:null}
  </div>
  <p className="text-xs text-text-secondary">{t('Matching appointments: {value0}',{value0:formatNumber(matching.length)})}</p>
  <div className="space-y-3 xl:hidden">{visible.map(row=><button key={String(row.id)} onClick={()=>router.push(href(row))} className="w-full space-y-3 rounded-xl border border-border bg-white p-4 text-left"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm">{date(row)}</b>{badge(row)}</div><div className="flex items-start gap-3"><span className="rounded-full bg-primary/5 p-2 text-primary"><UserRound size={22}/></span><div className="min-w-0"><h2 data-no-translate className="break-words font-serif text-lg">{String(row.guest_name||t('Customer'))}</h2><p data-no-translate className="break-words text-sm">{style(row)}</p><p data-no-translate className="text-xs text-text-secondary">{professional(row)}</p></div></div><div className="grid grid-cols-2 gap-2 border-t border-border pt-3 text-xs"><p>{t('Deposit')} <b>{money(row.deposit_amount)}</b><span className="block text-text-secondary">{t(String(row.deposit_status||'Not recorded'))}</span></p><p>{t('Balance')} <b>{money(row.balance_due)}</b><span className="block text-text-secondary">{t(String(row.balance_status||'Not recorded'))}</span></p></div><p className="text-xs text-text-secondary">{source(row)} · <span data-no-translate>#{bookingReference(row)}</span></p></button>)}</div>
  {visible.length?<div className="hidden overflow-x-auto rounded-xl border border-border bg-white xl:block"><table className="w-full min-w-[660px] text-left text-xs"><thead className="bg-surface-subtle"><tr>{['Date / Time','Client','Service','Stylist','Deposit','Balance','Status','Actions'].map(label=><th key={label} className="p-3 font-semibold">{t(label)}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={String(row.id)} className="border-t border-border"><td className="p-3 font-semibold">{date(row,true)}<span data-no-translate className="mt-1 block text-[10px] font-normal text-text-secondary">#{bookingReference(row)}</span></td><td data-no-translate className="p-3 font-semibold">{String(row.guest_name||t('Customer'))}</td><td className="p-3"><span data-no-translate>{style(row)}</span><span className="mt-1 block text-text-secondary">{source(row)}</span></td><td data-no-translate className="p-3">{professional(row)}</td><td className="p-3">{money(row.deposit_amount)}<span className="mt-1 block text-text-secondary">{t(String(row.deposit_status||'Not recorded'))}</span></td><td className="p-3">{money(row.balance_due)}<span className="mt-1 block text-text-secondary">{t(String(row.balance_status||'Not recorded'))}</span></td><td className="p-3">{badge(row)}</td><td className="p-3"><Link href={href(row)} className="inline-flex min-h-11 items-center font-semibold text-primary">{t('Open')}</Link></td></tr>)}</tbody></table></div>:null}
  {!matching.length?<div className="rounded-xl border border-dashed border-border bg-white p-6 text-center"><h2 className="font-serif text-xl">{t('No appointments match these filters')}</h2><p className="mt-2 text-sm text-text-secondary">{t('Try another date or clear filters. New appointments use the existing availability and conflict checks.')}</p><Link href="/salon/dashboard/bookings/new" className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-primary">{t('Add an appointment')}</Link></div>:null}
  {pages>1?<nav aria-label={t('Appointment pages')} className="flex items-center justify-between gap-2"><button disabled={page<=1} onClick={()=>set({page:String(page-1)})} className={control+' gc-disabled-control'}>{t('Previous')}</button><span className="text-sm">{formatNumber(page)} / {formatNumber(pages)}</span><button disabled={page>=pages} onClick={()=>set({page:String(page+1)})} className={control+' gc-disabled-control'}>{t('Next')}</button></nav>:null}
 </section>;
}
