"use client";
import {useState} from "react";
import Link from "next/link";
import {CalendarDays,Check,CircleDollarSign,Clock3,ImagePlus,Megaphone,UsersRound} from "lucide-react";
import {useI18n} from "@/components/i18n/LocaleProvider";
import {businessOverview,type OverviewPeriod} from "@/lib/businessOverview";
import {profileCompletion} from "@/lib/ownerBusinessMetrics";
import SalonOpenStatusControl from "./SalonOpenStatusControl";
import PushSetup from "@/components/notifications/PushSetup";
import BusinessMorningBrief from "./BusinessMorningBrief";
import {businessLabels} from "@/lib/businessLabels";
import {isSoloPlan} from "@/lib/plans";
type Row=Record<string,unknown>;
const box="min-w-0 rounded-2xl border border-border bg-white p-4 sm:p-5";
export default function BusinessOverview({salon,bookings,reviews,styles,stylists,access,actorName,cancellationThreshold,plan}:{plan:string;salon:Row;bookings:Row[];reviews:Row[];styles:Row[];stylists:Row[];access:Record<string,boolean>|null;actorName:string;cancellationThreshold:number}){
 const {translateSource:t,formatCurrency:money,formatDate,formatNumber:number}=useI18n();
 const [now]=useState(()=>Date.now()),[period,setPeriod]=useState<OverviewPeriod>("month"),[trend,setTrend]=useState<"appointments"|"completed_value_cents">("appointments");
 const timeZone=String(salon.time_zone||"America/New_York"),data=businessOverview(bookings,period,timeZone,now);
 const allowed=(key:string)=>access===null||Boolean(access[key]);
 const bookingAccess=allowed("bookings"),completion=profileCompletion(salon,styles.length,stylists.length,isSoloPlan(plan));
 const labels=businessLabels(salon.business_type,isSoloPlan(plan));
 const checks:[string,boolean,string][]=[["Business information",Boolean(salon.name&&salon.phone),"my-page"],["Description",Boolean(salon.description),"my-page/description"],["Location",Boolean(salon.address_street),"my-page/address"],["Cover photo",Boolean(salon.cover_photo_url),"photos/cover"],[labels.services,styles.length>0,"styles"],...(labels.team?[[labels.team,stylists.length>0,"stylists"] as [string,boolean,string]]:[])];
 const summary=[
  ["Appointments",bookingAccess?number(data.appointments):"—",CalendarDays],
  ["Identified clients",bookingAccess?number(data.identified_clients):"—",UsersRound],
  ["Completed marketplace value",bookingAccess?money(data.completed_value_cents/100):"—",CircleDollarSign],
  ["Business cancellation rate",bookingAccess&&data.cancellation_rate!==null?number(data.cancellation_rate,{style:"percent",maximumFractionDigits:1}):"—",Clock3],
 ] as const;
 const maximum=Math.max(1,...data.trend.map(row=>row[trend]));
 function appointment(row:Row){return <Link key={String(row.id)} href={`/salon/dashboard/bookings/${row.id}`} className="grid min-h-16 grid-cols-[68px_minmax(0,1fr)] items-start gap-3 border-b border-border py-3 last:border-0"><time className="text-xs font-semibold">{formatDate(String(row.appointment_datetime),{timeZone,hour:"numeric",minute:"2-digit"})}<span className="mt-1 block font-normal text-muted">{formatDate(String(row.appointment_datetime),{timeZone,month:"short",day:"numeric"})}</span></time><div className="min-w-0"><b className="block break-words text-sm" data-no-translate>{String(row.guest_name||t("Customer"))}</b><span className="block break-words text-xs text-muted" data-no-translate>{String(row.manual_service_name||styles.find(style=>style.id===row.style_id)?.name||t("Appointment"))}</span><span className="mt-1 inline-block rounded-full bg-subtle px-2 py-1 text-xs font-medium">{t(String(row.status||"Confirmed"))}</span></div></Link>;}
 return <div className="space-y-4">
  <header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-serif text-3xl sm:text-4xl">{actorName?t("Welcome back, {value0}",{value0:actorName}):t("Welcome back")}</h1><p className="mt-1 text-sm text-muted" data-no-translate>{String(salon.name||"")}</p></div><time className="flex items-center gap-2 text-sm"><CalendarDays size={18}/>{formatDate(now,{timeZone,weekday:"short",month:"short",day:"numeric",year:"numeric"})}</time></header>
  {access===null?<BusinessMorningBrief key={String(salon.id)}/>:null}
  <div className="grid items-stretch gap-3 xl:grid-cols-2"><PushSetup scope="salon" compact/>{allowed("availability")?<SalonOpenStatusControl salon={salon} compact/>:null}</div>
  <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-muted">{t("Appointment dates in {value0}",{value0:timeZone.replaceAll("_"," ")})}</p><label className="flex items-center gap-2 text-xs font-semibold">{t("Summary period")}<select value={period} onChange={e=>setPeriod(e.target.value as OverviewPeriod)} className="min-h-11 rounded-xl border border-border bg-white px-3"><option value="today">{t("Today")}</option><option value="week">{t("This week to date")}</option><option value="month">{t("This month to date")}</option></select></label></div>
  {bookingAccess&&data.cancellation_rate!==null&&data.cancellation_rate*100>cancellationThreshold?<Link href="/salon/dashboard/availability" className="block rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-text-danger">{t("Your business cancellation rate is above {value0}% for this period. Review availability before accepting more appointments.",{value0:number(cancellationThreshold)})}</Link>:null}
  <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{summary.map(([label,value,Icon])=><div key={label} className={box}><Icon className="mb-2 text-primary" size={19}/><p className="text-xs leading-5 text-muted">{t(label)}</p><strong className="mt-1 block break-words font-serif text-2xl sm:text-3xl">{value}</strong></div>)}</div>
  <p className="text-xs leading-5 text-muted">{bookingAccess?t("{value0} marketplace appointments · {value1} business-added appointments. Completed value is not cash received. Identified clients exclude unnamed guests.",{value0:number(data.marketplace),value1:number(data.business_added)}):t("Booking metrics are not assigned to this role.")}{data.missing_completed_prices?` ${t("Some completed appointments have no recorded price.")}`:""}</p>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(250px,1fr)]">
   <section className={box} aria-label={t("Booking trends")}><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-serif text-xl">{t("Booking trends")}</h2><label className="text-xs"><span className="sr-only">{t("Trend measure")}</span><select value={trend} onChange={e=>setTrend(e.target.value as typeof trend)} className="min-h-11 max-w-full rounded-lg border border-border px-2"><option value="appointments">{t("Appointments")}</option><option value="completed_value_cents">{t("Completed marketplace value")}</option></select></label></div><p className="mt-1 text-xs text-muted">{t("Last six months through today")}</p>{bookingAccess&&data.trend.some(row=>row.appointments>0)?<><div className="mt-6 grid h-52 grid-cols-6 items-end gap-2 border-b border-border" role="img" aria-label={t("Monthly totals; exact values are listed below")}>{data.trend.map(row=><div key={row.month} className="flex h-full flex-col justify-end"><span className="mb-1 text-center text-[11px] font-semibold">{trend==="appointments"?number(row[trend]):money(row[trend]/100)}</span><div className="mx-auto w-3/4 rounded-t-lg bg-primary" style={{height:`${row[trend]/maximum*80}%`,minHeight:row[trend]?3:0}}/></div>)}</div><div className="grid grid-cols-6 gap-2 pt-2 text-center text-xs">{data.trend.map(row=><span key={row.month}>{formatDate(`${row.month}-15T12:00:00Z`,{month:"short",timeZone:"UTC"})}</span>)}</div></>:<p className="grid min-h-52 place-items-center text-center text-sm text-muted">{t(bookingAccess?"No appointment activity in this period.":"Booking metrics are not assigned to this role.")}</p>}<details className="mt-4 text-xs"><summary className="min-h-11 cursor-pointer py-3 font-semibold">{t("View totals and definitions")}</summary><p className="mb-3 leading-5">{t("Based on loaded appointment records. Test bookings are excluded. Cancellation rate uses completed, cancelled and no-show marketplace outcomes; the numerator is cancellations by this business.")}</p>{bookingAccess?<ul className="space-y-2">{data.trend.map(row=><li key={row.month} className="flex flex-wrap justify-between gap-2"><span>{row.month}</span><span>{number(row.appointments)} {t("Appointments")} · {money(row.completed_value_cents/100)}</span></li>)}</ul>:null}</details></section>
   <section className={box}><div className="flex items-center justify-between gap-3"><h2 className="font-serif text-xl">{t("Today's schedule")}</h2>{bookingAccess?<Link href="/salon/dashboard/bookings" className="text-xs font-semibold text-primary">{t("View all")}</Link>:null}</div>{bookingAccess&&data.today.length?data.today.slice(0,5).map(appointment):<p className="py-8 text-sm text-muted">{t(bookingAccess?"No appointments today.":"Booking metrics are not assigned to this role.")}</p>}</section>
  </div>
  <div className="grid gap-4 xl:grid-cols-3">
   <section className={box}><h2 className="font-serif text-xl">{t("Page health")}</h2><div className="my-4 flex items-center gap-3"><strong className="font-serif text-3xl text-primary">{number(completion)}%</strong><div className="h-2 flex-1 rounded-full bg-subtle"><div className="h-2 rounded-full bg-primary" style={{width:`${completion}%`}}/></div></div><ul className="space-y-2">{checks.filter(([, ,path])=>allowed(path.split('/')[0].replace('-','_'))).map(([label,done,path])=><li key={label}><Link href={`/salon/dashboard/${path}`} className="flex min-h-9 items-center gap-2 text-xs"><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-full border ${done?"border-emerald-700 bg-emerald-700 text-white":"border-border"}`} aria-label={t(done?"Complete":"Incomplete")}>{done?<Check size={14}/>:null}</span>{t(label)}</Link></li>)}</ul>{allowed("my_page")?<Link href="/salon/dashboard/my-page" className="mt-4 flex min-h-11 items-center justify-center rounded-xl border border-primary px-3 text-sm font-semibold text-primary">{t("Improve my page")}</Link>:null}</section>
   <section className={box}><h2 className="font-serif text-xl">{t("Upcoming Appointments")}</h2>{bookingAccess&&data.upcoming.length?data.upcoming.slice(0,3).map(appointment):<p className="py-8 text-sm text-muted">{t(bookingAccess?"No upcoming appointments.":"Booking metrics are not assigned to this role.")}</p>}</section>
   <section className={box}><h2 className="font-serif text-xl">{t("Recent Reviews")}</h2>{allowed("reviews")&&reviews.length?reviews.slice(0,3).map(row=><article key={String(row.id)} className="mt-3 border-t border-border pt-3"><b className="text-xs" data-no-translate>{String(row.display_name||t("Customer"))}</b><p className="mt-1 text-xs text-primary">{number(Number(row.rating_overall||0))} / 5</p><p className="mt-1 line-clamp-3 text-xs leading-5" data-no-translate>{String(row.written_review||"")}</p></article>):<p className="py-8 text-sm text-muted">{t(allowed("reviews")?"Reviews will appear after completed bookings.":"Reviews are not assigned to this role.")}</p>}{allowed("reviews")?<Link href="/salon/dashboard/reviews" className="mt-4 inline-flex min-h-11 items-center text-xs font-semibold text-primary">{t("View all")}</Link>:null}</section>
  </div>
  <section className={box}><h2 className="font-serif text-xl">{t("Quick Actions")}</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{([["Add an appointment","bookings/new","bookings",CalendarDays],["Manage hours","availability","availability",Clock3],["Add Photos","photos","photos",ImagePlus],["Create a promotion","promotions","promotions",Megaphone]] as const).filter(([, ,key])=>allowed(key)).map(([label,path,,Icon])=><Link key={path} href={`/salon/dashboard/${path}`} className="flex min-h-12 items-center gap-2 rounded-xl bg-subtle px-3 py-2 text-xs font-semibold"><Icon size={18} className="shrink-0 text-primary"/>{t(label)}</Link>)}</div></section>
 </div>;
}
