"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useI18n } from "@/components/i18n/LocaleProvider";
import { getSessionForScope } from "@/lib/supabase";
import { OwnerActionError, readOwnerResponse } from "@/lib/ownerActionError";
import { emptyOnboardingFacts, onboardingPolicyTemplate, ONBOARDING_DAYS, ONBOARDING_SECTIONS, type OnboardingDraft, type OnboardingFacts, type OnboardingSection, type OnboardingSource } from "@/lib/businessOnboardingDraft";
import { onboardingText } from "@/i18n/business-onboarding-copy";
import { structureOwnerSource } from "@/lib/businessOnboardingSource";
import BusinessPolicyEditor from "@/components/owner/BusinessPolicyEditor";
import { PolicySummary } from "@/components/owner/BusinessPolicies";
import InstagramOnboardingSource from "@/components/owner/InstagramOnboardingSource";
import { instagramOnboardingText } from "@/i18n/instagram-onboarding-copy";
import { instagramOnboardingAssetId, type InstagramOnboardingPreview } from "@/lib/instagramOnboardingMedia";

const control = "mt-1 min-h-11 w-full rounded-lg border border-border bg-white p-2 text-base";
const button = "min-h-11 rounded-lg border border-border px-4 py-2 font-semibold gc-disabled-control";
const identityLabels = { name: "Business Name", description: "Business Description", phone: "Phone", address_street: "Street address", address_city: "City", address_state: "State", address_zip: "ZIP code" } as const;
type Workspace = { drafts: OnboardingDraft[]; owned_photos: string[]; private_photos?: InstagramOnboardingPreview[]; groups: { id: string; name: string }[]; current_name: string; live_business: boolean; current_is_discoverable: boolean; page_path: string | null };
async function api(body?: Record<string, unknown>) {
  const session = await getSessionForScope("salon");
  if (!session) throw new OwnerActionError("ONBOARDING_ACCESS_DENIED");
  return readOwnerResponse(await fetch("/api/salon/onboarding-draft", { method: body ? "POST" : "GET", headers: { Authorization: `Bearer ${session.access_token}`, ...(body ? { "Content-Type": "application/json" } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }), "ONBOARDING_UNAVAILABLE");
}
export default function BusinessOnboardingDraft() {
  const { locale, translateSource: translate, formatNumber } = useI18n();
  const t = (key: Parameters<typeof onboardingText>[1]) => onboardingText(locale, key);
  const instagramCopy = (key: Parameters<typeof instagramOnboardingText>[1]) => instagramOnboardingText(locale, key);
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [facts, setFacts] = useState<OnboardingFacts>(emptyOnboardingFacts);
  const [source, setSource] = useState<{ kind: OnboardingSource["kind"]; reference: string; permitted: boolean; text: string }>({ kind: "manual", reference: "", permitted: false, text: "" });
  const [structured, setStructured] = useState<{ count: number; unresolved: number[] } | null>(null);
  const [sourceLocale, setSourceLocale] = useState<string>(["en", "fr", "es", "zh-CN"].includes(locale) ? locale : "en");
  const [draft, setDraft] = useState<OnboardingDraft | null>(null);
  const [dirty, setDirty] = useState(false);
  const [reviewed, setReviewed] = useState<OnboardingSection[]>([]);
  const [keepPrivate, setKeepPrivate] = useState(false);
  const [busy, setBusy] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [loadAttempt, setLoadAttempt] = useState(0);
  const [notice, setNotice] = useState("");
  const [reference, setReference] = useState("");
  const aiRunning = useRef(false);
  function readDraft(next: OnboardingDraft) {
    setDraft(next); setFacts(next.facts); setSource({ kind: next.source.kind, reference: next.source.reference, permitted: true, text: next.source.text || "" }); setSourceLocale(next.source.locale || "en"); setDirty(false); setReviewed([]); setKeepPrivate(false);
  }
  useEffect(() => {
    let active = true;
    void api().then((data: Workspace) => { if (!active) return; setWorkspace(data); if (data.drafts[0]) readDraft(data.drafts[0]); setLoaded(true); setNotice(""); }).catch(error => { if (!active) return; setNotice(error instanceof OwnerActionError ? error.code : "ONBOARDING_UNAVAILABLE"); setReference(error instanceof OwnerActionError ? error.reference : ""); });
    return () => { active = false; };
  }, [loadAttempt]);
  function changed(next: OnboardingFacts) { setFacts(next); setDirty(true); setReviewed([]); setKeepPrivate(false); setNotice(""); }
  function sourceChanged(next: typeof source) { setSource(next); setDirty(true); setReviewed([]); setKeepPrivate(false); setNotice(""); }
  function failure(error: unknown) { setNotice(error instanceof OwnerActionError ? error.code : "ONBOARDING_UNAVAILABLE"); setReference(error instanceof OwnerActionError ? error.reference : ""); }
  async function save() {
    setBusy(true); setNotice(""); setReference("");
    try {
      const result = await api({ action: "draft", id: draft?.status === "draft" ? draft.id : null, revision: draft?.revision, source, facts, locale: sourceLocale });
      if (!result.verified || !result.draft?.id || result.published !== false) throw new OwnerActionError("ONBOARDING_UNAVAILABLE");
      readDraft(result.draft); setNotice("DRAFT_SAVED");
    } catch (error) { failure(error); } finally { setBusy(false); }
  }
  async function generate() {
    if (aiRunning.current || busy) return;
    aiRunning.current = true; setBusy(true); setNotice(""); setReference("");
    try {
      const result = await api({ action: "structure", source, locale: sourceLocale });
      if (!result.verified || result.provider !== "openai" || result.draft?.source?.extraction?.method !== "openai_source_quotes" || result.published !== false) throw new OwnerActionError("ONBOARDING_AI_UNAVAILABLE");
      readDraft(result.draft); setStructured(null); setNotice("AI_DRAFT_SAVED");
    } catch (error) { failure(error); } finally { aiRunning.current = false; setBusy(false); }
  }
  async function confirm() {
    if (!draft || dirty) return;
    setBusy(true); setNotice(""); setReference("");
    try {
      const result = await api({ action: "confirm", id: draft.id, revision: draft.revision, reviewed, confirm: keepPrivate, keep_unpublished: workspace?.live_business !== true, public_impact: workspace?.live_business === true });
      if (!result.verified || result.draft?.status !== "applied" || typeof result.published !== "boolean") throw new OwnerActionError("ONBOARDING_UNAVAILABLE");
      setWorkspace(current => current ? { ...current, current_is_discoverable: result.current_is_discoverable === true, live_business: result.live_business === true } : current);
      readDraft(result.draft); setNotice("APPLIED");
    } catch (error) { failure(error); } finally { setBusy(false); }
  }
  const errorText = notice === "AI_DRAFT_SAVED" ? t("aiSaved") : notice === "ONBOARDING_AI_PLAN_REQUIRED" ? t("aiPlan") : notice === "ONBOARDING_AI_BUDGET_LIMIT" ? t("aiBudget") : notice.startsWith("ONBOARDING_AI_") ? t("aiUnavailable") : notice === "DRAFT_SAVED" ? t("draftSaved") : notice === "APPLIED" ? t(workspace?.current_is_discoverable ? "liveSaved" : "saved") : /ACCESS|OWNER_REQUIRED/.test(notice) ? t("access") : /STALE|WORKSPACE_CHANGED|EXISTING_|CATALOG_CHANGED/.test(notice) ? t("stale") : notice === "ONBOARDING_PHOTO_NOT_OWNED" ? t("ownership") : notice === "ONBOARDING_NAME_REQUIRED" ? t("completeName") : notice === "ONBOARDING_LIVE_BUSINESS_REVIEW_REQUIRED" ? t("liveChanged") : /INVALID|DUPLICATE|REVIEW_REQUIRED/.test(notice) ? t("invalid") : t("unavailable");
  const applied = draft?.status === "applied";
  const photoUrl = (photo: string) => instagramOnboardingAssetId(photo) ? workspace?.private_photos?.find(item => item.token === photo)?.url : photo;
  const selectedPhotosUnavailable = facts.photos.some(photo => !photoUrl(photo));
  async function importedDraft(next: OnboardingDraft) {
    const updated: Workspace = await api();
    if (!updated.drafts.some(row => row.id === next.id && row.revision === next.revision)) throw new OwnerActionError("ONBOARDING_UNAVAILABLE");
    setWorkspace(updated); readDraft(next); setNotice("DRAFT_SAVED");
  }
  function sectionFacts(section: OnboardingSection) {
    if (section === "identity") return <dl className="space-y-2">{Object.entries(facts.identity).map(([key, value]) => <div key={key}><dt className="text-sm font-semibold">{translate(identityLabels[key as keyof typeof identityLabels])}</dt><dd data-no-translate className="whitespace-pre-wrap break-words">{value || t("unknown")}</dd></div>)}</dl>;
    if (section === "services") return facts.services.length ? <ul className="space-y-3">{facts.services.map((row, index) => <li key={index} className="rounded-lg bg-subtle p-3"><strong data-no-translate>{row.name}</strong><p>{t("price")}: {row.price === null ? t("unknown") : formatNumber(row.price)} · {t("duration")}: {row.minutes === null ? t("unknown") : formatNumber(row.minutes)}</p><p>{t("group")}: <span data-no-translate>{workspace?.groups.find(group => group.id === row.group_id)?.name || t("unknown")}</span></p></li>)}</ul> : <p>{t("unknown")}</p>;
    if (section === "hours") return <dl className="space-y-1">{ONBOARDING_DAYS.map(day => <div key={day} className="flex justify-between gap-4"><dt>{translate(day)}</dt><dd>{!facts.hours[day] ? t("unknown") : facts.hours[day]?.closed ? t("closed") : `${facts.hours[day]?.open} – ${facts.hours[day]?.close}`}</dd></div>)}</dl>;
    if (section === "photos") return facts.photos.length ? <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{facts.photos.map((photo, index) => photoUrl(photo) ? <a href={photoUrl(photo)} target="_blank" rel="noopener noreferrer" key={photo} className="inline-flex min-h-11 items-center break-all underline">{t("photos")} {formatNumber(index + 1)}</a> : <p key={photo} data-no-translate>{instagramCopy("previewUnavailable")}</p>)}</div> : <p>{t("unknown")}</p>;
    if (section === "team") return facts.team.length ? <ul className="space-y-2">{facts.team.map((row, index) => <li key={index} data-no-translate><strong>{row.name}</strong><p>{row.bio}</p></li>)}</ul> : <p>{t("unknown")}</p>;
    return facts.policies ? <PolicySummary policy={facts.policies} /> : <p>{t("unknown")}</p>;
  }
  return <section className="mx-auto w-full max-w-5xl space-y-6 p-4 pb-24 text-text-primary sm:p-6">
    <header><Link className="inline-flex min-h-11 items-center underline" href="/salon/dashboard">{t("workspace")}</Link><h1 className="font-serif text-3xl font-semibold">{t("title")}</h1><p className="mt-2">{t("intro")}</p></header>
    {notice ? <div role={notice === "DRAFT_SAVED" || notice === "AI_DRAFT_SAVED" || notice === "APPLIED" ? "status" : "alert"} className="rounded-xl border border-border bg-subtle p-4"><p>{errorText}</p>{reference ? <p className="mt-2 break-all text-sm">{t("support")}: <span data-no-translate>{reference}</span></p> : null}</div> : null}
    {!loaded ? <div><p>{t("loading")}</p>{notice ? <button className={button} onClick={() => setLoadAttempt(value => value + 1)}>{t("retry")}</button> : null}</div> : <>
      {!applied ? <InstagramOnboardingSource disabled={busy || dirty} onDraft={importedDraft} onBusyChange={setBusy} onDisconnect={async () => {
        setReviewed([]); setKeepPrivate(false); setWorkspace(current => current ? { ...current, private_photos: [] } : current);
        const next: Workspace = await api(); setWorkspace(next);
        const current = next.drafts.find(row => row.id === draft?.id); if (current) readDraft(current);
      }} /> : null}
      {!applied ? <form onSubmit={event => { event.preventDefault(); void save(); }} className="space-y-6">
        <fieldset disabled={busy} className="space-y-4 rounded-xl border border-border p-4"><legend className="px-2 font-serif text-xl font-semibold">{t("source")}</legend><p data-no-translate className="rounded-lg bg-subtle p-3">{instagramCopy("manualHelp")}</p>
          <div className="grid gap-4 sm:grid-cols-2"><label>{t("source")}<select className={control} value={source.kind} onChange={event => sourceChanged({ ...source, kind: event.target.value as OnboardingSource["kind"], reference: "" })}><option value="manual">{t("manual")}</option><option value="instagram">{t("instagram")}</option><option value="website">{t("website")}</option></select></label><label>{source.kind === "instagram" ? t("instagram") : t("reference")}<input data-no-translate className={control} value={source.reference} maxLength={500} required={source.kind !== "manual"} onChange={event => sourceChanged({ ...source, reference: event.target.value })} /></label></div>
          <label className="flex min-h-11 items-start gap-3"><input className="mt-1 size-5 shrink-0" type="checkbox" required checked={source.permitted} onChange={event => sourceChanged({ ...source, permitted: event.target.checked })} /><span>{t("permission")}</span></label>
          <label className="block">{t("sourceText")}<textarea data-no-translate className={control} rows={6} maxLength={12000} value={source.text} onChange={event => { sourceChanged({ ...source, text: event.target.value }); setStructured(null); }} /></label><p className="text-sm">{t("sourceHelp")}</p><button type="button" className={button} disabled={!source.permitted || !source.text.trim()} onClick={() => { const result = structureOwnerSource(source.text, facts); changed(result.facts); setStructured({ count: result.evidence.length, unresolved: result.unresolved }); }}>{t("structure")}</button>{structured ? <div role="status"><p>{t("importedFields")}: {formatNumber(structured.count)}</p>{structured.unresolved.length ? <p>{t("unresolvedLines")}: {structured.unresolved.map(value => formatNumber(value)).join(", ")}</p> : null}</div> : null}
          <p className="text-sm">{t("aiHelp")}</p><button type="button" className={`${button} bg-primary text-white`} disabled={!source.permitted || source.text.trim().length < 10 || Boolean(draft?.source.extraction?.method === "openai_source_quotes" && draft.source.text === source.text && draft.source.kind === source.kind && draft.source.reference === source.reference)} onClick={() => void generate()}>{busy ? t("saving") : t("aiCreate")}</button>
        </fieldset>
        <fieldset disabled={busy} className="rounded-xl border border-border p-4"><legend className="px-2 font-serif text-xl font-semibold">{t("identity")}</legend><div className="grid gap-4 sm:grid-cols-2">{Object.entries(identityLabels).map(([key, label]) => <label key={key} className={key === "description" ? "sm:col-span-2" : ""}>{translate(label)}{key === "description" ? <textarea data-no-translate className={control} rows={4} maxLength={2000} value={facts.identity.description} onChange={event => changed({ ...facts, identity: { ...facts.identity, description: event.target.value } })} /> : <input data-no-translate className={control} value={facts.identity[key as keyof typeof identityLabels]} maxLength={240} onChange={event => changed({ ...facts, identity: { ...facts.identity, [key]: event.target.value } })} />}</label>)}</div></fieldset>
        <fieldset disabled={busy} className="space-y-4 rounded-xl border border-border p-4"><legend className="px-2 font-serif text-xl font-semibold">{t("services")}</legend>{facts.services.map((row, index) => <div key={index} className="grid gap-3 rounded-lg bg-subtle p-3 sm:grid-cols-2"><label>{translate("Service name")}<input data-no-translate className={control} required maxLength={120} value={row.name} onChange={event => changed({ ...facts, services: facts.services.map((item, at) => at === index ? { ...item, name: event.target.value } : item) })} /></label><label>{t("group")}<select className={control} value={row.group_id || ""} onChange={event => changed({ ...facts, services: facts.services.map((item, at) => at === index ? { ...item, group_id: event.target.value || null } : item) })}><option value="">{t("unknown")}</option>{workspace?.groups.map(group => <option key={group.id} value={group.id}>{translate(group.name)}</option>)}</select></label>{([['price', 'price'], ['minutes', 'duration']] as const).map(([key, label]) => <label key={key}>{t(label)}<input className={control} type="number" min={key === "price" ? 0 : 1} max={key === "price" ? 100000 : 1440} step={key === "price" ? "0.01" : 1} value={row[key] ?? ""} onChange={event => changed({ ...facts, services: facts.services.map((item, at) => at === index ? { ...item, [key]: event.target.value === "" ? null : event.target.valueAsNumber } : item) })} /></label>)}<button type="button" className={button} onClick={() => changed({ ...facts, services: facts.services.filter((_, at) => at !== index) })}>{t("remove")}</button></div>)}<button type="button" className={button} disabled={facts.services.length >= 50} onClick={() => changed({ ...facts, services: [...facts.services, { name: "", price: null, minutes: null, group_id: null }] })}>{t("addService")}</button></fieldset>
        <fieldset disabled={busy} className="space-y-3 rounded-xl border border-border p-4"><legend className="px-2 font-serif text-xl font-semibold">{t("hours")}</legend>{ONBOARDING_DAYS.map(day => { const slot = facts.hours[day]; return <div key={day} className="grid grid-cols-1 items-end gap-3 sm:grid-cols-3"><label>{translate(day)}<select className={control} value={!slot ? "unknown" : slot.closed ? "closed" : "open"} onChange={event => { const hours = { ...facts.hours }; if (event.target.value === "unknown") delete hours[day]; else hours[day] = event.target.value === "closed" ? { closed: true } : { closed: false, open: "", close: "" }; changed({ ...facts, hours }); }}><option value="unknown">{t("unknown")}</option><option value="closed">{t("closed")}</option><option value="open">{t("open")}</option></select></label>{slot && !slot.closed ? (['open', 'close'] as const).map(key => <label key={key}>{translate(key === 'open' ? "Opens" : "Closes")}<input className={control} type="time" required step={900} value={slot[key] || ""} onChange={event => changed({ ...facts, hours: { ...facts.hours, [day]: { ...slot, [key]: event.target.value } } })} /></label>) : null}</div>; })}</fieldset>
        <fieldset disabled={busy} className="space-y-3 rounded-xl border border-border p-4"><legend className="px-2 font-serif text-xl font-semibold">{t("photos")}</legend><p data-no-translate>{instagramCopy("photosHelp")}</p><Link href="/salon/dashboard/photos" target="_blank" className="inline-flex min-h-11 items-center underline">{t("photos")}</Link>{[...new Set([...(workspace?.owned_photos || []), ...(draft?.source.provider_import?.media_ids.map(id => `instagram-asset:${id}`) || []), ...facts.photos.filter(photo => instagramOnboardingAssetId(photo))])].map((photo, index) => <label className="flex min-h-11 items-center gap-3" key={photo}><input type="checkbox" className="size-5" checked={facts.photos.includes(photo)} onChange={event => changed({ ...facts, photos: event.target.checked ? [...facts.photos, photo] : facts.photos.filter(item => item !== photo) })} />{photoUrl(photo) ? <a className="underline" href={photoUrl(photo)} target="_blank" rel="noopener noreferrer">{t("photos")} {formatNumber(index + 1)}</a> : <span data-no-translate>{instagramCopy("previewUnavailable")}</span>}</label>)}</fieldset>
        <fieldset disabled={busy} className="space-y-4 rounded-xl border border-border p-4"><legend className="px-2 font-serif text-xl font-semibold">{t("team")}</legend><p>{t("privateTeam")}</p>{facts.team.map((row, index) => <div key={index} className="grid gap-3 rounded-lg bg-subtle p-3 sm:grid-cols-2"><label>{translate("Name")}<input data-no-translate className={control} required value={row.name} maxLength={120} onChange={event => changed({ ...facts, team: facts.team.map((item, at) => at === index ? { ...item, name: event.target.value } : item) })} /></label><label>{t("bio")}<input data-no-translate className={control} maxLength={500} value={row.bio} onChange={event => changed({ ...facts, team: facts.team.map((item, at) => at === index ? { ...item, bio: event.target.value } : item) })} /></label><button type="button" className={button} onClick={() => changed({ ...facts, team: facts.team.filter((_, at) => at !== index) })}>{t("remove")}</button></div>)}<button type="button" className={button} disabled={facts.team.length >= 30} onClick={() => changed({ ...facts, team: [...facts.team, { name: "", bio: "" }] })}>{t("addTeam")}</button></fieldset>
        <fieldset disabled={busy} className="space-y-3 rounded-xl border border-border p-4"><legend className="px-2 font-serif text-xl font-semibold">{t("policies")}</legend>{facts.policies ? <><p>{t("policyHelp")}</p><label>{translate("Policy language")}<select data-no-translate className={control} value={sourceLocale} onChange={event => { setSourceLocale(event.target.value); changed(facts); }}><option value="en">English</option><option value="fr">Français</option><option value="es">Español</option><option value="zh-CN">中文（简体）</option></select></label><BusinessPolicyEditor policy={facts.policies} onChange={policies => changed({ ...facts, policies })} disabled={busy} /></> : null}<button type="button" className={button} onClick={() => changed({ ...facts, policies: facts.policies ? null : onboardingPolicyTemplate() })}>{facts.policies ? t("policyRemove") : t("policyAdd")}</button></fieldset>
        <button type="submit" disabled={busy} className={`${button} bg-primary text-white`}>{busy ? t("saving") : t("save")}</button>
      </form> : null}
      {draft?.source.provider_import ? <aside className="rounded-lg bg-subtle p-3" data-no-translate><h2 className="font-semibold">{instagramCopy("imported")}</h2><p>@{draft.source.provider_import.username}</p><p>{instagramCopy("captured")}: {draft.source.provider_import.imported_at}</p><p className="mt-2 text-sm">{instagramCopy("evidence")}</p></aside> : null}
      {draft && !dirty ? <section className="space-y-5 rounded-xl border-2 border-primary p-4" aria-label={t("review")}><h2 className="font-serif text-2xl font-semibold">{t("review")}</h2><p>{applied ? t(workspace?.current_is_discoverable ? "liveSaved" : "saved") : t("notPublished")}</p>{draft.source.extraction?.method === "openai_source_quotes" ? <details className="rounded-lg border border-border p-3"><summary className="min-h-11 cursor-pointer font-semibold">{t("evidence")}</summary><p>{t("evidenceHelp")}</p><ul className="space-y-3">{draft.source.extraction.evidence.map((item, index) => <li key={index}><strong>{t(item.field.split(".")[0] as OnboardingSection)}</strong><blockquote data-no-translate className="whitespace-pre-wrap break-words border-l-2 border-primary pl-3">{item.quote}</blockquote></li>)}</ul>{draft.source.extraction.unresolved.length ? <><h3 className="mt-4 font-semibold">{t("unresolvedQuotes")}</h3><ul className="space-y-2">{draft.source.extraction.unresolved.map((value, index) => <li key={index} data-no-translate className="whitespace-pre-wrap break-words">{value}</li>)}</ul></> : null}</details> : null}{draft.uncertain.length ? <aside className="rounded-lg bg-subtle p-3"><h3 className="font-semibold">{t("missing")}</h3><p>{t("missingHelp")}</p><ul className="mt-2 list-inside list-disc">{[...new Set(draft.uncertain.map(value => value.split(".")[0] as OnboardingSection))].map(section => <li key={section}>{t(section)}</li>)}</ul></aside> : null}{ONBOARDING_SECTIONS.map(section => <section key={section} className="space-y-3 border-t border-border pt-4"><h3 className="font-serif text-xl font-semibold">{t(section)}</h3>{sectionFacts(section)}{!applied ? <label className="flex min-h-11 items-start gap-3"><input className="mt-1 size-5 shrink-0" type="checkbox" disabled={busy || section === "photos" && selectedPhotosUnavailable} checked={reviewed.includes(section)} onChange={event => setReviewed(current => event.target.checked ? [...current, section] : current.filter(value => value !== section))} /><span>{t("reviewed")}</span></label> : null}</section>)}
        {!applied ? <><><label className="flex min-h-11 items-start gap-3"><input className="mt-1 size-5 shrink-0" type="checkbox" checked={keepPrivate} disabled={busy} onChange={event => setKeepPrivate(event.target.checked)} /><span>{t(workspace?.live_business ? "liveHold" : "hold")}</span></label><button className={`${button} bg-primary text-white`} disabled={busy || selectedPhotosUnavailable || reviewed.length !== 6 || !keepPrivate || !facts.identity.name} onClick={() => void confirm()}>{busy ? t("saving") : t(workspace?.live_business ? "publicConfirm" : "confirm")}</button></></> : <><dl className="space-y-2"><div><dt>{t("totalServices")}</dt><dd>{formatNumber(Number(draft.result?.services_created || 0))}</dd></div><div><dt>{t("totalTeam")}</dt><dd>{formatNumber(Array.isArray(draft.result?.team_ids) ? draft.result.team_ids.length : 0)}</dd></div></dl><h3 className="font-semibold">{t("remaining")}</h3><ul className="space-y-2"><li><Link className="inline-flex min-h-11 items-center underline" href="/salon/dashboard/styles">{t("reviewServices")}</Link></li><li><Link className="inline-flex min-h-11 items-center underline" href="/salon/dashboard/stylists">{t("reviewTeam")}</Link></li><li><Link className="inline-flex min-h-11 items-center underline" href={`/salon/dashboard/my-page/business-policies${typeof draft.result?.policy_revision_id === "string" ? `?draft=${encodeURIComponent(draft.result.policy_revision_id)}` : ""}`}>{t("reviewPolicy")}</Link></li><li><Link className="inline-flex min-h-11 items-center underline" href="/salon/onboarding">{t("reviewPage")}</Link></li><li><Link className="inline-flex min-h-11 items-center underline" href="/salon/dashboard/settings/marketplace">{translate("Marketplace status")}</Link></li></ul>{workspace?.page_path ? <div><h3 className="font-semibold">{t("page")}</h3><p className="break-all" data-no-translate>https://girlzculture.com{workspace.page_path}</p>{workspace?.current_is_discoverable ? <Link href={workspace.page_path} target="_blank" className="inline-flex min-h-11 items-center underline">{translate("View Public Page")}</Link> : <p>{t("inactiveLink")}</p>}</div> : null}<button className={button} onClick={() => { setDraft(null); setFacts(emptyOnboardingFacts()); setSource({ kind: "manual", reference: "", permitted: false, text: "" }); setStructured(null); setDirty(false); setNotice(""); }}>{t("newDraft")}</button></>}
      </section> : null}
    </>}
  </section>;
}
