"use client";
import {useEffect,useRef,useState} from 'react';
import {useI18n} from '@/components/i18n/LocaleProvider';
import {createAuthenticatedApiClient} from '@/lib/scopedApiClient';
import {ScopedApiError} from '@/lib/scopedApiCore';
import type {AdQuote,BusinessAds} from '@/lib/businessAdvertising';
const button='min-h-11 rounded-lg border border-border px-4 py-2 text-sm font-semibold gc-disabled-control';
export default function BusinessAdvertising({businessId}:{businessId:string}){
 const {translateSource:t,locale}=useI18n();const [data,setData]=useState<BusinessAds|null>(null),[version,setVersion]=useState(0),[review,setReview]=useState<AdQuote|null>(null),[cancel,setCancel]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState<string|null>(null),[notice,setNotice]=useState('');
 const pending=useRef<{id:string;action:'reserve';space_id:string;fingerprint:string}|null>(null);
 const money=(cents:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:'USD'}).format(cents/100);const date=(value:string)=>new Date(value).toLocaleString(locale);
 useEffect(()=>{const controller=new AbortController();void(async()=>{try{const api=await createAuthenticatedApiClient('salon'),body=await api.request<{ads:BusinessAds}>('/api/salon/advertising',{signal:controller.signal});if(body.ads.salon_id!==businessId)throw Error('AD_SCOPE');if(!controller.signal.aborted){setData(body.ads);setReview(null);setCancel(null);setError('');setReference(null);pending.current=null;}}catch(failure){if(!controller.signal.aborted){setError('Advertising details could not be loaded.');setReference(failure instanceof ScopedApiError?failure.requestId:null);}}})();return()=>controller.abort();},[businessId,version]);
 async function save(){if(busy||!review&&!cancel)return;setBusy(true);setError('');setReference(null);setNotice('');
  if(review&&(!pending.current||pending.current.space_id!==review.id||pending.current.fingerprint!==review.fingerprint))pending.current={id:crypto.randomUUID(),action:'reserve',space_id:review.id,fingerprint:review.fingerprint};
  const payload=cancel?{action:'cancel',id:cancel}:pending.current;
  try{const api=await createAuthenticatedApiClient('salon'),body=await api.request<{ads:BusinessAds;verified:boolean;id:string}>('/api/salon/advertising',{method:'POST',body:JSON.stringify(payload)});if(!body.verified||body.ads.salon_id!==businessId||!body.ads.reservations.some(r=>r.id===body.id))throw Error('AD_READBACK');setData(body.ads);setReview(null);setCancel(null);pending.current=null;setNotice(cancel?'Reservation cancelled. Unused credit is available in the same allowance period.':'Reservation saved. Platform support must verify the invoice balance before scheduling the placement.');}
  catch(failure){setError(failure instanceof ScopedApiError&&failure.status===409?'Availability or pricing changed. Reload and review the current offer.':'The reservation could not be confirmed. Your review is retained.');setReference(failure instanceof ScopedApiError?failure.requestId:null);}finally{setBusy(false);}
 }
 return <section aria-label={t('Advertising benefits')} className='mt-5 space-y-4 rounded-xl border border-border bg-white p-5'>
  <h2 className='font-serif text-2xl'>{t('Advertising benefits')}</h2><p className='text-sm'>{t('Advertising benefits are separate from organic search results.')}</p>
  {data?<><dl className='grid gap-3 text-sm sm:grid-cols-3'><div><dt>{t('Advertising discount')}</dt><dd>{data.benefits.discount_percent}%</dd></div><div><dt>{t('Available advertising credit')}</dt><dd>{money(data.benefits.credit_available_cents)}</dd></div><div><dt>{t('Early access')}</dt><dd>{data.benefits.early_hours} {t('hours')}</dd></div></dl>
   <p className='text-sm'>{t('Credits reset on the UTC calendar month or quarter for your plan. They do not roll over, have no cash value and apply after the plan discount.')} {t('Next reset:')} {date(data.benefits.period_end)}</p>
   {!data.eligible?<p className='rounded-lg bg-subtle p-3 text-sm'>{t(data.is_demo?'Demo businesses cannot reserve public advertising.':'A public business with a verified location is required to reserve an ad space.')}</p>:null}
   <p className='text-sm'>{t('Reservations hold the space and credit for up to 48 hours. No payment is collected here. A placement begins only after platform review and verification of any remaining invoice balance.')}</p>
   {data.offers.length?<ul className='grid gap-3 md:grid-cols-2'>{data.offers.map(offer=><li key={offer.id} className='min-w-0 space-y-2 rounded-lg border border-border p-4'><h3 className='font-semibold break-words' data-no-translate>{offer.title}</h3><p className='text-sm'>{date(offer.starts_at)} – {date(offer.ends_at)}</p><p className='text-sm'>{t('Placement radius')}: {offer.radius_miles} {t('miles')}</p><p className='text-sm'>{t('Price after benefits')}: {money(offer.balance_cents)}</p><button className={button} disabled={!data.eligible||busy} onClick={()=>{setReview(offer);setCancel(null);setNotice('');}}>{t('Review ad reservation')}</button></li>)}</ul>:<p className='text-sm'>{t('No ad spaces are available for your plan right now.')}</p>}
   {review?<div role='group' aria-label={t('Review ad reservation')} className='space-y-3 rounded-lg border border-primary p-4'><h3 className='font-semibold' data-no-translate>{review.title}</h3><dl className='grid grid-cols-2 gap-2 text-sm'>{[['Listed price',review.price_cents],['Plan discount',review.discount_cents],['Advertising credit',review.credit_cents],['Invoice balance',review.balance_cents]].map(([label,value])=><div key={label}><dt>{t(String(label))}</dt><dd>{money(Number(value))}</dd></div>)}</dl><div className='flex flex-wrap gap-3'><button className={button} disabled={busy} onClick={()=>void save()}>{t('Confirm reservation')}</button><button className={button} disabled={busy} onClick={()=>setReview(null)}>{t('Back')}</button></div></div>:null}
   {data.reservations.length?<ul aria-label={t('Your ad reservations')} className='space-y-3'>{data.reservations.map(r=><li key={r.id} className='rounded-lg border border-border p-3 text-sm'><strong data-no-translate>{r.title}</strong> · {t({reserved:'Awaiting review',fulfilled:'Scheduled placement',cancelled:'Cancelled',expired:'Expired'}[r.status])}<p>{t('Invoice balance')}: {money(r.balance_cents)}</p>{r.status==='reserved'?<button className={button} disabled={busy} onClick={()=>{setReview(null);setCancel(r.id);}}>{t('Cancel reservation')}</button>:null}</li>)}</ul>:null}
   {cancel?<div role='group' aria-label={t('Cancel reservation')} className='flex flex-wrap gap-3'><button className={button} disabled={busy} onClick={()=>void save()}>{t('Confirm cancellation')}</button><button className={button} disabled={busy} onClick={()=>setCancel(null)}>{t('Back')}</button></div>:null}
  </>:!error?<p role='status'>{t('Loading…')}</p>:null}
  {notice?<p role='status' className='text-sm'>{t(notice)}</p>:null}{error?<p role='alert' className='break-words text-sm gc-text-danger'>{t(error)}{reference?<span className='block' data-no-translate>{reference}</span>:null}</p>:null}
  <button className={button} disabled={busy} onClick={()=>{setNotice('');setVersion(n=>n+1);}}>{t('Reload advertising')}</button>
 </section>;
}
