"use client";
import {useSearchParams} from "next/navigation";
import {updateFinanceLocation} from "@/lib/financeWorkspace";
import { useI18n } from "@/components/i18n/LocaleProvider";
import { type OperatingBooks, type OperatingSale, type summarizeOperatingBooks, financeSalePayable } from "@/lib/businessFinanceCore";
import { financeButton as button, financePanel as panel, financeLabels as labels, financeInput as input } from "./FinanceUI";

export default function FinanceRecords({books,summary,names,loggable,manageable,onAction,timeZone}:{books:OperatingBooks;summary:ReturnType<typeof summarizeOperatingBooks>;names:Map<string,string>;loggable:boolean;manageable:boolean;onAction:(action:string,sale:OperatingSale)=>void;timeZone:string}) {
  const {translateSource:t,locale}=useI18n();
  const params=useSearchParams();
  const filter=params.get("finance_balance")==="unpaid"?"unpaid":"all",search=(params.get("finance_search")||"").slice(0,160);
  const money=(cents:number)=>new Intl.NumberFormat(locale,{style:"currency",currency:"USD"}).format(cents/100);
  const date=(at:string)=>new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(at));
  const balances=new Map(summary.balances.map(row=>[row.sale_id,row.unpaid_cents]));
  const sales=books.sales.filter(sale=>balances.has(sale.id) && (filter!=="unpaid" || (balances.get(sale.id)||0)>0) && `${sale.name} ${sale.client_name||""} ${names.get(sale.stylist_id||"")||""}`.toLocaleLowerCase(locale).includes(search.trim().toLocaleLowerCase(locale)));
  const actions=(sale:OperatingSale)=><div className="flex flex-wrap gap-2">{loggable && (balances.get(sale.id)||0)>0?<button className={button} onClick={()=>onAction("receipt",sale)}>{t("Record balance")}</button>:null}{manageable && books.payments.some(payment=>payment.sale_id===sale.id && payment.id.startsWith("receipt:") && payment.stage!=="refund")?<button className={button} onClick={()=>onAction("refund",sale)}>{t("Record refund")}</button>:null}</div>;
  const history=(sale:OperatingSale)=><details className="mt-2 text-xs"><summary className="cursor-pointer text-magenta">{t("Payment history")}</summary><ul className="mt-2 space-y-2">{books.payments.filter(payment=>payment.sale_id===sale.id).map(payment=><li key={payment.id}>{date(payment.occurred_at)} · {t(labels[payment.stage])} · {t(labels[payment.method])} · {money(payment.amount_cents)}{payment.original_payment_id?<span className="block gc-text-secondary">{t("Linked to the original payment")}</span>:null}</li>)}</ul></details>;
  return <section className={panel}><h2 className="font-serif text-xl font-bold">{t("Sales and balances")}</h2><div className="my-3 flex flex-wrap gap-2"><input aria-label={t("Search finance records")} className={`${input} max-w-sm`} value={search} onChange={event=>updateFinanceLocation({finance_search:event.target.value.slice(0,160)},true)} placeholder={t("Search service, client or stylist")}/><select aria-label={t("Balance filter")} className={`${input} max-w-48`} value={filter} onChange={event=>updateFinanceLocation({finance_balance:event.target.value},true)}><option value="all">{t("All records")}</option><option value="unpaid">{t("Unpaid balances")}</option></select></div>
    <p className="mb-3 text-xs gc-text-secondary">{t("Balances as of")}: {summary.position_as_of}. {t("Sales include pending bookings; only completed sales contribute to revenue.")}</p>
    {!sales.length?<p className="py-4 text-sm gc-text-secondary">{t("No matching finance records.")}</p>:null}
    <div className="space-y-3 md:hidden">{sales.map(sale=><article key={sale.id} data-finance-sale className="rounded-lg border border-plum/10 p-3"><div className="flex justify-between gap-3"><h3 data-no-translate className="font-semibold">{sale.name}</h3><span className="text-xs gc-text-secondary">{t(labels[sale.status])}</span></div><p className="my-2 text-xs gc-text-secondary">{t(labels[sale.source])} · {date(sale.occurred_at)}<br/><span data-no-translate>{names.get(sale.stylist_id||"")||""}</span>{sale.client_name?<span data-no-translate>{` · ${sale.client_name}`}</span>:null}</p><dl className="my-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-xs gc-text-secondary">{t("Agreed price")}</dt><dd className="font-semibold">{money(financeSalePayable(sale))}</dd></div><div><dt className="text-xs gc-text-secondary">{t("Unpaid")}</dt><dd className="font-semibold">{money(balances.get(sale.id)||0)}</dd></div></dl>{actions(sale)}{history(sale)}</article>)}</div>
    <div className="hidden overflow-x-auto md:block focus-visible:outline-2 focus-visible:outline-magenta" role="region" aria-label={t("Sales and balances")} tabIndex={0}><table className="w-full min-w-[620px] text-left text-sm"><thead><tr>{["Service or product","Source","Stylist","Agreed price","Unpaid","Actions"].map(label=><th key={label} className="border-b border-plum/10 py-3 pr-3">{t(label)}</th>)}</tr></thead><tbody>{sales.map(sale=><tr key={sale.id} data-finance-sale><td className="border-b border-plum/5 py-3 pr-3"><b data-no-translate>{sale.name}</b><span className="block text-xs gc-text-secondary">{t(labels[sale.status])} · {date(sale.occurred_at)}{sale.client_name?<span data-no-translate>{` · ${sale.client_name}`}</span>:null}</span>{history(sale)}</td><td>{t(labels[sale.source])}</td><td data-no-translate>{names.get(sale.stylist_id||"")||"—"}</td><td>{money(financeSalePayable(sale))}</td><td>{money(balances.get(sale.id)||0)}</td><td>{actions(sale)}</td></tr>)}</tbody></table></div>
  </section>;
}
