"use client";
import {useI18n} from '@/components/i18n/LocaleProvider';
import {financeDailyClose} from '@/lib/financeDailyClose';
import {type OperatingBooks,type FinancePeriod,type summarizeOperatingBooks} from '@/lib/businessFinanceCore';
import {financePanel as panel} from './FinanceUI';
export default function FinancePeriodRecords({kind,salonId,books,period,summary,includeExpenses}:{kind:'expenses'|'daily';includeExpenses:boolean;salonId:string;books:OperatingBooks;period:FinancePeriod;summary:ReturnType<typeof summarizeOperatingBooks>}){
 const {translateSource:t,locale}=useI18n();
 const money=(cents:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:'USD'}).format(cents/100);
 const date=(day:string)=>new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));
 const daily=financeDailyClose(salonId,books,period);
 if(kind==='expenses'){
  const format=new Intl.DateTimeFormat('en-CA',{timeZone:period.timeZone,year:'numeric',month:'2-digit',day:'2-digit'});
  const rows=books.expenses.filter(row=>{const parts=format.formatToParts(new Date(row.occurred_at));const key=['year','month','day'].map(type=>parts.find(p=>p.type===type)?.value).join('-');return key>=period.from&&key<=period.to;}).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at));
  return <div className="space-y-4"><section className={panel}><h2 className="font-serif text-xl font-bold">{t('Expense categories')}</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(summary.expense_categories).map(([name,amount])=><div key={name} className="flex justify-between gap-2"><dt data-no-translate>{name}</dt><dd>{money(amount)}</dd></div>)}</dl><p className="mt-3 text-sm">{t('Operating expenses')}: {money(summary.operating_expenses_cents)} · {t('Inventory purchases')}: {money(summary.inventory_purchases_cents)}</p></section><section className={panel}><h2 className="font-serif text-xl font-bold">{t('Expense records')}</h2>{rows.length?<ul className="mt-3 divide-y divide-plum/10">{rows.map(row=><li key={row.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><b data-no-translate>{row.category}</b><p className="text-xs gc-text-secondary">{new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:period.timeZone}).format(new Date(row.occurred_at))} · {t(row.treatment==='operating'?'Operating expense':'Inventory purchase — cost when sold')}</p></div><strong>{money(row.amount_cents)}</strong></li>)}</ul>:<p className="mt-3 text-sm gc-text-secondary">{t('No expenses recorded for this period.')}</p>}</section></div>;
 }
 return <section className={panel}><h2 className="font-serif text-xl font-bold">{t('Daily close')}</h2><p className="mt-1 text-xs gc-text-secondary">{t('Sales follow completion dates. Payments and expenses follow their recorded dates. This is not a bank reconciliation.')}</p>{!daily.length?<p className="mt-4 text-sm">{t('No recorded activity for this period.')}</p>:<div className="mt-4 grid gap-3 lg:grid-cols-2">{daily.map(row=><article key={row.day} className="rounded-lg border border-plum/10 p-3"><h3 className="font-semibold">{date(row.day)}</h3><dl className="mt-3 space-y-2 text-sm">{[['Visits',row.visits],['Completed sales',row.sales_cents],['Payments received',row.receipts_cents],['Recorded refunds',row.refunds_cents],['Cash',row.methods.cash],['Card',row.methods.card],['Transfer',row.methods.transfer],['Other',row.methods.other],...(includeExpenses?[['Operating expenses',row.operating_expenses_cents],['Inventory purchases',row.inventory_purchases_cents]]:[])].map(([label,amount])=><div key={label} className="flex justify-between gap-3"><dt>{t(String(label))}</dt><dd className="text-right font-medium">{label==='Visits'?amount:money(Number(amount))}</dd></div>)}</dl></article>)}</div>}</section>;
}
