"use client";

import {useRef,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {ArrowLeft,MessageSquare,Star,Flag,CheckCircle,Search} from 'lucide-react';
import {useI18n} from '@/components/i18n/LocaleProvider';
import {getSessionForScope} from '@/lib/supabase';
import {readApiResponse} from '@/lib/apiResponseClient';
import {filterReviews,reviewMetrics,reviewState,REVIEW_VIEWS,type ReviewView} from '@/lib/businessReviews';

type Row=Record<string,unknown>;
type Props={reviews:Row[];bookings:Row[];styles:Row[];timeZone:string;recordId?:string;setReviews:(fn:(rows:Row[])=>Row[])=>void;saveRecord:(table:string,values:Row,id?:string,throwOnFailure?:boolean)=>Promise<Row|null>};
export default function ReviewsWorkspace({reviews,bookings,styles,timeZone,recordId='',setReviews,saveRecord}:Props){
 const {translateSource:t,formatDate,formatNumber}=useI18n();const params=useSearchParams();
 const query=params.get('q')||'',view:ReviewView=REVIEW_VIEWS.includes(params.get('view') as ReviewView)?params.get('view') as ReviewView:'recent',rating=params.get('rating')||'',service=params.get('service')||'';
 const metrics=reviewMetrics(reviews,timeZone),matching=filterReviews(reviews,{query,view,rating,service},bookings);
 const pages=Math.max(1,Math.ceil(matching.length/20)),page=Math.min(pages,Math.max(1,Math.floor(Number(params.get('page'))||1))),visible=matching.slice((page-1)*20,page*20);
 const selected=reviews.find(row=>row.id===recordId)||(!recordId?visible.find(row=>row.id===params.get('selected'))||visible[0]:undefined);
 const [drafts,setDrafts]=useState<Record<string,{text:string;revision:number}>>({});
 const [busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[conflict,setConflict]=useState(''),[dispute,setDispute]=useState<string|null>(null),[reason,setReason]=useState('');
 const requestRef=useRef<{key:string;id:string}|null>(null),active=useRef('');active.current=String(selected?.id||'');
 const labels:Record<ReviewView,string>={recent:'Recent',awaiting:'Awaiting reply',replied:'Replied',disputed:'Under review',removed:'Removed by Platform Admin',all:'All'};
 const control='min-h-11 min-w-0 rounded-lg border border-border bg-white px-3 text-sm';
 const date=(value:unknown)=>Number.isFinite(Date.parse(String(value)))?formatDate(String(value),{dateStyle:'medium',timeZone}):t('Date unavailable');
 function set(values:Record<string,string>){const next=new URLSearchParams(window.location.search);next.delete('page');next.delete('selected');for(const[key,value]of Object.entries(values)){if(value)next.set(key,value);else next.delete(key);}window.history.replaceState(null,'',`/salon/dashboard/reviews${next.size?'?'+next:''}`);}
 const suffix=params.size?'?'+params:'';
 const stars=(value:unknown)=><span aria-label={`${Number(value)||0} / 5`} className="inline-flex items-center gap-1 gc-text-warning"><Star size={16} fill="currentColor"/><b>{formatNumber(Number(value)||0,{maximumFractionDigits:1})}</b><span className="text-text-secondary">/ 5</span></span>;
 const select=(row:Row)=>{setNotice('');setError('');setDispute(null);set({selected:String(row.id),page:String(page)});};
 async function reply(row:Row){
  const id=String(row.id),draft=drafts[id];if(!draft?.text.trim()||busy)return;
  const key=JSON.stringify([id,draft.text.trim(),draft.revision]);if(requestRef.current?.key!==key)requestRef.current={key,id:crypto.randomUUID()};
  setBusy(id);setError('');setNotice('');
  try{
   const session=await getSessionForScope('salon');if(!session)throw new Error('Your salon session expired. Please sign in again.');
   const response=await fetch(`/api/salon/reviews/${id}/reply`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({reply:draft.text.trim(),expected_revision:draft.revision,request_id:requestRef.current.id})});
   const body=await readApiResponse(response,'The review reply could not be saved.') as {error?:string;message?:string;review?:Row;content_status?:string;reference?:string;request_id?:string;code?:string};
   if(body.code==='REVIEW_REPLY_STALE')setConflict(id);
   if(!response.ok||body.error||!body.review||body.review.id!==id){const message=body.error||'The review reply could not be saved.';const reference=String(body.reference||body.request_id||'');throw new Error(/^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$/.test(reference)&&!message.includes(reference)?`${message} Reference ${reference}.`:message);}
   const saved=body.review;
   setReviews(rows=>rows.map(item=>item.id===id?{...item,...saved,reply_versions:[...(Array.isArray(item.reply_versions)?item.reply_versions:[]),{id:requestRef.current?.id,submitted_reply:draft.text.trim(),content_status:body.content_status,created_at:new Date().toISOString()}]}:item));
   setDrafts(current=>{const next={...current};delete next[id];return next;});requestRef.current=null;setConflict('');
   if(active.current===id)setNotice(body.message||'Your salon reply was saved.');
  }catch(failure){if(active.current===id)setError(failure instanceof Error?failure.message:'The review reply could not be saved.');}
  finally{setBusy('');}
 }
 async function loadCurrent(id:string){
  setBusy(id);try{const session=await getSessionForScope('salon');if(!session)throw new Error('Your salon session expired. Please sign in again.');
   const response=await fetch('/api/salon/workspace',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});
   const body=await readApiResponse(response,'The review could not be loaded.') as {records?:{reviews?:Row[]};error?:string};
   const latest=body.records?.reviews?.find(row=>row.id===id);if(!response.ok||!latest)throw new Error(body.error||'The review could not be loaded.');
   setReviews(rows=>rows.map(row=>row.id===id?latest:row));setDrafts(current=>current[id]?{...current,[id]:{...current[id],revision:Number(latest.reply_revision)||0}}:current);
   setConflict('');setError('');setNotice('Latest public reply loaded. Compare it with your draft before saving.');requestRef.current=null;
  }catch(failure){setError(failure instanceof Error?failure.message:'The review could not be loaded.');}finally{setBusy('');}
 }
 const detail=(row:Row)=>{
  const id=String(row.id),draft=drafts[id],removed=reviewState(row)==='removed';
  const pending=(Array.isArray(row.reply_queue)?row.reply_queue as Row[]:[]).find(item=>item.status==='Pending');
  const booking=bookings.find(item=>item.id===row.booking_id),style=styles.find(item=>item.id===booking?.style_id);
  const startEdit=()=>{setDrafts(current=>({...current,[id]:{text:String(pending?.submitted_reply||row.salon_reply||''),revision:Number(row.reply_revision)||0}}));setError('');setNotice('');};
  return <article aria-label={t('Selected review')} className="space-y-4 rounded-xl border border-border bg-white p-4 sm:p-5">
   <header className="flex items-start justify-between gap-3"><div><h2 data-no-translate className="font-serif text-xl">{String(row.display_name||t('Customer'))}</h2>{stars(row.rating_overall)}<p className="mt-1 text-xs text-text-secondary">{date(row.created_at)}</p></div><span className="rounded-lg bg-primary/5 px-2 py-1 text-xs text-primary">{t(labels[reviewState(row)])}</span></header>
   {row.review_title?<h3 data-no-translate className="font-semibold">{String(row.review_title)}</h3>:null}
   <p data-no-translate className="whitespace-pre-wrap break-words text-sm leading-6">{String(row.written_review||'')}</p>
   {Array.isArray(row.result_photos)&&row.result_photos.length?<div className="flex gap-2 overflow-x-auto">{row.result_photos.map((photo,index)=>{const url=typeof photo==='string'?photo:String((photo as Row)?.url||'');return /^https:\/\//.test(url)?<a key={index} href={url} target="_blank" rel="noreferrer" className="min-h-11 rounded-lg border border-border p-3 text-sm text-primary">{t('Customer photo')} {index+1}</a>:null;})}</div>:null}
   {row.salon_reply?<section aria-label={t('Public salon reply')} className="rounded-lg bg-primary/5 p-3"><h3 className="font-semibold">{t('Salon reply')}</h3><p data-no-translate className="mt-2 whitespace-pre-wrap break-words text-sm">{String(row.salon_reply)}</p></section>:null}
   {pending?<section aria-label={t('Unpublished reply')} className="rounded-lg border border-amber-200 bg-amber-50 p-3"><p className="text-sm">{t('This reply is awaiting moderation. The current public reply stays unchanged.')}</p><p data-no-translate className="mt-2 whitespace-pre-wrap break-words text-sm">{String(pending.submitted_reply)}</p></section>:null}
   {!removed&&row.moderation_status==='Published'?<div className="space-y-3">
    {draft||(!row.salon_reply&&!pending)?<form onSubmit={event=>{event.preventDefault();void reply(row);}}><label className="block text-sm font-semibold">{t('Reply as the salon')}<textarea rows={4} maxLength={2000} value={draft?.text||''} disabled={busy===id} onChange={event=>setDrafts(current=>({...current,[id]:{text:event.target.value,revision:current[id]?.revision??(Number(row.reply_revision)||0)}}))} className="mt-2 w-full rounded-lg border border-border p-3 font-normal"/></label><p className="mt-1 text-xs text-text-secondary">{t('Your reply is public only after it passes moderation. Customer words stay unchanged.')}</p><div className="mt-3 flex flex-wrap gap-2"><button disabled={Boolean(busy)||!draft?.text.trim()} className={control+' bg-primary! font-semibold text-white gc-disabled-control'}>{t(busy===id?'Saving reply…':'Save reply')}</button>{draft&&row.salon_reply?<button type="button" disabled={Boolean(busy)} onClick={()=>setDrafts(current=>{const next={...current};delete next[id];return next;})} className={control}>{t('Cancel')}</button>:null}</div></form>:<button onClick={startEdit} disabled={Boolean(busy)} className={control+' text-primary'}>{t('Edit reply')}</button>}
   </div>:<p className="rounded-lg bg-surface-subtle p-3 text-sm">{t('This review is not public. Its history is retained; public replies are unavailable.')}</p>}
   {active.current===id&&notice?<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm gc-text-success">{t(notice)}</p>:null}
   {active.current===id&&error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm gc-text-danger">{t(error)}</p>:null}
   {conflict===id?<button disabled={Boolean(busy)} onClick={()=>void loadCurrent(id)} className={control+' text-primary'}>{t('Review latest reply')}</button>:null}
   <details className="border-t border-border pt-3"><summary className="min-h-11 cursor-pointer content-center text-sm font-semibold">{t('Booking context and review history')}</summary>
    {booking?<div className="space-y-2 text-sm"><p data-no-translate>{String(booking.manual_service_name||style?.name||'')}</p><p>{date(booking.appointment_datetime)}</p><Link className="inline-flex min-h-11 items-center text-primary" href={`/salon/dashboard/bookings/${booking.id}`}>{t('Open booking')}</Link></div>:<p className="text-sm">{t('Booking details are unavailable for your current access.')}</p>}
    {row.moderation_reason?<p data-no-translate className="my-3 text-sm">{String(row.moderation_reason)}</p>:null}
    {[...(Array.isArray(row.moderation_events)?row.moderation_events as Row[]:[]),...(Array.isArray(row.dispute_events)?row.dispute_events as Row[]:[])].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(event=><div key={String(event.id)} className="mt-2 rounded-lg bg-surface-subtle p-3 text-sm"><b>{t(String(event.action||'Updated').replaceAll('_',' '))}</b><span className="ml-2 text-xs">{date(event.created_at)}</span>{event.reason?<p data-no-translate className="mt-1">{String(event.reason)}</p>:null}</div>)}
    {(Array.isArray(row.reply_versions)?row.reply_versions as Row[]:[]).slice().reverse().map(version=><details key={String(version.id)} className="mt-2 rounded-lg border border-border p-2 text-sm"><summary className="min-h-11 cursor-pointer content-center">{t('Reply submitted')} · {date(version.created_at)} · {t(version.content_status==='pending'?'Held for moderation at submission':'Published at submission')}</summary><p data-no-translate className="whitespace-pre-wrap">{String(version.submitted_reply)}</p></details>)}
   </details>
   {!removed?<button onClick={()=>{setDispute(id);setReason('');setError('');}} className="inline-flex min-h-11 items-center gap-2 text-sm text-primary"><Flag size={16}/>{t('Flag / Dispute')}</button>:null}
   {dispute===id?<form className="space-y-3 rounded-lg border border-border p-3" onSubmit={async event=>{event.preventDefault();if(reason.trim().length<10||busy)return;setBusy(id);setError('');try{const result=await saveRecord('reviews',{dispute_status:'Disputed',dispute_reason:reason.trim()},id,true);if(!result)throw new Error('The review could not be sent for moderation.');setReviews(rows=>rows.map(item=>item.id===id?{...item,...result}:item));setDispute(null);setReason('');setNotice('Review dispute saved with its reason and audit record.');}catch(failure){setError(failure instanceof Error?failure.message:'The review could not be sent for moderation.');}finally{setBusy('');}}}><label className="block text-sm">{t('Why should the platform review this feedback?')}<textarea value={reason} onChange={event=>setReason(event.target.value)} required minLength={10} maxLength={1000} rows={3} className="mt-2 w-full rounded-lg border border-border p-3"/></label><button disabled={Boolean(busy)} className={control+' text-primary'}>{t(busy?'Submitting…':'Submit dispute')}</button><button type="button" disabled={Boolean(busy)} onClick={()=>setDispute(null)} className={control+' ml-2'}>{t('Cancel')}</button></form>:null}
  </article>;
 };
 const summary=<div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{[[Star,'Public average rating',metrics.average===null?'—':formatNumber(metrics.average,{maximumFractionDigits:1})],[MessageSquare,'Public reviews',formatNumber(metrics.total)],[CheckCircle,'Ratings of 4–5 stars',metrics.total?formatNumber(metrics.highRating/metrics.total,{style:'percent',maximumFractionDigits:0}):'—'],[Flag,'Under review',formatNumber(metrics.counts.disputed)]].map(([Icon,label,value])=>{const Symbol=Icon as typeof Star;return <div key={String(label)} className="rounded-xl border border-border bg-white p-3"><Symbol size={18} className="text-primary"/><p className="mt-2 text-xs">{t(String(label))}</p><p className="mt-1 font-serif text-2xl">{String(value)}</p></div>;})}</div>;
 if(recordId)return <section aria-label={t('Reviews workspace')} className="space-y-4"><Link href={'/salon/dashboard/reviews'+suffix} className="inline-flex min-h-11 items-center gap-2 text-sm text-primary"><ArrowLeft size={18}/>{t('Back to reviews')}</Link><h1 className="font-serif text-3xl">{t('Review details')}</h1>{selected?detail(selected):<p>{t('This review could not be found.')}</p>}</section>;
 return <section aria-label={t('Reviews workspace')} className="space-y-4"><header><h1 className="font-serif text-3xl">{t('Reviews')}</h1><p className="mt-1 text-sm text-text-secondary">{t('See what clients are saying, respond and grow your reputation.')}</p></header>
  <div className="hidden sm:block">{summary}</div><details className="rounded-xl border border-border bg-white p-3 sm:hidden"><summary className="min-h-11 cursor-pointer content-center text-sm font-semibold">{t('Public reviews')} · {formatNumber(metrics.total)} · {metrics.average===null?'—':formatNumber(metrics.average,{maximumFractionDigits:1})}/5</summary>{summary}</details>
  <p className="text-xs text-text-secondary">{t('All-time public ratings exclude hidden, removed and archived reviews. Star ratings are not sentiment analysis.')}</p>
  <div className="space-y-3 rounded-xl border border-border bg-white p-3"><div role="group" aria-label={t('Review status filters')} className="flex gap-2 overflow-x-auto">{REVIEW_VIEWS.map(value=><button key={value} aria-pressed={view===value} onClick={()=>set({view:value==='recent'?'':value})} className={control+' shrink-0 '+(view===value?'bg-primary! text-white':'')}>{t(labels[value])} {formatNumber(metrics.counts[value])}</button>)}</div>
   <form role="search" className="flex gap-2" onSubmit={event=>{event.preventDefault();set({q:String(new FormData(event.currentTarget).get('review-search')||'').trim()});}}><label className="min-w-0 flex-1"><span className="sr-only">{t('Search reviews')}</span><input key={query} name="review-search" type="search" defaultValue={query} placeholder={t('Search review or booking')} className={control+' w-full'}/></label><button aria-label={t('Search')} className={control+' text-primary'}><Search size={18}/></button></form>
   <details open={Boolean(rating||service)}><summary className="min-h-11 cursor-pointer content-center text-sm text-primary">{t('Rating and service filters')}</summary><div className="grid grid-cols-2 gap-2"><label className="text-xs">{t('Rating')}<select value={rating} onChange={event=>set({rating:event.target.value})} className={control+' mt-1 w-full'}><option value="">{t('All ratings')}</option>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} / 5</option>)}</select></label><label className="text-xs">{t('Service')}<select value={service} onChange={event=>set({service:event.target.value})} className={control+' mt-1 w-full'}><option value="">{t('All services')}</option>{styles.map(row=><option key={String(row.id)} data-no-translate value={String(row.id)}>{String(row.name)}</option>)}</select></label></div></details>
  </div>
  <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)]"><div className="min-w-0 space-y-3"><h2 className="font-serif text-xl">{t('Review inbox')} · {formatNumber(matching.length)}</h2>{visible.map(row=><article key={String(row.id)} className={'rounded-xl border bg-white p-4 '+(selected?.id===row.id?'border-primary':'border-border')}><div className="flex justify-between gap-2"><h3 data-no-translate className="font-semibold">{String(row.display_name||t('Customer'))}</h3>{stars(row.rating_overall)}</div><p className="mt-1 text-xs">{date(row.created_at)} · {t(labels[reviewState(row)])}</p><p data-no-translate className="mt-2 line-clamp-3 break-words text-sm">{String(row.written_review||'')}</p><Link href={`/salon/dashboard/reviews/${row.id}${suffix}`} className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-primary xl:hidden">{t('Open review')}</Link><button onClick={()=>select(row)} aria-pressed={selected?.id===row.id} className="mt-2 hidden min-h-11 items-center text-sm font-semibold text-primary xl:inline-flex">{t('Open review')}</button></article>)}{!matching.length?<p className="rounded-lg border border-dashed border-border p-5 text-sm">{t('No reviews match this search and status.')}</p>:null}
  {pages>1?<nav aria-label={t('Review pages')} className="flex items-center justify-between gap-2"><button disabled={page<=1} onClick={()=>set({page:String(page-1)})} className={control+' gc-disabled-control'}>{t('Previous')}</button><span>{formatNumber(page)}/{formatNumber(pages)}</span><button disabled={page>=pages} onClick={()=>set({page:String(page+1)})} className={control+' gc-disabled-control'}>{t('Next')}</button></nav>:null}</div><div className="hidden min-w-0 xl:block">{selected?detail(selected):null}</div></div>
  <details className="rounded-xl border border-border bg-white p-4"><summary className="min-h-11 cursor-pointer content-center font-serif text-xl">{t('Rating distribution and trend')}</summary><p className="mb-4 text-xs">{t('Last six months with public review activity. Empty months are not invented.')}</p><div className="grid gap-5 md:grid-cols-2"><div className="space-y-3">{metrics.distribution.map(item=><div key={item.star} className="grid grid-cols-[3rem_1fr_3rem] items-center gap-2 text-sm"><span>{item.star} / 5</span><span className="h-3 overflow-hidden rounded-full bg-primary/10"><span className="block h-full rounded-full bg-primary" style={{width:(metrics.total?item.count/metrics.total*100:0)+'%'}}/></span><span>{formatNumber(item.count)}</span></div>)}</div><div>{metrics.trend.map(point=><div key={point.month} className="grid grid-cols-[5rem_1fr] gap-2 border-b border-border py-2 text-sm"><span>{formatDate(point.month+'-15T12:00:00Z',{month:'short',year:'numeric',timeZone:'UTC'})}</span><span>{formatNumber(point.average,{maximumFractionDigits:1})}/5 · {formatNumber(point.count)} {t('Public reviews')}</span></div>)}{!metrics.trend.length?<p className="text-sm">{t('No public review activity yet.')}</p>:null}</div></div></details>
 </section>;
}
