"use client";
import {useEffect,useRef,useState} from "react";
import Image from "next/image";
import Link from "next/link";
import {CalendarDays,CheckCircle2,Circle,UserRound,Users} from "lucide-react";
import {useI18n} from "@/components/i18n/LocaleProvider";
import ProfessionalServiceAssignments from "./ProfessionalServiceAssignments";
import {professionalHours,professionalPerformance} from "@/lib/businessTeamPerformance";
type Row=Record<string,unknown>&{id?:string;name?:string};
type Props={salon:Row;stylists:Row[];bookings:Row[];access:Record<string,boolean>|null;params:URLSearchParams;services:Row[];saveAssignments:(professional:Row,ids:string[]|null)=>Promise<void>};
export default function TeamWorkspace({salon,stylists,bookings,access,params,services,saveAssignments}:Props){
 const {translateSource:t,formatNumber,formatCurrency,formatDate}=useI18n();
 const [now]=useState(()=>Date.now());
 const can=(permission:string)=>access===null||access[permission]===true;
 const query=params.get('q')||'',status=params.get('status')||'all',availability=params.get('availability')||'all';
 const rawTab=params.get('tab')||'members',tab=['members','performance','schedules','onboarding'].includes(rawTab)&&(rawTab!=='performance'||can('bookings'))?rawTab:'members';
 const hasHours=(row:Row)=>professionalHours(row.availability).some(day=>!day.closed);
 const visible=stylists.filter(row=>(status==='all'||(status==='active'?row.is_active!==false:row.is_active===false))&&(availability==='all'||(availability==='set'?hasHours(row):!hasHours(row)))&&[row.name,row.bio,...(Array.isArray(row.specialties)?row.specialties:[])].some(value=>String(value||'').toLocaleLowerCase().includes(query.toLocaleLowerCase())));
 const selected=visible.find(row=>row.id===params.get('person'))||null;
 const detailRef=useRef<HTMLElement>(null), focusSelection=useRef(false);
 useEffect(()=>{if(selected&&focusSelection.current){focusSelection.current=false;if(window.innerWidth<1024){detailRef.current?.focus({preventScroll:true});detailRef.current?.scrollIntoView({block:'start',behavior:'instant'});}}},[selected]);
 const control="min-h-11 min-w-0 rounded-lg border border-border bg-white px-3 py-2 text-sm";
 function set(key:string,value:string){const next=new URLSearchParams(window.location.search);if(!value||value==='all'||value==='members')next.delete(key);else next.set(key,value);window.history.replaceState(null,'',window.location.pathname+(next.size?'?'+next:''));}
 const href=(row:Row)=>`/salon/dashboard/stylists/${row.id}${params.size?'?'+params:''}`;
 const scheduleHref=(row:Row)=>`/salon/dashboard/availability/stylists?stylist=${encodeURIComponent(String(row.id))}`;
 const metrics=(row:Row)=>professionalPerformance(bookings,String(salon.id),String(row.id),String(salon.time_zone||'America/New_York'),now);
 function photo(row:Row){const compact="max-lg:[@media(max-height:600px)]:h-10 max-lg:[@media(max-height:600px)]:w-10";return row.avatar_url?<Image unoptimized width={96} height={96} src={String(row.avatar_url)} alt={String(row.name||'')} className={`h-20 w-20 rounded-full object-cover ${compact}`}/>:<span className={`grid h-20 w-20 place-items-center rounded-full bg-subtle text-primary ${compact}`}><UserRound size={32}/></span>;}
 function specialties(row:Row){return <div className="flex flex-wrap gap-1.5">{Array.isArray(row.specialties)&&row.specialties.length?row.specialties.map(value=><span data-no-translate key={String(value)} className="break-words rounded-lg bg-primary/5 px-2 py-1 text-xs text-primary">{String(value)}</span>):<p className="text-xs text-text-secondary">{t('No specialties selected')}</p>}</div>;}
 function checklist(row:Row){return [['Profile photo',Boolean(row.avatar_url)],['Biography',Boolean(String(row.bio||'').trim())],['Specialties',Array.isArray(row.specialties)&&row.specialties.length>0],['Working hours',hasHours(row)]] as const;}
 function hours(row:Row){return <dl className="space-y-1">{professionalHours(row.availability).map(day=><div key={day.day} className="flex justify-between gap-3 rounded-lg bg-subtle px-3 py-2 text-sm"><dt>{t(day.day)}</dt><dd>{!day.configured?t('Not set'):day.closed?t('Off'):`${day.open}–${day.close}`}</dd></div>)}</dl>;}
 return <div className="space-y-5 max-lg:[@media(max-height:600px)]:flex max-lg:[@media(max-height:600px)]:flex-col max-lg:[@media(max-height:600px)]:gap-2 max-lg:[@media(max-height:600px)]:space-y-0">
  <nav aria-label={t('Team workspace')} className="flex flex-wrap gap-2 border-b border-border pb-3 max-lg:[@media(max-height:600px)]:pb-2">
   <select aria-label={t('Team view')} value={tab} onChange={event=>set('tab',event.target.value)} className={control+' flex-1 sm:hidden'}>{[['members','Team Members'],...(can('bookings')?[['performance','Performance']]:[]),['schedules','Schedules'],['onboarding','Onboarding']].map(([value,label])=><option key={value} value={value}>{t(label)}</option>)}</select>
   {(can('earnings')||can('earnings_own')||access===null)?<details className="relative sm:hidden"><summary aria-label={t('More team actions')} className={control+' content-center cursor-pointer text-primary'}>{t('More')}</summary><div className="absolute right-0 z-10 mt-2 w-64 rounded-xl border border-border bg-white p-2 shadow-lg">{(can('earnings')||can('earnings_own'))?<Link href="/salon/dashboard/earnings" className="flex min-h-11 items-center p-2 text-sm">{t('Compensation and rent')}</Link>:null}{access===null?<Link href="/salon/dashboard/settings/team" className="flex min-h-11 items-center p-2 text-sm">{t('Team Settings')}</Link>:null}</div></details>:null}
   {[['members','Team Members'],...(can('bookings')?[['performance','Performance']]:[]),['schedules','Schedules'],['onboarding','Onboarding']].map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>set('tab',value)} className={`${control} hidden sm:inline-flex sm:items-center ${tab===value?'!border-primary !bg-primary text-white':'text-primary'}`}>{t(label)}</button>)}
   {(can('earnings')||can('earnings_own'))?<Link href="/salon/dashboard/earnings" className={`${control} hidden content-center text-primary sm:block`}>{t('Compensation and rent')}</Link>:null}
   {access===null?<Link href="/salon/dashboard/settings/team" className={`${control} hidden content-center text-primary sm:block`}>{t('Team Settings')}</Link>:null}
  </nav>
  <div className="grid grid-cols-3 gap-3 max-lg:[@media(max-height:600px)]:order-last">{[['Total stylists',stylists.length],['Active stylists',stylists.filter(row=>row.is_active!==false).length],['Schedules configured',stylists.filter(hasHours).length]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-border bg-white p-3 sm:p-4"><p className="text-xs text-text-secondary">{t(String(label))}</p><p className="mt-2 font-serif text-2xl">{formatNumber(Number(value))}</p></div>)}</div>
  <div className="grid grid-cols-2 gap-2 rounded-xl border border-border bg-white p-3 sm:grid-cols-3 max-lg:[@media(max-height:600px)]:p-2">
   <input aria-label={t('Search stylists')} placeholder={t('Search name or specialty')} value={query} onChange={event=>set('q',event.target.value)} className={control+' col-span-2 sm:col-span-1'}/>
   <select aria-label={t('Stylist status')} value={status} onChange={event=>set('status',event.target.value)} className={control}><option value="all">{t('All statuses')}</option><option value="active">{t('Active')}</option><option value="inactive">{t('Inactive')}</option></select>
    <select aria-label={t('Stylist availability')} value={availability} onChange={event=>set('availability',event.target.value)} className={control}><option value="all">{t('All schedules')}</option><option value="set">{t('Set')}</option><option value="missing">{t('Not set')}</option></select>
  </div>
  {tab==='performance'&&can('bookings')?<section aria-label={t('Team performance')} className="space-y-3"><p className="text-sm text-text-secondary">{t('Month to date in your business time zone. Only appointments available to your role are included. Completed booking value is not cash received or staff pay.')}</p><div className="grid gap-4 sm:grid-cols-2">{visible.map(row=>{const data=metrics(row);return <article key={row.id} className="rounded-xl border border-border bg-white p-4"><h2 data-no-translate className="font-serif text-xl">{row.name}</h2><p className="mt-1 text-xs">{formatDate(new Date(data.from+'T12:00:00Z'),{dateStyle:'medium',timeZone:'UTC'})}–{formatDate(new Date(data.to+'T12:00:00Z'),{dateStyle:'medium',timeZone:'UTC'})}</p><dl className="mt-4 grid grid-cols-2 gap-4">{[['Appointments',data.appointments],['Completed',data.completed],['Cancellations',data.cancellations]].map(([label,value])=><div key={String(label)}><dt className="text-xs text-text-secondary">{t(String(label))}</dt><dd className="mt-1 text-xl font-semibold">{formatNumber(Number(value))}</dd></div>)}<div><dt className="text-xs text-text-secondary">{t('Completed booking value')}</dt><dd className="mt-1 text-xl font-semibold">{formatCurrency(data.completed_value_cents/100)}</dd></div></dl>{data.missing_prices?<p className="mt-3 text-xs">{t('Some completed bookings have no recorded price; their value is excluded.')}</p>:null}</article>;})}</div></section>:null}
  {tab==='schedules'?<section aria-label={t('Team schedules')} className="grid gap-4 sm:grid-cols-2">{visible.map(row=><article key={row.id} className="space-y-4 rounded-xl border border-border bg-white p-4"><h2 data-no-translate className="font-serif text-xl">{row.name}</h2>{hours(row)}{can('availability')?<Link href={scheduleHref(row)} className="flex min-h-11 items-center gap-2 font-semibold text-primary"><CalendarDays size={16}/>{t('Edit working hours')}</Link>:null}</article>)}</section>:null}
  {tab==='onboarding'?<section aria-label={t('Team onboarding')} className="space-y-4"><p className="text-sm text-text-secondary">{t('Profile readiness uses saved information. It does not certify training or create a staff login.')}</p><div className="grid gap-4 sm:grid-cols-2">{visible.map(row=><article key={row.id} className="rounded-xl border border-border bg-white p-4"><h2 data-no-translate className="font-serif text-xl">{row.name}</h2><ul className="my-4 space-y-3">{checklist(row).map(([label,complete])=><li key={label} className="flex items-center gap-2 text-sm">{complete?<CheckCircle2 size={17} className="text-primary"/>:<Circle size={17} className="text-text-secondary"/>}{t(label)}<span className="ml-auto text-xs">{t(complete?'Complete':'Needs setup')}</span></li>)}</ul><Link href={href(row)} className={`${control} inline-flex items-center text-primary`}>{t('Edit profile')}</Link></article>)}</div></section>:null}
  {tab==='members'?<div className={`grid gap-4 ${selected?'lg:grid-cols-[minmax(0,1fr)_280px]':''}`}>
   <div className={`grid content-start gap-4 sm:grid-cols-2 ${selected?'':'xl:grid-cols-3'}`}>{visible.map(row=><article key={row.id} aria-labelledby={`professional-${row.id}`} className={`min-w-0 space-y-4 rounded-xl border bg-white p-4 ${selected?.id===row.id?'border-primary bg-primary/5':'border-border'}`}>
    <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-x-2 gap-y-4 max-lg:[@media(max-height:600px)]:grid-cols-[auto_minmax(0,1fr)_auto] max-lg:[@media(max-height:600px)]:items-center">{photo(row)}<span className={`justify-self-end rounded-full px-2 py-1 text-xs max-lg:[@media(max-height:600px)]:col-start-3 ${row.is_active===false?'bg-subtle':'bg-primary/10 text-primary'}`}>{t(row.is_active===false?'Inactive':'Active')}</span>
    <div className="col-span-2 max-lg:[@media(max-height:600px)]:col-span-1 max-lg:[@media(max-height:600px)]:col-start-2 max-lg:[@media(max-height:600px)]:row-start-1"><h2 id={`professional-${row.id}`} data-no-translate className="break-words font-serif text-xl">{row.name}</h2><p className="mt-1 text-xs text-text-secondary">{t('Years of experience: {value0}',{value0:formatNumber(Number(row.years_experience||0))})}</p></div></div>
    {specialties(row)}<p className="flex items-center gap-2 text-xs text-primary"><CalendarDays size={15}/>{t(hasHours(row)?'Availability configured':'Availability needs setup')}</p>
    <div className="flex flex-wrap gap-2 border-t border-border pt-3"><button type="button" aria-pressed={selected?.id===row.id} onClick={()=>{focusSelection.current=true;set('person',selected?.id===row.id?'':String(row.id));}} className={`${control} flex-1 text-primary`}>{t('View professional')}</button><Link href={href(row)} className="flex min-h-11 items-center px-2 text-sm font-semibold text-primary">{t('Edit profile')}</Link></div>
   </article>)}</div>
   {selected?<aside ref={detailRef} tabIndex={-1} aria-label={t('Selected professional')} className="order-first scroll-mt-32 lg:order-last h-fit space-y-4 rounded-xl border border-primary/20 bg-white p-4 max-lg:[@media(max-height:600px)]:space-y-2 max-lg:[@media(max-height:600px)]:p-2"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-x-3 gap-y-4 max-lg:[@media(max-height:600px)]:grid-cols-[auto_minmax(0,1fr)_auto] max-lg:[@media(max-height:600px)]:items-center">{photo(selected)}<button aria-label={t('Close professional details')} onClick={()=>set('person','')} className={control+' max-lg:[@media(max-height:600px)]:col-start-3'}>×</button><h2 data-no-translate className="col-span-2 break-words font-serif text-2xl max-lg:[@media(max-height:600px)]:col-span-1 max-lg:[@media(max-height:600px)]:col-start-2 max-lg:[@media(max-height:600px)]:row-start-1 max-lg:[@media(max-height:600px)]:text-xl">{selected.name}</h2></div><p data-no-translate className="whitespace-pre-wrap break-words text-sm">{String(selected.bio||'')}</p>{specialties(selected)}{can("styles")&&can("stylists")?<ProfessionalServiceAssignments key={selected.id} professional={selected} services={services} save={ids=>saveAssignments(selected,ids)}/>:null}<h3 className="font-semibold">{t('Working hours')}</h3>{hours(selected)}{can('availability')?<Link href={scheduleHref(selected)} className="flex min-h-11 items-center text-sm font-semibold text-primary">{t('Edit working hours')}</Link>:null}<Link href={href(selected)} className={`${control} flex items-center justify-center text-primary`}>{t('Edit profile')}</Link></aside>:null}
  </div>:null}
  {!visible.length?<p className="rounded-xl border border-dashed border-border p-6 text-center text-sm"><Users size={24} className="mx-auto mb-3 text-primary"/>{t(stylists.length?'No stylists match these filters.':'Add your first stylist.')}</p>:null}
 </div>;
}
