import { requireAdminPermission } from "@/lib/supabaseAdmin";
import { cleanText, errorResponse } from "@/lib/requestSecurity";

type Setting = Record<string, unknown> & { setting_key:string; value_type:string; validation?:Record<string,unknown>; impact_level:string; version:number; is_secret_status:boolean };

function validateValue(setting:Setting,value:unknown) {
  const rules=setting.validation&&typeof setting.validation==="object"?setting.validation:{};
  if(["number","percentage","currency"].includes(setting.value_type)){
    const number=Number(value);const min=rules.min==null?Number.NEGATIVE_INFINITY:Number(rules.min);const max=rules.max==null?Number.POSITIVE_INFINITY:Number(rules.max);
    if(!Number.isFinite(number)||number<min||number>max||rules.integer===true&&!Number.isInteger(number))throw new Error(`Enter a valid value between ${Number.isFinite(min)?min:"the minimum"} and ${Number.isFinite(max)?max:"the maximum"}.`);return number;
  }
  if(setting.value_type==="boolean")return value===true||value==="true";
  if(["list","reorderable_list"].includes(setting.value_type)){const list=Array.isArray(value)?value:String(value||"").split(/\r?\n|,/).map(item=>item.trim()).filter(Boolean);if(rules.maxItems&&list.length>Number(rules.maxItems))throw new Error(`Use no more than ${rules.maxItems} items.`);return list}
  if(["schedule","template","relationship"].includes(setting.value_type)){if(value&&typeof value==="object")return value;try{return JSON.parse(String(value||"{}"))}catch{throw new Error("This structured setting is not valid. Review the editor values.")}}
  const text=String(value??"").trim();if(rules.minLength&&text.length<Number(rules.minLength))throw new Error("This value is too short.");if(rules.maxLength&&text.length>Number(rules.maxLength))throw new Error("This value is too long.");if(rules.pattern&&!new RegExp(String(rules.pattern)).test(text))throw new Error("This value does not match the required format.");if(Array.isArray(rules.allowed)&&!rules.allowed.includes(text))throw new Error("Choose one of the approved values.");return text;
}

export async function GET(request:Request){try{const{admin}=await requireAdminPermission(request,"settings");const[{data:settings,error},{data:history,error:historyError}]=await Promise.all([admin.from("engine_settings").select("*").order("category").order("sort_order").order("display_name"),admin.from("engine_setting_versions").select("*").order("created_at",{ascending:false}).limit(500)]);if(error)throw error;if(historyError)throw historyError;const environmentStatus=[{key:"supabase",label:"Supabase server access",configured:Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY)},{key:"stripe",label:"Stripe payments",configured:Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_WEBHOOK_SECRET)},{key:"email",label:"Transactional email",configured:Boolean(process.env.RESEND_API_KEY)},{key:"push",label:"Web push",configured:Boolean(process.env.VAPID_PRIVATE_KEY&&process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY)}];return Response.json({settings:settings||[],history:history||[],environmentStatus,environment:process.env.CONTEXT||process.env.NODE_ENV||"development"})}catch(error){console.error("Engine configuration load failed",error);return errorResponse(error,"Unable to load Engine configuration.")}}

export async function PATCH(request:Request){try{const{admin,user}=await requireAdminPermission(request,"settings");const body=await request.json() as Record<string,unknown>;const key=cleanText(body.setting_key,120);const action=cleanText(body.action,30);const{data:setting,error}=await admin.from("engine_settings").select("*").eq("setting_key",key).single();if(error||!setting)throw error||new Error("Setting not found.");if(setting.is_secret_status)throw new Error("Secret configuration is read-only here. Use the deployment environment settings.");const value=action==="rollback"?null:validateValue(setting as Setting,body.value);const reason=cleanText(body.reason,500);const expected=Number(body.expected_version);if(!Number.isInteger(expected)||expected<1)throw new Error("Reload this setting before saving.");const targetVersion=body.target_version==null?null:Number(body.target_version);const result=await admin.rpc("engine_apply_setting",{p_setting_key:key,p_expected_version:expected,p_action:action,p_value:value,p_reason:reason||null,p_target_version:targetVersion,p_confirm_high_impact:body.confirm_high_impact===true,p_actor_user_id:user.id,p_environment:cleanText(body.environment,30)||"all"});if(result.error){if(result.error.message.includes("SETTING_VERSION_CONFLICT"))return Response.json({error:"Another administrator changed this setting. Reload before saving."},{status:409});throw result.error}await admin.from("admin_security_events").insert({actor_user_id:user.id,action:`engine_${action}`,result:"Allowed",details:{setting_key:key,reason:reason||null,impact_level:setting.impact_level,environment:body.environment||"all"}});return Response.json({setting:result.data})}catch(error){console.error("Engine configuration change failed",error);return errorResponse(error,"Unable to save this Engine setting.")}}
