import { requireAdminPermission } from "@/lib/supabaseAdmin";
import { cleanText, errorResponse } from "@/lib/requestSecurity";
import { assertRecentHighRiskVerification } from "@/lib/identityDeletionServer";

type Setting = Record<string, unknown> & { setting_key:string; value_type:string; validation?:Record<string,unknown>; impact_level:string; version:number; is_secret_status:boolean };
const serverEnvironment=()=>{const value=process.env.CONTEXT||process.env.NODE_ENV||"development";return value==="production"?"production":value.includes("preview")||value==="branch-deploy"?"preview":"development"};

function validateValue(setting:Setting,value:unknown) {
  const rules=setting.validation&&typeof setting.validation==="object"?setting.validation:{};
  if(["number","percentage","currency"].includes(setting.value_type)){
    const number=Number(value);const min=rules.min==null?Number.NEGATIVE_INFINITY:Number(rules.min);const max=rules.max==null?Number.POSITIVE_INFINITY:Number(rules.max);
    if(!Number.isFinite(number)||number<min||number>max||rules.integer===true&&!Number.isInteger(number))throw new Error(`Enter a valid value between ${Number.isFinite(min)?min:"the minimum"} and ${Number.isFinite(max)?max:"the maximum"}.`);return number;
  }
  if(setting.value_type==="boolean")return value===true||value==="true";
  if(["list","reorderable_list"].includes(setting.value_type)){const list=Array.isArray(value)?value.map(item=>String(item).trim()).filter(Boolean):String(value||"").split(/\r?\n|,/).map(item=>item.trim()).filter(Boolean);if(rules.maxItems&&list.length>Number(rules.maxItems))throw new Error(`Use no more than ${rules.maxItems} items.`);if(Array.isArray(rules.allowedItems)&&list.some(item=>!(rules.allowedItems as unknown[]).includes(item)))throw new Error("This list contains an item that is not enabled for the current platform market.");return list}
  if(["schedule","template","relationship"].includes(setting.value_type)){if(value&&typeof value==="object")return value;try{return JSON.parse(String(value||"{}"))}catch{throw new Error("This structured setting is not valid. Review the editor values.")}}
  const text=String(value??"").trim();if(rules.minLength&&text.length<Number(rules.minLength))throw new Error("This value is too short.");if(rules.maxLength&&text.length>Number(rules.maxLength))throw new Error("This value is too long.");if(rules.pattern&&!new RegExp(String(rules.pattern)).test(text))throw new Error("This value does not match the required format.");if(Array.isArray(rules.allowed)&&!rules.allowed.includes(text))throw new Error("Choose one of the approved values.");return text;
}

export async function GET(request:Request){try{const{admin}=await requireAdminPermission(request,"settings");const[{data:settings,error},{data:history,error:historyError}]=await Promise.all([admin.from("engine_settings").select("*").order("category").order("sort_order").order("display_name"),admin.from("engine_setting_versions").select("*").order("created_at",{ascending:false}).limit(500)]);if(error)throw error;if(historyError)throw historyError;const environmentStatus=[{key:"supabase",label:"Supabase server access",configured:Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY)},{key:"stripe",label:"Stripe payments",configured:Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_WEBHOOK_SECRET)},{key:"email",label:"Transactional email",configured:Boolean(process.env.RESEND_API_KEY)},{key:"sms",label:"Transactional SMS",configured:Boolean(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_PHONE_NUMBER)},{key:"push",label:"Web push",configured:Boolean(process.env.VAPID_PRIVATE_KEY&&process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY)}];return Response.json({settings:settings||[],history:history||[],environmentStatus,environment:serverEnvironment()})}catch(error){console.error("Engine configuration load failed",error);return errorResponse(error,"Unable to load Engine configuration.")}}

export async function PATCH(request:Request){try{const{admin,user}=await requireAdminPermission(request,"settings");const body=await request.json() as Record<string,unknown>;const key=cleanText(body.setting_key,120);const action=cleanText(body.action,30);const{data:setting,error}=await admin.from("engine_settings").select("*").eq("setting_key",key).single();if(error||!setting)throw error||new Error("Setting not found.");if(setting.is_secret_status)throw new Error("Secret configuration is read-only here. Use the deployment environment settings.");const value=action==="rollback"?null:validateValue(setting as Setting,body.value);const reason=cleanText(body.reason,500);const expected=Number(body.expected_version);if(!Number.isInteger(expected)||expected<1)throw new Error("Reload this setting before saving.");const targetVersion=body.target_version==null?null:Number(body.target_version);const environment=serverEnvironment();if(setting.environment!=="all"&&setting.environment!==environment)throw new Error(`This setting belongs to the ${setting.environment} environment.`);const result=await admin.rpc("engine_apply_setting",{p_setting_key:key,p_expected_version:expected,p_action:action,p_value:value,p_reason:reason||null,p_target_version:targetVersion,p_confirm_high_impact:body.confirm_high_impact===true,p_actor_user_id:user.id,p_environment:environment});if(result.error){if(result.error.message.includes("SETTING_VERSION_CONFLICT"))return Response.json({error:"Another administrator changed this setting. Reload before saving."},{status:409});throw result.error}await admin.from("admin_security_events").insert({actor_user_id:user.id,action:`engine_${action}`,result:"Allowed",details:{setting_key:key,reason:reason||null,impact_level:setting.impact_level,environment}});return Response.json({setting:result.data})}catch(error){console.error("Engine configuration change failed",error);return errorResponse(error,"Unable to save this Engine setting.")}}

export async function POST(request:Request){try{const{admin,user}=await requireAdminPermission(request,"settings");const body=await request.json() as Record<string,unknown>;const action=cleanText(body.action,40);const environment=serverEnvironment();
  if(action==="preview_import"||action==="import_drafts"){const payload=body.payload&&typeof body.payload==="object"?body.payload as Record<string,unknown>:{};if(payload.schema!=="girlz-culture-engine-export/v1")throw new Error("Choose a Girlz Culture Engine v1 export.");if(payload.environment!==environment)throw new Error(`This export belongs to the ${String(payload.environment||"unknown")} environment, not ${environment}.`);const incoming=Array.isArray(payload.settings)?payload.settings.slice(0,101):[];if(!incoming.length||incoming.length>100)throw new Error("Choose a valid Engine export containing 1 to 100 non-secret settings.");const keys=incoming.map(item=>cleanText((item as Record<string,unknown>).setting_key,120));const duplicateKeys=keys.filter((key,index)=>key&&keys.indexOf(key)!==index);const{data:stored,error}=await admin.from("engine_settings").select("*").in("setting_key",keys);if(error)throw error;const index=new Map((stored||[]).map(item=>[item.setting_key,item]));const errors:string[]=[...new Set(duplicateKeys)].map(key=>`${key}: duplicate setting in import`);const entries=incoming.flatMap(raw=>{const item=raw as Record<string,unknown>;const key=cleanText(item.setting_key,120);if(duplicateKeys.includes(key))return[];const setting=index.get(key);if(!setting){errors.push(`${key||"Unknown key"}: setting not found`);return[];}if(setting.is_secret_status){errors.push(`${key}: secret status cannot be imported`);return[];}if(setting.environment!=="all"&&setting.environment!==environment){errors.push(`${key}: belongs to ${setting.environment}`);return[];}try{const value=validateValue(setting as Setting,item.value);return[{setting_key:key,value,expected_version:Number(setting.version),current_draft:setting.draft_value,current_published:setting.published_value,impact_level:setting.impact_level,affected_surfaces:Array.isArray(setting.affected_surfaces)?setting.affected_surfaces:[]}]}catch(validationError){errors.push(`${key}: ${validationError instanceof Error?validationError.message:"invalid value"}`);return[];}});const preview={environment,entries,errors,changed:entries.filter(entry=>JSON.stringify(entry.value)!==JSON.stringify(entry.current_draft)).length};if(action==="preview_import")return Response.json({preview});if(errors.length)throw new Error("Resolve every import validation error before saving drafts.");await assertRecentHighRiskVerification(admin,user.id,"admin");const confirmation=cleanText(body.confirmation,100);const result=await admin.rpc("engine_import_drafts",{p_entries:entries.map(({setting_key,value,expected_version})=>({setting_key,value,expected_version})),p_actor_user_id:user.id,p_environment:environment,p_confirmation:confirmation});if(result.error)throw result.error;await admin.from("admin_security_events").insert({actor_user_id:user.id,action:"engine_import_drafts",result:"Allowed",details:{environment,count:entries.length}});return Response.json({result:result.data});}
  if(action==="emergency_revert"){await assertRecentHighRiskVerification(admin,user.id,"admin");const key=cleanText(body.setting_key,120);const reason=cleanText(body.reason,500);const expected=Number(body.expected_version);const confirmation=cleanText(body.confirmation,180);const result=await admin.rpc("engine_emergency_revert_setting",{p_setting_key:key,p_expected_version:expected,p_actor_user_id:user.id,p_reason:reason,p_confirmation:confirmation,p_environment:environment});if(result.error){if(result.error.message.includes("SETTING_VERSION_CONFLICT"))return Response.json({error:"Another administrator changed this setting. Reload before recovery."},{status:409});throw result.error;}await admin.from("admin_security_events").insert({actor_user_id:user.id,action:"engine_emergency_revert",result:"Allowed",details:{setting_key:key,environment,reason}});return Response.json({setting:result.data});}
  throw new Error("Choose a supported Engine governance action.");
}catch(error){console.error("Engine governance action failed",error);return errorResponse(error,"The Engine governance action could not be completed.");}}
