"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Eye, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { adminSupabase as supabase } from "@/lib/supabase";
import { EMAIL_PATTERN, isValidEmail, normalizeEmail } from "@/lib/validation";

export default function AdminLogin() {
  const router=useRouter();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [show,setShow]=useState(false);const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setMessage("");if(!isValidEmail(email)){setMessage("Please enter a valid email address (name@example.com).");return;}const validEmail=normalizeEmail(email);setLoading(true);const {data,error}=await supabase.auth.signInWithPassword({email:validEmail,password});if(error){console.info("Admin login",{email:validEmail,foundInAdminUsers:false,result:"authentication_failed"});setMessage(error.message);setLoading(false);return;}const response=await fetch("/api/admin/verify",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`}});const result=await response.json();console.info("Admin login",{email:result.email||validEmail,foundInAdminUsers:Boolean(result.isAdmin),result:result.isAdmin?"allowed":"denied"});setLoading(false);if(!result.isAdmin){await supabase.auth.signOut();setMessage("This account does not have admin access");return;}router.replace("/admin");router.refresh();}
  return <form onSubmit={submit} className="space-y-5"><div><label className="mb-2 block text-sm font-semibold">Email</label><div className="flex items-center gap-3 rounded-[9px] border border-plum/15 px-4 py-3"><Mail size={18}/><input required type="email" pattern={EMAIL_PATTERN} title="Enter a valid email address such as name@example.com" value={email} onChange={event=>setEmail(event.target.value)} placeholder="admin@girlzculture.com" className="w-full bg-transparent outline-none"/></div></div><div><label className="mb-2 block text-sm font-semibold">Password</label><div className="flex items-center gap-3 rounded-[9px] border border-plum/15 px-4 py-3"><LockKeyhole size={18}/><input required type={show?"text":"password"} value={password} onChange={event=>setPassword(event.target.value)} className="w-full bg-transparent outline-none"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}><Eye size={18}/></button></div></div><Link href="/forgot-password" className="block text-right text-sm font-semibold text-magenta">Forgot password?</Link>{message?<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>:null}<button disabled={loading} className="w-full rounded-[9px] bg-magenta py-3.5 font-bold text-white">{loading?"Verifying access…":"Log in to Admin"}</button><p className="flex items-center justify-center gap-2 text-xs text-ink/50"><ShieldCheck size={15}/>Internal Girlz Culture team access only</p></form>;
}
