"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Building2, LockKeyhole } from "lucide-react";
import { supabase } from "@/lib/supabase";

const states=["New York","New Jersey","Delaware","Texas","Georgia","Florida","California","Maryland","Other"];
const initial={business_name:"",owner_name:"",business_email:"",phone:"",street_address:"",city:"",state:"New York",zip_code:"",neighborhood:"",business_type:"Braiding Studio",referral_source:""};
export default function SalonApplication(){const router=useRouter();const [form,setForm]=useState(initial);const [salonId,setSalonId]=useState("");const [userId,setUserId]=useState("");const [checks,setChecks]=useState([false,false,false]);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(!data.user){router.replace("/salon/login");return;}setUserId(data.user.id);setForm(f=>({...f,business_email:data.user?.email||"",phone:String(data.user?.user_metadata?.phone||"")}));const {data:salon}=await supabase.from("salons").select("id").eq("user_id",data.user.id).maybeSingle();if(salon)setSalonId(salon.id);});},[router]);
  function update(key:string,value:string){setForm(current=>({...current,[key]:value}));}
  async function submit(e:FormEvent){e.preventDefault();if(!checks.every(Boolean)){setMessage("Please accept all three confirmations.");return;}if(!salonId||!userId){setMessage("Your pending salon record is not ready. Please sign in again.");return;}setSaving(true);const slug=form.business_name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");const {error:salonError}=await supabase.from("salons").update({name:form.business_name,owner_name:form.owner_name,email:form.business_email,phone:form.phone,address_street:form.street_address,address_city:form.city,address_state:form.state,address_zip:form.zip_code,neighborhood:form.neighborhood,business_type:form.business_type,application_state:form.state,slug,status:"Pending"}).eq("id",salonId);const {error}=await supabase.from("salon_applications").upsert({...form,salon_id:salonId,user_id:userId,consent_authorized:checks[0],consent_terms:checks[1],consent_photos:checks[2],status:"Pending"},{onConflict:"salon_id"});setSaving(false);if(error||salonError){setMessage(error?.message||salonError?.message||"Unable to submit");return;}router.push("/salon/application-submitted");}
  return <form onSubmit={submit} className="rounded-[18px] border border-plum/10 bg-white/85 p-5 shadow-[0_20px_60px_rgba(26,18,32,.08)] sm:p-8"><div className="mb-7 flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-[15px] bg-blush text-magenta"><Building2 size={34}/></span><div><h1 className="font-serif text-4xl font-semibold text-plum">Salon Application</h1><p className="mt-1 text-sm text-ink/65">Tell us about your business so we can help you grow with Girlz Culture.</p></div></div><div className="grid gap-4 sm:grid-cols-2">
    {[["business_name","Business / Salon Name"],["owner_name","Owner / Contact Full Name"],["business_email","Business Email"],["phone","Phone Number"]].map(([key,label])=><Input key={key} label={label} value={(form as Record<string,string>)[key]} onChange={v=>update(key,v)}/>)}
    <div className="sm:col-span-2"><Input label="Street Address" value={form.street_address} onChange={v=>update("street_address",v)}/></div><Input label="City" value={form.city} onChange={v=>update("city",v)}/><label className="block"><span className="mb-2 block text-xs font-bold">State *</span><select value={form.state} onChange={e=>update("state",e.target.value)} className="w-full rounded-[8px] border border-plum/15 bg-white px-3 py-3 text-sm">{states.map(s=><option key={s}>{s}</option>)}</select></label><Input label="Zip Code" value={form.zip_code} onChange={v=>update("zip_code",v)}/><Input label="Neighborhood" value={form.neighborhood} onChange={v=>update("neighborhood",v)} required={false}/><label><span className="mb-2 block text-xs font-bold">Type of Business *</span><select value={form.business_type} onChange={e=>update("business_type",e.target.value)} className="w-full rounded-[8px] border border-plum/15 bg-white px-3 py-3 text-sm">{["Hair Salon","Beauty Shop","Barber Shop","Braiding Studio","Other"].map(s=><option key={s}>{s}</option>)}</select></label><div className="sm:col-span-2"><Input label="How did you hear about us? (Optional)" value={form.referral_source} onChange={v=>update("referral_source",v)} required={false}/></div></div>
    <div className="mt-6 space-y-3">{["I confirm the information is accurate and I’m authorized to represent this business.","I agree to the Terms of Service and Partner Agreement.","I confirm I have permission and rights for any photos I upload."].map((label,i)=><label key={label} className="flex gap-3 text-sm"><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(c=>c.map((v,j)=>j===i?e.target.checked:v))} className="accent-magenta"/>{label}</label>)}</div>{message?<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>:null}<button disabled={saving} className="mt-6 w-full rounded-[8px] bg-magenta py-3.5 font-bold text-white">{saving?"Submitting…":"Submit Application"}</button><p className="mt-4 flex items-center justify-center gap-2 text-[11px] text-ink/50"><LockKeyhole size={13}/>Your information is secure and will never be shared.</p></form>}
function Input({label,value,onChange,required=true}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label className="block"><span className="mb-2 block text-xs font-bold">{label}{required?" *":""}</span><input required={required} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-[8px] border border-plum/15 bg-white px-3 py-3 text-sm"/></label>}
