"use client";

import Link from "next/link";
import { useState } from "react";
import { CalendarDays, Home, Scissors, Users, ArrowLeft } from "lucide-react";
import WorkspaceCalendar from "@/components/dashboard/WorkspaceCalendar";

// Deliberately isolated from real business records, financial ledgers and APIs.
// These sample values must never be seeded into Isha Five Stars or a real account.
const services = [{ name: "Knotless braids", category: "Hair & braiding", duration: "4 hours", price: 180 }, { name: "Silk press", category: "Hair styling", duration: "90 minutes", price: 85 }, { name: "Gel manicure", category: "Nails", duration: "45 minutes", price: 45 }];
const appointments = [{ id: "demo-1", start: "2026-09-15T14:00:00-04:00", title: "Example client A", subtitle: "Knotless braids · Maya", status: "Confirmed" }, { id: "demo-2", start: "2026-09-16T10:30:00-04:00", title: "Example client B", subtitle: "Silk press · Alex", status: "Confirmed" }, { id: "demo-3", start: "2026-09-17T13:00:00-04:00", title: "Example client C", subtitle: "Gel manicure · Sam", status: "Confirmed" }];
const destinations = [["overview", "Overview", Home], ["calendar", "Calendar", CalendarDays], ["services", "Services & pricing", Scissors], ["team", "Team", Users]] as const;

export default function DemoBusinessWorkspace() {
  const [tab, setTab] = useState("overview");
  return <div className="gc-dashboard min-h-screen bg-white text-ink lg:grid lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="gc-workspace-sidebar p-5"><Link href="/site-access" className="flex min-h-11 items-center gap-2 text-sm font-bold"><ArrowLeft size={18}/>Marketplace demo</Link><h1 className="mt-5 text-xl">Girlz Culture<br/>Demo Studio</h1><p className="mt-2 text-sm">Sample workspace only</p><nav className="mt-6 flex flex-wrap gap-2 lg:flex-col" aria-label="Demonstration pages">{destinations.map(([id, label, Icon]) => <button key={id} type="button" aria-pressed={tab === id} onClick={() => setTab(id)} className={`flex min-h-11 items-center gap-3 rounded-lg px-3 text-left text-sm font-semibold ${tab === id ? "bg-magenta text-white" : "text-white"}`}><Icon size={18}/>{label}</button>)}</nav><Link href="/salon/login" className="mt-8 inline-flex min-h-11 items-center text-sm font-bold underline">Open a real business account</Link></aside>
  <main className="min-w-0 space-y-6 p-4 sm:p-8"><div role="note" className="rounded-xl border border-amber/40 bg-amber/10 p-4 text-sm"><b>Demonstration data — September 2026 scenario.</b> All figures, clients and staff on this page are fictional. This page is read-only and creates no bookings, payments, reviews or customer accounts.</div><header><p className="text-sm font-semibold text-teal">Business workspace</p><h2 className="mt-2 text-3xl">{destinations.find(([id]) => id === tab)?.[1]}</h2><p className="mt-2 text-sm">A sample for business demonstrations. Real dashboards show only their own recorded activity.</p></header>
    {tab === "overview" ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Sample appointments", "24"], ["Sample completed booking value", "$2,840"], ["Sample returning clients", "8"], ["Sample services", "3"]].map(([label,value]) => <article className="gc-stat" key={label}><p>{label}</p><strong>{value}</strong></article>)}</div><div className="grid gap-5 xl:grid-cols-2"><section className="gc-panel"><h3 className="text-xl">Sample weekly appointment activity</h3><p className="mt-1 text-sm">Fictional counts for demonstration, not a sales forecast.</p><div className="mt-5 space-y-3">{[["Mon", 5], ["Tue", 4], ["Wed", 6], ["Thu", 3], ["Fri", 6]].map(([day,count]) => <div key={day} className="grid grid-cols-[36px_1fr_24px] items-center gap-3 text-sm"><span>{day}</span><div className="h-6 rounded bg-teal/10"><div className="h-full rounded bg-teal" style={{width: `${Number(count)/6*100}%`}}/></div><b>{count}</b></div>)}</div></section><section className="gc-panel"><h3 className="text-xl">A connected business workspace</h3><p className="mt-3 text-sm leading-7">Browse the calendar, sample services and team using the navigation. The authenticated GC Assistant uses the business’s authorized records and published Girlz Culture knowledge. It requires a real business login; this sample does not simulate an AI reply or perform an action.</p><Link href="/salon/login" className="mt-4 inline-flex min-h-11 items-center rounded-lg bg-teal px-5 text-sm font-bold text-white">Business login</Link></section></div></> : null}
    {tab === "calendar" || tab === "overview" ? <WorkspaceCalendar title="Sample appointment calendar" timeZone="America/New_York" initialDate="2026-09-15" events={appointments}/> : null}
    {tab === "services" ? <section className="gc-panel"><h3 className="mb-4 text-xl">Sample service menu</h3><div className="gc-table-scroll" role="region" aria-label="Sample services" tabIndex={0}><table><thead><tr><th>Service</th><th>Category</th><th>Duration</th><th>Sample price</th></tr></thead><tbody>{services.map(service => <tr key={service.name}><td><b>{service.name}</b></td><td>{service.category}</td><td>{service.duration}</td><td>${service.price}</td></tr>)}</tbody></table></div><p className="mt-4 text-sm">In a real account, businesses can import their own Excel headings, map columns, review every row and save their service order.</p></section> : null}
    {tab === "team" ? <section className="gc-panel"><h3 className="mb-4 text-xl">Sample professionals</h3><div className="grid gap-4 sm:grid-cols-3">{[["Maya", "Hair & braiding"], ["Alex", "Hair styling"], ["Sam", "Nails"]].map(([name,role]) => <article key={name} className="rounded-xl border border-teal/20 p-5"><span className="grid h-12 w-12 place-items-center rounded-full bg-teal/10 text-lg font-bold">{name[0]}</span><h4 className="mt-3 text-lg">{name}</h4><p className="mt-1 text-sm">{role}</p><p className="mt-3 text-xs">Fictional demonstration professional</p></article>)}</div></section> : null}
  </main></div>;
}
