import { cleanText, errorResponse } from "@/lib/requestSecurity";
import { requireAdmin } from "@/lib/supabaseAdmin";
import { assertRecentHighRiskVerification, identityDependencySummary, prepareAndDeleteIdentity, type DeletionRole } from "@/lib/identityDeletionServer";

const sources={customer:{table:"customers",email:"email",name:"name",user:"id"},salon_owner:{table:"salons",email:"email",name:"name",user:"user_id"},salon_team:{table:"salon_team_members",email:"email",name:"name",user:"user_id"},admin:{table:"admin_users",email:"email",name:"name",user:"user_id"}} as const;
const roles=Object.keys(sources) as DeletionRole[];
async function superContext(request:Request){const context=await requireAdmin(request);if(!(context.adminUser as{is_super_admin?:boolean}).is_super_admin)throw new Error("Only a Super Admin can permanently remove identities.");return context}
async function target(admin:Awaited<ReturnType<typeof requireAdmin>>["admin"],role:DeletionRole,id:string){const source=sources[role];const{data,error}=await admin.from(source.table).select("*").eq("id",id).maybeSingle();if(error)throw error;if(!data)throw new Error("Identity record not found.");return{id:String(data.id),userId:String(data[source.user]||data.id||""),email:String(data[source.email]||"").trim().toLowerCase(),name:String(data[source.name]||data[source.email]||"Account"),status:String(data.status||"Active"),isSuperAdmin:Boolean(data.is_super_admin)};}

export async function GET(request:Request){
  try{const{admin}=await superContext(request);const url=new URL(request.url);const role=cleanText(url.searchParams.get("role"),30) as DeletionRole;const id=cleanText(url.searchParams.get("id"),60);if(role&&roles.includes(role)&&id){const item=await target(admin,role,id);return Response.json({target:item,dependencies:await identityDependencySummary(admin,item.userId,role,id),eligible:role!=="salon_owner",blocker:role==="salon_owner"?"Transfer or offboard this salon before owner identity removal.":null});}
    const result:Record<string,unknown[]>={};for(const itemRole of roles){const source=sources[itemRole];const{data,error}=await admin.from(source.table).select("*").order(source.email,{ascending:true}).limit(250);if(error){console.warn("Identity deletion source unavailable",{role:itemRole,code:error.code});result[itemRole]=[];continue;}result[itemRole]=(data||[]).map(row=>({id:String(row.id),email:String(row[source.email]||""),name:String(row[source.name]||row[source.email]||"Account"),status:String(row.status||"Active"),user_id:String(row[source.user]||row.id||"")}));}return Response.json({roles:result});
  }catch(error){return errorResponse(error,"Unable to load identity deletion.");}
}

export async function POST(request:Request){
  try{const{admin,user}=await superContext(request);await assertRecentHighRiskVerification(admin,user.id,"admin");const body=await request.json() as Record<string,unknown>;const role=cleanText(body.role,30) as DeletionRole;const id=cleanText(body.id,60);const reason=cleanText(body.reason,500);if(!roles.includes(role))return Response.json({error:"Choose an identity role."},{status:400});const item=await target(admin,role,id);if(!item.userId)throw new Error("This legacy record has no canonical authentication identity. Review it in the conflict queue.");if(item.userId===user.id)throw new Error("You cannot remove the account currently performing this action.");if(cleanText(body.confirmation,320).toLowerCase()!==item.email)throw new Error(`Type ${item.email} exactly to confirm.`);if(reason.length<8)throw new Error("Enter a reason of at least 8 characters.");if(role==="salon_owner")throw new Error("Transfer or offboard the salon before removing its owner identity.");const dependencies=await identityDependencySummary(admin,item.userId,role,id);const result=await prepareAndDeleteIdentity(admin,{targetUserId:item.userId,role,targetRecordId:id,actorUserId:user.id,reason,dependencies});return Response.json({ok:true,...result,message:`${item.email} was removed. Its normalized email is available for a new account and old access cannot be inherited.`});
  }catch(error){console.error("Protected identity deletion failed",error);return errorResponse(error,"The identity could not be removed safely.");}
}
