import { Quote, Star } from "lucide-react";
import { PublicFooter, PublicHeader } from "@/components/site/PublicChrome";
import { getContentPage } from "@/lib/content";

export const dynamic = "force-dynamic";
export default async function TestimonialsPage() {
  const page = await getContentPage("testimonials", { slug: "testimonials", title: "Testimonials", hero_title: "Loved by the Girlz Culture community.", hero_subtitle: "Real clients. Real appointments. Real results.", sections: [{ title: "Jasmine P. - Brooklyn, NY", body: "The booking was simple, the price was clear, and my knotless braids came out beautifully." }] });
  return <main className="min-h-screen bg-cream text-ink"><PublicHeader/><section className="relative overflow-hidden bg-plum px-5 py-16 text-center text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(214,24,107,.35),transparent_30%),radial-gradient(circle_at_85%_80%,rgba(224,163,78,.22),transparent_28%)]"/><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-amber">{page.eyebrow || "Real clients. Real results."}</p><h1 className="mx-auto mt-3 max-w-4xl font-serif text-5xl leading-[.95] sm:text-6xl">{page.hero_title || page.title}</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-white/70">{page.hero_subtitle}</p></div></section><section className="mx-auto grid w-full max-w-[1320px] gap-5 px-5 py-12 sm:px-8 md:grid-cols-2 lg:grid-cols-3 lg:py-16">{(page.sections || []).map((testimonial, index)=><article key={`${testimonial.title}-${index}`} className="flex min-h-[280px] flex-col rounded-3xl border border-plum/10 bg-white p-6 shadow-[0_14px_45px_rgba(26,18,32,.06)]"><Quote className="text-magenta" size={30}/><div className="mt-5 flex gap-1 text-amber">{Array.from({length:5}).map((_,i)=><Star key={i} size={16} fill="currentColor"/>)}</div><blockquote className="mt-4 flex-1 font-serif text-2xl leading-9 text-plum">“{testimonial.body}”</blockquote><p className="mt-6 border-t border-plum/10 pt-4 text-sm font-bold text-ink">{testimonial.title}</p></article>)}</section><PublicFooter/></main>;
}
