-- Final pilot publication correction:
--   * one config-aware publication diagnostic governs lifecycle, profile RLS,
--     discovery, and explicit admin activation;
--   * public profile visibility is distinct from current booking availability;
--   * pilot overrides are explicit, authorized, idempotent, and immutably
--     audited without creating or changing any financial record;
--   * stylist profile URLs use stable, collision-safe slugs.
begin;

alter table public.stylists
  add column if not exists slug text;

create or replace function public.stylist_slugify(value text)
returns text
language sql
immutable
parallel safe
set search_path = public
as $$
  select trim(
    both '-'
    from regexp_replace(
      regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '-', 'g'),
      '-+',
      '-',
      'g'
    )
  );
$$;

create or replace function public.generate_unique_stylist_slug(
  p_salon_id uuid,
  p_stylist_id uuid,
  p_name text
)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_base text;
  v_candidate text;
  v_suffix integer := 1;
begin
  v_base := left(nullif(public.stylist_slugify(p_name), ''), 72);
  if v_base is null then
    v_base := 'stylist';
  end if;
  v_candidate := v_base;

  while exists (
    select 1
    from public.stylists stylist
    where stylist.salon_id = p_salon_id
      and stylist.id is distinct from p_stylist_id
      and stylist.slug = v_candidate
  ) loop
    v_suffix := v_suffix + 1;
    v_candidate := left(v_base, greatest(1, 72 - length(v_suffix::text) - 1))
      || '-' || v_suffix::text;
  end loop;

  return v_candidate;
end;
$$;

do $$
declare
  v_stylist record;
begin
  for v_stylist in
    select id, salon_id, name
    from public.stylists
    where nullif(trim(coalesce(slug, '')), '') is null
    order by salon_id, created_at, id
  loop
    perform pg_advisory_xact_lock(
      hashtextextended('stylist-slug:' || v_stylist.salon_id::text, 0)
    );
    update public.stylists
    set slug = public.generate_unique_stylist_slug(
      v_stylist.salon_id,
      v_stylist.id,
      v_stylist.name
    )
    where id = v_stylist.id;
  end loop;
end
$$;

alter table public.stylists
  alter column slug set not null;

alter table public.stylists
  drop constraint if exists stylists_slug_format_check;
alter table public.stylists
  add constraint stylists_slug_format_check
  check (
    length(slug) between 1 and 72
    and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  );

create unique index if not exists stylists_salon_slug_unique_idx
  on public.stylists(salon_id, slug);

create or replace function public.assign_stable_stylist_slug()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.slug is distinct from old.slug then
    raise exception 'Published stylist URLs are stable and cannot be changed.'
      using errcode = '22023';
  end if;

  -- The public identifier is always generated by the database. Ignoring a
  -- caller-supplied INSERT value prevents malformed or path-like slugs from
  -- bypassing the canonical URL contract through a direct API insert.
  if tg_op = 'INSERT' then
    perform pg_advisory_xact_lock(
      hashtextextended('stylist-slug:' || new.salon_id::text, 0)
    );
    new.slug := public.generate_unique_stylist_slug(
      new.salon_id,
      new.id,
      new.name
    );
  end if;
  return new;
end;
$$;

drop trigger if exists stylists_assign_stable_slug on public.stylists;
create trigger stylists_assign_stable_slug
before insert or update of slug on public.stylists
for each row execute function public.assign_stable_stylist_slug();

revoke all on function public.stylist_slugify(text)
  from public, anon, authenticated;
revoke all on function public.generate_unique_stylist_slug(uuid, uuid, text)
  from public, anon, authenticated;
revoke all on function public.assign_stable_stylist_slug()
  from public, anon, authenticated;

create table if not exists public.salon_publication_overrides (
  id uuid primary key default gen_random_uuid(),
  salon_id uuid not null unique references public.salons(id) on delete restrict,
  application_id uuid not null references public.salon_applications(id) on delete restrict,
  is_active boolean not null default true,
  reason text not null check (length(trim(reason)) >= 12),
  overridden_gates jsonb not null default '[]'::jsonb
    check (jsonb_typeof(overridden_gates) = 'array'),
  gate_snapshot jsonb not null default '{}'::jsonb
    check (jsonb_typeof(gate_snapshot) = 'object'),
  granted_by uuid references auth.users(id) on delete set null,
  granted_at timestamptz not null default now(),
  revoked_by uuid references auth.users(id) on delete set null,
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  check (
    (is_active and revoked_at is null)
    or (not is_active and revoked_at is not null)
  )
);

create table if not exists public.salon_publication_override_audit (
  id uuid primary key default gen_random_uuid(),
  override_id uuid not null references public.salon_publication_overrides(id) on delete restrict,
  salon_id uuid not null references public.salons(id) on delete restrict,
  application_id uuid not null references public.salon_applications(id) on delete restrict,
  action text not null check (action in ('Granted', 'Updated', 'Revoked')),
  reason text not null,
  overridden_gates jsonb not null default '[]'::jsonb
    check (jsonb_typeof(overridden_gates) = 'array'),
  gate_snapshot jsonb not null default '{}'::jsonb
    check (jsonb_typeof(gate_snapshot) = 'object'),
  acting_admin_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists salon_publication_override_audit_salon_idx
  on public.salon_publication_override_audit(salon_id, created_at desc);

alter table public.salon_publication_overrides enable row level security;
alter table public.salon_publication_override_audit enable row level security;
revoke all on public.salon_publication_overrides
  from public, anon, authenticated;
revoke all on public.salon_publication_override_audit
  from public, anon, authenticated;
grant all on public.salon_publication_overrides to service_role;
grant all on public.salon_publication_override_audit to service_role;

create or replace function public.prevent_publication_override_audit_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Publication override audit records are immutable.';
end;
$$;

drop trigger if exists salon_publication_override_audit_immutable
  on public.salon_publication_override_audit;
create trigger salon_publication_override_audit_immutable
before update or delete on public.salon_publication_override_audit
for each row execute function public.prevent_publication_override_audit_mutation();

-- The publication diagnostic is authoritative. It uses the configurable
-- lifecycle gates, corrects subscription truth from the subscriptions table,
-- adds the public-slug gate, and then applies only the exact gates recorded by
-- an active pilot override. Raw and effective completion remain separately
-- visible so an override can never masquerade as a completed requirement.
create or replace function public.salon_publication_diagnostic(p_salon_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_base jsonb;
  v_salon public.salons%rowtype;
  v_override public.salon_publication_overrides%rowtype;
  v_checks jsonb;
  v_key text;
  v_check jsonb;
  v_required boolean;
  v_passed boolean;
  v_overridden boolean;
  v_required_count integer := 0;
  v_passed_count integer := 0;
  v_effective_passed_count integer := 0;
  v_raw_complete boolean := true;
  v_effective_complete boolean := true;
  v_raw_missing_keys jsonb := '[]'::jsonb;
  v_raw_missing_labels jsonb := '[]'::jsonb;
  v_effective_missing_keys jsonb := '[]'::jsonb;
  v_effective_missing_labels jsonb := '[]'::jsonb;
  v_slug_ready boolean;
  v_profile_public boolean;
  v_discovery_eligible boolean;
  v_closed_today boolean;
begin
  select *
  into v_salon
  from public.salons
  where id = p_salon_id;
  if not found then
    raise exception 'Salon not found.';
  end if;

  select *
  into v_override
  from public.salon_publication_overrides publication_override
  where publication_override.salon_id = p_salon_id
    and publication_override.is_active = true;

  v_base := public.salon_lifecycle_diagnostic(p_salon_id);
  v_slug_ready :=
    nullif(trim(coalesce(v_salon.slug, '')), '') is not null
    and v_salon.slug !~ '^pending-';

  v_checks := coalesce(v_base -> 'checks', '{}'::jsonb)
    || jsonb_build_object(
      'public_slug',
      jsonb_build_object(
        'label', 'Public salon URL',
        'required', true,
        'passed', v_slug_ready,
        'action', '/salon/dashboard/my-page'
      )
    );

  -- The authoritative subscription relation, not its asynchronous mirror,
  -- controls publication.
  if v_checks ? 'active_subscription' then
    v_checks := jsonb_set(
      v_checks,
      '{active_subscription,passed}',
      to_jsonb(public.has_active_subscription(p_salon_id)),
      true
    );
  end if;

  for v_key, v_check in
    select item.key, item.value
    from jsonb_each(v_checks) item
  loop
    v_required := coalesce((v_check ->> 'required')::boolean, false);
    v_passed := coalesce((v_check ->> 'passed')::boolean, false);
    v_overridden :=
      v_required
      and not v_passed
      and v_override.id is not null
      and v_override.overridden_gates ? v_key;

    v_checks := jsonb_set(
      v_checks,
      array[v_key],
      v_check || jsonb_build_object(
        'overridden', v_overridden,
        'effective_passed', v_passed or v_overridden
      ),
      true
    );

    if v_required then
      v_required_count := v_required_count + 1;
      if v_passed then
        v_passed_count := v_passed_count + 1;
      else
        v_raw_complete := false;
        v_raw_missing_keys := v_raw_missing_keys || jsonb_build_array(v_key);
        v_raw_missing_labels := v_raw_missing_labels
          || jsonb_build_array(coalesce(v_check ->> 'label', v_key));
      end if;

      if v_passed or v_overridden then
        v_effective_passed_count := v_effective_passed_count + 1;
      else
        v_effective_complete := false;
        v_effective_missing_keys :=
          v_effective_missing_keys || jsonb_build_array(v_key);
        v_effective_missing_labels :=
          v_effective_missing_labels
          || jsonb_build_array(coalesce(v_check ->> 'label', v_key));
      end if;
    end if;
  end loop;

  v_profile_public :=
    v_effective_complete
    and v_salon.status = 'Active'
    and v_salon.is_discoverable = true
    and v_salon.owner_unpublished_at is null;
  v_closed_today :=
    coalesce(v_salon.is_closed_override, false) = true
    and v_salon.closed_override_date = (
      now() at time zone coalesce(
        nullif(v_salon.time_zone, ''),
        'America/New_York'
      )
    )::date;
  v_discovery_eligible :=
    v_profile_public
    and coalesce(v_salon.accepting_bookings, true) = true
    and not v_closed_today;

  return v_base || jsonb_build_object(
    'checks', v_checks,
    'valid_public_slug', v_slug_ready,
    'actual_required_complete', v_raw_complete,
    'all_required_complete', v_effective_complete,
    'required_count', v_required_count,
    'passed_count', v_passed_count,
    'effective_passed_count', v_effective_passed_count,
    'progress',
      case
        when v_required_count = 0 then 100
        else round(
          (v_passed_count::numeric / v_required_count::numeric) * 100
        )::integer
      end,
    'missing_gate_keys', v_raw_missing_keys,
    'missing_gate_labels', v_raw_missing_labels,
    'effective_missing_gate_keys', v_effective_missing_keys,
    'effective_missing_gate_labels', v_effective_missing_labels,
    'override_active', v_override.id is not null,
    'override_id', v_override.id,
    'overridden_gates',
      coalesce(v_override.overridden_gates, '[]'::jsonb),
    'override_reason', v_override.reason,
    'public_eligible',
      v_effective_complete
      and v_salon.status not in ('Suspended', 'Offboarded', 'New', 'Pending')
      and v_salon.owner_unpublished_at is null,
    'profile_public', v_profile_public,
    'discovery_eligible', v_discovery_eligible,
    'application_state',
      case
        when coalesce(
          (v_checks #>> '{application_approved,effective_passed}')::boolean,
          false
        ) then 'Approved'
        else 'Awaiting approval'
      end,
    'setup_state',
      case
        when v_raw_complete then 'Complete'
        when v_override.id is not null and v_effective_complete
          then 'Pilot override'
        else 'Needs setup'
      end,
    'subscription_state',
      case
        when public.has_active_subscription(p_salon_id) then 'active'
        else 'inactive'
      end,
    'address_state',
      case
        when v_salon.geocode_status = 'success'
          and not v_salon.address_needs_review then 'Ready'
        else 'Needs review'
      end,
    'marketplace_state', v_salon.status,
    'publication_state',
      case
        when v_salon.status = 'Suspended' then 'Suspended'
        when v_salon.status = 'Offboarded' then 'Offboarded'
        when v_salon.owner_unpublished_at is not null then 'Owner unpublished'
        when v_profile_public then 'Published'
        when v_override.id is not null and not v_effective_complete
          then 'Override needs review'
        else 'Not published'
      end,
    'accepting_bookings', v_salon.accepting_bookings,
    'closed_today', v_closed_today,
    'owner_unpublished_at', v_salon.owner_unpublished_at,
    'owner_unpublished_reason', v_salon.owner_unpublished_reason,
    'closure_requested_at', v_salon.closure_requested_at
  );
end;
$$;

-- Compatibility helper now follows the configurable, authoritative diagnostic
-- instead of the removed hard-coded photo/stylist gate list.
create or replace function public.salon_setup_complete(target_salon_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select coalesce(
    (
      public.salon_publication_diagnostic(target_salon_id)
      ->> 'actual_required_complete'
    )::boolean,
    false
  );
$$;

create or replace function public.is_salon_profile_public(
  target_salon_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select coalesce(
    (
      public.salon_publication_diagnostic(target_salon_id)
      ->> 'profile_public'
    )::boolean,
    false
  );
$$;

-- Historical callers use is_marketplace_visible for discovery/bookability.
-- It intentionally excludes a published salon that is temporarily paused or
-- closed today, while is_salon_profile_public keeps its profile readable.
create or replace function public.is_marketplace_visible(
  target_salon_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select coalesce(
    (
      public.salon_publication_diagnostic(target_salon_id)
      ->> 'discovery_eligible'
    )::boolean,
    false
  );
$$;

-- Keep automatic reconciliation idempotent. Active pilot salons do not churn
-- through Needs Attention while the exact recorded override remains effective;
-- newly introduced, non-overridden required gates still remove eligibility.
create or replace function public.reconcile_salon_publication(
  p_salon_id uuid,
  p_actor_id uuid default null,
  p_reason text default 'Eligibility recalculated'
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_before public.salons%rowtype;
  v_after public.salons%rowtype;
  v_diagnostic jsonb;
  v_approved boolean;
  v_override_effective boolean;
  v_application_active boolean;
  v_future_count integer;
begin
  select *
  into v_before
  from public.salons
  where id = p_salon_id
  for update;
  if not found then
    raise exception 'Salon not found.';
  end if;

  select
    v_before.approved_at is not null
    or exists (
      select 1
      from public.salon_applications application
      where application.salon_id = p_salon_id
        and application.status in ('Approved', 'Active')
    )
  into v_approved;

  if v_approved
     and nullif(trim(coalesce(v_before.name, '')), '') is not null
     and v_before.name <> 'Pending salon application'
     and (
       v_before.slug is null
       or v_before.slug ~ '^pending-'
     ) then
    update public.salons
    set slug = public.generate_unique_salon_slug(id, name)
    where id = p_salon_id;
  end if;

  v_diagnostic := public.salon_publication_diagnostic(p_salon_id);
  v_override_effective :=
    coalesce((v_diagnostic ->> 'override_active')::boolean, false)
    and coalesce(
      (v_diagnostic ->> 'all_required_complete')::boolean,
      false
    );

  if not (
    v_before.status = 'Active'
    and v_override_effective
  ) then
    perform public.reconcile_salon_lifecycle(
      p_salon_id,
      p_actor_id,
      p_reason
    );
  end if;

  v_diagnostic := public.salon_publication_diagnostic(p_salon_id);
  select exists (
    select 1
    from public.salon_applications application
    where application.salon_id = p_salon_id
      and application.status = 'Active'
  )
  into v_application_active;

  select *
  into v_after
  from public.salons
  where id = p_salon_id
  for update;

  if coalesce((v_diagnostic ->> 'all_required_complete')::boolean, false)
     and coalesce((v_diagnostic ->> 'override_active')::boolean, false)
     and (v_before.status = 'Active' or v_application_active)
     and v_after.status not in ('Suspended', 'Offboarded')
     and v_after.owner_unpublished_at is null then
    if v_after.status is distinct from 'Active' then
      select count(*)::integer
      into v_future_count
      from public.bookings booking
      where booking.salon_id = p_salon_id
        and booking.appointment_datetime >= now()
        and lower(coalesce(booking.status, ''))
          not in ('cancelled', 'canceled', 'completed');

      insert into public.salon_status_audit(
        salon_id,
        previous_status,
        new_status,
        reason,
        acting_admin_id,
        future_booking_count,
        actor_type,
        source
      ) values (
        p_salon_id,
        v_after.status,
        'Active',
        'Authorized pilot publication override remains effective',
        p_actor_id,
        v_future_count,
        case when p_actor_id is null then 'engine' else 'admin' end,
        'pilot_publication_override'
      );
    end if;

    update public.salons
    set status = 'Active',
        is_discoverable = true,
        activated_at = coalesce(activated_at, now()),
        lifecycle_reason = 'Authorized pilot publication override'
    where id = p_salon_id;
  elsif not coalesce(
    (v_diagnostic ->> 'all_required_complete')::boolean,
    false
  ) then
    update public.salons
    set is_discoverable = false
    where id = p_salon_id;
  else
    update public.salons
    set is_discoverable =
      is_discoverable
      and owner_unpublished_at is null
      and status = 'Active'
      and slug is not null
      and slug !~ '^pending-'
    where id = p_salon_id;
  end if;

  return public.salon_publication_diagnostic(p_salon_id);
end;
$$;

create or replace function public.admin_set_salon_publication_override(
  p_application_id uuid,
  p_actor_id uuid,
  p_enabled boolean,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_application public.salon_applications%rowtype;
  v_override public.salon_publication_overrides%rowtype;
  v_diagnostic jsonb;
  v_gates jsonb;
  v_changed boolean := false;
  v_action text;
  v_reason text;
begin
  if not exists (
    select 1
    from public.admin_users admin_user
    where coalesce(admin_user.user_id, admin_user.id) = p_actor_id
      and admin_user.status = 'Active'
      and (
        coalesce(admin_user.is_super_admin, false)
        or coalesce(
          (
            admin_user.permissions
            ->> 'pilot_activation_override'
          )::boolean,
          false
        )
      )
  ) then
    raise exception 'Forbidden' using errcode = '42501';
  end if;

  v_reason := trim(coalesce(p_reason, ''));
  if length(v_reason) < 12 then
    raise exception 'Enter an override reason of at least 12 characters.'
      using errcode = '22023';
  end if;

  select *
  into v_application
  from public.salon_applications
  where id = p_application_id
  for update;
  if not found then
    raise exception 'Application not found.' using errcode = 'P0002';
  end if;
  if v_application.status not in ('Approved', 'Active') then
    raise exception 'This salon application must be approved first.'
      using errcode = '22023';
  end if;

  perform 1
  from public.salons
  where id = v_application.salon_id
  for update;
  if not found then
    raise exception 'Salon not found.' using errcode = 'P0002';
  end if;

  v_diagnostic :=
    public.salon_publication_diagnostic(v_application.salon_id);
  v_gates := coalesce(
    v_diagnostic -> 'missing_gate_keys',
    '[]'::jsonb
  );

  select *
  into v_override
  from public.salon_publication_overrides publication_override
  where publication_override.salon_id = v_application.salon_id
  for update;

  if p_enabled then
    if jsonb_array_length(v_gates) = 0 then
      return jsonb_build_object(
        'changed', false,
        'active', false,
        'reason', 'No incomplete gate needs an override.',
        'lifecycle', v_diagnostic
      );
    end if;

    if v_override.id is null then
      insert into public.salon_publication_overrides(
        salon_id,
        application_id,
        is_active,
        reason,
        overridden_gates,
        gate_snapshot,
        granted_by,
        granted_at,
        revoked_by,
        revoked_at,
        updated_at
      ) values (
        v_application.salon_id,
        v_application.id,
        true,
        v_reason,
        v_gates,
        coalesce(v_diagnostic -> 'checks', '{}'::jsonb),
        p_actor_id,
        now(),
        null,
        null,
        now()
      )
      returning * into v_override;
      v_changed := true;
      v_action := 'Granted';
    elsif not v_override.is_active
       or v_override.reason is distinct from v_reason
       or v_override.overridden_gates is distinct from v_gates
       or v_override.application_id is distinct from v_application.id then
      update public.salon_publication_overrides
      set application_id = v_application.id,
          is_active = true,
          reason = v_reason,
          overridden_gates = v_gates,
          gate_snapshot = coalesce(
            v_diagnostic -> 'checks',
            '{}'::jsonb
          ),
          granted_by = p_actor_id,
          granted_at = now(),
          revoked_by = null,
          revoked_at = null,
          updated_at = now()
      where id = v_override.id
      returning * into v_override;
      v_changed := true;
      v_action := 'Updated';
    end if;
  elsif v_override.id is not null and v_override.is_active then
    update public.salon_publication_overrides
    set is_active = false,
        reason = v_reason,
        revoked_by = p_actor_id,
        revoked_at = now(),
        updated_at = now()
    where id = v_override.id
    returning * into v_override;
    v_changed := true;
    v_action := 'Revoked';
  end if;

  if v_changed then
    insert into public.salon_publication_override_audit(
      override_id,
      salon_id,
      application_id,
      action,
      reason,
      overridden_gates,
      gate_snapshot,
      acting_admin_id
    ) values (
      v_override.id,
      v_application.salon_id,
      v_application.id,
      v_action,
      v_reason,
      v_override.overridden_gates,
      v_override.gate_snapshot,
      p_actor_id
    );
  end if;

  v_diagnostic := public.reconcile_salon_publication(
    v_application.salon_id,
    p_actor_id,
    case
      when p_enabled then 'Authorized pilot publication override reviewed'
      else 'Authorized pilot publication override revoked'
    end
  );

  return jsonb_build_object(
    'changed', v_changed,
    'active', coalesce(v_override.is_active, false),
    'override_id', v_override.id,
    'overridden_gates',
      coalesce(v_override.overridden_gates, '[]'::jsonb),
    'lifecycle', v_diagnostic
  );
end;
$$;

create or replace function public.admin_activate_salon_application(
  p_application_id uuid,
  p_actor_id uuid,
  p_use_pilot_override boolean default false,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_application public.salon_applications%rowtype;
  v_salon public.salons%rowtype;
  v_current public.salons%rowtype;
  v_diagnostic jsonb;
  v_override_result jsonb;
  v_override_changed boolean := false;
  v_changed boolean := false;
  v_future_count integer := 0;
begin
  if not exists (
    select 1
    from public.admin_users admin_user
    where coalesce(admin_user.user_id, admin_user.id) = p_actor_id
      and admin_user.status = 'Active'
      and (
        coalesce(admin_user.is_super_admin, false)
        or coalesce(
          (admin_user.permissions ->> 'submissions')::boolean,
          false
        )
      )
  ) then
    raise exception 'Forbidden' using errcode = '42501';
  end if;

  select *
  into v_application
  from public.salon_applications
  where id = p_application_id
  for update;
  if not found then
    raise exception 'Application not found.' using errcode = 'P0002';
  end if;

  select *
  into v_salon
  from public.salons
  where id = v_application.salon_id
  for update;
  if not found then
    raise exception 'Salon not found.' using errcode = 'P0002';
  end if;

  if v_application.status not in ('Approved', 'Active') then
    return jsonb_build_object(
      'ok', false,
      'changed', false,
      'code', 'APPLICATION_NOT_APPROVED',
      'message', 'This salon application must be approved before publication.'
    );
  end if;

  perform public.reconcile_salon_publication(
    v_application.salon_id,
    p_actor_id,
    'Authorized admin publication check'
  );

  if p_use_pilot_override then
    v_override_result := public.admin_set_salon_publication_override(
      v_application.id,
      p_actor_id,
      true,
      p_reason
    );
    v_override_changed := coalesce(
      (v_override_result ->> 'changed')::boolean,
      false
    );
  end if;

  v_diagnostic := public.reconcile_salon_publication(
    v_application.salon_id,
    p_actor_id,
    case
      when p_use_pilot_override
        then 'Authorized pilot publication activation'
      else 'Authorized admin publication activation'
    end
  );

  if not coalesce(
    (v_diagnostic ->> 'all_required_complete')::boolean,
    false
  ) then
    return jsonb_build_object(
      'ok', false,
      'changed', v_override_changed,
      'code', 'PUBLICATION_GATES_INCOMPLETE',
      'message', 'This salon still has incomplete publication requirements.',
      'missing', coalesce(
        v_diagnostic -> 'effective_missing_gate_labels',
        '[]'::jsonb
      ),
      'lifecycle', v_diagnostic
    );
  end if;

  select *
  into v_current
  from public.salons
  where id = v_application.salon_id
  for update;

  if v_current.status in ('Suspended', 'Offboarded', 'New', 'Pending')
     or v_current.owner_unpublished_at is not null then
    return jsonb_build_object(
      'ok', false,
      'changed', v_override_changed,
      'code', 'SALON_STATE_BLOCKS_PUBLICATION',
      'message', 'This salon state does not allow public activation.',
      'missing', '[]'::jsonb,
      'lifecycle', v_diagnostic
    );
  end if;

  if v_current.status is distinct from 'Active' then
    select count(*)::integer
    into v_future_count
    from public.bookings booking
    where booking.salon_id = v_application.salon_id
      and booking.appointment_datetime >= now()
      and lower(coalesce(booking.status, ''))
        not in ('cancelled', 'canceled', 'completed');

    insert into public.salon_status_audit(
      salon_id,
      previous_status,
      new_status,
      reason,
      acting_admin_id,
      future_booking_count,
      actor_type,
      source
    ) values (
      v_application.salon_id,
      v_current.status,
      'Active',
      case
        when p_use_pilot_override
          then 'Authorized pilot publication override'
        else 'Every required publication gate passed'
      end,
      p_actor_id,
      v_future_count,
      'admin',
      case
        when p_use_pilot_override
          then 'pilot_publication_override'
        else 'admin_submissions'
      end
    );
    v_changed := true;
  end if;

  update public.salons
  set status = 'Active',
      is_discoverable = true,
      approved_at = coalesce(approved_at, now()),
      activated_at = coalesce(activated_at, now()),
      lifecycle_reason = case
        when p_use_pilot_override
          then 'Authorized pilot publication override'
        else null
      end
  where id = v_application.salon_id;

  if v_application.status is distinct from 'Active' then
    update public.salon_applications
    set status = 'Active',
        reviewed_by = p_actor_id,
        reviewed_at = coalesce(reviewed_at, now()),
        rejection_reason = null
    where id = v_application.id;
    v_changed := true;
  end if;

  v_changed := v_changed or v_override_changed;
  v_diagnostic :=
    public.salon_publication_diagnostic(v_application.salon_id);

  return jsonb_build_object(
    'ok', true,
    'changed', v_changed,
    'idempotent', not v_changed,
    'application_id', v_application.id,
    'salon_id', v_application.salon_id,
    'application_status', 'Active',
    'override_active',
      coalesce((v_diagnostic ->> 'override_active')::boolean, false),
    'overridden_gates',
      coalesce(v_diagnostic -> 'overridden_gates', '[]'::jsonb),
    'lifecycle', v_diagnostic
  );
end;
$$;

revoke all on function public.salon_publication_diagnostic(uuid)
  from public, anon, authenticated;
revoke all on function public.salon_setup_complete(uuid)
  from public, anon, authenticated;
revoke all on function public.is_salon_profile_public(uuid)
  from public;
revoke all on function public.is_marketplace_visible(uuid)
  from public;
revoke all on function public.reconcile_salon_publication(uuid, uuid, text)
  from public, anon, authenticated;
revoke all on function public.admin_set_salon_publication_override(
  uuid, uuid, boolean, text
) from public, anon, authenticated;
revoke all on function public.admin_activate_salon_application(
  uuid, uuid, boolean, text
) from public, anon, authenticated;

grant execute on function public.salon_publication_diagnostic(uuid)
  to service_role;
grant execute on function public.salon_setup_complete(uuid)
  to service_role;
grant execute on function public.is_salon_profile_public(uuid)
  to anon, authenticated, service_role;
grant execute on function public.is_marketplace_visible(uuid)
  to anon, authenticated, service_role;
grant execute on function public.reconcile_salon_publication(uuid, uuid, text)
  to service_role;
grant execute on function public.admin_set_salon_publication_override(
  uuid, uuid, boolean, text
) to service_role;
grant execute on function public.admin_activate_salon_application(
  uuid, uuid, boolean, text
) to service_role;

-- Profile content remains readable while a published salon temporarily pauses
-- bookings. Availability and organic discovery still use the stricter
-- is_marketplace_visible predicate.
drop policy if exists salons_public_read on public.salons;
create policy salons_public_read
on public.salons for select to anon, authenticated
using (
  public.is_salon_profile_public(id)
  or public.salon_has_permission(id, 'my_page')
  or public.is_admin()
);

drop policy if exists styles_public_read on public.styles;
create policy styles_public_read
on public.styles for select to anon, authenticated
using (
  (
    not is_draft
    and archived_at is null
    and public.is_salon_profile_public(salon_id)
  )
  or public.salon_has_permission(salon_id, 'styles')
  or public.admin_has_permission('salons')
);

drop policy if exists stylists_public_read on public.stylists;
create policy stylists_public_read
on public.stylists for select to anon, authenticated
using (
  (
    is_active
    and not is_draft
    and archived_at is null
    and public.is_salon_profile_public(salon_id)
  )
  or public.salon_has_permission(salon_id, 'stylists')
  or public.admin_has_permission('salons')
);

drop policy if exists availability_public_read on public.availability;
create policy availability_public_read
on public.availability for select to anon, authenticated
using (
  public.is_marketplace_visible(salon_id)
  or public.salon_has_permission(salon_id, 'availability')
  or public.admin_has_permission('bookings')
);

drop policy if exists style_materials_public_read on public.style_materials;
create policy style_materials_public_read
on public.style_materials for select to anon, authenticated
using (
  exists (
    select 1
    from public.styles style
    where style.id = style_materials.style_id
      and (
        (
          not style.is_draft
          and style.archived_at is null
          and public.is_salon_profile_public(style.salon_id)
        )
        or public.salon_has_permission(style.salon_id, 'styles')
        or public.admin_has_permission('salons')
      )
  )
);

drop policy if exists reviews_public_read on public.reviews;
create policy reviews_public_read
on public.reviews for select to anon, authenticated
using (
  (
    moderation_status = 'Published'
    and coalesce(dispute_status, 'None') <> 'Removed'
    and public.is_salon_profile_public(salon_id)
  )
  or public.salon_has_permission(salon_id, 'reviews')
  or public.admin_has_permission('reviews')
);

drop policy if exists salon_products_public_read on public.salon_products;
create policy salon_products_public_read
on public.salon_products for select to anon, authenticated
using (
  (
    is_visible
    and product_status = 'Active'
    and archived_at is null
    and public.is_salon_profile_public(salon_id)
  )
  or public.salon_has_permission(salon_id, 'products')
  or public.admin_has_permission('salons')
);

drop policy if exists salon_promotions_public_read on public.salon_promotions;
create policy salon_promotions_public_read
on public.salon_promotions for select to anon, authenticated
using (
  (
    status = 'Active'
    and is_active = true
    and archived_at is null
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at >= now())
    and public.is_salon_profile_public(salon_id)
    and public.salon_has_feature(salon_id, 'promotions')
  )
  or public.salon_has_permission(salon_id, 'promotions')
  or public.admin_has_permission('marketing')
);

update public.engine_settings
set published_value = '"20260727230000"'::jsonb,
    draft_value = '"20260727230000"'::jsonb,
    updated_at = now()
where setting_key = 'integrations.expected_migration';

commit;
